default/objects/Client_Offer_Additional_Service__c/Client_Offer_Additional_Service__c.object-meta.xml
<CustomObject>
    <label>Client Offer Additional Service</label>
    <nameField>
        <displayFormat>COAS-{0000000}</displayFormat>
        <label>Client Offer Additional Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Offer Additional Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Client_Offer_Additional_Service__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Offer Additional Services</relationshipLabel>
    <relationshipName>Client_Offer_Additional_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/TemporaryBatchToUpdateClientOfferAS.cls
public class TemporaryBatchToUpdateClientOfferAS implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
                SELECT  Account__c, Opportunity__r.AccountId
                FROM    Client_Offer_Additional_Service__c
                WHERE   CreatedDate >= 2020-01-01T01:01:01Z AND
                        Opportunity__r.AccountId != NULL AND
                        Account__c = NULL
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Client_Offer_Additional_Service__c> scope) {
        ClientOfferAddServiceHandler.enablesTrigger = false;
        for (Client_Offer_Additional_Service__c n : scope) {
            n.Account__c = n.Opportunity__r.AccountId;
        }
        update scope;
    }

    public void finish(Database.BatchableContext bc) {}
}