default/objects/Lead/fields/Anzahl_der_Fahrzeuge__c.field-meta.xml
<CustomField>
    <fullName>Anzahl_der_Fahrzeuge__c</fullName>
    <label>Anzahl der Fahrzeuge?</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Lead/fields/CCS_number_of_cards__c.field-meta.xml
<CustomField>
    <fullName>CCS_number_of_cards__c</fullName>
    <label>CCS_number_of_cards</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Первый контакт по inbound</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Anruf</fullName>
            </value>
            <value>
                <fullName>FLMT_Form</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/First_Call__c.field-meta.xml
<CustomField>
    <fullName>First_Call__c</fullName>
    <label>First Call</label>
    <type>DateTime</type>
</CustomField>

default/objects/Lead/fields/Is_External__c.field-meta.xml
<CustomField>
    <fullName>Is_External__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is External</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Lead/fields/Last_Owner_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Owner_Change_Date__c</fullName>
    <label>Last Owner Change Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Lead/fields/Lead_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Type__c</fullName>
    <label>Lead Source Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Quali_Status__c.field-meta.xml
<CustomField>
    <fullName>Quali_Status__c</fullName>
    <label>Quali-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>-</fullName>
            </value>
            <value>
                <fullName>Already Allstar Customer</fullName>
            </value>
            <value>
                <fullName>Already CCS customer</fullName>
            </value>
            <value>
                <fullName>Already Lotos Customer</fullName>
            </value>
            <value>
                <fullName>Anwahllimit erreicht</fullName>
            </value>
            <value>
                <fullName>Bereits Kunde - FleetCor</fullName>
            </value>
            <value>
                <fullName>Bereits Kunde - Shell</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Centrally decided</fullName>
            </value>
            <value>
                <fullName>Company ceased to exist</fullName>
            </value>
            <value>
                <fullName>Competitor´s customer - CS request</fullName>
            </value>
            <value>
                <fullName>Competitor - request</fullName>
            </value>
            <value>
                <fullName>Competitors</fullName>
            </value>
            <value>
                <fullName>Coverage/Acceptance</fullName>
            </value>
            <value>
                <fullName>Customer reached – additional information required</fullName>
            </value>
            <value>
                <fullName>Customer reached – call later</fullName>
            </value>
            <value>
                <fullName>Customer reached – didn’t talk to decision maker</fullName>
            </value>
            <value>
                <fullName>Customer reached – email sent</fullName>
            </value>
            <value>
                <fullName>Customer reached – first meeting</fullName>
            </value>
            <value>
                <fullName>Customer reached – follow up (seasonality)</fullName>
            </value>
            <value>
                <fullName>Customer reached – forwarded to Field</fullName>
            </value>
            <value>
                <fullName>Customer reached – next meeting(s)</fullName>
            </value>
            <value>
                <fullName>Do Not Contact</fullName>
            </value>
            <value>
                <fullName>Dublette</fullName>
            </value>
            <value>
                <fullName>Financial/Credit</fullName>
            </value>
            <value>
                <fullName>Follow UP</fullName>
            </value>
            <value>
                <fullName>Follow up email #1 sent</fullName>
            </value>
            <value>
                <fullName>Follow up email #2 sent</fullName>
            </value>
            <value>
                <fullName>Forwarded</fullName>
            </value>
            <value>
                <fullName>Forwarded internally</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Recycle_counter__c.field-meta.xml
<CustomField>
    <fullName>Recycle_counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Recycle counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Lead/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/recordTypes/Lotos.recordType-meta.xml
<RecordType>
    <fullName>Lotos</fullName>
    <active>true</active>
    <businessProcess>Datensatztyp</businessProcess>
    <label>Lotos</label>
</RecordType>

default/objects/LeadRelocationSettings__c/LeadRelocationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>LeadRelocationSettings</label>
</CustomObject>

default/objects/LeadRelocationSettings__c/fields/EU_Enabled__c.field-meta.xml
<CustomField>
    <fullName>EU_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enables relocation of EU Leads in LeadRelocationBatch</description>
    <label>EU Enabled</label>
    <type>Checkbox</type>
</CustomField>

default/classes/LeadRelocationBatch.cls
global class LeadRelocationBatch implements Database.Batchable<sObject> {
    private static String REGIONS = 'regions';
    private static String RU = 'ru';
    private static String EU = 'eu';
    private static String NAME = 'name';
    private static String L_R_COUNTRIES = 'LeadRelocationCountries';
    
    public String query;
    public Date myDate;
    private Set<String> RWLlistid = new Set<String>();
    private Datetime correctDatetime;
    private Id russianQueueId;
    private Boolean euEnabled = (LeadRelocationSettings__c.getInstance() == null ? true : LeadRelocationSettings__c.getInstance().EU_Enabled__c);
    private Set<String> countriesSet = new Set<String>();

    global LeadRelocationBatch() {
        this.query = '';
        Boolean ExecuteJobInBerlin = false;
        Boolean ExecuteJobInMoscow = false;

        Datetime GMTDate = Datetime.newInstanceGmt(
                datetime.now().yearGmt(), datetime.now().monthGmt(), datetime.now().dayGmt(),
                datetime.now().hourGmt(), datetime.now().minuteGmt(), 0);
        Integer HourBerlin = Integer.valueOf(GMTDate.format('HH', 'Europe/Berlin'));
        Integer HourMoscow = Integer.valueOf(GMTDate.format('HH', 'Europe/Moscow'));

        if ((HourBerlin >= 8) && (HourBerlin <= 17)) ExecuteJobInBerlin = true;
        if ((HourMoscow >= 8) && (HourMoscow <= 17)) ExecuteJobInMoscow = true;
        if (Test.isRunningTest()) {
            ExecuteJobInBerlin = true;
            ExecuteJobInMoscow = true;
        }

        setCountriesFromResource();

        if (ExecuteJobInBerlin || ExecuteJobInMoscow) {
            this.query = 'SELECT Owner.Email, Status, CreatedDate, Sec_Channel__c, OwnerId, Last_Owner_Change_Date__c, Channel__c,' +
                    '       LeadSource, Country, Salutation, CountryCode, RecordType.Name, Is_External__c, Lead_Source_type__c, Anzahl_der_Fahrzeuge__c, CCS_number_of_cards__c, ' +
                    '       Recycle_counter__c, Quali_Status__c, ' +
                    '       (SELECT OldValue, NewValue FROM Histories WHERE Field = \'Quali_Status__c\') ' +
                    'FROM Lead ' +
                    'WHERE  isConverted = FALSE AND ' +
                    '       Last_Owner_Change_Date__c != NULL AND ' +
                    '       Country IN :countriesSet  AND ' +
                    '       RecordType.Name NOT IN (\'CCS Sales process\', \'Lotos\') AND ' +
                    '       (Recycle_counter__c = 0 OR Recycle_counter__c = null) AND ' +
                    '(';
            if (ExecuteJobInBerlin) {
                myDate = date.newinstance(2016, 3, 30);
                this.query +=
                        '   ( ' +
                                '     ((Sec_Channel__c = \'Inbound\' AND (Channel__c = \'Internet\' OR Channel__c = \'E-mail\')) OR ' +
                                '      (Sec_Channel__c = \'JITB\' AND Channel__c = \'Internet\') OR (Sec_Channel__c = \'Partner\')) AND ' +
                                '       Status = \'Open\'  AND ' +
                                '       First_Call__c = NULL AND ' +
                                '       LeadSource != \'Online_chat\' AND ' +
                                '       CreatedDate >= :myDate ' +
                                '   ) OR';
            }
            if (ExecuteJobInMoscow) {
                RWLlistid.clear();
                List<Group> russianQueue = [
                        SELECT Id
                        FROM Group
                        WHERE Name = 'Russian Web Leads'
                ];
                if (!russianQueue.isEmpty()) {
                    RWLlistid.add(russianQueue.get(0).Id);
                    russianQueueId = russianQueue.get(0).Id;
                }
                for (GroupMember gm : [Select UserOrGroupId From GroupMember where Group.name = 'Russian Web Leads']) {
                    RWLlistid.add(gm.UserOrGroupId);
                }
                correctDatetime = System.now().addMinutes(-9);
                this.query +=
                        '   ( ' +
                                '        OwnerId IN :RWLlistid AND ' +
                                '        Status = \'NEW - Not Yet Contacted\' AND ' +
                                '       (Last_Owner_Change_Date__c <= :correctDatetime OR OwnerId = :russianQueueId ) AND ' +
                                '       (Lead_Source_Type__c = \'Webform\' OR Lead_Source_Type__c = \'Popup\' OR ' +
                                '        Lead_Source_Type__c = \'Chat\'    OR Lead_Source_Type__c = \'Email\') ' +
                                '   ) ';
            }
            this.query = this.query.removeEnd('OR');
            this.query += ') ';
        } else {
            this.query = 'SELECT id,name FROM Lead WHERE id=\'0BLANKIDBLANKID\'';
        }

        System.debug('HERE ' + this.query);
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        LeadRelocationService.customLeadAssignBatch(scope);
        LeadHandler.isSwitchToE2E = false;

        List<SObject> objectsToUpdate = new List<SObject>();

        Map<Id, SObject> mapSObjects = new Map<Id, SObject>();

        System.debug(scope.size());
        System.debug(scope.get(0).get('Id') + ' ' + scope.get(0).get('Status'));

        for (SObject lead : scope) {
            mapSObjects.put(Id.valueOf(String.valueOf(lead.get('Id'))), lead);
        }

        List<Lead> leadsToCheck = [SELECT Id, Status FROM Lead WHERE Id IN :mapSObjects.keySet()];
        for(Lead lead : leadsToCheck) {
            if(lead.Status != mapSObjects.get(lead.Id).get('Status')) {
                mapSObjects.remove(lead.Id);
            }
        }

        update mapSObjects.values();
    }

    global void finish(Database.BatchableContext BC) {
    }

    public void setCountriesFromResource() {
        StaticResource countriesResource = [
            SELECT Body 
            FROM StaticResource 
            WHERE Name =: L_R_COUNTRIES
            LIMIT 1
        ];
        Map<String, Object> countriesMap = (Map<String, Object>) JSON.deserializeUntyped(countriesResource.Body.toString());

        if (countriesMap.containsKey(REGIONS)) {
            Map<String, Object> regionsMap = (Map<String, Object>)countriesMap.get(REGIONS);
            
            if (regionsMap.containsKey(RU)) {
                countriesSet.addAll(getNamesFromRegions(regionsMap, RU));
            }

            if (euEnabled && regionsMap.containsKey(EU)) {
                countriesSet.addAll(getNamesFromRegions(regionsMap, EU));
            }
        }
    }

    private List<String> getNamesFromRegions(Map<String, Object> regionsMap, String region) {
        List<String> countries = new List<String>();
        List<Object> regionCountries = (List<Object>)regionsMap.get(region);

        if (regionCountries != null && !regionCountries.isEmpty()) {
            for (Object regionCountry : regionCountries) {
                Map<String, object> mapValue = (Map<String, Object>)regionCountry;
                countries.add((String)mapValue.get(NAME));
            }
        }

        return countries;
    }
}