default/objects/Lead/fields/E2E_Adoption_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Adoption_Status__c</fullName>
    <defaultValue>'Manual Process'</defaultValue>
    <label>E2E Adoption Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manual Process</fullName>
                <default>true</default>
                <label>Manual Process</label>
            </value>
            <value>
                <fullName>Adoption Email Sent</fullName>
            </value>
            <value>
                <fullName>Successful Adoption</fullName>
            </value>
            <value>
                <fullName>Returned to Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Quali_Status__c.field-meta.xml
<CustomField>
    <fullName>Quali_Status__c</fullName>
    <label>Quali-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>-</fullName>
            </value>
            <value>
                <fullName>Already Allstar Customer</fullName>
            </value>
            <value>
                <fullName>Already CCS customer</fullName>
            </value>
            <value>
                <fullName>Already Lotos Customer</fullName>
            </value>
            <value>
                <fullName>Anwahllimit erreicht</fullName>
            </value>
            <value>
                <fullName>Bereits Kunde - FleetCor</fullName>
            </value>
            <value>
                <fullName>Bereits Kunde - Shell</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Centrally decided</fullName>
            </value>
            <value>
                <fullName>Company ceased to exist</fullName>
            </value>
            <value>
                <fullName>Competitor´s customer - CS request</fullName>
            </value>
            <value>
                <fullName>Competitor - request</fullName>
            </value>
            <value>
                <fullName>Competitors</fullName>
            </value>
            <value>
                <fullName>Coverage/Acceptance</fullName>
            </value>
            <value>
                <fullName>Customer reached – additional information required</fullName>
            </value>
            <value>
                <fullName>Customer reached – call later</fullName>
            </value>
            <value>
                <fullName>Customer reached – didn’t talk to decision maker</fullName>
            </value>
            <value>
                <fullName>Customer reached – email sent</fullName>
            </value>
            <value>
                <fullName>Customer reached – first meeting</fullName>
            </value>
            <value>
                <fullName>Customer reached – follow up (seasonality)</fullName>
            </value>
            <value>
                <fullName>Customer reached – forwarded to Field</fullName>
            </value>
            <value>
                <fullName>Customer reached – next meeting(s)</fullName>
            </value>
            <value>
                <fullName>Do Not Contact</fullName>
            </value>
            <value>
                <fullName>Dublette</fullName>
            </value>
            <value>
                <fullName>Financial/Credit</fullName>
            </value>
            <value>
                <fullName>Follow UP</fullName>
            </value>
            <value>
                <fullName>Follow up email #1 sent</fullName>
            </value>
            <value>
                <fullName>Follow up email #2 sent</fullName>
            </value>
            <value>
                <fullName>Forwarded</fullName>
            </value>
            <value>
                <fullName>Forwarded internally</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/UpdateLeadsTempBatchTest.cls
@isTest
private class UpdateLeadsTempBatchTest {
    static testMethod void testMethod1() {
        Lead lead = new Lead(
        	LastName = 'test',
        	Company = 'Test',
        	Country = 'Germany',
        	E2E_Adoption_Status__c = null);
        insert lead;
        Test.setCreatedDate(lead.Id, Datetime.newInstance(Date.newInstance(2018, 12, 5), Time.newInstance(0, 0, 0, 0)));

        Test.startTest();
        	Database.executeBatch(new UpdateLeadsTempBatch(), 1);
        Test.stopTest();
    }


    static testMethod void testMethod2() {
        Lead lead2 = new Lead(
        	LastName = 'test',
        	Company = 'Test',
        	Country = 'Germany',
        	Quali_Status__c = 'Switched to E2E',
        	E2E_Adoption_Status__c = null);        
        insert lead2;
        Test.setCreatedDate(lead2.Id, Datetime.newInstance(Date.newInstance(2018, 12, 5), Time.newInstance(0, 0, 0, 0)));

        Test.startTest();
        	Database.executeBatch(new UpdateLeadsTempBatch(), 1);
        Test.stopTest();
    }
}