default/objects/Lead/fields/E2E_Adoption_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Adoption_Status__c</fullName>
    <defaultValue>'Manual Process'</defaultValue>
    <label>E2E Adoption Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manual Process</fullName>
                <default>true</default>
                <label>Manual Process</label>
            </value>
            <value>
                <fullName>Adoption Email Sent</fullName>
            </value>
            <value>
                <fullName>Successful Adoption</fullName>
            </value>
            <value>
                <fullName>Returned to Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Quali_Status__c.field-meta.xml
<CustomField>
    <fullName>Quali_Status__c</fullName>
    <label>Quali-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>-</fullName>
            </value>
            <value>
                <fullName>Already Allstar Customer</fullName>
            </value>
            <value>
                <fullName>Already CCS customer</fullName>
            </value>
            <value>
                <fullName>Already Lotos Customer</fullName>
            </value>
            <value>
                <fullName>Anwahllimit erreicht</fullName>
            </value>
            <value>
                <fullName>Bereits Kunde - FleetCor</fullName>
            </value>
            <value>
                <fullName>Bereits Kunde - Shell</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Centrally decided</fullName>
            </value>
            <value>
                <fullName>Company ceased to exist</fullName>
            </value>
            <value>
                <fullName>Competitor´s customer - CS request</fullName>
            </value>
            <value>
                <fullName>Competitor - request</fullName>
            </value>
            <value>
                <fullName>Competitors</fullName>
            </value>
            <value>
                <fullName>Coverage/Acceptance</fullName>
            </value>
            <value>
                <fullName>Customer reached – additional information required</fullName>
            </value>
            <value>
                <fullName>Customer reached – call later</fullName>
            </value>
            <value>
                <fullName>Customer reached – didn’t talk to decision maker</fullName>
            </value>
            <value>
                <fullName>Customer reached – email sent</fullName>
            </value>
            <value>
                <fullName>Customer reached – first meeting</fullName>
            </value>
            <value>
                <fullName>Customer reached – follow up (seasonality)</fullName>
            </value>
            <value>
                <fullName>Customer reached – forwarded to Field</fullName>
            </value>
            <value>
                <fullName>Customer reached – next meeting(s)</fullName>
            </value>
            <value>
                <fullName>Do Not Contact</fullName>
            </value>
            <value>
                <fullName>Dublette</fullName>
            </value>
            <value>
                <fullName>Financial/Credit</fullName>
            </value>
            <value>
                <fullName>Follow UP</fullName>
            </value>
            <value>
                <fullName>Follow up email #1 sent</fullName>
            </value>
            <value>
                <fullName>Follow up email #2 sent</fullName>
            </value>
            <value>
                <fullName>Forwarded</fullName>
            </value>
            <value>
                <fullName>Forwarded internally</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/UpdateLeadsTempBatch.cls
global class UpdateLeadsTempBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public String query;

    global UpdateLeadsTempBatch() {
        this.query = 'SELECT IsConverted, Quali_Status__c, E2E_Adoption_Status__c, Status, ' + 
                    '(' +
                        'SELECT  OldValue, ' + 
                        'Field, ' + 
                        'NewValue ' +
                        ' FROM    Histories' +
                        ' WHERE   Field = \'Quali_Status__c\'' +
                    ')' +
            ' FROM    Lead ' +
            ' WHERE   E2E_Adoption_Status__c = NULL ' +
            ' AND     CreatedDate > 2018-11-01T00:00:00Z ' +
            ' AND     CreatedDate < 2019-01-01T00:00:00Z ' +
            ' AND     Country IN :countriesSet ' +
            ' ORDER BY CreatedDate DESC ' + 
            ' LIMIT 50000';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        LeadHandler.enablesTrigger = false;
        List<Lead> leadsToUpdate = new List<Lead>();
        for(Lead lead : (List<Lead>)scope){
            if(lead.Quali_Status__c == 'Switched to E2E' && !lead.IsConverted){
                lead.E2E_Adoption_Status__c = 'Adoption Email Sent';
                leadsToUpdate.add(lead);
            }
            if(lead.IsConverted && lead.Quali_Status__c =='Switched to E2E' && lead.Status != 'Disqualified'){
                lead.E2E_Adoption_Status__c = 'Successful Adoption';
                leadsToUpdate.add(lead);
            }
            if(lead.Quali_Status__c !='Switched to E2E' && !lead.Histories.isEmpty()){
                for(LeadHistory history : lead.Histories){
                    if(history.OldValue == 'Switched to E2E'){
                        lead.E2E_Adoption_Status__c = 'Returned to Manual';
                        leadsToUpdate.add(lead);
                        break;
                    }
                }        
            }
            if(String.isEmpty(lead.E2E_Adoption_Status__c)){
                lead.E2E_Adoption_Status__c = 'Manual Process';
                leadsToUpdate.add(lead);
            }
        }
        update leadsToUpdate;
    }

    global void finish(Database.BatchableContext BC) {

    }

    global static Set<String> countriesSet = new Set<String>{
        'Germany',
        'Poland',
        'Hungary',
        'France',
        'Netherlands',
        'Austria',
        'Belgium-FR',
        'Belgium-NL',
        'Switzerland-DE',
        'Switzerland-FR'
    };
}