default/objects/E2E_Data_Log__c/E2E_Data_Log__c.object-meta.xml
<CustomObject>
    <label>E2E Data Log</label>
    <nameField>
        <label>E2E Data Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Log__c/fields/E2E_Data_Object__c.field-meta.xml
<CustomField>
    <fullName>E2E_Data_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E2E Data Object</label>
    <referenceTo>E2E_Data_Object__c</referenceTo>
    <relationshipLabel>E2E Data Logs</relationshipLabel>
    <relationshipName>E2E_Data_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2E_Data_Log__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <label>Error Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/E2E_Data_Log__c/fields/Exception_Description__c.field-meta.xml
<CustomField>
    <fullName>Exception_Description__c</fullName>
    <label>Exception Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/E2E_Data_Log__c/fields/Exception_Source__c.field-meta.xml
<CustomField>
    <fullName>Exception_Source__c</fullName>
    <label>Exception Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backend</fullName>
            </value>
            <value>
                <fullName>Frontend</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System Error</fullName>
            </value>
            <value>
                <fullName>Process Error</fullName>
            </value>
            <value>
                <fullName>Credit Logic</fullName>
            </value>
            <value>
                <fullName>CF System Error</fullName>
            </value>
            <value>
                <fullName>Company search</fullName>
            </value>
            <value>
                <fullName>Credit Factory Error</fullName>
                <isActive>false</isActive>
                <label>Credit Factory Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Log__c/recordTypes/Exception.recordType-meta.xml
<RecordType>
    <fullName>Exception</fullName>
    <active>true</active>
    <label>Exception</label>
</RecordType>

default/objects/E2E_Data_Object__c/E2E_Data_Object__c.object-meta.xml
<CustomObject>
    <label>E2E Data Object</label>
    <nameField>
        <label>E2E Data Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Object__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>de</fullName>
            </value>
            <value>
                <fullName>at</fullName>
            </value>
            <value>
                <fullName>nl</fullName>
            </value>
            <value>
                <fullName>pl</fullName>
            </value>
            <value>
                <fullName>hu</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>befr</fullName>
            </value>
            <value>
                <fullName>benl</fullName>
            </value>
            <value>
                <fullName>chde</fullName>
            </value>
            <value>
                <fullName>chfr</fullName>
            </value>
            <value>
                <fullName>sk</fullName>
            </value>
            <value>
                <fullName>cz</fullName>
            </value>
            <value>
                <fullName>lu</fullName>
            </value>
            <value>
                <fullName>be_fr</fullName>
                <isActive>false</isActive>
                <label>be_fr</label>
            </value>
            <value>
                <fullName>be_nl</fullName>
                <isActive>false</isActive>
                <label>be_nl</label>
            </value>
            <value>
                <fullName>ch_de</fullName>
                <isActive>false</isActive>
                <label>ch_de</label>
            </value>
            <value>
                <fullName>ch_fr</fullName>
                <isActive>false</isActive>
                <label>ch_fr</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Current_Step__c</fullName>
    <label>Current Step</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Type__c</fullName>
    <label>Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desktop</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/ETEResponseHandler.cls
public class ETEResponseHandler {

    public Map<String, Object> generateResponseStatus(String message) {
        Map<String, Object> responseMap = new Map<String, Object>();
        Integer statusCode = returnStatusCode(message);
        responseMap.put('statusCode', statusCode);
        if (statusCode != 200) {
            responseMap.put('message', message);
        } else {
            responseMap.put('message', 'unknown error');
        }
        return responseMap;
    }

    private static Integer returnStatusCode(String errorMessage) {
        switch on errorMessage {
            when null,
                    'report ordering',
                    'Black list',
                    'High e-mail risk',
                    'High risk industry' {
                return 100;
            }
            when 'job pending' {
                return 101;
            }
            when 'order completed' {
                return 102;
            }
            when 'redirection need' {
                return 103;
            }
            // Credit Logic
            when 'Too high limit',
                    'Too risky',
                    'Risky but manageable',
                    'Inactive company',
                    'Empty address',
                    'Negative information',
                    'Executions and potentially high exposure' {
                return 104;
            }
            when 'report pending' {
                return 105;
            }
            // CF System Error
            when 'Unknown credit factory error',
                'The order is still being processed. Please contact your administrator.' {
                return 106;
            }
            when 'authorization need' {
                return 107;
            }
            when 'verification code is not valid' {
                return 108;
            }
            when else {
                return 200;
            }
        }
    }

    public String checkCreditScoringErrors(String verdict, String statusCode) {
        if (verdict == 'Yes' && statusCode == '001') {
            return null;
        } else if (verdict == 'No' && (statusCode == '002' || statusCode == '004')) {
            return 'Too high limit';
        } else if (verdict == 'No' && statusCode == '005') {
            return 'Too risky';
        } else if (verdict == 'No' && statusCode == '006') {
            return 'Risky but manageable';
        } else if (verdict == 'No' && statusCode == '008') {
            return 'Black list';
        } else if (verdict == 'No' && statusCode == '009') {
            return 'High e-mail risk';
        } else if (verdict == 'No' && statusCode == '010') {
            return 'High risk industry';
        } else if (verdict == 'No' && statusCode == '007') {
            return 'Too risky';
        } else if (verdict == 'No' && statusCode == '012') {
            return 'Inactive company';
        } else if (verdict == 'No' && statusCode == '013') {
            return 'Empty address';
        } else if (verdict == 'No' && statusCode == '014') {
            return 'Executions and potentially high exposure';
        } else if (verdict == 'No' && statusCode == '016') {
            return 'Negative information';
        } else {
            return 'Unknown credit factory error';
        }
    }


    public void createExceptionLog(Map<String, Object> exceptionLogParams) {
        if (! exceptionLogParams.isEmpty()) {
            String countryCode = String.valueOf(exceptionLogParams.get('countryCode'));
            ETEDatabaseInterface e2eDatabase = ETEGlobalUtils.getDatabaseConnector(countryCode);
            String recordTypeId = Schema.SObjectType.E2E_Data_Log__c.getRecordTypeInfosByName().get('Exception').getRecordTypeId();
            String dataObjectId = ETEGlobalUtils.doDecryptParams((String) exceptionLogParams.get('source'), countryCode);
            E2E_Data_Log__c newExceptionDataLog = new E2E_Data_Log__c();
            newExceptionDataLog.put('Name', 'Exception on ' + String.valueOf(exceptionLogParams.get('currentStep')) + ' step');
            newExceptionDataLog.put('E2E_Data_Object__c', dataObjectId);
            newExceptionDataLog.put('RecordTypeId', recordTypeId);
            if (exceptionLogParams.containsKey('statusCode') && exceptionLogParams.get('statusCode') != null) {
                newExceptionDataLog.put('Error_Code__c', Decimal.valueOf(String.valueOf(exceptionLogParams.get('statusCode'))));
            }
            newExceptionDataLog.put('Exception_Type__c', exceptionLogParams.get('exceptionType'));
            newExceptionDataLog.put('Exception_Description__c', exceptionLogParams.get('exceptionMessage'));
            newExceptionDataLog.put('Exception_Source__c', exceptionLogParams.get('exceptionSource'));
            newExceptionDataLog.put('Device_Type__c', exceptionLogParams.get('deviceType'));
            e2eDatabase.upsertE2EDataLogs(new List<E2E_Data_Log__c>{newExceptionDataLog});
        }
    }


    public Map<String, Object> prepareExceptionLogParams(Map<String, Object> requestParams,
            String deviceType,
            Object statusCode,
            String errorMessage,
            Exception exceptionDetails,
            String exceptionSource) {
        Map<String, Object> exceptionLogParamsMap = new Map<String, Object>();
        if (requestParams.containsKey('user_model')) {
            String requestUserModelJson = JSON.serialize(requestParams.get('user_model'));
            ETEUserModel userModelFromRequest = (ETEUserModel) System.JSON.deserialize(requestUserModelJson, Type.forName('ETEUserModel'));
            if (! String.isEmpty(userModelFromRequest.source)) {
                exceptionLogParamsMap.put('currentStep', userModelFromRequest.currentStep);
                exceptionLogParamsMap.put('countryCode', userModelFromRequest.countryCode);
                exceptionLogParamsMap.put('source', userModelFromRequest.source);
            }
        } else if (requestParams.containsKey('source') && requestParams.containsKey('country')) {
            String countryCode = (String) requestParams.get('country');
            ETEDatabaseInterface e2eDatabase = ETEGlobalUtils.getDatabaseConnector(countryCode);
            String dataObjectId = ETEGlobalUtils.doDecryptParams((String) requestParams.get('source'), countryCode);
            E2E_Data_Object__c dataObject = e2eDatabase.retrieveETEDataObject(dataObjectId);
            exceptionLogParamsMap.put('currentStep', dataObject.Current_Step__c);
            exceptionLogParamsMap.put('countryCode', dataObject.Country_Code__c);
            exceptionLogParamsMap.put('source', requestParams.get('source'));
        }
        if (! exceptionLogParamsMap.isEmpty()) {
            exceptionLogParamsMap.put('deviceType', deviceType);
            exceptionLogParamsMap.put('exceptionSource', exceptionSource);
            exceptionLogParamsMap.put('statusCode', statusCode);
            if (exceptionDetails != null) {
                errorMessage += ' (Cls: ' + exceptionDetails.getStackTraceString() + ')';
                exceptionLogParamsMap.put('exceptionType', 'System Error');
            } else {
                if (statusCode == 104 || statusCode == 100) {
                    exceptionLogParamsMap.put('exceptionType', 'Credit Logic');
                } else if (statusCode == 106) {
                    exceptionLogParamsMap.put('exceptionType', 'CF System Error');
                }
            }
            exceptionLogParamsMap.put('exceptionMessage', errorMessage);
        }
        return exceptionLogParamsMap;
    }


    public String convertResponseToJson(Map<String, Object> responseParams) {
        String responseJson = JSON.serialize(responseParams);
        return responseJson;
    }
}