default/objects/E2E_Data_Log__c/E2E_Data_Log__c.object-meta.xml
<CustomObject>
    <label>E2E Data Log</label>
    <nameField>
        <label>E2E Data Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Log__c/fields/Exception_Description__c.field-meta.xml
<CustomField>
    <fullName>Exception_Description__c</fullName>
    <label>Exception Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/E2E_Data_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System Error</fullName>
            </value>
            <value>
                <fullName>Process Error</fullName>
            </value>
            <value>
                <fullName>Credit Logic</fullName>
            </value>
            <value>
                <fullName>CF System Error</fullName>
            </value>
            <value>
                <fullName>Company search</fullName>
            </value>
            <value>
                <fullName>Credit Factory Error</fullName>
                <isActive>false</isActive>
                <label>Credit Factory Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Log__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Restart</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Log__c/recordTypes/Exception.recordType-meta.xml
<RecordType>
    <fullName>Exception</fullName>
    <active>true</active>
    <label>Exception</label>
</RecordType>

default/classes/ETEJobsQueue.cls
public class ETEJobsQueue implements Queueable, Database.AllowsCallouts {
    private String jobToRunName;
    private ETEJobExecutor jobExecutorImpl;
    private ETEDatabaseInterface e2eDatabase;
    private String dataObjectId;
    private E2E_Data_Log__c existingJobInDataBase;
    private Map<String, E2E_Data_Log__c>  existingJobsMap;


    public ETEJobsQueue (List<String> jobsNeededToRun, String dataObjectId, String countryCode, String implKey) {
        this.dataObjectId = dataObjectId;
        jobExecutorImpl = ETEGlobalUtils.getJobExecutor(jobsNeededToRun, dataObjectId, countryCode, implKey);
        jobToRunName = jobsNeededToRun.get(0);
        e2eDatabase = ETEGlobalUtils.getDatabaseConnector(countryCode);
        existingJobsMap = returnExistingJobs(e2eDatabase, this.dataObjectId);
        existingJobInDataBase = existingJobsMap.get(jobToRunName);
    }


    public void execute(QueueableContext sc) {
        try {
            switch on jobToRunName {
                when 'checkBusinessObjects' {
                    jobExecutorImpl.checkBusinessObjects(e2eDatabase, existingJobInDataBase);
                } when 'reportRequest' {
                    jobExecutorImpl.doReportRequest(e2eDatabase, existingJobInDataBase);
                } when 'deduplication' {
                    jobExecutorImpl.doDeduplication(e2eDatabase, existingJobInDataBase);
                } when 'syncProductsAndServices',
                        'syncContactData',
                        'syncCompanyDetails',
                        'syncAdditionalServices',
                        'syncCreditDecisionsData',
                        'syncDocumentsAgreements',
                        'syncPaymentDetails',
                        'syncPaymentData',
                        'syncFinishedDeal' {
                    jobExecutorImpl.syncData(e2eDatabase, existingJobsMap, existingJobInDataBase, jobToRunName);
                }
            }
        } catch (Exception e) {
            existingJobInDataBase.Exception_Type__c = 'System Error';
            existingJobInDataBase.Job_Status__c = 'Failed';
            existingJobInDataBase.Exception_Description__c = e.getMessage() + ': ' + e.getStackTraceString();
            e2eDatabase.upsertE2EDataLogs(new List<E2E_Data_Log__c>{existingJobInDataBase});
        }
    }


    private Map<String, E2E_Data_Log__c> returnExistingJobs(ETEDatabaseInterface e2eDatabase, String dataObjectId) {
        List<E2E_Data_Log__c> exsistingLogsList = e2eDatabase.retrieveE2EDataLogs(dataObjectId);
        Map<String, E2E_Data_Log__c>  existingJobsMap = new Map<String, E2E_Data_Log__c>();
        for (E2E_Data_Log__c job : exsistingLogsList) {
            existingJobsMap.put(job.Name, job);
        }
        return existingJobsMap;
    }
}