default/objects/GFNI_Log__e/GFNI_Log__e.object-meta.xml
<CustomObject>
    <label>GFNI_Log</label>
    <pluralLabel>GFNI_Logs</pluralLabel>
</CustomObject>

default/objects/GFNI_Log__e/fields/IsFirst__c.field-meta.xml
<CustomField>
    <fullName>IsFirst__c</fullName>
    <label>IsFirst</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/GFNI_Log__e/fields/LogType__c.field-meta.xml
<CustomField>
    <fullName>LogType__c</fullName>
    <label>LogType</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

default/objects/GFNI_Log__e/fields/LookupObjectId__c.field-meta.xml
<CustomField>
    <fullName>LookupObjectId__c</fullName>
    <label>LookupObjectId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

default/objects/GFNI_Log__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/GFNI_Log__e/fields/RecordDateTime__c.field-meta.xml
<CustomField>
    <fullName>RecordDateTime__c</fullName>
    <label>RecordDateTime</label>
    <type>DateTime</type>
</CustomField>

default/objects/GFNI_Log__e/fields/Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Request_Id__c</fullName>
    <label>Request Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/GFNI_Opportunity_log__b/GFNI_Opportunity_log__b.object-meta.xml
<CustomObject>
    <label>GFNI Opportunity Log</label>
    <pluralLabel>GFNI Opportunity Logs</pluralLabel>
</CustomObject>

default/objects/GFNI_Opportunity_log__b/fields/IsFirst__c.field-meta.xml
<CustomField>
    <fullName>IsFirst__c</fullName>
    <label>IsFirst</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/GFNI_Opportunity_log__b/fields/LogType__c.field-meta.xml
<CustomField>
    <fullName>LogType__c</fullName>
    <label>Log Type</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/GFNI_Opportunity_log__b/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/GFNI_Opportunity_log__b/fields/RecordDateTime__c.field-meta.xml
<CustomField>
    <fullName>RecordDateTime__c</fullName>
    <label>Record Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

default/objects/GFNI_Opportunity_log__b/fields/Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Request_Id__c</fullName>
    <label>Request Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/GFNI_Logger.cls
/**
 * Created by Nikita.Mikhailov on 18.01.2019.
 *
 * Class to create and store logs in scope of GFN Integration project
 * All logs saves to BigObject GFNI_Opportunity_log__b
 *
 * Have a static workaround to save List<GFNI_Logger>
 */
public with sharing class GFNI_Logger {

    public List<GFNI_Log__e> logEvents { get; set; }
    public Id opportunityId { get; set; }
    public Boolean isFirst { get; set; }
    private Integer secondsToAdd;

    public GFNI_Logger(Id opportunityId, Boolean isFirst) {
        this.opportunityId = opportunityId;
        this.isFirst = isFirst;
        //Adding from 0 to 42 seconds to be sure that this BigObject Id is unique
        //42 - the answer to life, universe and everything
        this.secondsToAdd = Math.round(Math.random() * 42);
        this.logEvents = new List<GFNI_Log__e>();
    }

    /*******************************************************************************
    *  Name            : addLog
    *  Summary         : adds new log to the logs list
    *  CreatedDate     : 18/01/2019
    *  Parameters      : String logType('Request, Response, Error, Message etc.'), String message, String requestId in request
    *  Returns         : void
    ******************************************************************************/
    public void addLog(String logType, String message, String requestId) {
        GFNI_Log__e logEvent = new GFNI_Log__e (
                Request_Id__c = requestId,
                RecordDateTime__c = System.now().addSeconds(this.secondsToAdd),
                LogType__c = logType,
                Message__c = message,
                LookupObjectId__c = this.opportunityId
        );

        if (this.isFirst) {
            logEvent.IsFirst__c = 1;
            this.isFirst = false;
        } else {
            logEvent.IsFirst__c = 0;
        }

        this.logEvents.add(logEvent);
    }

    /*******************************************************************************
    *  Name            : saveLogs
    *  Summary         : saves logs to the BigObject GFNI_Opportunity_log__b
    *  CreatedDate     : 18/01/2019
    *  Parameters      : none
    *  Returns         : void
    ******************************************************************************/
    public void saveLogs() {
        if (this.logEvents.isEmpty())
            return;

        EventBus.publish(this.logEvents);
    }

    /*******************************************************************************
    *  Name            : saveLogsList
    *  Summary         : static workaround for saving logs for different objects. Method just moves all logs to one list and saves to the BigObject GFNI_Opportunity_log__b
    *  CreatedDate     : 18/01/2019
    *  Parameters      : List<GFNI_Logger> list of loggers
    *  Returns         : void
    ******************************************************************************/
    public static void saveLogsList(List<GFNI_Logger> logs) {
        List<GFNI_Log__e> allLogs = new List<GFNI_Log__e>();

        for (GFNI_Logger i : logs) {
            for (GFNI_Log__e j : i.logEvents) {
                allLogs.add(j);
            }
        }

        EventBus.publish(allLogs);
    }
}