default/objects/GFNI_Log__e/GFNI_Log__e.object-meta.xml
<CustomObject>
    <label>GFNI_Log</label>
    <pluralLabel>GFNI_Logs</pluralLabel>
</CustomObject>

default/objects/GFNI_Log__e/fields/IsFirst__c.field-meta.xml
<CustomField>
    <fullName>IsFirst__c</fullName>
    <label>IsFirst</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/GFNI_Log__e/fields/LogType__c.field-meta.xml
<CustomField>
    <fullName>LogType__c</fullName>
    <label>LogType</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

default/objects/GFNI_Log__e/fields/LookupObjectId__c.field-meta.xml
<CustomField>
    <fullName>LookupObjectId__c</fullName>
    <label>LookupObjectId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

default/objects/GFNI_Log__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/GFNI_Log__e/fields/RecordDateTime__c.field-meta.xml
<CustomField>
    <fullName>RecordDateTime__c</fullName>
    <label>RecordDateTime</label>
    <type>DateTime</type>
</CustomField>

default/objects/GFNI_Log__e/fields/Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Request_Id__c</fullName>
    <label>Request Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/GFNI_Opportunity_log__b/GFNI_Opportunity_log__b.object-meta.xml
<CustomObject>
    <label>GFNI Opportunity Log</label>
    <pluralLabel>GFNI Opportunity Logs</pluralLabel>
</CustomObject>

default/objects/GFNI_Opportunity_log__b/fields/IsFirst__c.field-meta.xml
<CustomField>
    <fullName>IsFirst__c</fullName>
    <label>IsFirst</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/GFNI_Opportunity_log__b/fields/LogType__c.field-meta.xml
<CustomField>
    <fullName>LogType__c</fullName>
    <label>Log Type</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/GFNI_Opportunity_log__b/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/GFNI_Opportunity_log__b/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>GFNI_Opportunity_log</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/objects/GFNI_Opportunity_log__b/fields/RecordDateTime__c.field-meta.xml
<CustomField>
    <fullName>RecordDateTime__c</fullName>
    <label>Record Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

default/objects/GFNI_Opportunity_log__b/fields/Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Request_Id__c</fullName>
    <label>Request Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/GFNI_LogEventTriggerHandler.cls
/**
 * Created by Nikita.Mikhailov on 19.10.2020.
 */

public with sharing class GFNI_LogEventTriggerHandler {
    public static void storeLogs(List<GFNI_Log__e> newLogEvents) {
        List<GFNI_Opportunity_log__b> logs = new List<GFNI_Opportunity_log__b>();

        for (GFNI_Log__e logEvent : newLogEvents) {
            GFNI_Opportunity_log__b log = new GFNI_Opportunity_log__b(
                    IsFirst__c = logEvent.IsFirst__c,
                    LogType__c = logEvent.LogType__c,
                    Opportunity__c = logEvent.LookupObjectId__c,
                    Message__c = logEvent.Message__c,
                    RecordDateTime__c = logEvent.RecordDateTime__c,
                    Request_Id__c = logEvent.Request_Id__c
            );
            logs.add(log);
        }

        System.debug('INSERTING LOGS ' + logs);

        if (!Test.isRunningTest())
            Database.insertImmediate(logs);
    }
}