default/objects/Contact/fields/Opportunity_Scoring__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Scoring__c</fullName>
    <description>Scoring from the parent Opportunity</description>
    <label>Opportunity Scoring</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Form_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Form_of_Payment__c</fullName>
    <label>Order Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer - after delivery</fullName>
            </value>
            <value>
                <fullName>Advanced payment</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Monthly_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Payment_Method__c</fullName>
    <label>Monthly Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bank transfer</fullName>
            </value>
            <value>
                <fullName>Your existing payment method</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Number_of_GPS_units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_GPS_units__c</fullName>
    <description>Number of Carnet Units - updated by Sales people as forecasted number &amp; when they create order and order units (Shell) or when Merlin adds ordered units (CCS) it is updated with correct number according to the custom objects.</description>
    <inlineHelpText>Number of Carnet Units (Telematics)</inlineHelpText>
    <label>Number of GPS units</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Pricing_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Approval_Status__c</fullName>
    <description>Status of Approval on Opportunity with relation to Carnet Unit object.</description>
    <label>Pricing Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not required</fullName>
                <default>true</default>
                <label>Not required</label>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product *</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BE-FR 2,5 Cent</fullName>
            </value>
            <value>
                <fullName>Carnet OBD</fullName>
            </value>
            <value>
                <fullName>Carnet Standard 2019</fullName>
            </value>
            <value>
                <fullName>Fuel Vehicle</fullName>
            </value>
            <value>
                <fullName>HOME 1</fullName>
            </value>
            <value>
                <fullName>Home Station offer (v.1)</fullName>
            </value>
            <value>
                <fullName>Inbound Typ B</fullName>
            </value>
            <value>
                <fullName>Inbound Typ C</fullName>
            </value>
            <value>
                <fullName>LOCAL - RED</fullName>
            </value>
            <value>
                <fullName>LOCAL - YELLOW</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes No fee</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes Standard</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>Sales no fee promo Feb 2016</fullName>
            </value>
            <value>
                <fullName>Shell Basic 2020</fullName>
            </value>
            <value>
                <fullName>Shell No fee 2020</fullName>
            </value>
            <value>
                <fullName>Shell Outbound 2020</fullName>
            </value>
            <value>
                <fullName>Shell Universal Card</fullName>
            </value>
            <value>
                <fullName>Smart</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + % fee)</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + fixed fee)</fullName>
            </value>
            <value>
                <fullName>Sonderangebot (s. Notizen)</fullName>
            </value>
            <value>
                <fullName>Swiss Pro</fullName>
            </value>
            <value>
                <fullName>Swiss Pro 5</fullName>
            </value>
            <value>
                <fullName>Swiss Star</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/recordTypes/Carnet.recordType-meta.xml
<RecordType>
    <fullName>Carnet</fullName>
    <active>true</active>
    <businessProcess>Carnet</businessProcess>
    <description>Record Type for Carnet records.</description>
    <label>Carnet</label>
</RecordType>

default/classes/OpportunityContactRoleTriggerTest.cls
@IsTest
private class OpportunityContactRoleTriggerTest {
    @TestSetup
    static void createTestData() {
        String carnetOppoRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Carnet').getRecordTypeId();
    
        Account acc = new Account(
                Name = 'TEST',
                BillingCountry = 'Poland',
                BillingCity = 'BERG',
                BillingStreet = 'LUDWIGSTRASSE 69');
        insert acc;

        Contact con1 = new Contact(
                Salutation = 'Herr',
                LastName = 'TEST1',
                AccountId = acc.Id,
                Email = 'test@test.com');
        Contact con2 = new Contact(
                Salutation = 'Herr',
                LastName = 'TEST2',
                AccountId = acc.Id,
                Email = 'test@test.com',
                Opportunity_Scoring__c = 20);
        Contact con3 = new Contact(
                Salutation = 'Herr',
                LastName = 'TEST3',
                AccountId = acc.Id,
                Email = 'test@test.com');
        Contact con4 = new Contact(
                Salutation = 'Herr',
                LastName = 'TEST4',
                AccountId = acc.Id,
                Email = 'test@test.com');
        Contact con5 = new Contact(
                Salutation = 'Herr',
                LastName = 'TEST5',
                AccountId = acc.Id,
                Email = 'test@test.com');
        insert new List <Contact> {con1, con2, con3, con4, con5};

        Opportunity opp1 = new Opportunity(
            Name = 'TEST1',
            Product__c = 'Carnet Standard 2019',
            RecordTypeId = carnetOppoRecId,
            AccountId = acc.id,
            CloseDate = Date.today(),
            StageName = 'Qualify',
            Type = 'New GFN',
            Form_of_Payment__c = 'Bank Transfer - after delivery',
            Monthly_Payment_Method__c = 'Bank transfer',
            Number_of_GPS_units__c = 3,
            Pricing_Approval_Status__c = 'Not required');
        Opportunity opp2 = new Opportunity(
                Name = 'TEST2',
                Product__c = 'Carnet Standard 2019',
                RecordTypeId = carnetOppoRecId,
                AccountId = acc.id,
                CloseDate = Date.today(),
                StageName = 'Qualify',
                Type = 'New GFN',
                Form_of_Payment__c = 'Bank Transfer - after delivery',
                Monthly_Payment_Method__c = 'Bank transfer',
                Number_of_GPS_units__c = 3,
                Pricing_Approval_Status__c = 'Not required');
        insert new List <Opportunity> {opp1, opp2};
    }

    @IsTest
    static void testSetOpportunityScoreOnContacts_OneOpptyScored() {
        // -------- Test case 1: --- one oppty only, scored, scoring is not set on contact yet ---
        // current scoring on the contact: null
        // existing open oppties the highest score: 33
        // score to set: 33 (the highest score from all open oppties)
        Map <String, opportunity> oppsByNameMap = new Map <String, Opportunity>();
        List <Opportunity> testOpps = [SELECT Id, Name FROM Opportunity];
        for (Opportunity opp: testOpps) {
            oppsByNameMap.put(opp.Name, opp);
        }
        Contact testCon = [SELECT Opportunity_Scoring__c from Contact WHERE LastName = 'TEST1'];

        OpportunityContactRole ocr_existingOpp = new OpportunityContactRole(
            OpportunityId = oppsByNameMap.get('TEST1').Id,
            ContactId = testCon.Id,
            IsPrimary = true
        );
        insert ocr_existingOpp; // add 1 existing open opportunity related to a contact

        ContactScoreHandler.theHighestScoreForTesting =  33;

        Test.startTest();
            OpportunityContactRole ocr = new OpportunityContactRole(
                OpportunityId = oppsByNameMap.get('TEST2').Id,
                ContactId = testCon.Id,
                IsPrimary = true
            );
            insert ocr; // add second opportunity related to a contact

            Contact updatedCon = [SELECT Opportunity_Scoring__c from Contact WHERE Id = :testCon.Id];
            system.assertEquals(33, updatedCon.Opportunity_Scoring__c);
        Test.stopTest();
    }

    @IsTest
    static void testSetOpportunityScoreOnContacts_OpptyScoredAndContactScored() {
        // -------- Test case 2: --- one oppty only, scored, contact scoring is set ---
        // current scoring on the contact: 20
        // existing open oppties the highest score: 15
        // score to set: 15 (the highest score from all open oppties)

        Map <String, opportunity> oppsByNameMap = new Map <String, Opportunity>();
        List <Opportunity> testOpps = [SELECT Id, Name FROM Opportunity];
        for (Opportunity opp: testOpps) {
            oppsByNameMap.put(opp.Name, opp);
        }
        Contact testCon = [SELECT Opportunity_Scoring__c from Contact WHERE LastName = 'TEST2'];

        OpportunityContactRole ocr_existingOpp = new OpportunityContactRole(
            OpportunityId = oppsByNameMap.get('TEST1').Id,
            ContactId = testCon.Id,
            IsPrimary = true
        );
        insert ocr_existingOpp; // add 1 existing open opportunity related to a contact

        ContactScoreHandler.theHighestScoreForTesting =  15;

        Test.startTest();
            OpportunityContactRole ocr = new OpportunityContactRole(
                OpportunityId = oppsByNameMap.get('TEST2').Id,
                ContactId = testCon.Id,
                IsPrimary = true
            );
            insert ocr;

            Contact updatedCon = [SELECT Opportunity_Scoring__c from Contact WHERE Id = :testCon.Id];
            system.assertEquals(15, updatedCon.Opportunity_Scoring__c);
        Test.stopTest();
    }

    @IsTest
    static void testSetOpportunityScoreOnContacts_OpptyNotScored() {
        // -------- Test case 3: --- oppty not scored ---
        // current scoring on the contact: null
        // existing open oppties the highest score: null
        // score to set: none

        Opportunity testOpp = [SELECT Id from Opportunity WHERE Name = 'TEST1'];
        Contact testCon = [SELECT Opportunity_Scoring__c from Contact WHERE LastName = 'TEST3'];
        ContactScoreHandler.theHighestScoreForTesting = null;

        Test.startTest();
            OpportunityContactRole ocr = new OpportunityContactRole(
                OpportunityId = testOpp.Id,
                ContactId = testCon.Id,
                IsPrimary = true
            );
            insert ocr;

            Contact updatedCon = [SELECT Opportunity_Scoring__c from Contact WHERE Id = :testCon.Id];
            system.assertEquals(null, updatedCon.Opportunity_Scoring__c);
        Test.stopTest();
    }
    
    @IsTest
    static void testSetOpportunityScoreOnContacts_FewContacts() {
        // -------- Test case 4: --- a few contacts added, one oppty scored ---
        // current scoring on the contact: null
        // existing open oppties the highest score: 30
        // score to set: 30

        Map <String, opportunity> oppsByNameMap = new Map <String, Opportunity>();
        List <Opportunity> testOpps = [SELECT Id, Name FROM Opportunity];
        for (Opportunity opp: testOpps) {
            oppsByNameMap.put(opp.Name, opp);
        }
        Map <Id, Contact> testConsMap = new Map <Id, Contact>([SELECT Id, Opportunity_Scoring__c from Contact WHERE LastName IN ('TEST4', 'TEST5')]);
        
        OpportunityContactRole ocr_existingOpp1 = new OpportunityContactRole(
            OpportunityId = oppsByNameMap.get('TEST1').Id,
            ContactId = testConsMap.values()[0].Id,
            IsPrimary = true
        );
        OpportunityContactRole ocr_existingOpp2 = new OpportunityContactRole(
            OpportunityId = oppsByNameMap.get('TEST1').Id,
            ContactId = testConsMap.values()[1].Id,
            IsPrimary = true
        );
        insert new List <OpportunityContactRole> {ocr_existingOpp1, ocr_existingOpp2}; // add 2 existing open opportunity related to a contact
        
        
        ContactScoreHandler.theHighestScoreForTesting = 30;

        Test.startTest();
            OpportunityContactRole ocr1 = new OpportunityContactRole(
                OpportunityId = oppsByNameMap.get('TEST2').Id,
                ContactId = testConsMap.values()[0].Id,
                IsPrimary = true
            );
            OpportunityContactRole ocr2 = new OpportunityContactRole(
                OpportunityId = oppsByNameMap.get('TEST2').Id,
                ContactId = testConsMap.values()[1].Id,
                IsPrimary = true
            );
            insert new List <OpportunityContactRole> {ocr1, ocr2};

            Map <Id, Contact> updatedConsMap = new Map <Id, Contact> ([SELECT Opportunity_Scoring__c from Contact WHERE Id IN :testConsMap.keyset()]);
            system.assertEquals(30, updatedConsMap.get(ocr1.ContactId).Opportunity_Scoring__c);
            system.assertEquals(30, updatedConsMap.get(ocr2.ContactId).Opportunity_Scoring__c);
        Test.stopTest();
    }
}