default/objects/Lead/recordTypes/Russian_Sales.recordType-meta.xml
<RecordType>
    <fullName>Russian_Sales</fullName>
    <active>true</active>
    <businessProcess>Russian Sales</businessProcess>
    <label>Russian Sales</label>
</RecordType>

default/objects/Naumen_Settings__c/Naumen_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for integration with Naumen CTI</description>
    <label>Naumen Settings</label>
</CustomObject>

default/objects/Naumen_Settings__c/fields/Admin_Emails__c.field-meta.xml
<CustomField>
    <fullName>Admin_Emails__c</fullName>
    <description>Admin Emails who will get errors notifications.</description>
    <inlineHelpText>example: &quot;test1@test.com,test2@test.com&quot;</inlineHelpText>
    <label>Admin Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Naumen_Settings__c/fields/REST_Passw__c.field-meta.xml
<CustomField>
    <fullName>REST_Passw__c</fullName>
    <description>Credentials for Naumen REST API</description>
    <label>REST Passw</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Naumen_Settings__c/fields/REST_URL__c.field-meta.xml
<CustomField>
    <fullName>REST_URL__c</fullName>
    <label>REST URL</label>
    <type>Url</type>
</CustomField>

default/objects/Naumen_Settings__c/fields/REST_Username__c.field-meta.xml
<CustomField>
    <fullName>REST_Username__c</fullName>
    <description>Credentials for Naumen REST API</description>
    <label>REST Username</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Naumen_Settings__c/fields/Supervisor_Emails__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_Emails__c</fullName>
    <description>Supervisor Emails who will get info notifications in certain cases.</description>
    <inlineHelpText>example: &quot;test1@test.com,test2@test.com&quot;</inlineHelpText>
    <label>Supervisor Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Naumen_Settings__c/fields/UploadResultsRecievers_Emails__c.field-meta.xml
<CustomField>
    <fullName>UploadResultsRecievers_Emails__c</fullName>
    <description>Emails to which upload results will be sent while uploading SF records to naumen autocall cases (Naumen Supervisor Panel uploading functionality)</description>
    <inlineHelpText>example: &quot;test1@test.com,test2@test.com&quot;</inlineHelpText>
    <label>Upload Results Recievers Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/classes/Naumen_UploadRecordsBatchTest.cls
@IsTest
public class Naumen_UploadRecordsBatchTest {
    @testSetup
    private static void setupData() {
        Naumen_Settings__c naumenSettings = new Naumen_Settings__c();
        naumenSettings.Admin_Emails__c = 'test@test.ru';
        naumenSettings.Supervisor_Emails__c = 'test1@test.ru';
        naumenSettings.UploadResultsRecievers_Emails__c = 'test2@test.ru';
        naumenSettings.REST_Passw__c = 'testpassw';
        naumenSettings.REST_URL__c = 'https://test.ru';
        naumenSettings.REST_Username__c = 'testusername';
        insert naumenSettings;

        Id leadRTIdRu = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Russian_Sales').getRecordTypeId();
        Lead newLead = new Lead(
            RecordTypeId = leadRTIdRu,
            FirstName = 'test name',
            LastName = 'l',
            Description = 'text 1.',
            Country = 'Russia',
            CountryCode = 'RU',
            Company = 'TestCompany',
            Phone = '+78887770000'
        );
        insert newLead;
    }
    @IsTest
    private static void testBatch_CheckRecordsAccess() {
        Test.startTest();
        List <String> queryFields = Naumen_SupervisorPanelCtrl.getFieldsToQueryRecord (Schema.Lead.sObjectType); 
        String query = 'SELECT ' + String.join(queryFields, ', ') + ' FROM Lead';
        String projectUUID = '11111';
        DateTime scheduledTime = system.now().addDays(1);
        Naumen_UploadRecordsBatch batch = new Naumen_UploadRecordsBatch ('Lead', query, true, projectUUID);
        Database.executeBatch(batch, 1);
        Test.stopTest();
    }
    @IsTest
    private static void testBatch_DontCheckRecordsAccess() {
        Test.startTest();
        String resultCaseUUID = 'ocpcas00000000000n7iar4b75sm4v7o';
        SingleRequestMock casesResultMock = new SingleRequestMock(200, null, '{"result":[{"code":"SUCCESS","value":"' + resultCaseUUID + '"}]}', null);
        Test.setMock(HttpCalloutMock.class, casesResultMock);
        List <String> queryFields = Naumen_SupervisorPanelCtrl.getFieldsToQueryRecord (Schema.Lead.sObjectType); 
        String query = 'SELECT ' + String.join(queryFields, ', ') + ' FROM Lead';
        String projectUUID = '11111';
        DateTime scheduledTime = system.now().addDays(1);
        system.debug(Database.query(query));
        Naumen_UploadRecordsBatch batch = new Naumen_UploadRecordsBatch ('Lead', query, false, projectUUID);
        Database.executeBatch(batch, 1);
        Test.stopTest();
    }
}