default/objects/FieldSalesTerritory_General_Settings__c/FieldSalesTerritory_General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>FieldSalesTerritory General Settings</label>
</CustomObject>

default/objects/FieldSalesTerritory_General_Settings__c/fields/Penalty_for_refusal__c.field-meta.xml
<CustomField>
    <fullName>Penalty_for_refusal__c</fullName>
    <label>Penalty for refusal</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Lead/fields/Anzahl_der_Fahrzeuge__c.field-meta.xml
<CustomField>
    <fullName>Anzahl_der_Fahrzeuge__c</fullName>
    <label>Anzahl der Fahrzeuge?</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Lead/fields/Beschaeftigte__c.field-meta.xml
<CustomField>
    <fullName>Beschaeftigte__c</fullName>
    <label>Beschäftigte</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1-4</fullName>
            </value>
            <value>
                <fullName>5-9</fullName>
            </value>
            <value>
                <fullName>10-19</fullName>
            </value>
            <value>
                <fullName>20-49</fullName>
            </value>
            <value>
                <fullName>50-74</fullName>
            </value>
            <value>
                <fullName>75-99</fullName>
            </value>
            <value>
                <fullName>100-149</fullName>
            </value>
            <value>
                <fullName>150-199</fullName>
            </value>
            <value>
                <fullName>&gt;200</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>1-9</fullName>
                <isActive>false</isActive>
                <label>1-9</label>
            </value>
            <value>
                <fullName>1.000-1.999</fullName>
                <isActive>false</isActive>
                <label>1.000-1.999</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>10 - 19</fullName>
                <isActive>false</isActive>
                <label>10 - 19</label>
            </value>
            <value>
                <fullName>10-19 Beschäftigte</fullName>
                <isActive>false</isActive>
                <label>10-19 Beschäftigte</label>
            </value>
            <value>
                <fullName>100</fullName>
                <isActive>false</isActive>
                <label>100</label>
            </value>
            <value>
                <fullName>100 - 199</fullName>
                <isActive>false</isActive>
                <label>100 - 199</label>
            </value>
            <value>
                <fullName>100-199</fullName>
                <isActive>false</isActive>
                <label>100-199</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000</fullName>
                <isActive>false</isActive>
                <label>1000</label>
            </value>
            <value>
                <fullName>101</fullName>
                <isActive>false</isActive>
                <label>101</label>
            </value>
            <value>
                <fullName>101-150</fullName>
                <isActive>false</isActive>
                <label>101-150</label>
            </value>
            <value>
                <fullName>102</fullName>
                <isActive>false</isActive>
                <label>102</label>
            </value>
            <value>
                <fullName>1026</fullName>
                <isActive>false</isActive>
                <label>1026</label>
            </value>
            <value>
                <fullName>1027</fullName>
                <isActive>false</isActive>
                <label>1027</label>
            </value>
            <value>
                <fullName>103</fullName>
                <isActive>false</isActive>
                <label>103</label>
            </value>
            <value>
                <fullName>104</fullName>
                <isActive>false</isActive>
                <label>104</label>
            </value>
            <value>
                <fullName>105</fullName>
                <isActive>false</isActive>
                <label>105</label>
            </value>
            <value>
                <fullName>106</fullName>
                <isActive>false</isActive>
                <label>106</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Duplicate_Record_Mark__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Record_Mark__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Флаг того что запись помечена как "Дубликат" (есть более актуальный аналог)</description>
    <label>Duplicate Record Mark</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Lead/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Tax identification number
        Must contain only numbers:
        Length 12 symbols for PE;
        Length 10 symbols for legal person.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Partner_OBN__c.field-meta.xml
<CustomField>
    <fullName>Partner_OBN__c</fullName>
    <label>Partner-OBN</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Rating_FS_Penalty__c.field-meta.xml
<CustomField>
    <fullName>Rating_FS_Penalty__c</fullName>
    <label>Rating FS Penalty</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region - field for Russian addresses</description>
    <inlineHelpText>Region - field for Russian addresses</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Central Bohemia</fullName>
            </value>
            <value>
                <fullName>Prague</fullName>
            </value>
            <value>
                <fullName>Алтайский край</fullName>
            </value>
            <value>
                <fullName>Амурская область</fullName>
            </value>
            <value>
                <fullName>Архангельская область</fullName>
            </value>
            <value>
                <fullName>Астраханская область</fullName>
            </value>
            <value>
                <fullName>Байконур</fullName>
            </value>
            <value>
                <fullName>Белгородская область</fullName>
            </value>
            <value>
                <fullName>Брянская область</fullName>
            </value>
            <value>
                <fullName>Владимирская область</fullName>
            </value>
            <value>
                <fullName>Волгоградская область</fullName>
            </value>
            <value>
                <fullName>Вологодская область</fullName>
            </value>
            <value>
                <fullName>Воронежская область</fullName>
            </value>
            <value>
                <fullName>Еврейская автономная область</fullName>
            </value>
            <value>
                <fullName>Забайкальский край</fullName>
            </value>
            <value>
                <fullName>Ивановская область</fullName>
            </value>
            <value>
                <fullName>Иркутская область</fullName>
            </value>
            <value>
                <fullName>Кабардино-Балкарская Республика</fullName>
            </value>
            <value>
                <fullName>Калининградская область</fullName>
            </value>
            <value>
                <fullName>Калужская область</fullName>
            </value>
            <value>
                <fullName>Камчатский край</fullName>
            </value>
            <value>
                <fullName>Карачаево-Черкесская Республика</fullName>
            </value>
            <value>
                <fullName>Кемеровская область</fullName>
            </value>
            <value>
                <fullName>Кировская область</fullName>
            </value>
            <value>
                <fullName>Костромская область</fullName>
            </value>
            <value>
                <fullName>Краснодарский край</fullName>
            </value>
            <value>
                <fullName>Красноярский край</fullName>
            </value>
            <value>
                <fullName>Курганская область</fullName>
            </value>
            <value>
                <fullName>Курская область</fullName>
            </value>
            <value>
                <fullName>Ленинградская область</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/LeadPenaltyDecreaseBatchTest.cls
@isTest
private class LeadPenaltyDecreaseBatchTest {
	@testSetup static void setup() {
	//----- CUSTOM SETTINGS -----
		FieldSalesTerritory_General_Settings__c fieldSalesSettings = new FieldSalesTerritory_General_Settings__c(
                Name = 'RU',
                Penalty_for_refusal__c = 365
        );
        insert fieldSalesSettings;
    }

	@isTest static void mainTest() {
    /* test decreasing lead penalty rating
	*/
    //----- OWNER -----
        User buddy = [SELECT Id FROM  User
                      WHERE Id IN (SELECT AssigneeId
                                  FROM PermissionSetAssignment
                                  WHERE PermissionSet.Name = 'FieldSalesTerritory_buddy')
                      LIMIT 1];
    //----- LEADS -----
		Id russianLeadRT = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Russian Sales').getRecordTypeId();
		Lead lead1 = new Lead (
			RecordTypeId = russianLeadRT,
			OwnerId = buddy.Id,
			Salutation = 'Herr1',
			LastName = 'Test LastName',
			LeadSource = 'Partner',
			Rating_FS__c = 30,
			Rating_FS_Penalty__c = 100,
			Status = 'Disqualified',
			Duplicate_Record_Mark__c = false,
			IsConverted = false,
			Phone = '+71231111111',
			Company = 'test1',
			Country = 'Russia',
	        Region__c = 'Кировская область',
			Street = 'САНКТ-ПЕТЕРБУРГ',
	        Partner_OBN__c = '123123',
	        INN__c = '234234123423',
	        Branche_NACE__c = 'Apotheken - 4773',
	        Anzahl_der_Fahrzeuge__c = 5,
	        Beschaeftigte__c = '1-4',
	        Sec_Channel__c = 'Inbound'
		);
		insert new List <Lead> {lead1};
	// ----- START TEST -----
		Test.startTest();
		LeadPenaltyDecreaseBatch batch = new LeadPenaltyDecreaseBatch ();
		database.executeBatch(batch, 200);
		Test.stopTest();
	}

	@isTest static void testEmpty() {
	/* no leads to decrease rating in the batch
	*/
    //----- OWNER -----
        User buddy = [SELECT Id FROM  User
                      WHERE Id IN (SELECT AssigneeId
                                  FROM PermissionSetAssignment
                                  WHERE PermissionSet.Name = 'FieldSalesTerritory_buddy')
                      LIMIT 1];
    //----- LEADS -----
		Id russianLeadRT = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Russian Sales').getRecordTypeId();
		Lead lead1 = new Lead (
			RecordTypeId = russianLeadRT,
			OwnerId = buddy.Id,
			Salutation = 'Herr1',
			LastName = 'Test LastName',
			LeadSource = 'Partner',
			Rating_FS__c = 30,
			Rating_FS_Penalty__c = 0, //  no penalty rating to decrease
			Status = 'Disqualified',
			Duplicate_Record_Mark__c = false,
			IsConverted = false,
			Phone = '+71231111111',
			Company = 'test1',
			Country = 'Russia',
	        Region__c = 'Кировская область',
			Street = 'САНКТ-ПЕТЕРБУРГ',
	        Partner_OBN__c = '123123',
	        INN__c = '234234123423',
	        Branche_NACE__c = 'Apotheken - 4773',
	        Anzahl_der_Fahrzeuge__c = 5,
	        Beschaeftigte__c = '1-4',
	        Sec_Channel__c = 'Inbound'
		);
		insert new List <Lead> {lead1};
	// ----- START TEST -----
		Test.startTest();
		LeadPenaltyDecreaseBatch batch = new LeadPenaltyDecreaseBatch ();
		database.executeBatch(batch, 200);
		Test.stopTest();
	}
}