default/objects/Account_GFN_Report_Email_Params__c/Account_GFN_Report_Email_Params__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Params for mailing an Account Report to GFN</description>
    <label>Account GFN Report Email Params</label>
</CustomObject>

default/objects/Account_GFN_Report_Email_Params__c/fields/Attach_format__c.field-meta.xml
<CustomField>
    <fullName>Attach_format__c</fullName>
    <description>A format for an attached file (starts from &quot;.&quot;)</description>
    <label>Attach format</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/objects/Account_GFN_Report_Email_Params__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The report will send on this email</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

default/objects/Account_GFN_Report_Email_Params__c/fields/Email_body__c.field-meta.xml
<CustomField>
    <fullName>Email_body__c</fullName>
    <description>This text will be in an email body</description>
    <label>Email body</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

default/objects/Account_GFN_Report_Email_Params__c/fields/Test_mode__c.field-meta.xml
<CustomField>
    <fullName>Test_mode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Enabled the report will send on Robot email and on Test email from custom settings (DEBUG MODE)</description>
    <inlineHelpText>If Enabled the report will send on Robot email and on Test email from custom settings (DEBUG MODE)</inlineHelpText>
    <label>Test mode</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2E_Data_Object__c/E2E_Data_Object__c.object-meta.xml
<CustomObject>
    <label>E2E Data Object</label>
    <nameField>
        <label>E2E Data Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Object__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>de</fullName>
            </value>
            <value>
                <fullName>at</fullName>
            </value>
            <value>
                <fullName>nl</fullName>
            </value>
            <value>
                <fullName>pl</fullName>
            </value>
            <value>
                <fullName>hu</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>befr</fullName>
            </value>
            <value>
                <fullName>benl</fullName>
            </value>
            <value>
                <fullName>chde</fullName>
            </value>
            <value>
                <fullName>chfr</fullName>
            </value>
            <value>
                <fullName>sk</fullName>
            </value>
            <value>
                <fullName>cz</fullName>
            </value>
            <value>
                <fullName>lu</fullName>
            </value>
            <value>
                <fullName>be_fr</fullName>
                <isActive>false</isActive>
                <label>be_fr</label>
            </value>
            <value>
                <fullName>be_nl</fullName>
                <isActive>false</isActive>
                <label>be_nl</label>
            </value>
            <value>
                <fullName>ch_de</fullName>
                <isActive>false</isActive>
                <label>ch_de</label>
            </value>
            <value>
                <fullName>ch_fr</fullName>
                <isActive>false</isActive>
                <label>ch_fr</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Security_Amount_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Security_Amount_To_Pay__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Security Amount To Pay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Selected_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Selected_Company_Name__c</fullName>
    <label>Selected Company Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/recordTypes/Germany.recordType-meta.xml
<RecordType>
    <fullName>Germany</fullName>
    <active>true</active>
    <label>Germany</label>
</RecordType>

default/objects/E2E_Data_Object__c/recordTypes/Poland.recordType-meta.xml
<RecordType>
    <fullName>Poland</fullName>
    <active>true</active>
    <label>Poland</label>
</RecordType>

default/objects/E2E_Form_General_Settings__c/E2E_Form_General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>E2E Form General Settings</label>
</CustomObject>

default/objects/E2E_Form_General_Settings__c/fields/Enable_authorization_non_granted_check__c.field-meta.xml
<CustomField>
    <fullName>Enable_authorization_non_granted_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable authorization non granted check</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2E_Form_General_Settings__c/fields/Files_Generator_Url__c.field-meta.xml
<CustomField>
    <fullName>Files_Generator_Url__c</fullName>
    <label>Files Generator Url</label>
    <type>Url</type>
</CustomField>

default/objects/E2E_Form_General_Settings__c/fields/Payment_URL__c.field-meta.xml
<CustomField>
    <fullName>Payment_URL__c</fullName>
    <label>Payment URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Form_General_Settings__c/fields/Set_GFN_Status__c.field-meta.xml
<CustomField>
    <fullName>Set_GFN_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Set GFN Status</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2EKeysAPI__c/E2EKeysAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Key values for e2e form</description>
    <label>E2EKeysAPI</label>
</CustomObject>

default/objects/E2EKeysAPI__c/fields/AES256_Key__c.field-meta.xml
<CustomField>
    <fullName>AES256_Key__c</fullName>
    <label>AES256_Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/E2EKeysAPI__c/fields/paymentTransactionURL__c.field-meta.xml
<CustomField>
    <fullName>paymentTransactionURL__c</fullName>
    <label>paymentTransactionURL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/E2EKeysAPI__c/fields/PSPID__c.field-meta.xml
<CustomField>
    <fullName>PSPID__c</fullName>
    <description>Ingenico PSPID</description>
    <label>PSPID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/E2EKeysAPI__c/fields/SHA_KeyIn__c.field-meta.xml
<CustomField>
    <fullName>SHA_KeyIn__c</fullName>
    <label>SHA_KeyIn</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

default/objects/E2EKeysAPI__c/fields/SHA_KeyOut__c.field-meta.xml
<CustomField>
    <fullName>SHA_KeyOut__c</fullName>
    <label>SHA_KeyOut</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

default/objects/GFNI_General_Settings__c/GFNI_General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>GFNI General Settings</label>
</CustomObject>

default/objects/GFNI_General_Settings__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <defaultValue>(&quot;/applicationstatus&quot;)</defaultValue>
    <label>Application Status URI</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/GFNI_General_Settings__c/fields/Create_Customer_and_Cards__c.field-meta.xml
<CustomField>
    <fullName>Create_Customer_and_Cards__c</fullName>
    <defaultValue>(&quot;/customer&quot;)</defaultValue>
    <label>Create Customer and Cards URI</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/GFNI_General_Settings__c/fields/Get_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Get_Customer_Id__c</fullName>
    <label>Get Customer Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/GFNI_General_Settings__c/fields/IsForRobot__c.field-meta.xml
<CustomField>
    <fullName>IsForRobot__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is For Robot</label>
    <type>Checkbox</type>
</CustomField>

default/objects/GFNI_General_Settings__c/fields/Number_Of_Send_Tries__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Send_Tries__c</fullName>
    <defaultValue>(3)</defaultValue>
    <label>Number Of Send Tries</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/GFNI_General_Settings__c/fields/Prod_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Prod_Endpoint__c</fullName>
    <label>Prod Endpoint</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/GFNI_General_Settings__c/fields/Support_email__c.field-meta.xml
<CustomField>
    <fullName>Support_email__c</fullName>
    <label>Support email</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/GFNI_General_Settings__c/fields/Test_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Test_Endpoint__c</fullName>
    <label>Test Endpoint</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

default/objects/GFNI_General_Settings__c/fields/Test_mode__c.field-meta.xml
<CustomField>
    <fullName>Test_mode__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>(DEBUG MODE)</inlineHelpText>
    <label>Test mode</label>
    <type>Checkbox</type>
</CustomField>

default/objects/GFNI_General_Settings__c/fields/Test_support_email__c.field-meta.xml
<CustomField>
    <fullName>Test_support_email__c</fullName>
    <label>Test support email</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/GFNI_General_Settings__c/fields/test_x_ibm_client_id__c.field-meta.xml
<CustomField>
    <fullName>test_x_ibm_client_id__c</fullName>
    <label>test_x_ibm_client_id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/GFNI_General_Settings__c/fields/test_x_ibm_client_secret__c.field-meta.xml
<CustomField>
    <fullName>test_x_ibm_client_secret__c</fullName>
    <label>test_x_ibm_client_secret</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/GFNI_General_Settings__c/fields/x_ibm_client_id__c.field-meta.xml
<CustomField>
    <fullName>x_ibm_client_id__c</fullName>
    <label>x_ibm_client_id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/GFNI_General_Settings__c/fields/x_ibm_client_secret__c.field-meta.xml
<CustomField>
    <fullName>x_ibm_client_secret__c</fullName>
    <label>x_ibm_client_secret</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Data_Object__c.field-meta.xml
<CustomField>
    <fullName>E2E_Data_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E2E Data Object</label>
    <referenceTo>E2E_Data_Object__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Opportunity/fields/E2E_payment_status__c.field-meta.xml
<CustomField>
    <fullName>E2E_payment_status__c</fullName>
    <label>E2E payment status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Garantie_other__c.field-meta.xml
<CustomField>
    <fullName>Garantie_other__c</fullName>
    <label>Garantie – Betrag</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Security_Amount_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Security_Amount_To_Pay__c</fullName>
    <label>Security Amount To Pay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <label>Payment Transaction</label>
    <nameField>
        <label>Payment Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Payment_Transaction__c/fields/Authorized__c.field-meta.xml
<CustomField>
    <fullName>Authorized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorized</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Payment_Transaction__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Сurrency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/objects/Payment_Transaction__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Payment_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/classes/PaymentTransactionHandlerTest.cls
@isTest
private class PaymentTransactionHandlerTest {

    static testMethod void testmethod1(){
        E2E_Form_General_Settings__c e2eFormGeneralSettings = new E2E_Form_General_Settings__c(
            Name = 'Germany',
            Test_mode__c = false,
            Payment_URL__c = 'https://e2e-e2efleetcor.cs89.force.com',
            Files_Generator_Url__c = 'https://e2e-e2efleetcor.cs89.force.com',
            Enable_authorization_non_granted_check__c = true,
            Set_GFN_Status__c = true
        );
        insert e2eFormGeneralSettings;
        Account account = new Account(Name = 'test1', BillingPostalCode = '1231', BillingCountry = 'Poland');
        insert account;
        Opportunity opportunity = new Opportunity(Name = 'test1', StageName = 'Qualified Lead', CloseDate = date.today(), Accountid = account.id);
        insert opportunity;

        Payment_Transaction__c paymentTransaction = new Payment_Transaction__c();
        paymentTransaction.Amount__c = 10;
        paymentTransaction.currency__c = 'EUR';
        paymentTransaction.OpportunityId__c = opportunity.id;
        insert paymentTransaction;

        paymentTransaction.Status__c = '0';
        update paymentTransaction;

        List<Payment_transaction__c> list1 = [
                SELECT id
                FROM Payment_Transaction__c
                WHERE id = :paymentTransaction.id
                AND Authorized__c = TRUE
        ];
        system.assertEquals(list1.size(),0);
    }


    static testMethod void testmethod2(){
        E2E_Form_General_Settings__c e2eFormGeneralSettings = new E2E_Form_General_Settings__c(
            Name = 'Germany',
            Test_mode__c = false,
            Payment_URL__c = 'https://e2e-e2efleetcor.cs89.force.com',
            Files_Generator_Url__c = 'https://e2e-e2efleetcor.cs89.force.com',
            Enable_authorization_non_granted_check__c = true,
            Set_GFN_Status__c = true
        );
        insert e2eFormGeneralSettings;
        Account account = new Account(Name = 'test1', BillingPostalCode = '1231', BillingCountry = 'Germany');
        insert account;
        Opportunity opportunity = new Opportunity(Name = 'test1', StageName = 'Qualified Lead', CloseDate = date.today(), Accountid = account.id,
                Security_Amount_To_Pay__c=10);
        insert opportunity;

        Payment_Transaction__c paymentTransaction = new Payment_Transaction__c();
        paymentTransaction.Amount__c = 10;
        paymentTransaction.currency__c = 'EUR';
        paymentTransaction.OpportunityId__c = opportunity.id;
        insert paymentTransaction;

        paymentTransaction.status__c = '9';
        paymentTransaction.Authorized__c = TRUE;
        update paymentTransaction;

        List<Payment_transaction__c> list1 = [
                SELECT id
                FROM Payment_Transaction__c
                WHERE id = :paymentTransaction.id
                AND Authorized__c = TRUE
        ];

        List<Opportunity> list2 = [
                SELECT id, stagename, garantie_other__c
                FROM Opportunity
                WHERE id=:opportunity.id
                LIMIT 1
        ];

        system.assertEquals(list1.size(),1);
        system.assertEquals(list2.get(0).Stagename,'Closed Won');
        system.assertEquals(list2.get(0).garantie_other__c,paymentTransaction.Amount__c);
    }

    static testMethod void testmethod3(){
        E2E_Form_General_Settings__c e2eFormGeneralSettings = new E2E_Form_General_Settings__c(
            Name = 'Germany',
            Test_mode__c = false,
            Payment_URL__c = 'https://e2e-e2efleetcor.cs89.force.com',
            Files_Generator_Url__c = 'https://e2e-e2efleetcor.cs89.force.com',
            Enable_authorization_non_granted_check__c = true,
            Set_GFN_Status__c = true
        );
        insert e2eFormGeneralSettings;
        Account account = new Account(Name = 'test1', BillingPostalCode = '1231', BillingCountry = 'Poland');
        insert account;
        Opportunity opportunity = new Opportunity(Name = 'test1', StageName = 'Qualified Lead', CloseDate = date.today(), Accountid = account.id,
                Security_Amount_To_Pay__c=10);
        insert opportunity;

        Payment_Transaction__c paymentTransaction = new Payment_Transaction__c();
        paymentTransaction.Amount__c = 10;
        paymentTransaction.currency__c = 'EUR';
        paymentTransaction.OpportunityId__c = opportunity.id;
        insert paymentTransaction;

        paymentTransaction.status__c = '1';
        paymentTransaction.Authorized__c = TRUE;
        update paymentTransaction;

        List<Payment_transaction__c> list1 = [
                SELECT id
                FROM Payment_Transaction__c
                WHERE id = :paymentTransaction.id
                AND Authorized__c = TRUE
        ];
        system.assertEquals(list1.size(),1);
    }


    static testMethod void testmethod4(){
        E2E_Form_General_Settings__c e2eFormGeneralSettings = new E2E_Form_General_Settings__c(
            Name = 'Germany',
            Test_mode__c = false,
            Payment_URL__c = 'https://e2e-e2efleetcor.cs89.force.com',
            Files_Generator_Url__c = 'https://e2e-e2efleetcor.cs89.force.com',
            Enable_authorization_non_granted_check__c = true,
            Set_GFN_Status__c = true
        );
        insert e2eFormGeneralSettings;
        Account account = new Account(Name = 'test1', BillingPostalCode = '1231', BillingCountry = 'Poland');
        insert account;
        Opportunity opportunity = new Opportunity(Name = 'test1', StageName = 'Qualified Lead', CloseDate = date.today(), Accountid = account.id,
                Security_Amount_To_Pay__c=10);
        insert opportunity;

        Payment_Transaction__c paymentTransaction = new Payment_Transaction__c();
        paymentTransaction.Amount__c = 10;
        paymentTransaction.currency__c = 'EUR';
        paymentTransaction.OpportunityId__c = opportunity.id;
        insert paymentTransaction;

        paymentTransaction.status__c = '2';
        paymentTransaction.Authorized__c = TRUE;
        update paymentTransaction;

        List<Payment_transaction__c> list1 = [
                SELECT id
                FROM Payment_Transaction__c
                WHERE id = :paymentTransaction.id
                AND Authorized__c = TRUE
        ];
        system.assertEquals(list1.size(),1);
    }


    static testMethod void testmethod5(){
        E2E_Form_General_Settings__c e2eFormGeneralSettings = new E2E_Form_General_Settings__c(
            Name = 'Germany',
            Test_mode__c = false,
            Payment_URL__c = 'https://e2e-e2efleetcor.cs89.force.com',
            Files_Generator_Url__c = 'https://e2e-e2efleetcor.cs89.force.com',
            Enable_authorization_non_granted_check__c = true,
            Set_GFN_Status__c = true
        );
        insert e2eFormGeneralSettings;
        Account account = new Account(Name = 'test1', BillingPostalCode = '1231', BillingCountry = 'Poland');
        insert account;
        Opportunity opportunity = new Opportunity(Name = 'test1', StageName = 'Qualified Lead', CloseDate = date.today(), Accountid = account.id,
                Security_Amount_To_Pay__c=10);
        insert opportunity;

        Payment_Transaction__c paymentTransaction = new Payment_Transaction__c();
        paymentTransaction.Amount__c = 10;
        paymentTransaction.currency__c = 'EUR';
        paymentTransaction.OpportunityId__c = opportunity.id;
        insert paymentTransaction;

        paymentTransaction.status__c = '12';
        paymentTransaction.Authorized__c = TRUE;
        update paymentTransaction;

        List<Payment_transaction__c> list1 = [
                SELECT id
                FROM Payment_Transaction__c
                WHERE id = :paymentTransaction.id
                AND Authorized__c = TRUE
        ];
        system.assertEquals(list1.size(),1);
    }


    static testMethod void payUTestMethod() {
        List<SObject> e2eSettingsToInsertList = new List<SObject>();
        E2E_Form_General_Settings__c e2eFormGeneralSettings = new E2E_Form_General_Settings__c(
            Name = 'Poland',
            Test_mode__c = false,
            Payment_URL__c = 'https://e2e-e2efleetcor.cs89.force.com',
            Files_Generator_Url__c = 'https://e2e-e2efleetcor.cs89.force.com',
            Enable_authorization_non_granted_check__c = true,
            Set_GFN_Status__c = true
        );
        e2eSettingsToInsertList.add(e2eFormGeneralSettings);

        GFNI_General_Settings__c gfniGeneralSettings = new GFNI_General_Settings__c();
        gfniGeneralSettings.Name = 'PL';
        gfniGeneralSettings.Application_Status__c = '/applicationstatus';
        gfniGeneralSettings.Create_Customer_and_Cards__c = '/customer';
        gfniGeneralSettings.Get_Customer_Id__c = '/customerId';
        gfniGeneralSettings.IsForRobot__c = true;
        gfniGeneralSettings.Number_Of_Send_Tries__c = 3;
        gfniGeneralSettings.Prod_Endpoint__c = 'https://api-fleetcor-eu.apiconnect.ibmcloud.com/fleetcor-eu/sb';
        gfniGeneralSettings.Test_Endpoint__c = 'https://api-fleetcor-eu.apiconnect.ibmcloud.com/fleetcor-eu/sb';
        gfniGeneralSettings.x_ibm_client_id__c = '49a8caea-2a51-4172-b387-c102be154f6f';
        gfniGeneralSettings.x_ibm_client_secret__c = 'eB8xT3aH6yY3rL4oO8fQ2sG2aJ5pL8rS4tD6kB0hU4kM4pS5fE';
        gfniGeneralSettings.Support_email__c = 'test@email.com';
        gfniGeneralSettings.Test_support_email__c = 'test@test.com';
        gfniGeneralSettings.test_x_ibm_client_id__c = '49a8caea-2a51-4172-b387-c102be154f6f';
        gfniGeneralSettings.test_x_ibm_client_secret__c = 'eB8xT3aH6yY3rL4oO8fQ2sG2aJ5pL8rS4tD6kB0hU4kM4pS5fE';
        gfniGeneralSettings.Test_mode__c = true;
        e2eSettingsToInsertList.add(gfniGeneralSettings);

        Account_GFN_Report_Email_Params__c gfnReport = new Account_GFN_Report_Email_Params__c(
                Attach_format__c = '.xls',
                Email__c = 'fleetcor@enway.co',
                Email_body__c = 'Attached file is generated using Salesforce for a robot processing',
                Name = 'Excel'
        );
        e2eSettingsToInsertList.add(gfnReport);

        E2E_PayU_Settings__c e2ePayUSettings = new E2E_PayU_Settings__c(
            Name = 'Poland',
            IsActive__c = true
        );
        e2eSettingsToInsertList.add(e2ePayUSettings);
        insert e2eSettingsToInsertList;
        Account account = new Account(Name = 'payUTest', BillingPostalCode = '1231', BillingCountry = 'Poland');
        insert account;
        Opportunity opportunity = new Opportunity(
            Name = 'payUTest',
            StageName = 'Prospecting',
            CloseDate = date.today(),
            Accountid = account.Id,
            Security_Amount_To_Pay__c = 10);
        insert opportunity;

        Payment_Transaction__c paymentTransaction = new Payment_Transaction__c();
        paymentTransaction.Amount__c = 10;
        paymentTransaction.currency__c = 'PL';
        paymentTransaction.OpportunityId__c = opportunity.Id;
        insert paymentTransaction;

        paymentTransaction.Status__c = 'COMPLETED';
        update paymentTransaction;

        List<Opportunity> oppList = [SELECT Garantie_other__c, E2E_payment_status__c, StageName FROM Opportunity WHERE Id = :opportunity.Id];
        System.assertEquals(10, oppList.get(0).Garantie_other__c);
        System.assertEquals('ACCEPT', oppList.get(0).E2E_payment_status__c);
    }


    static testMethod void ete20PayUTest() {
        List<SObject> e2eSettingsToInsertList = new List<SObject>();
        E2E_Form_General_Settings__c e2eFormGeneralSettings = new E2E_Form_General_Settings__c(
                Name = 'Poland',
                Test_mode__c = false,
                Payment_URL__c = 'https://e2e-e2efleetcor.cs89.force.com',
                Files_Generator_Url__c = 'https://e2e-e2efleetcor.cs89.force.com',
                Enable_authorization_non_granted_check__c = true,
                Set_GFN_Status__c = true
        );
        e2eSettingsToInsertList.add(e2eFormGeneralSettings);

        E2E_PayU_Settings__c e2ePayUSettings = new E2E_PayU_Settings__c(
                Name = 'Poland',
                IsActive__c = true
        );
        e2eSettingsToInsertList.add(e2ePayUSettings);
        E2EKeysAPI__c e2eKeysApi = new E2EKeysAPI__c(
                Name = 'E2EFormPL',
                AES256_Key__c = 'F1kCSPMj49W2arKn9Ut0DmywkswU6E1Q/wlyutztVww=',
                paymentTransactionURL__c = 'https://ogone.test.v-psp.com/ncol/test//orderstandard_utf8.asp',
                PSPID__c = 'fleetcorTEST',
                SHA_KeyIn__c = 'FleetcorTest!12@',
                SHA_KeyOut__c = 'IngenFleetTest1!'
        );
        e2eSettingsToInsertList.add(e2eKeysApi);
        insert e2eSettingsToInsertList;

        Account account = new Account(Name = 'payUTest', BillingPostalCode = '1231', BillingCountry = 'Poland');
        insert account;

        String recordTypeId = Schema.SObjectType.E2E_Data_Object__c.getRecordTypeInfosByName().get('Poland').getRecordTypeId();
        E2E_Data_Object__c dataObject = new E2E_Data_Object__c(
            RecordTypeId = recordTypeId,
            Name = 'Test Company',
            Selected_Company_Name__c = 'Test Company',
            Salutation__c = 'Mr.',
            First_Name__c = 'John',
            Last_Name__c = 'Johnson',
            Email__c = 'test@test.com',
            Phone__c = '+48 777-777-777',
            Country_Code__c = 'pl',
            Security_Amount_To_Pay__c = 10);
        insert dataObject;

        Contact contact = new Contact(
                AccountId = account.Id,
                Salutation = dataObject.Salutation__c,
                FirstName = dataObject.First_Name__c,
                LastName = dataObject.Last_Name__c,
                E2E__c = true,
                Email = dataObject.Email__c,
                Phone = dataObject.Phone__c
        );
        insert contact;

        Opportunity opportunity = new Opportunity(
                Name = 'Test Company',
                E2E_Data_Object__c = dataObject.Id,
                Security_To_Pay__c = 'Kaution',
                Security_Amount_To_Pay__c = 10,
                StageName = 'Prospecting',
                CloseDate = date.today(),
                Accountid = account.Id);
        insert opportunity;

        OpportunityContactRole ocr = new OpportunityContactRole(
                IsPrimary = true,
                OpportunityId = opportunity.Id,
                ContactId = contact.Id
        );
        insert ocr;

        Payment_Transaction__c paymentTransaction = new Payment_Transaction__c();
        paymentTransaction.Amount__c = 10;
        paymentTransaction.currency__c = 'PL';
        paymentTransaction.OpportunityId__c = opportunity.Id;
        insert paymentTransaction;

        Test.startTest();
            paymentTransaction.Status__c = 'COMPLETED';
            update paymentTransaction;
        Test.stopTest();

        List<Opportunity> oppList = [SELECT Garantie_other__c, E2E_payment_status__c, StageName FROM Opportunity WHERE Id = :opportunity.Id];
        System.assertEquals(10, oppList.get(0).Garantie_other__c);
        System.assertEquals('ACCEPT', oppList.get(0).E2E_payment_status__c);
        System.assertEquals('Closed Won', oppList.get(0).StageName);
    }


    static testMethod void ete20PayuInvalidCaseTest() {
        List<SObject> e2eSettingsToInsertList = new List<SObject>();
        E2E_Form_General_Settings__c e2eFormGeneralSettings = new E2E_Form_General_Settings__c(
                Name = 'Poland',
                Test_mode__c = false,
                Payment_URL__c = 'https://e2e-e2efleetcor.cs89.force.com',
                Files_Generator_Url__c = 'https://e2e-e2efleetcor.cs89.force.com',
                Enable_authorization_non_granted_check__c = true,
                Set_GFN_Status__c = true
        );
        e2eSettingsToInsertList.add(e2eFormGeneralSettings);

        E2E_PayU_Settings__c e2ePayUSettings = new E2E_PayU_Settings__c(
                Name = 'Poland',
                IsActive__c = true
        );
        e2eSettingsToInsertList.add(e2ePayUSettings);
        E2EKeysAPI__c e2eKeysApi = new E2EKeysAPI__c(
                Name = 'E2EFormPL',
                AES256_Key__c = 'F1kCSPMj49W2arKn9Ut0DmywkswU6E1Q/wlyutztVww=',
                paymentTransactionURL__c = 'https://ogone.test.v-psp.com/ncol/test//orderstandard_utf8.asp',
                PSPID__c = 'fleetcorTEST',
                SHA_KeyIn__c = 'FleetcorTest!12@',
                SHA_KeyOut__c = 'IngenFleetTest1!'
        );
        e2eSettingsToInsertList.add(e2eKeysApi);
        insert e2eSettingsToInsertList;

        Account account = new Account(Name = 'payUTest', BillingPostalCode = '1231', BillingCountry = 'Poland');
        insert account;

        String recordTypeId = Schema.SObjectType.E2E_Data_Object__c.getRecordTypeInfosByName().get('Poland').getRecordTypeId();
        E2E_Data_Object__c dataObject = new E2E_Data_Object__c(
                RecordTypeId = recordTypeId,
                Name = 'Test Company',
                Selected_Company_Name__c = 'Test Company',
                StageName__c = 'Prospecting',
                Salutation__c = 'Mr.',
                First_Name__c = 'John',
                Last_Name__c = 'Johnson',
                Email__c = 'test@test.com',
                Phone__c = '+48 777-777-777',
                Country_Code__c = 'pl',
                Security_Amount_To_Pay__c = 10);
        insert dataObject;

        Contact contact = new Contact(
                AccountId = account.Id,
                Salutation = dataObject.Salutation__c,
                FirstName = dataObject.First_Name__c,
                LastName = dataObject.Last_Name__c,
                E2E__c = true,
                Email = dataObject.Email__c,
                Phone = dataObject.Phone__c
        );
        insert contact;

        Opportunity opportunity = new Opportunity(
                Name = 'Test Company',
                E2E_Data_Object__c = dataObject.Id,
                Security_To_Pay__c = 'Kaution',
                Security_Amount_To_Pay__c = 10,
                StageName = 'Prospecting',
                CloseDate = date.today(),
                Accountid = account.Id);
        insert opportunity;

        OpportunityContactRole ocr = new OpportunityContactRole(
                IsPrimary = true,
                OpportunityId = opportunity.Id,
                ContactId = contact.Id
        );
        insert ocr;

        Payment_Transaction__c paymentTransaction = new Payment_Transaction__c();
        paymentTransaction.Amount__c = 10;
        paymentTransaction.currency__c = 'PL';
        paymentTransaction.OpportunityId__c = opportunity.Id;
        insert paymentTransaction;

        Test.startTest();
        paymentTransaction.Status__c = 'REJECTED';
        update paymentTransaction;
        Test.stopTest();

        List<Opportunity> oppList = [SELECT Garantie_other__c, E2E_payment_status__c, StageName FROM Opportunity WHERE Id = :opportunity.Id];
        System.assertNotEquals(10, oppList.get(0).Garantie_other__c);
        System.assertEquals('REJECTED', oppList.get(0).E2E_payment_status__c);
        System.assertEquals('Prospecting', oppList.get(0).StageName);
    }


    static testMethod void ete20IngenicoTest() {
        List<SObject> e2eSettingsToInsertList = new List<SObject>();
        E2E_Form_General_Settings__c e2eFormGeneralSettings = new E2E_Form_General_Settings__c(
                Name = 'Germany',
                Test_mode__c = false,
                Payment_URL__c = 'https://e2e-e2efleetcor.cs89.force.com',
                Files_Generator_Url__c = 'https://e2e-e2efleetcor.cs89.force.com',
                Enable_authorization_non_granted_check__c = true,
                Set_GFN_Status__c = true
        );
        e2eSettingsToInsertList.add(e2eFormGeneralSettings);

        E2EKeysAPI__c e2eKeysApi = new E2EKeysAPI__c(
                Name = 'E2EForm',
                AES256_Key__c = 'F1kCSPMj49W2arKn9Ut0DmywkswU6E1Q/wlyutztVww=',
                paymentTransactionURL__c = 'https://ogone.test.v-psp.com/ncol/test//orderstandard_utf8.asp',
                PSPID__c = 'fleetcorTEST',
                SHA_KeyIn__c = 'FleetcorTest!12@',
                SHA_KeyOut__c = 'IngenFleetTest1!'
        );
        e2eSettingsToInsertList.add(e2eKeysApi);
        insert e2eSettingsToInsertList;

        Account account = new Account(Name = 'IngenicoTest', BillingPostalCode = '1231', BillingCountry = 'Germany');
        insert account;

        String recordTypeId = Schema.SObjectType.E2E_Data_Object__c.getRecordTypeInfosByName().get('Germany').getRecordTypeId();
        E2E_Data_Object__c dataObject = new E2E_Data_Object__c(
                RecordTypeId = recordTypeId,
                Name = 'Test Company',
                Selected_Company_Name__c = 'Test Company',
                Salutation__c = 'Mr.',
                First_Name__c = 'John',
                Last_Name__c = 'Johnson',
                Email__c = 'test@test.com',
                Phone__c = '+48 777-777-777',
                Country_Code__c = 'de',
                Security_Amount_To_Pay__c = 10);
        insert dataObject;

        Contact contact = new Contact(
                AccountId = account.Id,
                Salutation = dataObject.Salutation__c,
                FirstName = dataObject.First_Name__c,
                LastName = dataObject.Last_Name__c,
                E2E__c = true,
                Email = dataObject.Email__c,
                Phone = dataObject.Phone__c
        );
        insert contact;

        Opportunity opportunity = new Opportunity(
                Name = 'Test Company',
                E2E_Data_Object__c = dataObject.Id,
                Security_To_Pay__c = 'Kaution',
                Security_Amount_To_Pay__c = 10,
                StageName = 'Prospecting',
                CloseDate = date.today(),
                Accountid = account.Id);
        insert opportunity;

        OpportunityContactRole ocr = new OpportunityContactRole(
                IsPrimary = true,
                OpportunityId = opportunity.Id,
                ContactId = contact.Id
        );
        insert ocr;

        Payment_Transaction__c paymentTransaction = new Payment_Transaction__c();
        paymentTransaction.Amount__c = 10;
        paymentTransaction.currency__c = 'EUR';
        paymentTransaction.OpportunityId__c = opportunity.Id;
        insert paymentTransaction;

        Test.startTest();
        paymentTransaction.Status__c = '9';
        update paymentTransaction;
        Test.stopTest();

        List<Opportunity> oppList = [SELECT Garantie_other__c, E2E_payment_status__c, StageName FROM Opportunity WHERE Id = :opportunity.Id];
        System.assertEquals(10, oppList.get(0).Garantie_other__c);
        System.assertEquals('ACCEPT', oppList.get(0).E2E_payment_status__c);
        System.assertEquals('Closed Won', oppList.get(0).StageName);
    }
}