default/objects/GFNI_Batch_Settings__c/GFNI_Batch_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>GFNI Batch Settings</label>
</CustomObject>

default/objects/GFNI_Batch_Settings__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <label>Batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/classes/ScheduleBatchUpdateGfnNumberOfCards.cls
public with sharing class ScheduleBatchUpdateGfnNumberOfCards implements Schedulable {

    public void execute(SchedulableContext SC) {
        // GFNI_Utils.runGfnRelatedBatch(new UpdateGfnNumberOfCardsBatch(batchSetting), 'Update_Gfn_Number_of_cards', 100);
        Integer batchSize = 100;
        GFNI_Batch_Settings__c batchSetting = GFNI_Utils.getGfnRelatedBatchSettings('Update_Gfn_Number_of_cards');
        if(batchSetting.Batch_Size__c != null && batchSetting.Batch_Size__c < batchSize) {
            batchSize = Integer.valueOf(batchSetting.Batch_Size__c);
        }
        Id batchJobId = Database.executeBatch(new UpdateGfnNumberOfCardsBatch(batchSetting), batchSize);
    }

}