default/objects/E2E_Error_message__c/E2E_Error_message__c.object-meta.xml
<CustomObject>
    <description>Info about Error message related to opportunity</description>
    <label>E2E Error message</label>
    <nameField>
        <displayFormat>Error-{0000}</displayFormat>
        <label>E2E Error message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>E2E Error messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Error_message__c/fields/CausedBy__c.field-meta.xml
<CustomField>
    <fullName>CausedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CausedBy</label>
    <referenceTo>E2E_Error_message__c</referenceTo>
    <relationshipLabel>E2E Error messages</relationshipLabel>
    <relationshipName>E2E_Error_messages</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2E_Error_message__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <label>LineNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/E2E_Error_message__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>E2E Error messages</relationshipLabel>
    <relationshipName>Error_messages</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2E_Error_message__c/fields/StackTraceString__c.field-meta.xml
<CustomField>
    <fullName>StackTraceString__c</fullName>
    <label>StackTraceString</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/E2E_Error_message__c/fields/TypeName__c.field-meta.xml
<CustomField>
    <fullName>TypeName__c</fullName>
    <label>TypeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/classes/E2EErrorService.cls
global class E2EErrorService {
    public static Id createNewErrorMessage(Exception e, Id opportunityId) {
        E2E_Error_message__c newMessage = new E2E_Error_message__c(
            LineNumber__c = e.getLineNumber(),
            Message__c = e.getMessage(),
            StackTraceString__c = e.getStackTraceString(),
            TypeName__c = e.getTypeName(),
            Opportunity__c = opportunityId
        );
        if (e.getCause() != null) {
            newMessage.CausedBy__c = E2EErrorService.createNewErrorMessage(e.getCause(), null);
        }
        insert newMessage;
        return newMessage.Id;
    }
}