default/objects/GATEWAY__c/GATEWAY__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>GATEWAY</label>
</CustomObject>

default/objects/GATEWAY__c/fields/CLIENT_ID__c.field-meta.xml
<CustomField>
    <fullName>CLIENT_ID__c</fullName>
    <label>CLIENT_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/GATEWAY__c/fields/CLIENT_SECRET__c.field-meta.xml
<CustomField>
    <fullName>CLIENT_SECRET__c</fullName>
    <label>CLIENT_SECRET</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/classes/EESBControllerLightningTest.cls
@IsTest
public with sharing class EESBControllerLightningTest {
    @TestSetup
    public static void initCreateDirectumContractData() {
        insert new GATEWAY__c(
                Name = 'directumCredentials',
                CLIENT_ID__c = '005056bd4e10',
                CLIENT_SECRET__c = '628c49df',
                URL__c = 'https://api.eu-de.apiconnect.appdomain.cloud'
        );
    }

    @IsTest
    public static void testCreateDirectumContract_positive() {

        DirectumContractRequestBody requestBody = new DirectumContractRequestBody();
        requestBody.DocumentKind ='mpd';
        requestBody.BusinessUnit = 'PPR';
        requestBody.Subject = 'Test contract';
        requestBody.Counterparty = 'Софтлайн Трейд|7736227885|770401001|119270, МОСКВА ГОРОД, НАБЕРЕЖНАЯ\n' +
                'ЛУЖНЕЦКАЯ, 2/4, СТР.3А, ОФИС 304|Г МОСКВА,УЛ ГУБКИНА, Д\n' +
                '8|7555555|softline@softline.ru|1027736009333||ОКПО|2782534392520000066';
        requestBody.ResponsibleEmployee='test@test.ru';
        requestBody.RequestID='0063N00000CUobGQAT';
        requestBody.Note='Important notes';

        Test.setMock(HttpCalloutMock.class, new SingleRequestMock(200, 'Complete', '', null));

        Test.startTest();
        Boolean result = EESBControllerLightning.createDirectumContract(requestBody);
        Test.stopTest();

        system.assertEquals(true, result);
    }

    @IsTest
    public static void testCreateDirectumContract_error() {

        DirectumContractRequestBody requestBody = new DirectumContractRequestBody();

        Test.startTest();
        Boolean result = EESBControllerLightning.createDirectumContract(requestBody);
        Test.stopTest();

        system.assertEquals(false, result);
    }

}