default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Account Status populated by users, by GFN in the future.</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Former Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/recordTypes/CCS.recordType-meta.xml
<RecordType>
    <fullName>CCS</fullName>
    <active>true</active>
    <label>CCS</label>
</RecordType>

default/objects/Account/recordTypes/Endkunde.recordType-meta.xml
<RecordType>
    <fullName>Endkunde</fullName>
    <active>true</active>
    <label>Endkunde</label>
</RecordType>

default/objects/Account_Price_Book__c/Account_Price_Book__c.object-meta.xml
<CustomObject>
    <description>Junction object to link existing Accounts to existing Price Books.</description>
    <label>Account Price Book</label>
    <nameField>
        <label>Account Price Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Price Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Account_Price_Book__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Select Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Price Books</relationshipLabel>
    <relationshipName>Account_Price_Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Account_Price_Book__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Select Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Account Price Books</relationshipLabel>
    <relationshipName>Account_Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Carnet_BO_Emails__c/Carnet_BO_Emails__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of Carnet BO Email addresses.</description>
    <label>Carnet BO Emails</label>
</CustomObject>

default/objects/Carnet_Closed_Won_Files_Allowed_Profiles__c/Carnet_Closed_Won_Files_Allowed_Profiles__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Carnet Closed Won Files Allowed Profiles</label>
</CustomObject>

default/objects/Carnet_Closed_Won_Files_Allowed_Profiles__c/fields/Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Profile_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Profile Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Carnet_Opportunity_Fields_after_Closed__c/Carnet_Opportunity_Fields_after_Closed__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Settings of Opportunity fields to allow their edit after Opportunity is closed.</description>
    <label>Carnet Opportunity Fields after Closed</label>
</CustomObject>

default/objects/Carnet_Profiles_Approval__c/Carnet_Profiles_Approval__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Carnet - Closed Won allowed Profiles</label>
</CustomObject>

default/objects/Carnet_Profiles_Approval__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Account_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Account_Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select Account Price Book from Account. If you don't see any, create new under your Account.</inlineHelpText>
    <label>Account Price Book</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You must add Account Price Book under Account!</errorMessage>
        <filterItems>
            <field>Account_Price_Book__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Account_Price_Book__c.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Not required, Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account_Price_Book__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Opportunity/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Former Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Deposit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Amount__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Ticking this confirmation box will move Opportunity to the Closed Won status.</inlineHelpText>
    <label>Payment received - confirmation</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/DocuSign_Status__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Status__c</fullName>
    <label>DocuSign Status</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Form_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Form_of_Payment__c</fullName>
    <label>Order Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer - after delivery</fullName>
            </value>
            <value>
                <fullName>Advanced payment</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/recordTypes/Carnet.recordType-meta.xml
<RecordType>
    <fullName>Carnet</fullName>
    <active>true</active>
    <businessProcess>Carnet</businessProcess>
    <description>Record Type for Carnet records.</description>
    <label>Carnet</label>
</RecordType>

default/objects/Pricebook2/fields/Standard_Unit_Package__c.field-meta.xml
<CustomField>
    <fullName>Standard_Unit_Package__c</fullName>
    <description>The standard pack for stationary installations, appropriate monitoring cars and trucks. The pack includes GPS unit and antenna, CAN GO CLICK and route type switch.</description>
    <inlineHelpText>one-time fee / unit</inlineHelpText>
    <label>Standard Unit Package</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

default/classes/ContentDocumentTriggerHandlerTest.cls
/**
 * Created by marekhaken on 22/10/2020.
 */

@IsTest
private class ContentDocumentTriggerHandlerTest {
    @IsTest
    private static void testCarnetDeleteContentDocument(){
        String carnetOppoRecId = GlobalUtils.returnRecordTypeId('Opportunity', 'Carnet');
        String endkundeAccRecId = GlobalUtils.returnRecordTypeId('Account', 'Endkunde');

        List<User> User = [SELECT Id, ProfileId FROM User WHERE Profile.Name = 'CCS System Administrator' AND UserRole.Name = 'Role Up' AND IsActive = true LIMIT 1];

        List<Profile> AdminUser = [SELECT Id, Name FROM Profile WHERE Name = 'API Only' LIMIT 1];

        Carnet_Profiles_Approval__c carnetSettings = new Carnet_Profiles_Approval__c(
                Name = AdminUser.get(0).Name,
                Field_Name__c = AdminUser.get(0).Name);
        insert carnetSettings;

        Carnet_Opportunity_Fields_after_Closed__c carnetSettings2 = new Carnet_Opportunity_Fields_after_Closed__c(
                Name = 'Account_Status__c');
        insert carnetSettings2;

        Carnet_Opportunity_Fields_after_Closed__c carnetSettings3 = new Carnet_Opportunity_Fields_after_Closed__c(
                Name = 'Number_of_open_tasks__c');
        insert carnetSettings3;

        Carnet_BO_Emails__c BOe = new Carnet_BO_Emails__c(
                Name = 'Poland',
                Email__c = 'info@intercodec.cz');
        insert BOe;

        Account account = new Account(
                Name = 'TESTCARNET',
                BillingPostalCode = '12345',
                Phone = '+72234567891',
                BillingStreet = 'TEST',
                BillingCountry = 'Poland',
                Account_Status__c = 'Prospect',
                OwnerId= User.get(0).Id,
                RecordTypeId = endkundeAccRecId);
        insert account;

        Pricebook2 pcb = new Pricebook2(
                Name = 'test',
                IsActive = true,
                Standard_Unit_Package__c = 289);
        insert pcb;

        Account_Price_Book__c apb = new Account_Price_Book__c(
                Name = 'test',
                Account__c = account.Id,
                Price_Book__c = pcb.Id);
        insert apb;

        Contact contact = new Contact(
                Salutation = 'Herr',
                LastName = 'Test',
                AccountId = account.Id,
                Email = 'test123123@test.com',
                OwnerId= User.get(0).Id);
        insert contact;

        ContentVersion contentVersion = new ContentVersion(
                Title = 'Carnet_podsumowanie_zamowienia',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true,
                PathOnClient = 'Test.pdf'
        );
        insert contentVersion;

        Opportunity opportunity = new Opportunity(
                Name = 'CarnetTest',
                StageName = 'Qualify',
                AccountId = account.id,
                Probability = 0,
                OwnerId = User.get(0).Id,
                RecordTypeId = carnetOppoRecId,
                CloseDate = date.today(),
                Form_of_Payment__c = 'Advanced payment',
                Account_Price_Book__c = apb.Id,
                DocuSign_Status__c = 'Completed',
                Deposit_Amount__c = true);
        insert opportunity;

        OpportunityContactRole ocr = new OpportunityContactRole(
                ContactId = contact.Id,
                OpportunityId = opportunity.Id,
                IsPrimary = true,
                Role = 'Business User');
        insert ocr;

        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: contentVersion.Id].ContentDocumentId;
        cdl.LinkedEntityId = opportunity.Id;
        cdl.ShareType = 'I';
        insert cdl;

        System.runAs(User.get(0)) {
            opportunity.StageName = 'Closed Lost';
            update opportunity;
        }

        ContentVersion cv = new ContentVersion(
                Title = 'Test',
                PathOnClient = 'Test.jpg',
                VersionData = Blob.valueOf('Test Content Data'),
                IsMajorVersion = true
        );
        insert cv;

        ContentDocument cd = [SELECT Id FROM ContentDocument WHERE ContentDocument.LatestPublishedVersionId = :cv.Id];

        ContentDocumentLink cdl2 = new ContentDocumentLink(
                ContentDocumentId = cd.Id,
                LinkedEntityId = opportunity.Id,
                ShareType = 'I'
        );
        insert cdl2;


        /*Carnet_Closed_Won_Files_Allowed_Profiles__c ap = new Carnet_Closed_Won_Files_Allowed_Profiles__c(
                Name = 'Admin',
                Profile_Id__c = User.get(0).ProfileId
        );*/
        //insert ap;

        System.runAs(User.get(0)){
            try{
                delete cd;
            }
            catch(Exception e){
                System.debug(e.getMessage());
                Boolean expectedExceptionThrown = e.getMessage().contains('allowed') ? true : false;
                system.assertEquals(expectedExceptionThrown,true);
            }
        }
    }

    @IsTest
    private static void testCarnetDeleteContentDocument2(){
        String carnetOppoRecId = GlobalUtils.returnRecordTypeId('Opportunity', 'Carnet');
        String endkundeAccRecId = GlobalUtils.returnRecordTypeId('Account', 'Endkunde');

        List<User> User = [SELECT Id, ProfileId FROM User WHERE Profile.Name = 'CCS System Administrator' AND UserRole.Name = 'Role Up' AND IsActive = true LIMIT 1];

        List<Profile> AdminUser = [SELECT Id, Name FROM Profile WHERE Name = 'API Only' LIMIT 1];

        Carnet_Profiles_Approval__c carnetSettings = new Carnet_Profiles_Approval__c(
                Name = AdminUser.get(0).Name,
                Field_Name__c = AdminUser.get(0).Name);
        insert carnetSettings;

        Carnet_Opportunity_Fields_after_Closed__c carnetSettings2 = new Carnet_Opportunity_Fields_after_Closed__c(
                Name = 'Account_Status__c');
        insert carnetSettings2;

        Carnet_Opportunity_Fields_after_Closed__c carnetSettings3 = new Carnet_Opportunity_Fields_after_Closed__c(
                Name = 'Number_of_open_tasks__c');
        insert carnetSettings3;

        Carnet_BO_Emails__c BOe = new Carnet_BO_Emails__c(
                Name = 'Poland',
                Email__c = 'info@intercodec.cz');
        insert BOe;

        Account account = new Account(
                Name = 'TESTCARNET',
                BillingPostalCode = '12345',
                Phone = '+72234567891',
                BillingStreet = 'TEST',
                BillingCountry = 'Poland',
                Account_Status__c = 'Prospect',
                OwnerId= User.get(0).Id,
                RecordTypeId = endkundeAccRecId);
        insert account;

        Pricebook2 pcb = new Pricebook2(
                Name = 'test',
                IsActive = true,
                Standard_Unit_Package__c = 289);
        insert pcb;

        Account_Price_Book__c apb = new Account_Price_Book__c(
                Name = 'test',
                Account__c = account.Id,
                Price_Book__c = pcb.Id);
        insert apb;

        Contact contact = new Contact(
                Salutation = 'Herr',
                LastName = 'Test',
                AccountId = account.Id,
                Email = 'test123123@test.com');
        insert contact;

        ContentVersion contentVersion = new ContentVersion(
                Title = 'Carnet_podsumowanie_zamowienia',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true,
                PathOnClient = 'Test.pdf'
        );
        insert contentVersion;

        Opportunity opportunity = new Opportunity(
                Name = 'CarnetTest',
                StageName = 'Qualify',
                AccountId = account.id,
                Probability = 0,
                OwnerId = User.get(0).Id,
                RecordTypeId = carnetOppoRecId,
                CloseDate = date.today(),
                Form_of_Payment__c = 'Advanced payment',
                Account_Price_Book__c = apb.Id,
                DocuSign_Status__c = 'Completed',
                Deposit_Amount__c = true);
        insert opportunity;

        OpportunityContactRole ocr = new OpportunityContactRole(
                ContactId = contact.Id,
                OpportunityId = opportunity.Id,
                IsPrimary = true,
                Role = 'Business User');
        insert ocr;

        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: contentVersion.Id].ContentDocumentId;
        cdl.LinkedEntityId = opportunity.Id;
        cdl.ShareType = 'I';
        insert cdl;

        System.runAs(User.get(0)) {
            opportunity.StageName = 'Closed Lost';
            update opportunity;
        }

        ContentVersion cv = new ContentVersion(
                Title = 'Test',
                PathOnClient = 'Test.jpg',
                VersionData = Blob.valueOf('Test Content Data'),
                IsMajorVersion = true
        );
        insert cv;

        ContentDocument cd = [SELECT Id FROM ContentDocument WHERE ContentDocument.LatestPublishedVersionId = :cv.Id];

        ContentDocumentLink cdl2 = new ContentDocumentLink(
                ContentDocumentId = cd.Id,
                LinkedEntityId = opportunity.Id,
                ShareType = 'I'
        );
        insert cdl2;


        /*Carnet_Closed_Won_Files_Allowed_Profiles__c ap = new Carnet_Closed_Won_Files_Allowed_Profiles__c(
                Name = 'Admin',
                Profile_Id__c = User.get(0).ProfileId
        );
        insert ap;*/

        System.runAs(User.get(0)){
            try{
                delete cd;
            }
            catch(Exception e){

            }
        }
    }
}