default/objects/Account/fields/Agree_to_process_pers_data_for_marketing__c.field-meta.xml
<CustomField>
    <fullName>Agree_to_process_pers_data_for_marketing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Customer agrees that his personal information can be processed for marketing purposes.</description>
    <inlineHelpText>Customer agrees that his personal information can be processed for marketing purposes.</inlineHelpText>
    <label>Agree to process pers data for marketing</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Account/fields/Agree_to_receive_comm_info_by_email__c.field-meta.xml
<CustomField>
    <fullName>Agree_to_receive_comm_info_by_email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Customer agrees to receive the commercial information by email.</description>
    <inlineHelpText>Customer agrees to receive the commercial information by email.</inlineHelpText>
    <label>Agree to receive comm info by email</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Account/fields/Agree_to_telephone_contact__c.field-meta.xml
<CustomField>
    <fullName>Agree_to_telephone_contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Customer agrees to be contacted by phone.</description>
    <inlineHelpText>Customer agrees to be contacted by phone.</inlineHelpText>
    <label>Agree to telephone contact</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Account/fields/CCS_account_merge_status__c.field-meta.xml
<CustomField>
    <fullName>CCS_account_merge_status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CCS_account_merge_status</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Account/fields/CCS_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>CCS_Company_ID__c</fullName>
    <inlineHelpText>IČO</inlineHelpText>
    <label>ICO</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/CCS_Cribis__c.field-meta.xml
<CustomField>
    <fullName>CCS_Cribis__c</fullName>
    <label>CCS Cribis</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>Š</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/fields/Date_Agreed_GDPR__c.field-meta.xml
<CustomField>
    <fullName>Date_Agreed_GDPR__c</fullName>
    <description>Date and time when user agreed to tel. contact, email contact or marketing communication with FleetCor (and its divisions).</description>
    <inlineHelpText>GDPR</inlineHelpText>
    <label>Date Agreed (GDPR)</label>
    <type>DateTime</type>
</CustomField>

default/objects/Account/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>DO Markenpartner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/recordTypes/CCS.recordType-meta.xml
<RecordType>
    <fullName>CCS</fullName>
    <active>true</active>
    <label>CCS</label>
</RecordType>

default/objects/CCS_Order__c/CCS_Order__c.object-meta.xml
<CustomObject>
    <description>CCS Order custom object for all orders from Merlin.</description>
    <label>CCS Order</label>
    <nameField>
        <label>CCS Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CCS Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/CCS_Order__c/fields/Accident_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Accident_Insurance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accident Insurance</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CCS_Order__c/fields/CCS_MerlinID__c.field-meta.xml
<CustomField>
    <fullName>CCS_MerlinID__c</fullName>
    <externalId>true</externalId>
    <label>CCS Merlin ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Contact/fields/Customer_IP_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_IP_Address__c</fullName>
    <description>Field used for storing IP adresses of users coming through website (Web-to-Lead, web orders). GDPR Regulation.</description>
    <label>Customer IP Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Agree_to_process_pers_data_for_marketing__c.field-meta.xml
<CustomField>
    <fullName>Agree_to_process_pers_data_for_marketing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Customer agrees that his personal information can be processed for marketing purposes</inlineHelpText>
    <label>Agree to process pers data for marketing</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Lead/fields/CCS_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>CCS_Company_ID__c</fullName>
    <description>IČo</description>
    <inlineHelpText>IČo</inlineHelpText>
    <label>CCS Company ID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/CCS_Cribis__c.field-meta.xml
<CustomField>
    <fullName>CCS_Cribis__c</fullName>
    <description>Hodnocení Cribis.</description>
    <inlineHelpText>Hodnocení Cribis.</inlineHelpText>
    <label>CCS Cribis</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>Š</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/CCS_priobjednavka__c.field-meta.xml
<CustomField>
    <fullName>CCS_priobjednavka__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Přiobjednávka?</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Lead/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Agree_to_receive_comm_info_by_email__c.field-meta.xml
<CustomField>
    <fullName>Agree_to_receive_comm_info_by_email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Customer agrees to receive commercial information by email.</inlineHelpText>
    <label>Agree to receive comm info by email</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Agree_to_telephone_contact__c.field-meta.xml
<CustomField>
    <fullName>Agree_to_telephone_contact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Customer agrees to be contacted via phone.</inlineHelpText>
    <label>Agree to telephone contact</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Agree_to_VAT_Recovery_TC__c.field-meta.xml
<CustomField>
    <fullName>Agree_to_VAT_Recovery_TC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agree to VAT-Recovery T&amp;C</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/CCS_Accident_Insurance__c.field-meta.xml
<CustomField>
    <fullName>CCS_Accident_Insurance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to indicate whether the customer opted for accident insurance or not.</description>
    <label>CCS Accident Insurance</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/CCS_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>CCS_Company_ID__c</fullName>
    <description>CCS Company ID (IČ) mirrored from Account.</description>
    <formula>Account.CCS_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>CCS Company ID from Account.</inlineHelpText>
    <label>CCS Company ID</label>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/CCS_Cribis__c.field-meta.xml
<CustomField>
    <fullName>CCS_Cribis__c</fullName>
    <description>CCS Cribis</description>
    <inlineHelpText>CCS Cribis</inlineHelpText>
    <label>CCS Cribis</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>Š</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/CCS_MerlinID__c.field-meta.xml
<CustomField>
    <fullName>CCS_MerlinID__c</fullName>
    <label>CCS MerlinID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/CCS_priobjednavka__c.field-meta.xml
<CustomField>
    <fullName>CCS_priobjednavka__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Jedná se o přiobjednávku?</description>
    <inlineHelpText>Jedná se o přiobjednávku?</inlineHelpText>
    <label>Přiobjednávka?</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Date_Agreed_GDPR__c.field-meta.xml
<CustomField>
    <fullName>Date_Agreed_GDPR__c</fullName>
    <description>Date and time when user agreed to tel. contact, email contact or marketing communication with FleetCor (and its divisions).</description>
    <label>Date Agreed (GDPR)</label>
    <type>DateTime</type>
</CustomField>

default/objects/Opportunity/fields/Do_Not_Call__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Call</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Primary_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Phone__c</fullName>
    <label>Primary Contact Phone</label>
    <type>Phone</type>
</CustomField>

default/objects/Opportunity/fields/Product_Solicited__c.field-meta.xml
<CustomField>
    <fullName>Product_Solicited__c</fullName>
    <description>Name of the product the Customer Applied for</description>
    <inlineHelpText>Select the product the customer applied for.</inlineHelpText>
    <label>Product Solicited</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCS Aukce</fullName>
            </value>
            <value>
                <fullName>CCS Bonus</fullName>
            </value>
            <value>
                <fullName>CCS Bonus+</fullName>
            </value>
            <value>
                <fullName>CCS Bonus Fleet</fullName>
            </value>
            <value>
                <fullName>CCS Carnet</fullName>
            </value>
            <value>
                <fullName>CCS Limit</fullName>
            </value>
            <value>
                <fullName>CCS Limit+</fullName>
            </value>
            <value>
                <fullName>CCS Limit+ mini</fullName>
            </value>
            <value>
                <fullName>CCS Toll</fullName>
            </value>
            <value>
                <fullName>CCS Trucks</fullName>
            </value>
            <value>
                <fullName>UTA/CCS</fullName>
            </value>
            <value>
                <fullName>CCS Limit M4</fullName>
            </value>
            <value>
                <fullName>CCS Limit PRIM</fullName>
            </value>
            <value>
                <fullName>CCS Limit NP</fullName>
            </value>
            <value>
                <fullName>CCS Carnet NP</fullName>
            </value>
            <value>
                <fullName>CCS_Handy Card</fullName>
                <label>CCS Handy Card</label>
            </value>
            <value>
                <fullName>CCS LIMIT Exclusive</fullName>
            </value>
            <value>
                <fullName>E-shop</fullName>
            </value>
            <value>
                <fullName>ERV insurance</fullName>
            </value>
            <value>
                <fullName>OMV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/showCCSOrderTest.cls
@isTest
public class showCCSOrderTest {
public Id OpportunityId {get;set;}
    
@isTest static void testing() {
        
        Account a = new Account(
              Name = 'VÁCLAV KALAŠ',                                         // Account Name
              CCS_Company_ID__c = '71506233',                                // CCS Company ID
              Phone = '+420321321321',                                       // Phone
              Agree_to_process_pers_data_for_marketing__c = false,           // Agree to process pers data for marketing
              Agree_to_receive_comm_info_by_email__c = false,                // Agree to receive comm info by email
              Agree_to_telephone_contact__c = true,                          // Agree to telephone contact
              AccountSource = 'OZ login - Web CCS (objednávka CCS Limit)',   // Account Source
              Customer_IP_Address__c = '82.113.58.203',                      // Customer IP Address
              Date_Agreed_GDPR__c = Date.today(),  // Date Agreed (GDPR)
              BillingCountry = 'Czech Republic',
              CCS_account_merge_status__c = false);
       insert a;
       
       Opportunity o = new Opportunity(
              Name = 'VÁCLAV KALAŠ',                                         // Opportunity Name
              Type = 'New GFN',                                              // Type
              CloseDate = Date.today(),                                      // Close Date
              AccountId = a.Id,                                              // Account Name
              StageName = 'Order entered',                                   // Stage
              Primary_Contact_Phone__c = '+420321321321',                    // Primary Contact Phone
              CCS_Cribis__c = 'F',                                           // CCS Cribis
              CCS_MerlinID__c = '00161',                                     // CCS MerlinID
              CCS_priobjednavka__c = false,                                  // Přiobjednávka?
              Agree_to_telephone_contact__c = true,                          // Agree to telephone contact
              Agree_to_receive_comm_info_by_email__c = false,                // Agree to receive comm info by email
              Agree_to_process_pers_data_for_marketing__c = false,           // Agree to process pers data for marketing
              Do_Not_Call__c = false,                                        // Do Not Call
              Agree_to_VAT_Recovery_TC__c = false,                           // Agree to VAT-Recovery T&C
              CCS_Accident_Insurance__c = true,                              // CCS Accident Insurance
              Product_Solicited__c = 'CCS Limit',                            // Product Solicited
              LeadSource = 'OZ login - Web CCS (objednávka CCS Limit)',      // Lead Source
              Sec_Channel__c = 'Inbound',                                    // Sec. Channel
              Channel__c = 'web',                                            // Channel
              Customer_IP_Address__c = '82.113.58.203',                      // Customer IP Address
              Date_Agreed_GDPR__c = Date.today());
        insert o;
        
        CCS_Order__c ccsOrder = new CCS_Order__c(
              Name = 'Václav Kalaš',                       // CCS Order
              Account__c = a.Id,                           // Account
              OZ_Number__c = 'oznum',                      // OZ Number
              Opportunity__c = o.Id,                       // Opportunity
              Offer_Type__c = 'CCS Limit Moje síť/M4',     // Offer Type
              CCS_MerlinID__c = '00161',                   // CCS Merlin ID
              Number_of_Cards__c = 2,                      // Number of Cards
              Monthly_Bill_Email__c = false,               // Monthly Bill - Email
              Number_of_Card_Variants__c = 0,              // Number of Card Variants
              Monthly_Bill_Post__c = false,                // Monthly Bill - Post
              Number_of_Vehicles__c = 0,                   // Number of Vehicles
              Accident_Insurance__c = false,               // Accident Insurance
              T_C_Agree__c = false,                        // T&C Agree
              Financial_Credit__c = 0,                     // Financial Credit
              Card_Issuance_Price__c = 0,                  // Card Issuance Price
              Monthly_Fixed_Card_Payment__c = 0,           // Monthly Fixed Card Payment
              Total_Monthly_Payment__c = 0,                // Total Monthly Payment
              Price__c = 0);
        insert ccsOrder;
        
    
    test.startTest();
        Apexpages.currentPage().getParameters().put('id',o.Id);
        showCCSOrder SCO = new showCCSOrder();
        
        SCO.OpportunityId = o.Id;
        
        System.assertNotEquals(null, SCO.OpportunityId);
        System.assertNotEquals(null, SCO.getCCSOrder());
    }
}