default/objects/Account/fields/Anzahl_der_Karten__c.field-meta.xml
<CustomField>
    <fullName>Anzahl_der_Karten__c</fullName>
    <label>Anzahl der Karten</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Anzahl_der_Karten__c.field-meta.xml
<CustomField>
    <fullName>Anzahl_der_Karten__c</fullName>
    <label>Anzahl der Karten*</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Number_of_cars__c.field-meta.xml
<CustomField>
    <fullName>Number_of_cars__c</fullName>
    <inlineHelpText>should not be equal to '0'</inlineHelpText>
    <label>Number of cars</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/recordTypes/Carnet.recordType-meta.xml
<RecordType>
    <fullName>Carnet</fullName>
    <active>true</active>
    <businessProcess>Carnet</businessProcess>
    <description>Record Type for Carnet records.</description>
    <label>Carnet</label>
</RecordType>

default/classes/CarnetE2EServiceTest.cls
/**
 * Created by eugene on 10/2/19.
 */

@IsTest
private class CarnetE2EServiceTest {
    @IsTest
    static void testOpportunityCreation() {
        Account newAccount = new Account(
                Name = 'test account',
                BillingCountry = 'Poland'
        );
        insert newAccount;

        Contact newContact = new Contact(
                FirstName = 'test',
                LastName = 'test2',
                Phone = '+1112223333',
                AccountId = newAccount.Id
        );
        insert newContact;

        Opportunity newOpportunity = new Opportunity(
                Name = 'test opp',
                StageName = 'Prospecting',
                CloseDate = Date.today(),
                Number_of_cars__c = 1,
                Anzahl_der_Karten__c = 3,
                AccountId = newAccount.Id
        );
        insert newOpportunity;

        OpportunityContactRole role = new OpportunityContactRole(
                ContactId = newContact.Id,
                OpportunityId = newOpportunity.Id,
                IsPrimary = true
        );
        insert role;

        Test.startTest();
        CarnetE2EService.createCarnetOpportunity(newOpportunity.Id);
        Test.stopTest();
        List<Opportunity> testOpportunity = [SELECT Id FROM Opportunity WHERE Name = 'TEST ACCOUNT-CARNET'];
        System.assert( ! testOpportunity.isEmpty() );
    }
}