default/objects/Account/fields/Anzahl_der_Karten__c.field-meta.xml
<CustomField>
    <fullName>Anzahl_der_Karten__c</fullName>
    <label>Anzahl der Karten</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Account/fields/Beschaeftigte__c.field-meta.xml
<CustomField>
    <fullName>Beschaeftigte__c</fullName>
    <label>Beschäftigte *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-4</fullName>
            </value>
            <value>
                <fullName>5-9</fullName>
            </value>
            <value>
                <fullName>10-19</fullName>
            </value>
            <value>
                <fullName>20-49</fullName>
            </value>
            <value>
                <fullName>50-74</fullName>
            </value>
            <value>
                <fullName>75-99</fullName>
            </value>
            <value>
                <fullName>100-149</fullName>
            </value>
            <value>
                <fullName>150-199</fullName>
            </value>
            <value>
                <fullName>&gt;200</fullName>
            </value>
            <value>
                <fullName>k.A.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/fields/Bundesland__c.field-meta.xml
<CustomField>
    <fullName>Bundesland__c</fullName>
    <label>Bundesland *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Baden-Württemberg</fullName>
            </value>
            <value>
                <fullName>Bayern</fullName>
            </value>
            <value>
                <fullName>Berlin</fullName>
            </value>
            <value>
                <fullName>Brandenburg</fullName>
            </value>
            <value>
                <fullName>Bremen</fullName>
            </value>
            <value>
                <fullName>Hamburg</fullName>
            </value>
            <value>
                <fullName>Hessen</fullName>
            </value>
            <value>
                <fullName>Mecklenburg-Vorpommern</fullName>
            </value>
            <value>
                <fullName>Niedersachsen</fullName>
            </value>
            <value>
                <fullName>Nordrhein-Westfalen</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Rheinland-Pfalz</fullName>
            </value>
            <value>
                <fullName>Saarland</fullName>
            </value>
            <value>
                <fullName>Sachsen</fullName>
            </value>
            <value>
                <fullName>Sachsen-Anhalt</fullName>
            </value>
            <value>
                <fullName>Schleswig-Holstein</fullName>
            </value>
            <value>
                <fullName>Thüringen</fullName>
            </value>
            <value>
                <fullName>Wien</fullName>
            </value>
            <value>
                <fullName>Niederösterreich</fullName>
            </value>
            <value>
                <fullName>Oberösterreich</fullName>
            </value>
            <value>
                <fullName>Steiermark</fullName>
            </value>
            <value>
                <fullName>Burgenland</fullName>
            </value>
            <value>
                <fullName>Kärnten</fullName>
            </value>
            <value>
                <fullName>Salzburg</fullName>
            </value>
            <value>
                <fullName>Tirol</fullName>
            </value>
            <value>
                <fullName>Vorarlberg</fullName>
            </value>
            <value>
                <fullName>Antwerpen</fullName>
            </value>
            <value>
                <fullName>Vlaams-Brabant</fullName>
            </value>
            <value>
                <fullName>Hainaut</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/fields/GFN_Nr__c.field-meta.xml
<CustomField>
    <fullName>GFN_Nr__c</fullName>
    <description>Unique account identifier generated in GFN (Global FleetNet) system</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique account identifier generated in GFN (Global FleetNet) system</inlineHelpText>
    <label>GFN Nr.</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Account/fields/Gruende_fuer_Tankkarten__c.field-meta.xml
<CustomField>
    <fullName>Gruende_fuer_Tankkarten__c</fullName>
    <inlineHelpText>Aus Sicht des Ansprechpartners aufnehmen!</inlineHelpText>
    <label>Gründe für Tankkarten? *</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>vereinfachte Abrechnung</fullName>
            </value>
            <value>
                <fullName>Kostenersparnis</fullName>
            </value>
            <value>
                <fullName>bargeldloses Zahlungmittel</fullName>
            </value>
            <value>
                <fullName>Transparenz</fullName>
            </value>
            <value>
                <fullName>Andere</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/fields/Hausnummer_E__c.field-meta.xml
<CustomField>
    <fullName>Hausnummer_E__c</fullName>
    <label>Hausnummer *</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/IBAN_des_Zahlungspflichtigen__c.field-meta.xml
<CustomField>
    <fullName>IBAN_des_Zahlungspflichtigen__c</fullName>
    <label>IBAN des Zahlungspflichtigen *</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Kraftstoffverbrauch_Liter_Monat__c.field-meta.xml
<CustomField>
    <fullName>Kraftstoffverbrauch_Liter_Monat__c</fullName>
    <inlineHelpText>Über alle Karten hinweg!</inlineHelpText>
    <label>Kraftstoffverbrauch L/Monat</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Account/fields/Land__c.field-meta.xml
<CustomField>
    <fullName>Land__c</fullName>
    <label>Land *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deutschland</fullName>
            </value>
            <value>
                <fullName>Österreich</fullName>
            </value>
            <value>
                <fullName>Niederlande</fullName>
            </value>
            <value>
                <fullName>Frankreich</fullName>
            </value>
            <value>
                <fullName>Belgien</fullName>
            </value>
            <value>
                <fullName>Ungarn</fullName>
            </value>
            <value>
                <fullName>Polen</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Luxemburg</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
            <value>
                <fullName>Albanien</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Bosnien und Herzegowina</fullName>
            </value>
            <value>
                <fullName>Bulgarien</fullName>
            </value>
            <value>
                <fullName>Dänemark</fullName>
            </value>
            <value>
                <fullName>Estland</fullName>
            </value>
            <value>
                <fullName>Finnland</fullName>
            </value>
            <value>
                <fullName>Griechenland</fullName>
            </value>
            <value>
                <fullName>Irland</fullName>
            </value>
            <value>
                <fullName>Island</fullName>
            </value>
            <value>
                <fullName>Italien</fullName>
            </value>
            <value>
                <fullName>Kasachstan</fullName>
            </value>
            <value>
                <fullName>Kosovo</fullName>
            </value>
            <value>
                <fullName>Kroatien</fullName>
            </value>
            <value>
                <fullName>Lettland</fullName>
            </value>
            <value>
                <fullName>Liechtenstein</fullName>
            </value>
            <value>
                <fullName>Litauen</fullName>
            </value>
            <value>
                <fullName>Malta</fullName>
            </value>
            <value>
                <fullName>Mazedonien</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/fields/Land_E__c.field-meta.xml
<CustomField>
    <fullName>Land_E__c</fullName>
    <label>Land</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Deutschland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Nederland</fullName>
            </value>
            <value>
                <fullName>Österreich</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/fields/Name_Zahlungspflichtigen_Kontoinhaber__c.field-meta.xml
<CustomField>
    <fullName>Name_Zahlungspflichtigen_Kontoinhaber__c</fullName>
    <label>Name Zahlungspflichtigen/Kontoinhaber *</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Ort_E__c.field-meta.xml
<CustomField>
    <fullName>Ort_E__c</fullName>
    <label>Ort *</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/PLZ_E__c.field-meta.xml
<CustomField>
    <fullName>PLZ_E__c</fullName>
    <label>PLZ *</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/PLZ_und_Ort__c.field-meta.xml
<CustomField>
    <fullName>PLZ_und_Ort__c</fullName>
    <label>PLZ und Ort *</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>DO Markenpartner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/fields/Strasse_E__c.field-meta.xml
<CustomField>
    <fullName>Strasse_E__c</fullName>
    <label>Straße *</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Strasse_und_Hausnummer__c.field-meta.xml
<CustomField>
    <fullName>Strasse_und_Hausnummer__c</fullName>
    <label>Straße und Hausnummer *</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/SWIFT_BIC__c.field-meta.xml
<CustomField>
    <fullName>SWIFT_BIC__c</fullName>
    <label>SWIFT BIC *</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Anzahl_der_Karten__c.field-meta.xml
<CustomField>
    <fullName>Anzahl_der_Karten__c</fullName>
    <label>Anzahl der Karten*</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/GFN_Nr__c.field-meta.xml
<CustomField>
    <fullName>GFN_Nr__c</fullName>
    <formula>Account.GFN_Nr__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GFN Nr.</label>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/IBAN_des_Zahlungspflichtigen__c.field-meta.xml
<CustomField>
    <fullName>IBAN_des_Zahlungspflichtigen__c</fullName>
    <label>IBAN des Zahlungspflichtigen *</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Kraftstoffverbrauch_Liter_Monat__c.field-meta.xml
<CustomField>
    <fullName>Kraftstoffverbrauch_Liter_Monat__c</fullName>
    <label>Kraftstoffverbrauch Liter/Monat *</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/recordTypes/Euroshell.recordType-meta.xml
<RecordType>
    <fullName>Euroshell</fullName>
    <active>true</active>
    <businessProcess>Euroshell</businessProcess>
    <label>Euroshell</label>
</RecordType>

default/classes/BatchCheckingAdoptionJITBprocessTest.cls
@isTest
private class BatchCheckingAdoptionJITBprocessTest {
	public static Account acc;
	public static User abandonmentUser;

    
    /******************************************************************************
	*  Summary         : test checking adoption JITB process    
	*  CreatedDate     : 24/01/2019
	******************************************************************************/
    @isTest
    public static void testCheckingAdoptionJITBprocess() {
		createAbandonmentUser();
		createCustomSettings();
		createAccounts();
    	createOpportunities();

    	Test.startTest();
	    	BatchCheckingAdoptionJITBprocess batch = new BatchCheckingAdoptionJITBprocess();
	    	Database.executeBatch(batch);
    	Test.stopTest();

    	List<Opportunity> opptiesList = [SELECT OwnerId FROM Opportunity];
    	for (Opportunity oppty : opptiesList) {
    		System.assertEquals(abandonmentUser.Id, oppty.OwnerId);
    	}
    }


   	/******************************************************************************
   	*  Summary         : create users for test     
   	*  CreatedDate     : 24/01/2019
   	******************************************************************************/
   	private static void createAbandonmentUser() {
	   	List<User> usersList = [SELECT Id, Username FROM User WHERE Profile.Name = 'System Administrator' LIMIT 1];
	   	if (! usersList.isEmpty()) {
	   		abandonmentUser = usersList.get(0);
	   	}
   	}


    /******************************************************************************
    *  Summary         : create data for test (account and opportunity)    
    *  CreatedDate     : 24/01/2019
    ******************************************************************************/
    private static void createAccounts() {
    	acc = new Account(
    		Name = 'test',
    		GFN_Nr__c  = '123',
			Type = 'Customer',
			Bundesland__c = 'Germany',
			Beschaeftigte__c = '1-4',
    		Strasse_E__c = 'test',
    		Hausnummer_E__c = 'test',
    		PLZ_E__c = 'test',
    		Ort_E__c = 'tet',
    		Land_E__c = 'DE',
    		BillingCountry = 'Germany',
    		Name_Zahlungspflichtigen_Kontoinhaber__c = 'test',
    		Strasse_und_Hausnummer__c = 'tes',
    		PLZ_und_Ort__c = 'test',
    		IBAN_des_Zahlungspflichtigen__c = 'tes',					
    		SWIFT_BIC__c = 'test',
    		Land__c = 'test land',
    		Gruende_fuer_Tankkarten__c = 'vereinfachte Abrechnung',
    		Kraftstoffverbrauch_Liter_Monat__c = 2);
    	insert acc;

    	Datetime cd = Datetime.now().addDays(-6);
		Test.setCreatedDate(acc.Id, cd);
	}

    private static void createOpportunities() {
        List<User> usersList = [SELECT Id, Username FROM User WHERE Name = 'Integration Administrator' LIMIT 1];
        RecordType rt = [SELECT Id FROM RecordType WHERE Name = 'Euroshell' AND sObjectType = 'Opportunity' LIMIT 1];
        Opportunity oppty = new Opportunity(
            RecordTypeId = rt.Id,
            AccountId = acc.Id,
            OwnerId = usersList.get(0).Id,
            Kraftstoffverbrauch_Liter_Monat__c = 2,
            Anzahl_der_Karten__c = 5,
            E2E__c = true,
            Sec_Channel__c = 'JITB',
            Derzeitige_Zahlungsmethode__c = 'Bank',
            Kundensegment__c = 'Campaign_1',
            Zahlungsart__c = 'Lastschrift',
            Zahlungsziel__c = '7',
            Angebotsdauer__c = 'test',
            StageName = 'Prospecting',
            Name = 'test e2e opp',
            Product__c = 'None',
            Disable_for_KPI__c = FALSE,
            Last_Owner_Change_Date__c = Date.newinstance(2016, 12, 27),
            CloseDate = Date.newinstance(2016, 12, 28));
        insert oppty;

		Datetime cd = Datetime.now().addDays(-6);
		Test.setCreatedDate(oppty.Id, cd);
    }


    /******************************************************************************
    *  Summary         : create custom setting for test of checking adoption JITB process     
    *  CreatedDate     : 24/01/2019
    ******************************************************************************/
    private static void createCustomSettings() {
		List<SObject> customSettings = new List<SObject>();
		List<User> e2eUser = [SELECT Id, ProfileId FROM User WHERE Name = 'Integration Administrator' LIMIT 1];
        List<Profile> e2eAdminUser = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];

        Fleetcor_Profile_Info_Settings__c e2esSettings = new Fleetcor_Profile_Info_Settings__c(
            Name = 'E2E Profile',
            ProfileId__c = e2eUser.get(0).ProfileId);
        customSettings.add(e2esSettings);

		Adoption_Process_Settings__c adoptionSettings = new Adoption_Process_Settings__c(
			Name = 'GermanyJITB',
	        Number_Of_Days_To_Reassign__c = 5
		);
	    customSettings.add(adoptionSettings);

	    E2E_Form_General_Settings__c generalSettings = new E2E_Form_General_Settings__c(
			Name = 'Germany',
	        Abandonment_User__c = abandonmentUser.Id
		);
	    customSettings.add(generalSettings);

		insert customSettings;
    } 
}