default/objects/Account/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <description>Наименование банка</description>
    <label>Bank</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Black_list_check_code__c.field-meta.xml
<CustomField>
    <fullName>Black_list_check_code__c</fullName>
    <description>Код решения по черному списку в кредитной фабрике</description>
    <inlineHelpText>Код решения по черному списку в кредитной фабрике</inlineHelpText>
    <label>Black list code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Checking_Account__c.field-meta.xml
<CustomField>
    <fullName>Checking_Account__c</fullName>
    <description>Рассчетный счет</description>
    <label>Checking account</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Code_Word__c.field-meta.xml
<CustomField>
    <fullName>Code_Word__c</fullName>
    <label>Code Word</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Cor_bank_account__c.field-meta.xml
<CustomField>
    <fullName>Cor_bank_account__c</fullName>
    <description>КС (корреспондентский счет)</description>
    <label>Сorrespondent bank account</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Идентификационный номер налогоплательщика.
            Должен содержать только цифры:
            12 цифр - ИП;
            10 цифр - юр. лицо.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Account/fields/KPP__c.field-meta.xml
<CustomField>
    <fullName>KPP__c</fullName>
    <description>Please insert a KPP</description>
    <label>KPP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Account/fields/OGRN_ppr__c.field-meta.xml
<CustomField>
    <fullName>OGRN_ppr__c</fullName>
    <inlineHelpText>Основной Государственный Регистрационный Номер</inlineHelpText>
    <label>OGRN_ppr</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/OKPO_ppr__c.field-meta.xml
<CustomField>
    <fullName>OKPO_ppr__c</fullName>
    <inlineHelpText>Общероссийский Классификатор Предприятий и Организаций</inlineHelpText>
    <label>OKPO_ppr</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/OKVED__c.field-meta.xml
<CustomField>
    <fullName>OKVED__c</fullName>
    <label>OKVED</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/Account/recordTypes/Russian.recordType-meta.xml
<RecordType>
    <fullName>Russian</fullName>
    <active>true</active>
    <label>Russian</label>
</RecordType>

default/objects/Opportunity/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <label>Bank</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Derzeitige_Zahlungsmethode__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Commerzbank</fullName>
            </value>
            <value>
                <fullName>Deutsche Bank</fullName>
            </value>
            <value>
                <fullName>Sparkasse</fullName>
            </value>
            <value>
                <fullName>Andere</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Number_Business_CARD__c.field-meta.xml
<CustomField>
    <fullName>Number_Business_CARD__c</fullName>
    <description>Для учета Бизнес карт</description>
    <inlineHelpText>проданных Бизнес карт</inlineHelpText>
    <label>Number of Business CARD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Number_of_Cards__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Cards__c</fullName>
    <description>Number of Cards</description>
    <inlineHelpText>Number of Cards</inlineHelpText>
    <label>Number of Cards</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Number_of_trucks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_trucks__c</fullName>
    <inlineHelpText>should not be equal to '0'</inlineHelpText>
    <label>Number of trucks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Vehicles__c</fullName>
    <description>Number of vehicles</description>
    <inlineHelpText>Number of vehicles</inlineHelpText>
    <label>Number of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Product_PPR__c.field-meta.xml
<CustomField>
    <fullName>Product_PPR__c</fullName>
    <label>Product PPR</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Супер 2020 с карты</fullName>
            </value>
            <value>
                <fullName>Супер 2020 с договора</fullName>
            </value>
            <value>
                <fullName>Лайт 2020 с карты</fullName>
            </value>
            <value>
                <fullName>Лайт 2020 с договора</fullName>
            </value>
            <value>
                <fullName>Избранный - Газпромнефть 2020 с карты</fullName>
            </value>
            <value>
                <fullName>Избранный - Газпромнефть 2020 с договора</fullName>
            </value>
            <value>
                <fullName>Шелл Сайт_АИ</fullName>
            </value>
            <value>
                <fullName>Шелл Сайт_ДТ</fullName>
            </value>
            <value>
                <fullName>Избранный+ 2020 с карты</fullName>
            </value>
            <value>
                <fullName>Избранный+ 2020 с договора</fullName>
            </value>
            <value>
                <fullName>Оптимальный+ 2020</fullName>
            </value>
            <value>
                <fullName>Газпром+ 2020 с карты</fullName>
            </value>
            <value>
                <fullName>Газпром+ 2020 с договора</fullName>
            </value>
            <value>
                <fullName>ГАЗПРОМ 2020 с карты</fullName>
            </value>
            <value>
                <fullName>ГАЗПРОМ 2020 с договора</fullName>
            </value>
            <value>
                <fullName>Оптимальный 2020 с карты</fullName>
            </value>
            <value>
                <fullName>Оптимальный 2020 с договора</fullName>
            </value>
            <value>
                <fullName>Шелл Кард "АЗС"</fullName>
            </value>
            <value>
                <fullName>Winback 1</fullName>
            </value>
            <value>
                <fullName>Winback 2</fullName>
            </value>
            <value>
                <fullName>Командировки</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Projected_Liters_weekly__c.field-meta.xml
<CustomField>
    <fullName>Projected_Liters_weekly__c</fullName>
    <description>FORMULA FIELD:  Number of liters projected to be fueled per week for this prospect.  Calculated as the number of vehicles times the estimated liters per vehicle per week.
Russia uses liters projected per monthly.</description>
    <inlineHelpText>should not be equal to '0'</inlineHelpText>
    <label>Projected Liters (weekly)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Promo_campaign__c.field-meta.xml
<CustomField>
    <fullName>Promo_campaign__c</fullName>
    <label>Promo campaign</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5Г01</fullName>
            </value>
            <value>
                <fullName>9Е06</fullName>
            </value>
            <value>
                <fullName>9Е07</fullName>
            </value>
            <value>
                <fullName>9Е08</fullName>
            </value>
            <value>
                <fullName>9Е09</fullName>
            </value>
            <value>
                <fullName>9Е10</fullName>
            </value>
            <value>
                <fullName>9Е11</fullName>
            </value>
            <value>
                <fullName>9Е12</fullName>
            </value>
            <value>
                <fullName>9Е13</fullName>
            </value>
            <value>
                <fullName>9Е14</fullName>
            </value>
            <value>
                <fullName>9Е19</fullName>
            </value>
            <value>
                <fullName>9Е20</fullName>
            </value>
            <value>
                <fullName>9Е21</fullName>
            </value>
            <value>
                <fullName>PIU5</fullName>
            </value>
            <value>
                <fullName>9Е22</fullName>
            </value>
            <value>
                <fullName>9Е23</fullName>
            </value>
            <value>
                <fullName>9Е24</fullName>
            </value>
            <value>
                <fullName>9Е25</fullName>
            </value>
            <value>
                <fullName>Winback_1</fullName>
            </value>
            <value>
                <fullName>Winback_2</fullName>
            </value>
            <value>
                <fullName>Winback_3</fullName>
            </value>
            <value>
                <fullName>Winback_4</fullName>
            </value>
            <value>
                <fullName>Winback_5</fullName>
            </value>
            <value>
                <fullName>Winback_6</fullName>
            </value>
            <value>
                <fullName>Winback_7</fullName>
            </value>
            <value>
                <fullName>Winback_8</fullName>
            </value>
            <value>
                <fullName>Winback_9</fullName>
            </value>
            <value>
                <fullName>Winback_10</fullName>
            </value>
            <value>
                <fullName>Winback_11</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Promo_Code1__c.field-meta.xml
<CustomField>
    <fullName>Promo_Code1__c</fullName>
    <label>Promo Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1Ч01</fullName>
            </value>
            <value>
                <fullName>2И01</fullName>
            </value>
            <value>
                <fullName>2И02</fullName>
            </value>
            <value>
                <fullName>7Р01</fullName>
            </value>
            <value>
                <fullName>5БК6</fullName>
            </value>
            <value>
                <fullName>5БК7</fullName>
            </value>
            <value>
                <fullName>5БК9</fullName>
            </value>
            <value>
                <fullName>5РД1</fullName>
            </value>
            <value>
                <fullName>6З03</fullName>
                <label>7З03</label>
            </value>
            <value>
                <fullName>7З00</fullName>
            </value>
            <value>
                <fullName>7ВЗ1</fullName>
            </value>
            <value>
                <fullName>7З11</fullName>
            </value>
            <value>
                <fullName>7312</fullName>
            </value>
            <value>
                <fullName>7З06</fullName>
            </value>
            <value>
                <fullName>7З09</fullName>
            </value>
            <value>
                <fullName>9ИРК</fullName>
            </value>
            <value>
                <fullName>9ВЗ1</fullName>
            </value>
            <value>
                <fullName>9ВСТ</fullName>
            </value>
            <value>
                <fullName>CARW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Source_of_Lead_o__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Lead_o__c</fullName>
    <label>Source of Lead_o</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Актуализированная БД</fullName>
            </value>
            <value>
                <fullName>Прочая БД</fullName>
                <default>true</default>
                <label>Прочая БД</label>
            </value>
            <value>
                <fullName>Выставка</fullName>
            </value>
            <value>
                <fullName>Найден в Интернете</fullName>
            </value>
            <value>
                <fullName>Реклама Клиента</fullName>
            </value>
            <value>
                <fullName>Почтовая Рассылка</fullName>
            </value>
            <value>
                <fullName>Рекомендация</fullName>
            </value>
            <value>
                <fullName>Реклама на АЗС</fullName>
            </value>
            <value>
                <fullName>Email Рассылка</fullName>
            </value>
            <value>
                <fullName>Интернет Источники</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.ru</fullName>
            </value>
            <value>
                <fullName>Поисковая Система</fullName>
            </value>
            <value>
                <fullName>Business card</fullName>
            </value>
            <value>
                <fullName>Партнерская Программа</fullName>
            </value>
            <value>
                <fullName>Реклама в СМИ</fullName>
            </value>
            <value>
                <fullName>Полевой канал</fullName>
            </value>
            <value>
                <fullName>Сайт fuel.veb-leasing.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.kz</fullName>
            </value>
            <value>
                <fullName>Petrolcards.ru - АГГРЕГАТОР</fullName>
            </value>
            <value>
                <fullName>АЗС Заявка Shell</fullName>
            </value>
            <value>
                <fullName>Сайт gpc-store.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Shell Card.ru</fullName>
            </value>
            <value>
                <fullName>E2E Form RU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Source_PP__c.field-meta.xml
<CustomField>
    <fullName>Source_PP__c</fullName>
    <label>Источник ПП</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Virtual_cards__c.field-meta.xml
<CustomField>
    <fullName>Virtual_cards__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Issue virtual cards</description>
    <inlineHelpText>Issue virtual cards</inlineHelpText>
    <label>Virtual cards</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/recordTypes/Russian_Sales.recordType-meta.xml
<RecordType>
    <fullName>Russian_Sales</fullName>
    <active>true</active>
    <businessProcess>Russian Sales</businessProcess>
    <label>Russian Sales</label>

</RecordType>

default/classes/OrganizationRequisiteTestDataFactory.cls
@IsTest
public with sharing class OrganizationRequisiteTestDataFactory {

    public static Account createAccount(String INN, String accName, Integer KPP) {
        Account account = new Account(
                Name = accName,
                INN__c = INN,
                KPP__c = KPP,
                Black_list_check_code__c = '0',
                Bank__c = 'АО "ТИНЬКОФФ БАНК"',
                Checking_Account__c = '88794484848484848484',
                Cor_bank_account__c = '00288679',
                Code_Word__c = 'КОДВОРД',
                BillingCountry = GlobalUtils.FleetcorCountries.Russia.name(),
                ShippingCountry = GlobalUtils.FleetcorCountries.Russia.name(),
                OGRN_ppr__c = '1035901764910',
                OKPO_ppr__c = '14673197',
                OKVED__c = 'Деятельность стоянок для транспортных средств',
                RecordTypeId = GlobalUtils.getRecordTypeId('Account', 'Russian')
        );
        return account;
    }

    public static Contact createContact(Account account) {
        Contact contact = new Contact(
                AccountId = account.Id,
                FirstName = 'Contact Test',
                LastName = 'LastName',
                Title = 'генеральный директор',
                Phone = '+73444444444',
                Email = 'test@mai.ru',
                RecordTypeId = GlobalUtils.getRecordTypeId('Contact', 'Russian')
        );
        return contact;
    }

    public static Opportunity createOpportunity(Account account) {
        Opportunity opportunity = new Opportunity(
                Name = 'test opportunity',
                StageName = GlobalUtils.getOpportunityStageName(GlobalUtils.OpportunityStage.Qualified_Lead),
                AccountId = account.Id,
                CloseDate = Date.today(),
                Projected_Liters_weekly__c = 200,
                Number_of_Vehicles__c = 100,
                Number_of_trucks__c = 1,
                Source_PP__c = 'EP',
                Source_of_Lead_o__c = 'Прочая БД',
                Product_PPR__c = 'ГАЗПРОМ – сеть АЗС',
                Number_of_Cards__c = 1,
                Virtual_cards__c = true,
                Number_Business_CARD__c = 1,
                Promo_campaign__c = '5Г01',
                Promo_Code1__c = 'реанимация',
                Paid_personal_manager__c = false,
                CategoryContract__c = 'МО',
                Our_organization__c = 'GPC',
                Amount_payment__c = 33,
                Standard_contract__c = true,
                Subject_contract__c = '22',
                Note_contract__c = '42',
                Contract_amount__c = 421,
                Express_delivery_documents__c = true,
                RecordTypeId = GlobalUtils.getRecordTypeId('Opportunity', 'Russian_Sales')

        );
        return opportunity;
    }

    public static OpportunityContactRole createOpportunityContactRole(Contact contact, Opportunity opportunity) {
        OpportunityContactRole opportunityContactRole = new OpportunityContactRole(
                ContactId = contact.Id,
                OpportunityId = opportunity.Id,
                IsPrimary = true
        );
        return opportunityContactRole;
    }
}