default/objects/Account/fields/Cards_delivery_courier_info__c.field-meta.xml
<CustomField>
    <fullName>Cards_delivery_courier_info__c</fullName>
    <label>Cards delivery courier info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Original_document_courier_info__c.field-meta.xml
<CustomField>
    <fullName>Original_document_courier_info__c</fullName>
    <label>Original document courier info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Form_MZK_Settings__c/E2E_Form_MZK_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>E2E Form MZK Settings</label>
</CustomObject>

default/objects/E2E_Form_MZK_Settings__c/fields/Is_Common__c.field-meta.xml
<CustomField>
    <fullName>Is_Common__c</fullName>
    <label>Is Common</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2E_Form_MZK_Settings__c/fields/Is_Ruble__c.field-meta.xml
<CustomField>
    <fullName>Is_Ruble__c</fullName>
    <label>Is Ruble</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2E_Form_MZK_Settings__c/fields/Limit_Type_Ids__c.field-meta.xml
<CustomField>
    <fullName>Limit_Type_Ids__c</fullName>
    <label>Limit Type Ids</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2E_Form_MZK_Settings__c/fields/Limit_Values__c.field-meta.xml
<CustomField>
    <fullName>Limit_Values__c</fullName>
    <description>limits for services (splitted by &#39;&#39;;&quot;)</description>
    <label>Limit Values</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2E_Form_MZK_Settings__c/fields/Log_User__c.field-meta.xml
<CustomField>
    <fullName>Log_User__c</fullName>
    <label>Log User</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2E_Form_MZK_Settings__c/fields/Send_Type__c.field-meta.xml
<CustomField>
    <fullName>Send_Type__c</fullName>
    <label>Send Type</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/E2E_Form_MZK_Settings__c/fields/Service_Groups__c.field-meta.xml
<CustomField>
    <fullName>Service_Groups__c</fullName>
    <label>Service Groups</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2E_Form_MZK_Settings__c/fields/Service_Ids__c.field-meta.xml
<CustomField>
    <fullName>Service_Ids__c</fullName>
    <description>Service identifiers splitted by &quot;;&quot;</description>
    <label>Service Ids</label>
    <type>TextArea</type>
</CustomField>

default/objects/Opportunity/fields/ALL_Cards__c.field-meta.xml
<CustomField>
    <fullName>ALL_Cards__c</fullName>
    <formula>Number_of_Cards__c + Number_Business_CARD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ALL Cards</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Our_organization__c.field-meta.xml
<CustomField>
    <fullName>Our_organization__c</fullName>
    <label>Our organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PPR</fullName>
            </value>
            <value>
                <fullName>GPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Product_PPR__c.field-meta.xml
<CustomField>
    <fullName>Product_PPR__c</fullName>
    <label>Product PPR</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Супер 2020 с карты</fullName>
            </value>
            <value>
                <fullName>Супер 2020 с договора</fullName>
            </value>
            <value>
                <fullName>Лайт 2020 с карты</fullName>
            </value>
            <value>
                <fullName>Лайт 2020 с договора</fullName>
            </value>
            <value>
                <fullName>Избранный - Газпромнефть 2020 с карты</fullName>
            </value>
            <value>
                <fullName>Избранный - Газпромнефть 2020 с договора</fullName>
            </value>
            <value>
                <fullName>Шелл Сайт_АИ</fullName>
            </value>
            <value>
                <fullName>Шелл Сайт_ДТ</fullName>
            </value>
            <value>
                <fullName>Избранный+ 2020 с карты</fullName>
            </value>
            <value>
                <fullName>Избранный+ 2020 с договора</fullName>
            </value>
            <value>
                <fullName>Оптимальный+ 2020</fullName>
            </value>
            <value>
                <fullName>Газпром+ 2020 с карты</fullName>
            </value>
            <value>
                <fullName>Газпром+ 2020 с договора</fullName>
            </value>
            <value>
                <fullName>ГАЗПРОМ 2020 с карты</fullName>
            </value>
            <value>
                <fullName>ГАЗПРОМ 2020 с договора</fullName>
            </value>
            <value>
                <fullName>Оптимальный 2020 с карты</fullName>
            </value>
            <value>
                <fullName>Оптимальный 2020 с договора</fullName>
            </value>
            <value>
                <fullName>Шелл Кард "АЗС"</fullName>
            </value>
            <value>
                <fullName>Winback 1</fullName>
            </value>
            <value>
                <fullName>Winback 2</fullName>
            </value>
            <value>
                <fullName>Командировки</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Transit_ID__c.field-meta.xml
<CustomField>
    <fullName>Transit_ID__c</fullName>
    <description>Unique Transit ID</description>
    <label>Transit ID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/classes/MZKRequestDataBuilder.cls
public with sharing class MZKRequestDataBuilder {
    public static final String E2E_EXCEPTION = 'MZK Setting does not found';
    public static final String MZK_SETTING_NAME = 'E2EFormRu';
    public static final String PRODUCT_SETTING_NAME = 'mzkId';
    public static final String MZK_PRODUCT = 'product';
    private E2EFormRuDao e2eFormRuDao;

    public MZKRequestDataBuilder() {
        this.e2eFormRuDao = new E2EFormRuDaoImpl();
    }

    public MZKRequest buildForOrgReqv(Id opportunityId) {
        MZKRequest mzkRequest = new MZKRequest();
        if (opportunityId != null) {
            E2E_Form_MZK_Settings__c mzkSettings = E2E_Form_MZK_Settings__c.getValues(MZK_SETTING_NAME);
            Opportunity opportunity = this.e2eFormRuDao.getOpportunityById(opportunityId);
            Account account = this.e2eFormRuDao.getAccountById(opportunity.AccountId);
            Map<String, Object> productMapping = PPRProductSettingsUtils.getTariffMapping(opportunity.Product_PPR__c);
            Map<String, Object> organizationMapping = MZKRequestSettingUtils.getProductSettings();
            String product = '';
            if (productMapping != null) {
                product = String.valueOf(productMapping.get(MZK_PRODUCT));
            }

            if (mzkSettings != null) {
                mzkRequest.Cards = new MZKRequest.MzkCards();
                mzkRequest.Cards.sendType = mzkSettings.Send_Type__c.intValue();
                mzkRequest.Cards.transitId = opportunity.Transit_ID__c;
                mzkRequest.Cards.requestDescription = GlobalUtils.blankStringIfNull(account.Original_document_courier_info__c);
                mzkRequest.Cards.logUser = mzkSettings.Log_User__c;
                mzkRequest.Cards.isTemplate = 0;
                mzkRequest.Cards.eqv = Integer.valueOf(organizationMapping.get(opportunity.Our_organization__c));
                mzkRequest.Cards.serviceId = mzkSettings.Service_Ids__c;
                mzkRequest.Cards.limitVal = mzkSettings.Limit_Values__c;
                mzkRequest.Cards.limitTypeId = mzkSettings.Limit_Type_Ids__c;
                mzkRequest.Cards.isCommon = mzkSettings.Is_Common__c;
                mzkRequest.Cards.isRuble = mzkSettings.Is_Ruble__c;
                mzkRequest.Cards.totalLimitValue = null;
                mzkRequest.Cards.totalLimitType = null;
                mzkRequest.Cards.cardsNumber = Integer.valueOf(opportunity.ALL_Cards__c);
                mzkRequest.Cards.cardDescr = GlobalUtils.blankStringIfNull(account.Cards_delivery_courier_info__c);
                mzkRequest.Cards.serviceGroups = mzkSettings.Service_Groups__c;
                mzkRequest.Cards.productId = (Integer) PPRProductSettingsUtils.getProductSettings(product).get(PRODUCT_SETTING_NAME);
            } else {
                throw new E2EFormRuException(E2E_EXCEPTION);
            }
        }
        return mzkRequest;
    }
}