default/objects/Account/fields/ColCo__c.field-meta.xml
<CustomField>
    <fullName>ColCo__c</fullName>
    <label>ColCo</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Customer-ID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/GFN_Nr__c.field-meta.xml
<CustomField>
    <fullName>GFN_Nr__c</fullName>
    <description>Unique account identifier generated in GFN (Global FleetNet) system</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique account identifier generated in GFN (Global FleetNet) system</inlineHelpText>
    <label>GFN Nr.</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Account/recordTypes/Endkunde.recordType-meta.xml
<RecordType>
    <fullName>Endkunde</fullName>
    <active>true</active>
    <label>Endkunde</label>
</RecordType>

default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
                <default>true</default>
                <label>Germany</label>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <description>ID of a customer from web site</description>
    <inlineHelpText>ID of a customer from web site</inlineHelpText>
    <label>Customer ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Case/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
            </value>
            <value>
                <fullName>Hungarian</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>Slovak</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/Sub_topic__c.field-meta.xml
<CustomField>
    <fullName>Sub_topic__c</fullName>
    <label>Sub topic</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Topic__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice Dispute / Question</fullName>
            </value>
            <value>
                <fullName>+/-</fullName>
            </value>
            <value>
                <fullName>Order new card(s)</fullName>
            </value>
            <value>
                <fullName>Block my card(s)</fullName>
            </value>
            <value>
                <fullName>Forgotten PIN code</fullName>
            </value>
            <value>
                <fullName>Question about my Invoice</fullName>
            </value>
            <value>
                <fullName>Invoice Dispute</fullName>
            </value>
            <value>
                <fullName>Invoice Resend</fullName>
            </value>
            <value>
                <fullName>Change Method of invoice Distribution</fullName>
                <label>Change of Invoice Distribution/Freq</label>
            </value>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Contact Person Change</fullName>
            </value>
            <value>
                <fullName>Bank Details Change</fullName>
            </value>
            <value>
                <fullName>Company Name Change</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>ECO Program</fullName>
            </value>
            <value>
                <fullName>ClubSmart</fullName>
            </value>
            <value>
                <fullName>Guarantee</fullName>
            </value>
            <value>
                <fullName>General Inquiry</fullName>
                <label>FAQs/General queries</label>
            </value>
            <value>
                <fullName>Carnet</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>VAT Recovery</fullName>
            </value>
            <value>
                <fullName>Internal 1</fullName>
            </value>
            <value>
                <fullName>Card Parameter Change</fullName>
                <label>Card changes</label>
            </value>
            <value>
                <fullName>Card Other Questions</fullName>
                <label>Card other</label>
            </value>
            <value>
                <fullName>New Customer Credentials</fullName>
            </value>
            <value>
                <fullName>Payment confirmation</fullName>
            </value>
            <value>
                <fullName>Subaccount</fullName>
            </value>
            <value>
                <fullName>WPO</fullName>
            </value>
            <value>
                <fullName>EV Charging</fullName>
            </value>
            <value>
                <fullName>Order new Carnet/Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>My Carnet unit(s)</fullName>
                <label>Carnet</label>
            </value>
            <value>
                <fullName>My Card(s)</fullName>
                <label>Cards</label>
            </value>
            <value>
                <fullName>Update my account details</fullName>
                <label>Admin Account Changes</label>
            </value>
            <value>
                <fullName>Change of conditions</fullName>
            </value>
            <value>
                <fullName>Products &amp; Services</fullName>
            </value>
            <value>
                <fullName>Invoices &amp; Payments</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
                <label>Internal work</label>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case_management_settings__c/Case_management_settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings for Case management</description>
    <label>Case management settings</label>
</CustomObject>

default/objects/Case_management_settings__c/fields/Case_from_web_initial_status__c.field-meta.xml
<CustomField>
    <fullName>Case_from_web_initial_status__c</fullName>
    <description>Initial value of status field in Cases from website</description>
    <inlineHelpText>Initial value of status field in Cases from website</inlineHelpText>
    <label>Case from web initial status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Case_management_settings__c/fields/Case_from_web_origin__c.field-meta.xml
<CustomField>
    <fullName>Case_from_web_origin__c</fullName>
    <description>Initial value of origin field in Cases from website</description>
    <inlineHelpText>Initial value of origin field in Cases from website</inlineHelpText>
    <label>Case from web origin</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Case_management_settings__c/fields/Case_from_web_priority__c.field-meta.xml
<CustomField>
    <fullName>Case_from_web_priority__c</fullName>
    <description>Initial value of priority field in Cases from website</description>
    <inlineHelpText>Initial value of priority field in Cases from website</inlineHelpText>
    <label>Case from web priority</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/classes/CaseRestControllerTest.cls
@IsTest
public with sharing class CaseRestControllerTest {

    private static final String VALIDATION_ERROR_MESSAGE = 'Required field is missing: ';

    static {
        Case_management_settings__c settings = new Case_management_settings__c();
        settings.Name = 'SettingsEU';
        settings.Case_from_web_priority__c = 'Medium';
        settings.Case_from_web_origin__c = 'Web';
        settings.Case_from_web_initial_status__c = 'New';
        insert settings;
    }

    private static RestRequest prepareRequest() {
        RestRequest request = new RestRequest();
        request.addHeader('Content-Type', 'application/json;charset=UTF-8');
        request.httpMethod = 'POST';
        request.requestURI = Url.getSalesforceBaseUrl().toExternalForm() + '/services/apexrest/caseManagement/case/v1';
        return request;
    }

    @TestSetup
    static void createdTestData(){
        Account acc = new Account(
                RecordTypeId = GlobalUtils.getRecordTypeId('Account', 'Endkunde'),
                Name = 'Test GFN Account',
                GFN_Nr__c = 'DE12478550',
                ColCo__c = 'DE',
                BillingCountry = 'Germany'
        );
        insert acc;

        Contact newContact = new Contact (
    		Salutation = 'Herr',
    		FirstName = 'Bob',
    		LastName  = 'Test',
    		Phone = '1234567',
    		MailingCountry = 'Germany',
            MailingCountryCode = 'DE',
    		MailingStreet = '298 S. Ringo Street',
    		MailingCity = 'Little Rock',
			MailingPostalCode = '72201',
            Email = 'alex.fleetcor@gmail.com',
            AccountId = acc.Id
		);
		insert newContact;
    }

    @IsTest
    public static void testStatus200OptionalNull() {
        RestContext.request = prepareRequest();
        RestContext.request.requestBody = Blob.valueOf(
                '{"email": "alex.fleetcor@gmail.com",' +
                        '"fullName": "John cooper",' +
                        '"country": "Germany",' +
                        '"language": "German",' +
                        ' "description": "Ich brauche hilfe!",' +
                        ' "topic": "Invoices & Payments",' +
                        ' "subTopic": "Invoice Resend",' +
                        ' "customerId": null, ' +
                        '"phoneNumber": null, ' +
                        '"subject": "Erneute Rechnungs-Übersendung", ' +
                        '"ico": "12345678"}'
        );
        Map<String, Object> body = (Map<String, Object>) JSON.deserializeUntyped(RestContext.request.requestBody.toString());
        RestContext.response = new RestResponse();
        Test.startTest();
        CaseRestController.createCase(
                String.valueOf(body.get('email')),
                String.valueOf(body.get('fullName')),
                String.valueOf(body.get('country')),
                String.valueOf(body.get('language')),
                String.valueOf(body.get('description')),
                String.valueOf(body.get('topic')),
                String.valueOf(body.get('subTopic')),
                String.valueOf(body.get('customerId')),
                String.valueOf(body.get('phoneNumber')),
                String.valueOf(body.get('subject')),
                String.valueOf(body.get('ico'))
        );
        Test.stopTest();
        System.assertEquals(200, RestContext.response.statusCode);
        System.assertEquals('application/json;charset=UTF-8', RestContext.response.headers.get('Content-Type'));
        ResponseBody responseBody = (ResponseBody) JSON.deserialize(RestContext.response.responseBody.toString(), ResponseBody.class);
        System.assertEquals(true, responseBody.success);
        System.assertNotEquals(null, responseBody.id);
        System.assertEquals(null, responseBody.errors);
        Case createdCase = ([
                SELECT Id, SuppliedEmail, SuppliedName, SuppliedPhone, Topic__c, Subject,
                        Sub_topic__c, Description, Customer_ID__c, Country__c, Language__c
                FROM Case
                WHERE Id = :responseBody.id
        ]);
        System.assertEquals(String.valueOf(body.get('email')), createdCase.SuppliedEmail);
        System.assertEquals(String.valueOf(body.get('fullName')), createdCase.SuppliedName);
        System.assertEquals(String.valueOf(body.get('country')), createdCase.Country__c);
        System.assertEquals(String.valueOf(body.get('language')), createdCase.Language__c);
        System.assertEquals(String.valueOf(body.get('description')), createdCase.Description);
        System.assertEquals(String.valueOf(body.get('topic')), createdCase.Topic__c);
        System.assertEquals(String.valueOf(body.get('subTopic')), createdCase.Sub_topic__c);
        System.assertEquals(null, createdCase.Customer_ID__c);
        System.assertEquals(String.valueOf(body.get('subject')), createdCase.Subject);
        System.assertEquals(null, createdCase.SuppliedPhone);

    }

    @IsTest
    public static void testStatus200() {
        RestContext.request = prepareRequest();
        RestContext.request.requestBody = Blob.valueOf(
                '{"email": "alex.fleetcor@gmail.com",' +
                        '"fullName": "John cooper",' +
                        '"country": "Germany",' +
                        '"language": "German",' +
                        ' "description": "Ich brauche hilfe!",' +
                        ' "topic": "Invoices & Payments",' +
                        ' "subTopic": "Invoice Resend",' +
                        ' "customerId": "DE12345678", ' +
                        '"phoneNumber": "88005553535", ' +
                        '"subject": "Erneute Rechnungs-Übersendung", ' +
                        '"ico": "12345678"}'
        );
        Map<String, Object> body = (Map<String, Object>) JSON.deserializeUntyped(RestContext.request.requestBody.toString());
        RestContext.response = new RestResponse();
        Test.startTest();
        CaseRestController.createCase(
                String.valueOf(body.get('email')),
                String.valueOf(body.get('fullName')),
                String.valueOf(body.get('country')),
                String.valueOf(body.get('language')),
                String.valueOf(body.get('description')),
                String.valueOf(body.get('topic')),
                String.valueOf(body.get('subTopic')),
                String.valueOf(body.get('customerId')),
                String.valueOf(body.get('phoneNumber')),
                String.valueOf(body.get('subject')),
                String.valueOf(body.get('ico'))
        );
        Test.stopTest();
        System.assertEquals(200, RestContext.response.statusCode);
        System.assertEquals('application/json;charset=UTF-8', RestContext.response.headers.get('Content-Type'));
        ResponseBody responseBody = (ResponseBody) JSON.deserialize(RestContext.response.responseBody.toString(), ResponseBody.class);
        System.assertEquals(true, responseBody.success);
        System.assertNotEquals(null, responseBody.id);
        System.assertEquals(null, responseBody.errors);
        Case createdCase = ([
                SELECT Id, SuppliedEmail, SuppliedName, SuppliedPhone, Topic__c, Subject,
                        Sub_topic__c, Description, Customer_ID__c, Country__c, Language__c
                FROM Case
                WHERE Id = :responseBody.id
        ]);
        System.assertEquals(String.valueOf(body.get('email')), createdCase.SuppliedEmail);
        System.assertEquals(String.valueOf(body.get('fullName')), createdCase.SuppliedName);
        System.assertEquals(String.valueOf(body.get('country')), createdCase.Country__c);
        System.assertEquals(String.valueOf(body.get('language')), createdCase.Language__c);
        System.assertEquals(String.valueOf(body.get('description')), createdCase.Description);
        System.assertEquals(String.valueOf(body.get('topic')), createdCase.Topic__c);
        System.assertEquals(String.valueOf(body.get('subTopic')), createdCase.Sub_topic__c);
        System.assertEquals(String.valueOf(body.get('customerId')), createdCase.Customer_ID__c);
        System.assertEquals(String.valueOf(body.get('subject')), createdCase.Subject);
        System.assertEquals(String.valueOf(body.get('phoneNumber')), createdCase.SuppliedPhone);

    }

    @IsTest
    public static void testStatus500() {
        RestContext.request = prepareRequest();
        RestContext.request.requestBody = Blob.valueOf(
                '{"email": "alex.fleetcor@gmail.com",' +
                        '"fullName": "John cooper",' +
                        '"country": "Germany",' +
                        '"language": "German",' +
                        ' "description": "Ich brauche hilfe!",' +
                        ' "topic": "Invoices & Payments",' +
                        ' "subTopic": "IbIbIbIbIbIbIbIbIbIbIbIbIbIbIbIbIbIbIbIb",' +
                        ' "customerId": null, ' +
                        '"phoneNumber": null, ' +
                        '"subject": "Erneute Rechnungs-Übersendung", ' +
                        '"ico": "12345678"}'
        );
        Map<String, Object> body = (Map<String, Object>) JSON.deserializeUntyped(RestContext.request.requestBody.toString());
        RestContext.response = new RestResponse();
        Test.startTest();
        CaseRestController.createCase(
                String.valueOf(body.get('email')),
                String.valueOf(body.get('fullName')),
                String.valueOf(body.get('country')),
                String.valueOf(body.get('language')),
                String.valueOf(body.get('description')),
                String.valueOf(body.get('topic')),
                String.valueOf(body.get('subTopic')),
                String.valueOf(body.get('customerId')),
                String.valueOf(body.get('phoneNumber')),
                String.valueOf(body.get('subject')),
                String.valueOf(body.get('ico'))
        );
        Test.stopTest();
        System.assertEquals(500, RestContext.response.statusCode);
        System.assertEquals('application/json;charset=UTF-8', RestContext.response.headers.get('Content-Type'));
        ResponseBody responseBody = (ResponseBody) JSON.deserialize(RestContext.response.responseBody.toString(), ResponseBody.class);
        System.assertEquals(false, responseBody.success);
        System.assertEquals(null, responseBody.id);
        System.assertNotEquals(null, responseBody.errors);

    }

    @IsTest
    public static void testStatus400() {
        RestContext.request = prepareRequest();
        RestContext.response = new RestResponse();
        Test.startTest();
        CaseRestController.createCase(
                '',
                '',
                '',
                null,
                ' ',
                '',
                null,
                '',
                ' ',
                '',
                ''
        );
        Test.stopTest();
        System.assertEquals(400, RestContext.response.statusCode);
        System.assertEquals('application/json;charset=UTF-8', RestContext.response.headers.get('Content-Type'));
        ResponseBody responseBody = (ResponseBody) JSON.deserialize(RestContext.response.responseBody.toString(), ResponseBody.class);
        System.assertEquals(false, responseBody.success);
        System.assertEquals(null, responseBody.id);
        System.assert(responseBody.errors.contains(RestServiceUtils.VALIDATION_ERROR_MESSAGE + 'email'));
        System.assert(responseBody.errors.contains(RestServiceUtils.VALIDATION_ERROR_MESSAGE + 'fullName'));
        System.assert(responseBody.errors.contains(RestServiceUtils.VALIDATION_ERROR_MESSAGE + 'country'));
        System.assert(responseBody.errors.contains(RestServiceUtils.VALIDATION_ERROR_MESSAGE + 'language'));
        System.assert(responseBody.errors.contains(RestServiceUtils.VALIDATION_ERROR_MESSAGE + 'description'));
        System.assert(responseBody.errors.contains(RestServiceUtils.VALIDATION_ERROR_MESSAGE + 'topic'));
        System.assert(responseBody.errors.contains(RestServiceUtils.VALIDATION_ERROR_MESSAGE + 'subject'));
    }

}