default/objects/Account/fields/ColCo__c.field-meta.xml
<CustomField>
    <fullName>ColCo__c</fullName>
    <label>ColCo</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/GFN_Nr__c.field-meta.xml
<CustomField>
    <fullName>GFN_Nr__c</fullName>
    <description>Unique account identifier generated in GFN (Global FleetNet) system</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique account identifier generated in GFN (Global FleetNet) system</inlineHelpText>
    <label>GFN Nr.</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Case/fields/ERP__c.field-meta.xml
<CustomField>
    <fullName>ERP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GFN</label>
    <referenceTo>ERP__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Case/fields/Queue_Email__c.field-meta.xml
<CustomField>
    <fullName>Queue_Email__c</fullName>
    <description>STCP1-37/STCP1-214 -  updated in Process builder 'Save Last Queue Owner Email' or manually while creating a case, using in action button 'Email' on Case for pre-defined values of BCC and FromAddress fields</description>
    <inlineHelpText>Email which defines pre-defined values for FromAddress and BCC fields on outgoing email messages</inlineHelpText>
    <label>Queue Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>bonus@ccs.cz</fullName>
            </value>
            <value>
                <fullName>eurotoll@ccs.cz</fullName>
            </value>
            <value>
                <fullName>klantendienst@fleetcorcards.be</fullName>
            </value>
            <value>
                <fullName>klantenservice@fleetcor.nl</fullName>
            </value>
            <value>
                <fullName>kredit@ccs.cz</fullName>
            </value>
            <value>
                <fullName>kredit@ccs.sk</fullName>
            </value>
            <value>
                <fullName>kundenservice@fleetcor.at</fullName>
            </value>
            <value>
                <fullName>kundenservice@fleetcor.ch</fullName>
            </value>
            <value>
                <fullName>kundenservice@fleetcor.de</fullName>
            </value>
            <value>
                <fullName>market@ccs.cz</fullName>
            </value>
            <value>
                <fullName>myto@ccs.cz</fullName>
            </value>
            <value>
                <fullName>obchod@ccs.cz</fullName>
            </value>
            <value>
                <fullName>obslugaklienta@fleetcor.pl</fullName>
            </value>
            <value>
                <fullName>premiumservice@fleetcor.eu</fullName>
            </value>
            <value>
                <fullName>premiumservis@ccs.cz</fullName>
            </value>
            <value>
                <fullName>provoz@ccs.cz</fullName>
            </value>
            <value>
                <fullName>reklamace@ccs.cz</fullName>
            </value>
            <value>
                <fullName>serviceclients@fleetcor.ch</fullName>
            </value>
            <value>
                <fullName>serviceclients@fleetcor.fr</fullName>
            </value>
            <value>
                <fullName>serviceclients@fleetcor.lu</fullName>
            </value>
            <value>
                <fullName>serviceclients@fleetcorcards.be</fullName>
            </value>
            <value>
                <fullName>servizioclienti@fleetcor.ch</fullName>
            </value>
            <value>
                <fullName>ugyfelszolgalat@fleetcor.hu</fullName>
            </value>
            <value>
                <fullName>uta@ccs.cz</fullName>
            </value>
            <value>
                <fullName>zakaznicka.podpora@ccs.cz</fullName>
            </value>
            <value>
                <fullName>Zakaznicke@ccs.sk</fullName>
            </value>
            <value>
                <fullName>zakaznickyservis@fleetcor.cz</fullName>
            </value>
            <value>
                <fullName>zakaznickyservis@fleetcor.sk</fullName>
            </value>
            <value>
                <fullName>credit@fleetcor.de</fullName>
            </value>
            <value>
                <fullName>credit@fleetcor.nl</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/Sub_topic__c.field-meta.xml
<CustomField>
    <fullName>Sub_topic__c</fullName>
    <label>Sub topic</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Topic__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice Dispute / Question</fullName>
            </value>
            <value>
                <fullName>+/-</fullName>
            </value>
            <value>
                <fullName>Order new card(s)</fullName>
            </value>
            <value>
                <fullName>Block my card(s)</fullName>
            </value>
            <value>
                <fullName>Forgotten PIN code</fullName>
            </value>
            <value>
                <fullName>Question about my Invoice</fullName>
            </value>
            <value>
                <fullName>Invoice Dispute</fullName>
            </value>
            <value>
                <fullName>Invoice Resend</fullName>
            </value>
            <value>
                <fullName>Change Method of invoice Distribution</fullName>
                <label>Change of Invoice Distribution/Freq</label>
            </value>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Contact Person Change</fullName>
            </value>
            <value>
                <fullName>Bank Details Change</fullName>
            </value>
            <value>
                <fullName>Company Name Change</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>ECO Program</fullName>
            </value>
            <value>
                <fullName>ClubSmart</fullName>
            </value>
            <value>
                <fullName>Guarantee</fullName>
            </value>
            <value>
                <fullName>General Inquiry</fullName>
                <label>FAQs/General queries</label>
            </value>
            <value>
                <fullName>Carnet</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>VAT Recovery</fullName>
            </value>
            <value>
                <fullName>Internal 1</fullName>
            </value>
            <value>
                <fullName>Card Parameter Change</fullName>
                <label>Card changes</label>
            </value>
            <value>
                <fullName>Card Other Questions</fullName>
                <label>Card other</label>
            </value>
            <value>
                <fullName>New Customer Credentials</fullName>
            </value>
            <value>
                <fullName>Payment confirmation</fullName>
            </value>
            <value>
                <fullName>Subaccount</fullName>
            </value>
            <value>
                <fullName>WPO</fullName>
            </value>
            <value>
                <fullName>EV Charging</fullName>
            </value>
            <value>
                <fullName>Order new Carnet/Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Case/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>My Carnet unit(s)</fullName>
                <label>Carnet</label>
            </value>
            <value>
                <fullName>My Card(s)</fullName>
                <label>Cards</label>
            </value>
            <value>
                <fullName>Update my account details</fullName>
                <label>Admin Account Changes</label>
            </value>
            <value>
                <fullName>Change of conditions</fullName>
            </value>
            <value>
                <fullName>Products &amp; Services</fullName>
            </value>
            <value>
                <fullName>Invoices &amp; Payments</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
                <label>Internal work</label>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/ERP__c/ERP__c.object-meta.xml
<CustomObject>
    <label>GFN</label>
    <nameField>
        <label>GFN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GFNs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/ERP__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GFNs</relationshipLabel>
    <relationshipName>ERPs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/ERP__c/fields/ColCo__c.field-meta.xml
<CustomField>
    <fullName>ColCo__c</fullName>
    <label>ColCo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

default/objects/ERP__c/fields/ColCoID__c.field-meta.xml
<CustomField>
    <fullName>ColCoID__c</fullName>
    <label>ColCo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

default/objects/ERP__c/fields/GFN_Nr__c.field-meta.xml
<CustomField>
    <fullName>GFN_Nr__c</fullName>
    <externalId>true</externalId>
    <label>GFN Nr</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/ERP__c/fields/GFN_Number__c.field-meta.xml
<CustomField>
    <fullName>GFN_Number__c</fullName>
    <externalId>true</externalId>
    <label>GFN Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/GFN_Dashboard_UI_settings__mdt/GFN_Dashboard_UI_settings__mdt.object-meta.xml
<CustomObject>
    <description>List of components which should be displayed on GFN Dashboard</description>
    <label>GFN Dashboard UI settings</label>
    <pluralLabel>GFN Dashboard UI settings</pluralLabel>
</CustomObject>

default/objects/GFN_Dashboard_UI_settings__mdt/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <label>Fields</label>
    <type>TextArea</type>
</CustomField>

default/objects/GFN_Dashboard_UI_settings__mdt/fields/Line_Of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_Of_Business__c</fullName>
    <label>Line Of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SME</fullName>
                <default>true</default>
                <label>SME</label>
            </value>
            <value>
                <fullName>CCS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/GFN_Dashboard_UI_settings__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/GFN_Dashboard_UI_settings__mdt/fields/Tab__c.field-meta.xml
<CustomField>
    <fullName>Tab__c</fullName>
    <label>Tab</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

default/objects/GFN_Dashboard_UI_settings__mdt/fields/Tab_Icon__c.field-meta.xml
<CustomField>
    <fullName>Tab_Icon__c</fullName>
    <label>Tab Icon</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

default/objects/LiveChatTranscript/fields/GFN__c.field-meta.xml
<CustomField>
    <fullName>GFN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GFN</label>
    <referenceTo>ERP__c</referenceTo>
    <relationshipLabel>Chat Transcripts</relationshipLabel>
    <relationshipName>Chat_Transcripts</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/GFNI_DashboardDaoImpl.cls
public with sharing class GFNI_DashboardDaoImpl implements GFNI_DashboardDao {

    /*******************************************************************************
    *  Name            : getAccountById(Id accountId)
    *  Summary         : get account by id
    *  CreatedDate     : 25/07/2019
    *  ModifiedDate    : -
    *  Parameters      : Id accounts
    *  Returns         : account
    ******************************************************************************/
    public Account getAccountById(Id accountId) {
        Account accountObject = [
                SELECT Id, Name, GFN_Nr__c, ColCo__c, OwnerId
                FROM Account
                WHERE Id = :accountId
                LIMIT 1
        ];
        return accountObject;
    }


    /*******************************************************************************
    *  Name            : getCaseAccountById(Id caseId)
    *  Summary         : get case by id
    *  CreatedDate     : 25/07/2019
    *  ModifiedDate    : -
    *  Parameters      : Id case
    *  Returns         : case
    ******************************************************************************/
    public Case getCaseAccountById(Id caseId) {
        Case caseObject = [
                SELECT Id, 
                    CaseNumber, 
                    Account.GFN_Nr__c, 
                    Account.ColCo__c,
                    ERP__r.GFN_Number__c,
                    ERP__r.GFN_Nr__c,
                    ERP__r.ColCoID__c,
                    ERP__r.ColCo__c,
                    ERP__r.RecordTypeId,
                    RecordTypeId
                FROM Case
                WHERE Id = :caseId
                LIMIT 1
        ];
        return caseObject;
    }


    /*******************************************************************************
    *  Summary         : get task by id
    *  Created         : 27/12/2019 Anton Hrytsavets
    *  Parameters      : taskId - task Id
    *  Returns         : task for GFN dashboard
    ******************************************************************************/
    public Task getTaskById(Id taskId) {
        Task taskObject = [
                SELECT  Account__c, 
                        Account__r.GFN_Nr__c, 
                        Account__r.ColCo__c,
                        WhatId
                FROM    Task
                WHERE   Id = :taskId
                LIMIT   1
        ];
        return taskObject;
    }


    /*******************************************************************************
    *  Summary         : get erp(gfn) record by id
    *  Created         : 01/06/2020 Anton Hrytsavets
    *  Parameters      : erpId - erp Id
    *  Returns         : erp(gfn) for GFN dashboard
    ******************************************************************************/
    public ERP__c getERPById(Id erpId) {
        ERP__c erpObject = [
                SELECT  GFN_Number__c,
                        GFN_Nr__c,
                        ColCoID__c,
                        ColCo__c,
                        RecordTypeId
                FROM    ERP__c
                WHERE   Id = :erpId
                LIMIT   1
        ];
        return erpObject;
    }


    /*******************************************************************************
    *  Summary         : get ERP by liveChat record id
    *  Created         : 19/03/2021 Anton Hrytsavets
    *  Parameters      : chatTranscriptId - chat transcript Id
    *  Returns         : erp(gfn) for GFN dashboard
    ******************************************************************************/
    public ERP__c getErpByLiveChatTranscript(Id chatTranscriptId) {
        LiveChatTranscript chatObject = [
                SELECT  GFN__c,
                        GFN__r.GFN_Nr__c,
                        GFN__r.GFN_Number__c,
                        GFN__r.ColCoID__c,
                        GFN__r.ColCo__c,
                        GFN__r.RecordTypeId
                FROM    LiveChatTranscript
                WHERE   Id = :chatTranscriptId
                LIMIT   1
        ];
        return chatObject.GFN__r;
    }


    /*******************************************************************************
    *  Name            : getCaseCurrentInfo(String caseId)
    *  Summary         : get case info by Id
    *  CreatedDate     : 08/10/2019
    *  ModifiedDate    : -
    *  Parameters      : String caseId
    *  Returns         : list of cases
    ******************************************************************************/
    public List<Case> getCaseCurrentInfo(Id caseId) {
        List<Case> caseObject = [
                SELECT  Id, 
                        CaseNumber,
                        Description,
                        Origin,
                        Status,
                        Topic__c,
                        Sub_topic__c,
                        Queue_Email__c,
                        SuppliedEmail,
                        AccountId,
                        Account.Name,
                        Account.GFN_Nr__c, 
                        Account.ColCo__c   
                FROM Case
                WHERE Id = :caseId
                LIMIT 1
        ];
        return caseObject;
    }


    /*******************************************************************************
    *  Name            : getRelatedCases(Id accountId)
    *  Summary         : get case info by account Id
    *  CreatedDate     : 08/10/2019
    *  ModifiedDate    : -
    *  Parameters      : String caseId
    *  Returns         : list of cases
    ******************************************************************************/
    public List<Case> getRelatedCases(Id accountId) {
        List<Case> caseList = [
                SELECT  Id, 
                        CaseNumber,
                        Description,
                        Origin,
                        Status,
                        Topic__c,
                        Sub_topic__c,
                        Queue_Email__c,
                        SuppliedEmail,
                        Account.Name,
                        Account.GFN_Nr__c, 
                        Account.ColCo__c   
                FROM    Case
                WHERE   AccountId = :accountId
                AND     Status != 'Resolved'
                AND     Status != 'Closed'
        ];
        return caseList;
    }

    
    /*******************************************************************************
    *  Name            : getVersionByDocName(String docNumber)
    *  Summary         : get ContentVersion by document number
    *  CreatedDate     : 2/11/2019
    *  ModifiedDate    : -
    *  Parameters      : String docNumber
    *  Returns         : list of ContentVersion
    ******************************************************************************/
    public List<ContentVersion> getVersionByDocName(String docNumber) {
        List<ContentVersion> version = [
            SELECT  Id,
                    Title,
                    ContentDocumentId,
                    VersionData
            FROM    ContentVersion
            WHERE   Title =: docNumber+'.pdf'
            LIMIT   1
        ];
        return version;
    }

    
    /*******************************************************************************
    *  Name            : getDashboardUISettings(String recordType)
    *  Summary         : get Dashboard components to display by recordType
    *  CreatedDate     : 5/06/2020
    *  Parameters      : String recordType
    *  Returns         : list of GFN_Dashboard_UI_settings__mdt records
    ******************************************************************************/
    public List<GFN_Dashboard_UI_settings__mdt> getDashboardUISettings(String recordType) {
        List<GFN_Dashboard_UI_settings__mdt> uiSettings = [
            SELECT  Label,
                    DeveloperName,
                    Tab__c,
                    Line_Of_Business__c,
                    Fields__c,
                    Priority__c,
                    Tab_Icon__c
            FROM    GFN_Dashboard_UI_settings__mdt
            WHERE   Line_Of_Business__c=: recordType
            AND     Active__c = true
            ORDER BY Priority__c
        ];
        return uiSettings;
    }

    
    /*******************************************************************************
    *  Name            : getDistributionByVersionId(Id versionId)
    *  Summary         : get ContentDistribution by version Id
    *  CreatedDate     : 2/11/2019
    *  ModifiedDate    : -
    *  Parameters      : Id versionId
    *  Returns         : list of ContentDistribution
    ******************************************************************************/
    public List<ContentDistribution> getDistributionByVersionId(Id versionId) {
        List<ContentDistribution> existingDestributions = [
            SELECT  DistributionPublicUrl
            FROM    ContentDistribution
            WHERE   ContentVersionId =: versionId
            LIMIT   1
        ];
        return existingDestributions;
    }

    
    /*******************************************************************************
    *  Name            : createDistributionForVersion(ContentVersion version)
    *  Summary         : create ContentDistribution for content version and return new ContentDistribution record with autofilled fields
    *  CreatedDate     : 2/11/2019
    *  ModifiedDate    : -
    *  Parameters      : ContentVersion version
    *  Returns         : ContentDistribution
    ******************************************************************************/
    public ContentDistribution createDistributionForVersion(ContentVersion version) {
        ContentDistribution distribution = new ContentDistribution();
        distribution.Name = version.Title + ' ' + String.valueOf(Date.today());
        distribution.ContentVersionId = version.Id;
        distribution.PreferencesNotifyOnVisit = false;
        insert distribution;

        List<ContentDistribution> distributionList = [
            SELECT  DistributionPublicUrl
            FROM    ContentDistribution
            WHERE   Id =: distribution.Id
            LIMIT   1
        ];
        distribution = distributionList[0];
        return distribution;
    }

    
    /*******************************************************************************
    *  Name            : createContentVersionPDF(ContentVersion version)
    *  Summary         : create ContentDistribution for content version and return new ContentDistribution record with autofilled fields
    *  CreatedDate     : 2/11/2019
    *  ModifiedDate    : -
    *  Parameters      : ContentVersion version
    *  Returns         : ContentDistribution
    ******************************************************************************/
    public ContentVersion createContentVersionPDF(String encodedPDF, String docName) {
        ContentVersion newVersion = new ContentVersion();
        Blob pdf = EncodingUtil.base64Decode(encodedPDF);
        newVersion.VersionData = pdf;
        newVersion.Title = docName + '.pdf';
        newVersion.PathOnClient = docName + '.pdf';
        insert newVersion;
        return newVersion;
    }

}