default/objects/Account/fields/Company_Legal_Name1__c.field-meta.xml
<CustomField>
    <fullName>Company_Legal_Name1__c</fullName>
    <label>Full Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Идентификационный номер налогоплательщика.
            Должен содержать только цифры:
            12 цифр - ИП;
            10 цифр - юр. лицо.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Account/recordTypes/Russian.recordType-meta.xml
<RecordType>
    <fullName>Russian</fullName>
    <active>true</active>
    <label>Russian</label>
</RecordType>

default/objects/Contact/fields/PD_Avaliable_LastName_Update__c.field-meta.xml
<CustomField>
    <fullName>PD_Avaliable_LastName_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PD_Avaliable_LastName_Update</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Contact/recordTypes/Russian.recordType-meta.xml
<RecordType>
    <fullName>Russian</fullName>
    <active>true</active>
    <label>Russian</label>
</RecordType>

default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Первый контакт по inbound</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Anruf</fullName>
            </value>
            <value>
                <fullName>FLMT_Form</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/E2E_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Status__c</fullName>
    <label>E2E Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Drop off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Tax identification number
        Must contain only numbers:
        Length 12 symbols for PE;
        Length 10 symbols for legal person.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/recordTypes/Russian_Sales.recordType-meta.xml
<RecordType>
    <fullName>Russian_Sales</fullName>
    <active>true</active>
    <businessProcess>Russian Sales</businessProcess>
    <label>Russian Sales</label>
</RecordType>

default/objects/Opportunity/fields/Business_process__c.field-meta.xml
<CustomField>
    <fullName>Business_process__c</fullName>
    <description>The field for business process type</description>
    <inlineHelpText>The field for business process type</inlineHelpText>
    <label>Business process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>E2EClassic</fullName>
            </value>
            <value>
                <fullName>E2EBusiness</fullName>
            </value>
            <value>
                <fullName>E2ELink</fullName>
            </value>
            <value>
                <fullName>PPR_API</fullName>
                <label>PPR API</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Anruf</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/E2E_Active_Substep__c.field-meta.xml
<CustomField>
    <fullName>E2E_Active_Substep__c</fullName>
    <label>E2E Active Substep</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Last_Activity__c.field-meta.xml
<CustomField>
    <fullName>E2E_Last_Activity__c</fullName>
    <label>E2E Last Activity</label>
    <type>DateTime</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Sales_Type__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sales_Type__c</fullName>
    <label>E2E Sales Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fully E2E</fullName>
            </value>
            <value>
                <fullName>Fully manual</fullName>
            </value>
            <value>
                <fullName>E2E downgraded to manual</fullName>
            </value>
            <value>
                <fullName>Manual upgraded to E2E</fullName>
            </value>
            <value>
                <fullName>Чистый e2e</fullName>
            </value>
            <value>
                <fullName>Чистый e2e + помощь КЦ</fullName>
            </value>
            <value>
                <fullName>E2E с участием Inbound</fullName>
            </value>
            <value>
                <fullName>Стандартный ручной процесс</fullName>
            </value>
            <value>
                <fullName>Отклонен</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/E2E_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Status__c</fullName>
    <label>E2E Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Abandoned (soft)</fullName>
            </value>
            <value>
                <fullName>Abandoned (hard)</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Клиент Активен</fullName>
            </value>
            <value>
                <fullName>Клиент не активен</fullName>
            </value>
            <value>
                <fullName>Отказ от E2E</fullName>
            </value>
            <value>
                <fullName>Клиент завершил</fullName>
            </value>
            <value>
                <fullName>Introduction</fullName>
            </value>
            <value>
                <fullName>Drop off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Lead_Source_TypeOpp__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_TypeOpp__c</fullName>
    <label>Lead Source TypeOpp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Number_of_cars__c.field-meta.xml
<CustomField>
    <fullName>Number_of_cars__c</fullName>
    <inlineHelpText>should not be equal to '0'</inlineHelpText>
    <label>Number of cars</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Number_of_trucks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_trucks__c</fullName>
    <inlineHelpText>should not be equal to '0'</inlineHelpText>
    <label>Number of trucks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/PPR_First_Contact_Inbound_Outbound__c.field-meta.xml
<CustomField>
    <fullName>PPR_First_Contact_Inbound_Outbound__c</fullName>
    <description>Was first contact inbound from the Lead, or outbound by the sales team? This is particularly helpful to know when the Lead was included in a marketing campaign.</description>
    <inlineHelpText>Was first contact inbound from the Lead, or outbound by the sales team? This is particularly helpful to know when the Lead was included in a marketing campaign.</inlineHelpText>
    <label>PPR First Contact: Inbound/Outbound</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Outbound call</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Inbound Mail</fullName>
            </value>
            <value>
                <fullName>Inbound Website</fullName>
            </value>
            <value>
                <fullName>Onsite Visit</fullName>
            </value>
            <value>
                <fullName>Не контактировали</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Projected_amount_in_rub_month__c.field-meta.xml
<CustomField>
    <fullName>Projected_amount_in_rub_month__c</fullName>
    <inlineHelpText>in month, should not be equal to '0'</inlineHelpText>
    <label>Projected amount in rub (month)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Projected_Liters_weekly__c.field-meta.xml
<CustomField>
    <fullName>Projected_Liters_weekly__c</fullName>
    <description>FORMULA FIELD:  Number of liters projected to be fueled per week for this prospect.  Calculated as the number of vehicles times the estimated liters per vehicle per week.
Russia uses liters projected per monthly.</description>
    <inlineHelpText>should not be equal to '0'</inlineHelpText>
    <label>Projected Liters (weekly)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Source_if_self_sourced_c__c.field-meta.xml
<CustomField>
    <fullName>Source_if_self_sourced_c__c</fullName>
    <label>Source if self-sourced</label>
    <type>TextArea</type>
</CustomField>

default/objects/Opportunity/fields/Source_of_Lead_o__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Lead_o__c</fullName>
    <label>Source of Lead_o</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Актуализированная БД</fullName>
            </value>
            <value>
                <fullName>Прочая БД</fullName>
                <default>true</default>
                <label>Прочая БД</label>
            </value>
            <value>
                <fullName>Выставка</fullName>
            </value>
            <value>
                <fullName>Найден в Интернете</fullName>
            </value>
            <value>
                <fullName>Реклама Клиента</fullName>
            </value>
            <value>
                <fullName>Почтовая Рассылка</fullName>
            </value>
            <value>
                <fullName>Рекомендация</fullName>
            </value>
            <value>
                <fullName>Реклама на АЗС</fullName>
            </value>
            <value>
                <fullName>Email Рассылка</fullName>
            </value>
            <value>
                <fullName>Интернет Источники</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.ru</fullName>
            </value>
            <value>
                <fullName>Поисковая Система</fullName>
            </value>
            <value>
                <fullName>Business card</fullName>
            </value>
            <value>
                <fullName>Партнерская Программа</fullName>
            </value>
            <value>
                <fullName>Реклама в СМИ</fullName>
            </value>
            <value>
                <fullName>Полевой канал</fullName>
            </value>
            <value>
                <fullName>Сайт fuel.veb-leasing.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.kz</fullName>
            </value>
            <value>
                <fullName>Petrolcards.ru - АГГРЕГАТОР</fullName>
            </value>
            <value>
                <fullName>АЗС Заявка Shell</fullName>
            </value>
            <value>
                <fullName>Сайт gpc-store.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Shell Card.ru</fullName>
            </value>
            <value>
                <fullName>E2E Form RU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/recordTypes/Russian_Sales.recordType-meta.xml
<RecordType>
    <fullName>Russian_Sales</fullName>
    <active>true</active>
    <businessProcess>Russian Sales</businessProcess>
    <label>Russian Sales</label>

</RecordType>

default/classes/DeduplicationServiceTestDataFactory.cls
@isTest
public class DeduplicationServiceTestDataFactory {
    public DeduplicationService.DeduplicationData createDeduplData(String Email, String INN, User owner) {
        DeduplicationService.DeduplicationData deduplicationData = new DeduplicationService.DeduplicationData();
        List<Account> excludedAccounts = new List<Account>();
        excludedAccounts.add(createAccount('3333333333'));
        insert excludedAccounts;
        deduplicationData.excludedAccounts = excludedAccounts;

        List<Contact> excludedContacts = new List<Contact>();
        excludedContacts.add(createContact(excludedAccounts[0].Id, 'test@test.ru'));
        insert excludedContacts;
        deduplicationData.excludedContacts = excludedContacts;  
        
        Opportunity opportunity = createOpportunity('test', excludedAccounts[0].Id, 'Qualified Lead', Date.Today().addDays(15), owner);
        insert opportunity;
        deduplicationData.opportunity = opportunity;

        deduplicationData.INN = INN;
        deduplicationData.Email = Email;
        return deduplicationData;
    }

    public User createUser() {
        UserRole ur = [SELECT Id FROM UserRole WHERE Name = 'PPR_Fleetcor' AND DeveloperName = 'PPR_Fleetcor'];
        Profile p = [SELECT Id FROM Profile WHERE Name = :Label.System_Administrator];
        User user = new User(
            ProfileId = p.Id,
            UserRoleId = ur.Id,
            Username = 'new_user_email@email.ru',
            Email = 'new_user_email@email.ru',
            FirstName = 'User',
            LastName = 'Test',
            Alias = 'tuser',
            TimeZoneSidKey = 'America/Chicago',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8'
        );
        return user;
    }

    public User createAdminUser() {
        UserRole ur = [SELECT Id FROM UserRole WHERE Name = 'Role Up' AND DeveloperName = 'Role_Up'];
        Profile p = [SELECT Id FROM Profile WHERE Name = :Label.System_Administrator];
        User user = new User(
            Username = 'new_user_admin@Test.com',
            Email = 'admin@test.com',
            FirstName = 'AdminUser',
            LastName = 'admin_tester',
            ProfileId = p.Id,
            UserRoleId = ur.Id,
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'Europe/Moscow',
            EmailEncodingKey = 'UTF-8',
            Alias = 'admin'
        );
        return user;
    }

    public Account createAccount(String INN) {
        Account account = new Account(
            RecordTypeId = GlobalUtils.getRecordTypeId('Account', 'Russian'),
            Name = 'Test',
            BillingCountry = GlobalUtils.FleetcorCountries.Russia.name(),
            ShippingCountry = GlobalUtils.FleetcorCountries.Russia.name(),
            Type = 'Customer',
            AccountSource = 'E2E Form RU',
            INN__c = INN,
            Company_Legal_Name1__c = ''
        );
        return account;
    }

    public Contact createContact(Id accountId, String email) {
        Contact contact = new Contact(
            RecordTypeId = GlobalUtils.getRecordTypeId('Contact', 'Russian'),
            Salutation = 'Mr.',
            LeadSource = 'E2E Form RU',
            AccountId = accountId,
            FirstName = 'Contact Test',
            LastName = 'LastName',
            Title = 'генеральный директор',
            PD_Avaliable_LastName_Update__c = true,
            Phone = '+49 55455555045',
            MobilePhone = '+49 55455555045',
            Email = email
        );
        return contact;
    }

    public Opportunity createOpportunity(String name, Id accountId, String stageName, Date closeDate, User owner) {
        Opportunity opportunity = new Opportunity(
            Name = name,
            StageName = stageName,
            AccountId = accountId,
            CloseDate = closeDate,
            LeadSource = 'E2E Form RU',
            Lead_Source_TypeOpp__c = 'Webform',
            Source_of_Lead_o__c = 'E2E Form RU',
            Source_if_self_sourced_c__c = 'E2E Form RU',
            PPR_First_Contact_Inbound_Outbound__c = 'Inbound Website',
            Channel__c = 'Internet',
            RecordTypeId = GlobalUtils.getRecordTypeId('Opportunity', 'Russian_Sales'),
            E2E_Active_Substep__c = '',
            E2E_Last_Activity__c = Datetime.now(),
            E2E_Status__c = 'Клиент Активен',
            E2E_Sales_Type__c = 'Чистый e2e',
            Projected_Liters_weekly__c = 88.00,
            Projected_amount_in_rub_month__c = 55535.35,
            Number_of_cars__c = 2,
            Number_of_trucks__c = 1,
            Business_process__c = GlobalUtils.BusinessProcessType.E2EClassic.name(),
            OwnerId = owner.id
        );
        return opportunity;
    }
}