default/objects/Account/fields/Einwilligung_Lastschriftverfahren__c.field-meta.xml
<CustomField>
    <fullName>Einwilligung_Lastschriftverfahren__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Einwilligung Lastschriftverfahren</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Account/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/SWIFT_BIC__c.field-meta.xml
<CustomField>
    <fullName>SWIFT_BIC__c</fullName>
    <label>SWIFT BIC *</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/UMR__c.field-meta.xml
<CustomField>
    <fullName>UMR__c</fullName>
    <description>Unique Mandate Reference Number</description>
    <formula>RIGHT(Account_Nr__c , 7)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UMR</label>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/AGB_Datenschutzhinweise_Richtigkeit__c.field-meta.xml
<CustomField>
    <fullName>AGB_Datenschutzhinweise_Richtigkeit__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Kunde (bei Personengesellschaften aller inhaber) bestätigt, die Allgemeinen Geschäftsbedingungen inkl. der Datenschutzhinweise und der aktuellen Gebührenüberischt gelesen zu haben und erkennt diese an. Kunde bestätigt die Richtigkeit der gemachten Angaben</inlineHelpText>
    <label>AGB/Datenschutzhinweise/Richtigkeit</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Einwilligung_Lastschriftverfahren__c.field-meta.xml
<CustomField>
    <fullName>Einwilligung_Lastschriftverfahren__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SEPA PDF Formular</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN*</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Mandate_Activated__c.field-meta.xml
<CustomField>
    <fullName>Mandate_Activated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandate Activated</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Mandate_Last_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>Mandate_Last_Modified_Date__c</fullName>
    <label>Mandate Last Modified Date</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/SEPA_Request_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>SEPA_Request_Approval_Date__c</fullName>
    <label>SEPA Request Approval Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Opportunity/fields/SEPA_Request_Approved__c.field-meta.xml
<CustomField>
    <fullName>SEPA_Request_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SEPA Request Approved</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Starts_Payment_method__c.field-meta.xml
<CustomField>
    <fullName>Starts_Payment_method__c</fullName>
    <inlineHelpText>If the customer decides to switch payment method to Direct debit during DD Calls.</inlineHelpText>
    <label>Starts: Payment method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct debit</fullName>
            </value>
            <value>
                <fullName>Bank transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/UMR__c.field-meta.xml
<CustomField>
    <fullName>UMR__c</fullName>
    <formula>Account.UMR__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UMR</label>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Zahlungsart__c.field-meta.xml
<CustomField>
    <fullName>Zahlungsart__c</fullName>
    <label>Zahlungsart *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lastschrift</fullName>
            </value>
            <value>
                <fullName>Banküberweisung</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Twikey__c/Twikey__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Twikey</label>
</CustomObject>

default/classes/SepaActivationBatch.cls
public class SepaActivationBatch implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful {
    private Twikey__c twikeySettings;
    private TwikeyEntity twikeyFeedEntity;


    /*******************************************************************************
    *  Summary         : Constructor
    *  CreatedDate     : 06/10/2020 by Anton Buzak
    *  Parameters      : -
    *  Returns         : -
    ******************************************************************************/
    public SepaActivationBatch(Twikey__c twikeySettings, TwikeyEntity twikeyFeedEntity) {
        this.twikeySettings = twikeySettings;
        this.twikeyFeedEntity = twikeyFeedEntity;
    }


    /*******************************************************************************
    *  Summary         : Call this method for each batch of records.
    *  CreatedDate     : 02/07/2019
    *  ModifiedDate    : -
    *  Parameters      : Database.BatchableContext bc - object for tracking the progress of the batch job,
                         List<Opportunity> opportunitiesList - list of Opportunities to process
    *  Returns         : void
    ******************************************************************************/
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Set<String> mandateIdsSet = new Set<String>();
        if (this.twikeyFeedEntity.Messages != null) {
            for (TwikeyEntity.Messages message : twikeyFeedEntity.Messages) {
                if (message.Mndt != null && message.Mndt.MndtId != null) {
                    mandateIdsSet.add(message.Mndt.MndtId);
                }
                else if (message.CxlRsn != null) {
                    mandateIdsSet.add(message.OrgnlMndtId);
                }
            }
        }

        String query =
                'SELECT Account.UMR__c, StageName, Mandate_Last_Modified_Date__c, Mandate_Activated__c, ' +
                        '(SELECT Id ' +
                        'FROM Attachments ' +
                        'WHERE Name = \'SEPAMandate\') ' +
                'FROM Opportunity ' +
                'WHERE Account.UMR__c IN :mandateIdsSet AND SEPA_Request_Approved__c = false';
        return Database.getQueryLocator(query);
    }


    /*******************************************************************************
    *  Summary         : Call this method for each batch of records.
    *  CreatedDate     : 06/10/2020 by Anton Buzak
    *  Parameters      : bc - object for tracking the progress of the batch job,
                         opportunitiesList - list of Opportunities to process
    *  Returns         : -
    ******************************************************************************/
    public void execute(Database.BatchableContext BC, List<Opportunity> opportunitiesList) {
        try {
            List<Opportunity> opportunitiesListToUpdate = new List<Opportunity>();
            List<Attachment> attachmentsToInsertList = new List<Attachment>();
            List<Attachment> attachmentsToDeleteList = new List<Attachment>();
            for (Opportunity opportunity : opportunitiesList) {
                TwikeyEntity.Messages lastMessage;
                String messageEventTime;
                for (TwikeyEntity.Messages message : twikeyFeedEntity.Messages) {
                    if (message.EvtTime != opportunity.Mandate_Last_Modified_Date__c && (
                            message.Mndt != null && message.Mndt.MndtId == opportunity.Account.UMR__c ||
                            message.CxlRsn != null && message.OrgnlMndtId == opportunity.Account.UMR__c) &&
                            (messageEventTime == null || message.EvtTime > messageEventTime)) {
                        messageEventTime = message.EvtTime;
                        lastMessage = message;
                    }
                }

                if (lastMessage != null) {
                    if (lastMessage.Mndt != null && lastMessage.Mndt.MndtId == opportunity.Account.UMR__c) {
                        opportunity.IBAN__c = lastMessage.Mndt.DbtrAcct;
                        if (lastMessage.Mndt.DbtrAgt != null && lastMessage.Mndt.DbtrAgt.FinInstnId != null) {
                            opportunity.SWIFT_BIC__c = lastMessage.Mndt.DbtrAgt.FinInstnId.BICFI;
                        }

                        opportunity.Send_SEPA_approval_link__c = true;
                        opportunity.SEPA_Request_Approved__c = true;
                        opportunity.Einwilligung_Lastschriftverfahren__c = true;
                        opportunity.AGB_Datenschutzhinweise_Richtigkeit__c = true;
                        if (opportunity.StageName == 'Closed Won') {
                            opportunity.Starts_Payment_method__c = 'Direct debit';
                        } else {
                            opportunity.Zahlungsart__c = 'Lastschrift';
                        }

                        if (lastMessage.EvtTime != null) {
                            opportunity.Mandate_Last_Modified_Date__c = lastMessage.EvtTime;
                            if (opportunity.Mandate_Activated__c == false) {
                                opportunity.SEPA_Request_Approval_Date__c = Datetime.valueOf(lastMessage.EvtTime.replace('T', ' ').replace('Z', ''));
                            }
                        }

                        opportunity.Mandate_Activated__c = true;
                        opportunitiesListToUpdate.add(opportunity);

                        SepaWebTwikey sepaWebTwikey = new SepaWebTwikey();
                        Blob pdfBody = sepaWebTwikey.retreivePdf(this.twikeySettings, lastMessage.Mndt.MndtId);
                        Attachment attachment = new Attachment(
                                ParentId = opportunity.Id,
                                Body = pdfBody,
                                Name = 'SEPAMandate');
                        attachmentsToInsertList.add(attachment);

                        if (! opportunity.Attachments.isEmpty()) {
                            attachmentsToDeleteList.add(opportunity.Attachments);
                        }
                    }
                    else if (lastMessage.CxlRsn != null && lastMessage.OrgnlMndtId == opportunity.Account.UMR__c) {
                        opportunity.Mandate_Activated__c = false;
                        if (lastMessage.EvtTime != null) {
                            opportunity.Mandate_Last_Modified_Date__c = lastMessage.EvtTime;
                        }

                        opportunitiesListToUpdate.add(opportunity);
                    }
                }
            }

            update opportunitiesListToUpdate;
            insert attachmentsToInsertList;
            delete attachmentsToDeleteList;
        }
        catch (Exception e) {
            ExceptionLogger.sendException(String.valueOf(e.getMessage()), String.valueOf(e.getStackTraceString()));
        }
    }


    public void finish(Database.BatchableContext BC) {

    }
}