default/objects/Account/fields/ESI__c.field-meta.xml
<CustomField>
    <fullName>ESI__c</fullName>
    <label>ESI</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Czech</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Hungarian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Slovak</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/fields/OBN__c.field-meta.xml
<CustomField>
    <fullName>OBN__c</fullName>
    <label>OBN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>DO Markenpartner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Record type for Partner Accounts of Fleetcor EU</description>
    <label>Partner</label>
</RecordType>

default/objects/Contact/fields/E2E__c.field-meta.xml
<CustomField>
    <fullName>E2E__c</fullName>
    <defaultValue>false</defaultValue>
    <label>E2E</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2E_Form_General_Settings__c/E2E_Form_General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>E2E Form General Settings</label>
</CustomObject>

default/objects/E2E_Form_General_Settings__c/fields/Enable_authorization_non_granted_check__c.field-meta.xml
<CustomField>
    <fullName>Enable_authorization_non_granted_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable authorization non granted check</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2E_Form_General_Settings__c/fields/Files_Generator_Url__c.field-meta.xml
<CustomField>
    <fullName>Files_Generator_Url__c</fullName>
    <label>Files Generator Url</label>
    <type>Url</type>
</CustomField>

default/objects/E2E_Form_General_Settings__c/fields/Payment_URL__c.field-meta.xml
<CustomField>
    <fullName>Payment_URL__c</fullName>
    <label>Payment URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Form_General_Settings__c/fields/Set_GFN_Status__c.field-meta.xml
<CustomField>
    <fullName>Set_GFN_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Set GFN Status</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2E_Short_Url__c/E2E_Short_Url__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>E2E Short Url</label>
</CustomObject>

default/objects/E2E_Short_Url__c/fields/E2E_Form_Url__c.field-meta.xml
<CustomField>
    <fullName>E2E_Form_Url__c</fullName>
    <label>E2E Form Url</label>
    <type>Url</type>
</CustomField>

default/objects/E2E_Short_Url__c/fields/E2E_JITB_Form_Url__c.field-meta.xml
<CustomField>
    <fullName>E2E_JITB_Form_Url__c</fullName>
    <label>E2E JITB Form Url</label>
    <type>Url</type>
</CustomField>

default/objects/E2E_Short_Url__c/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <label>Private Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Short_Url__c/fields/Short_Url__c.field-meta.xml
<CustomField>
    <fullName>Short_Url__c</fullName>
    <label>Short Url</label>
    <type>Url</type>
</CustomField>

default/objects/E2EKeysAPI__c/E2EKeysAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Key values for e2e form</description>
    <label>E2EKeysAPI</label>
</CustomObject>

default/objects/E2EKeysAPI__c/fields/AES256_Key__c.field-meta.xml
<CustomField>
    <fullName>AES256_Key__c</fullName>
    <label>AES256_Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/E2EKeysAPI__c/fields/paymentTransactionURL__c.field-meta.xml
<CustomField>
    <fullName>paymentTransactionURL__c</fullName>
    <label>paymentTransactionURL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/E2EKeysAPI__c/fields/PSPID__c.field-meta.xml
<CustomField>
    <fullName>PSPID__c</fullName>
    <description>Ingenico PSPID</description>
    <label>PSPID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/E2EKeysAPI__c/fields/SHA_KeyIn__c.field-meta.xml
<CustomField>
    <fullName>SHA_KeyIn__c</fullName>
    <label>SHA_KeyIn</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

default/objects/E2EKeysAPI__c/fields/SHA_KeyOut__c.field-meta.xml
<CustomField>
    <fullName>SHA_KeyOut__c</fullName>
    <label>SHA_KeyOut</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/AGB_Datenschutzhinweise_Richtigkeit__c.field-meta.xml
<CustomField>
    <fullName>AGB_Datenschutzhinweise_Richtigkeit__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Kunde (bei Personengesellschaften aller inhaber) bestätigt, die Allgemeinen Geschäftsbedingungen inkl. der Datenschutzhinweise und der aktuellen Gebührenüberischt gelesen zu haben und erkennt diese an. Kunde bestätigt die Richtigkeit der gemachten Angaben</inlineHelpText>
    <label>AGB/Datenschutzhinweise/Richtigkeit</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Agree_to_Privacy_Policy__c.field-meta.xml
<CustomField>
    <fullName>Agree_to_Privacy_Policy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agree to Privacy Policy</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Anruf</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Date_for_Agree_to_Privacy_Policy__c.field-meta.xml
<CustomField>
    <fullName>Date_for_Agree_to_Privacy_Policy__c</fullName>
    <label>Date for Agree to Privacy Policy</label>
    <type>DateTime</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Short_Link__c.field-meta.xml
<CustomField>
    <fullName>E2E_Short_Link__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>E2E Short Link</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Opportunity/fields/Eco_Fee__c.field-meta.xml
<CustomField>
    <fullName>Eco_Fee__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Tick to set, to choose if the Customer want to take Eco Fee or not.</description>
    <label>Eco Fee</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/ESI__c.field-meta.xml
<CustomField>
    <fullName>ESI__c</fullName>
    <description>Stationnumber for Retailer Homestations</description>
    <label>ESI</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Home_Station__c.field-meta.xml
<CustomField>
    <fullName>Home_Station__c</fullName>
    <label>Home Station</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/Opportunity/fields/Language_preference__c.field-meta.xml
<CustomField>
    <fullName>Language_preference__c</fullName>
    <inlineHelpText>Please select the language preference of the contact person.</inlineHelpText>
    <label>Language Preference *</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Czech</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Hungarian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Slovak</fullName>
            </value>
            <value>
                <fullName>Russisch</fullName>
                <label>Russian</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Primary_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Phone__c</fullName>
    <label>Primary Contact Phone</label>
    <type>Phone</type>
</CustomField>

default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product *</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BE-FR 2,5 Cent</fullName>
            </value>
            <value>
                <fullName>Carnet OBD</fullName>
            </value>
            <value>
                <fullName>Carnet Standard 2019</fullName>
            </value>
            <value>
                <fullName>Fuel Vehicle</fullName>
            </value>
            <value>
                <fullName>HOME 1</fullName>
            </value>
            <value>
                <fullName>Home Station offer (v.1)</fullName>
            </value>
            <value>
                <fullName>Inbound Typ B</fullName>
            </value>
            <value>
                <fullName>Inbound Typ C</fullName>
            </value>
            <value>
                <fullName>LOCAL - RED</fullName>
            </value>
            <value>
                <fullName>LOCAL - YELLOW</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes No fee</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes Standard</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>Sales no fee promo Feb 2016</fullName>
            </value>
            <value>
                <fullName>Shell Basic 2020</fullName>
            </value>
            <value>
                <fullName>Shell No fee 2020</fullName>
            </value>
            <value>
                <fullName>Shell Outbound 2020</fullName>
            </value>
            <value>
                <fullName>Shell Universal Card</fullName>
            </value>
            <value>
                <fullName>Smart</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + % fee)</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + fixed fee)</fullName>
            </value>
            <value>
                <fullName>Sonderangebot (s. Notizen)</fullName>
            </value>
            <value>
                <fullName>Swiss Pro</fullName>
            </value>
            <value>
                <fullName>Swiss Pro 5</fullName>
            </value>
            <value>
                <fullName>Swiss Star</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Visitor_ID__c.field-meta.xml
<CustomField>
    <fullName>Visitor_ID__c</fullName>
    <label>Visitor_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/recordTypes/Lotos.recordType-meta.xml
<RecordType>
    <fullName>Lotos</fullName>
    <active>true</active>
    <businessProcess>Carnet</businessProcess>
    <label>Lotos</label>
</RecordType>

default/classes/ShortURLHookServiceTest.cls
@isTest
private class ShortURLHookServiceTest {

    // LinkRedirectController, TwilioSMSHookController

    public static final String COUNTRY_DE = 'Germany';
    public static final String COUNTRY_PL = 'Poland';
    public static final String COUNTRY_CHDE = 'Switzerland-DE';
    final static String client_number = '+0000000000';
    final static String obnNumberDE = '000000';
    final static String obnNumberPL = 'R000001';
    final static String nonexisting_obnNumber = '0001000';
    public static String existing_short_urlDE;
    public static String existing_encoded_urlDE;
    public static String existing_short_urlPL;
    public static String existing_encoded_urlPL;

    @isTest
    static void smsControllerTestDE() {
        OpportunityTriggerHandler.enablesTrigger = false;
        prepareRecordsDE();
        Test.startTest();
            RestRequest req = new RestRequest();
            req.requestURI = '/services/apexrest/twiliohook';
            req.httpMethod = 'POST';
            req.addParameter('from','123456789');
            req.addParameter('body','000000');
            req.addParameter('country','Germany');
            RestContext.request = req;
            String res = TwilioSMSHookController.getPost();
            System.assert(res.contains('{"link":"'));
        Test.stopTest();
    }

    @isTest
    static void smsControllerTestPL() {
        OpportunityTriggerHandler.enablesTrigger = false;
        prepareRecordsPL();
        Test.startTest();
            RestRequest req = new RestRequest();
            req.requestURI = '/services/apexrest/twiliohook';
            req.httpMethod = 'POST';
            req.addParameter('from','123456789');
            req.addParameter('body','000001');
            req.addParameter('country','Poland');
            RestContext.request = req;
            String res = TwilioSMSHookController.getPost();
            System.assert(res.contains('{"link":"'));
        Test.stopTest();
    }

    @isTest
    static void smsLotosCase1TestPL() {
        String lotosObn = 'LOTOSP123';
        Boolean isLotosPartnerExistInDataBase = true;
        prepareRecordsLotosPL(lotosObn, isLotosPartnerExistInDataBase);
        Test.startTest();
        RestRequest req = new RestRequest();
            req.requestURI = '/services/apexrest/twiliohook';
            req.httpMethod = 'POST';
            req.addParameter('from', '123456789');
            req.addParameter('body', lotosObn);
            req.addParameter('country', 'Poland');
            RestContext.request = req;
            String res = TwilioSMSHookController.getPost();
        Test.stopTest();
        List<Opportunity> oppList = [SELECT E2E_Short_Link__c FROM Opportunity];
        System.assert(res.contains(oppList.get(0).E2E_Short_Link__c));
    }

    @isTest
    static void smsLotosCase2TestPL() {
        String lotosObn = 'LOTOS123';
        Boolean isLotosPartnerExistInDataBase = true;
        prepareRecordsLotosPL(lotosObn, isLotosPartnerExistInDataBase);
        Test.startTest();
            RestRequest req = new RestRequest();
            req.requestURI = '/services/apexrest/twiliohook';
            req.httpMethod = 'POST';
            req.addParameter('from', '123456789');
            req.addParameter('body', lotosObn);
            req.addParameter('country', 'Poland');
            RestContext.request = req;
            String res = TwilioSMSHookController.getPost();
        Test.stopTest();
        List<Opportunity> oppList = [SELECT E2E_Short_Link__c FROM Opportunity];
        System.assert(res.contains(oppList.get(0).E2E_Short_Link__c));
    }

    @isTest
    static void smsLotosCase3TestPL() {
        String lotosObn = '123';
        Boolean isLotosPartnerExistInDataBase = false;
        prepareRecordsLotosPL(lotosObn, isLotosPartnerExistInDataBase);
        Test.startTest();
            RestRequest req = new RestRequest();
            req.requestURI = '/services/apexrest/twiliohook';
            req.httpMethod = 'POST';
            req.addParameter('from', '123456789');
            req.addParameter('body', lotosObn);
            req.addParameter('country', 'Poland');
            RestContext.request = req;
            String res = TwilioSMSHookController.getPost();
        Test.stopTest();
        E2E_Short_Url__c e2eShortUrlDetail = E2E_Short_Url__c.getInstance('Poland');
        System.assertEquals(e2eShortUrlDetail.E2E_Form_Url__c, 'https://online.fleetcor.pl/etepl');
    }


    private static void prepareRecordsPL() {
        String base_url = Url.getSalesforceBaseUrl().toString();
        List<SObject> custom_settings = new List<SObject>();

        E2E_Form_General_Settings__c settingseE2EFormGeneral = new E2E_Form_General_Settings__c();
        settingseE2EFormGeneral.Name = 'Poland';
        settingseE2EFormGeneral.Enable_authorization_non_granted_check__c = false;
        settingseE2EFormGeneral.Files_Generator_Url__c = base_url;
        settingseE2EFormGeneral.Payment_URL__c = base_url;
        settingseE2EFormGeneral.Set_GFN_Status__c = false;
        settingseE2EFormGeneral.Test_Mode__c = false;
        custom_settings.add(settingseE2EFormGeneral);

        E2E_Short_Url__c settingsE2EShortUrl = new E2E_Short_Url__c();
        settingsE2EShortUrl.Name = 'Poland';
        settingsE2EShortUrl.Private_Key__c = '1234567890123456';
        settingsE2EShortUrl.Short_Url__c = base_url + '/i';
        settingsE2EShortUrl.E2E_Form_Url__c = base_url + '/etepl';
        settingsE2EShortUrl.E2E_JITB_Form_Url__c = base_url + '/etejitblocator';
        custom_settings.add(settingsE2EShortUrl);

        E2E_Short_Url__c settingsE2EShortUrl2 = new E2E_Short_Url__c();
        settingsE2EShortUrl2.Name = 'Germany';
        settingsE2EShortUrl2.Private_Key__c = '1234567890123456';
        settingsE2EShortUrl2.Short_Url__c = base_url + '/i';
        settingsE2EShortUrl2.E2E_Form_Url__c = base_url + '/etede';
        settingsE2EShortUrl2.E2E_JITB_Form_Url__c = base_url + '/e2ejitblocator';
        custom_settings.add(settingsE2EShortUrl2);

        E2EKeysAPI__c settingsEKeysAPIPL = new E2EKeysAPI__c(Name = 'E2EFormPL', AES256_Key__c = 'F1kCSPMj49W2arKn9Ut0DmywkswU6E1Q/wlyutztVww=', paymentTransactionURL__c = 'https://ogone.test.v-psp.com/ncol/test//orderstandard_utf8.asp', PSPID__c = 'fleetcorTEST', SHA_KeyIn__c = 'FleetcorTest!12@', SHA_KeyOut__c = 'IngenFleetTest1!');
        custom_settings.add(settingsEKeysAPIPL);
        E2EKeysAPI__c settingsEKeysAPIDE = new E2EKeysAPI__c(Name = 'E2EForm', AES256_Key__c = 'F1kCSPMj49W2arKn9Ut0DmywkswU6E1Q/wlyutztVww=', paymentTransactionURL__c = 'https://ogone.test.v-psp.com/ncol/test//orderstandard_utf8.asp', PSPID__c = 'fleetcorTEST', SHA_KeyIn__c = 'FleetcorTest!12@', SHA_KeyOut__c = 'IngenFleetTest1!');
        custom_settings.add(settingsEKeysAPIDE);

        insert custom_settings;

        String esi;
        Account station;
        String homestation;

        Account retailerAccount = new Account(
                OBN__c = obnNumberPL,
                Name = 'ValidOBN2',
                ShippingCountry = 'Poland',
                BillingCountry = 'Poland',
                BillingCity = 'Warsaw',
                BillingStreet = 'Strasse',
                Type = 'Customer',
                E2E__c = true);
        insert retailerAccount;


        List<Account> checkRetailer = [SELECT BillingStreet,BillingCity,BillingCountry FROM Account WHERE BillingCountry = :COUNTRY_PL AND OBN__c != null AND OBN__c = :obnNumberPL ORDER BY CreatedDate DESC LIMIT 1];
        if ( ! checkRetailer.isEmpty() ) {
            esi = obnNumberPL;
            station = checkRetailer.get(0);
            homestation = station.BillingStreet +', '+station.BillingCity+', '+station.BillingCountry;
        }

        String tempLongFormName;
        Decimal random = math.random() * 100000000;
        if (client_number == null) {
            tempLongFormName = 'LongForm:' + obnNumberPL + '_' + random;
        } else {
            tempLongFormName = 'LongForm: ' + client_number;
        }

        Account account = new Account(
                Name = tempLongFormName,
                BillingCountry = 'Poland',
                ShippingCountry = 'Poland',
                Type = 'Customer',
                E2E__c = true);
        insert account;

        // Opportunity creation
        Opportunity opportunity = new Opportunity(
                Name = tempLongFormName,
                ESI__c = esi,
                Home_Station__c = homestation,
                StageName = 'Prospecting',
                Product__c = '',
                AccountId = account.Id,
                CloseDate = Date.today(),
                Language_preference__c = 'Polish',
                Primary_Contact_Phone__c = client_number,
                Agree_to_Privacy_Policy__c = true,
                Date_for_Agree_to_Privacy_Policy__c = Datetime.now(),
                E2E__c = true,
                Sec_Channel__c = 'JITB',
                Channel__c = 'POS',
                LeadSource = 'SMS',
                CurrencyIsoCode = 'EUR',
                Type = 'New Business',
                //Device_Type__c = deviceView,
                Eco_Fee__c = true,
                //Visitor_ID__c = ipAddress,
                AGB_Datenschutzhinweise_Richtigkeit__c = false,
                E2E_Form_of_Business__c = 'Form of Business',
                E2E_Active_Step__c = 0,
                E2E_Status__c = 'In progress',
                E2E_Sales_Type__c = 'Fully E2E');
        insert opportunity;

        Datetime to_be_removed_time = Datetime.now().addDays(-4).addHours(1);
        Opportunity opportunity2 = new Opportunity(
                Name = tempLongFormName,
                ESI__c = esi,
                Home_Station__c = homestation,
                StageName = 'Prospecting',
                Product__c = 'Shell Basic 2020',
                AccountId = account.Id,
                CloseDate = Date.today(),
                Language_preference__c = 'Polish',
                Primary_Contact_Phone__c = client_number,
                Agree_to_process_pers_data_for_marketing__c = true,
                Agree_to_telephone_contact__c = true,
                Agree_to_receive_comm_info_by_email__c = true,
                E2E__c = true,
                Sec_Channel__c = 'JITB',
                Channel__c = 'POS',
                LeadSource = 'Tablet',
                CurrencyIsoCode = 'PLN',
                Type = 'New Business',
                //Device_Type__c = deviceView,
                Eco_Fee__c = true,
                //Visitor_ID__c = ipAddress,
                AGB_Datenschutzhinweise_Richtigkeit__c = false,
                E2E_Active_Step__c = 0,
                E2E_Status__c = 'In progress',
                E2E_Sales_Type__c = 'Fully E2E');
        insert opportunity2;
        Test.setCreatedDate(opportunity2.Id, to_be_removed_time);

        // Contact creation
        Contact contact = new Contact(
                Salutation = 'Mrs',
                LastName = tempLongFormName,
                AccountId = account.Id,
                Phone = client_number,
                Authorised_signatory__c = false,
                E2E__c = true,
                MailingCountry = 'Poland');
        insert contact;

        // create contact role
        OpportunityContactRole oppContactRole = new OpportunityContactRole(
                OpportunityId = opportunity.Id,
                ContactId = contact.Id,
                IsPrimary = true);
        insert oppContactRole;

        if (station != null) {
            Partner newPartner = new Partner();
            newPartner.AccountToId = station.Id;
            newPartner.OpportunityId = opportunity.Id;
            newPartner.Role = 'Multiplier';
            insert newPartner;
        }

        opportunity.E2E_Short_Link__c = generateShortId(obnNumberPL, opportunity.Id);
        opportunity.E2E_Encoded_URL__c = LongFormGlobalUtils.generateOppWithEncodedUrl(opportunity, 'E2EFormPL');
        opportunity.SEPA_Mandate_URL__c = LongFormGlobalUtils.generateOppWithSepaUrl(opportunity, 'E2EFormPL');
        opportunity.E2E_Last_Activity__c = Datetime.now();
        update opportunity;

        existing_short_urlPL = opportunity.E2E_Short_Link__c;
        existing_encoded_urlPL = opportunity.E2E_Encoded_URL__c;
    }

    private static void prepareRecordsLotosPL(String obn, Boolean isPartnerExist) {
        String base_url = 'https://online.fleetcor.pl';
        List<SObject> custom_settings = new List<SObject>();
        E2E_Short_Url__c settingsE2EShortUrl = new E2E_Short_Url__c();
        settingsE2EShortUrl.Name = 'Poland';
        settingsE2EShortUrl.Private_Key__c = '1234567890123456';
        settingsE2EShortUrl.Short_Url__c = base_url + '/i';
        settingsE2EShortUrl.E2E_Form_Url__c = base_url + '/etepl';
        settingsE2EShortUrl.E2E_JITB_Form_Url__c = base_url + '/etejitblocator';
        custom_settings.add(settingsE2EShortUrl);
        insert custom_settings;

        E2EKeysAPI__c settingsEKeysAPI = new E2EKeysAPI__c(Name = 'E2EFormPL', AES256_Key__c = 'F1kCSPMj49W2arKn9Ut0DmywkswU6E1Q/wlyutztVww=', paymentTransactionURL__c = 'https://ogone.test.v-psp.com/ncol/test//orderstandard_utf8.asp', PSPID__c = 'fleetcorTEST', SHA_KeyIn__c = 'FleetcorTest!12@', SHA_KeyOut__c = 'IngenFleetTest1!');
        insert settingsEKeysAPI;

        if (isPartnerExist) {
            Account lotosPartner = new Account(
                    Name = 'LOTOS',
                    Phone = '+48123321321321',
                    Partnertyp__c = 'Lotos partner',
                    OBN__c = obn,
                    BillingCountry = 'Poland'
            );
            insert lotosPartner;
        }
    }

    private static void prepareRecordsDE() {
        String base_url = Url.getSalesforceBaseUrl().toString();
        List<SObject> custom_settings = new List<SObject>();

        E2E_Form_General_Settings__c settingseE2EFormGeneral = new E2E_Form_General_Settings__c();
        settingseE2EFormGeneral.Name = 'Germany';
        settingseE2EFormGeneral.Enable_authorization_non_granted_check__c = false;
        settingseE2EFormGeneral.Files_Generator_Url__c = base_url;
        settingseE2EFormGeneral.Payment_URL__c = base_url;
        settingseE2EFormGeneral.Set_GFN_Status__c = false;
        settingseE2EFormGeneral.Test_Mode__c = false;
        custom_settings.add(settingseE2EFormGeneral);

        E2E_Short_Url__c settingsE2EShortUrl = new E2E_Short_Url__c();
        settingsE2EShortUrl.Name = 'Germany';
        settingsE2EShortUrl.Private_Key__c = '1234567890123456';
        settingsE2EShortUrl.Short_Url__c = base_url + '/i';
        settingsE2EShortUrl.E2E_Form_Url__c = base_url + '/etede';
        settingsE2EShortUrl.E2E_JITB_Form_Url__c = base_url + '/etejitblocator';
        custom_settings.add(settingsE2EShortUrl);

        ShortLinkEmailNotification__c notifications = new ShortLinkEmailNotification__c();
        notifications.Name = 'roman.rastriga@fleetcor.ru';
        custom_settings.add(notifications);

        E2EKeysAPI__c settingsEKeysAPI = new E2EKeysAPI__c();
        settingsEKeysAPI.Name = 'E2EForm';
        settingsEKeysAPI.AES256_Key__c = 'MTIzNDU2Nzg5MDEyMzQ1NjEyMzQ1Njc4OTAxMjM0NTY=';
        custom_settings.add(settingsEKeysAPI);

        ShortLinkOBNsRefreshed__c cachedOBN = new ShortLinkOBNsRefreshed__c(Name = obnNumberDE);
        ShortLinkOBNsRefreshed__c cachedOBN2 = new ShortLinkOBNsRefreshed__c(Name = nonexisting_obnNumber);
        custom_settings.add(cachedOBN);
        custom_settings.add(cachedOBN2);

        insert custom_settings;

        String esi;
        Account station;
        String homestation;

        Account retailerAccount = new Account(
                OBN__c = obnNumberDE,
                Name = 'ValidOBN',
                ShippingCountry = 'Germany',
                BillingCountry = 'Germany',
                BillingCity = 'Berlin',
                BillingStreet = 'Strasse',
                Type = 'Customer',
                E2E__c = true);
        insert retailerAccount;


        List<Account> checkRetailer = [SELECT BillingStreet,BillingCity,BillingCountry FROM Account WHERE BillingCountry = :COUNTRY_DE AND OBN__c != null AND OBN__c = :obnNumberDE ORDER BY CreatedDate DESC LIMIT 1];
        if ( ! checkRetailer.isEmpty() ) {
            esi = obnNumberDE;
            station = checkRetailer.get(0);
            homestation = station.BillingStreet +', '+station.BillingCity+', '+station.BillingCountry;
        }

        String tempLongFormName;
        Decimal random = math.random() * 100000000;
        if (client_number == null) {
            tempLongFormName = 'LongForm:' + obnNumberDE + '_' + random;
        } else {
            tempLongFormName = 'LongForm: ' + client_number;
        }

        Account account = new Account(
                Name = tempLongFormName,
                BillingCountry = 'Germany',
                ShippingCountry = 'Germany',
                Type = 'Customer',
                E2E__c = true);
        insert account;

        // Opportunity creation
        Opportunity opportunity = new Opportunity(
                Name = tempLongFormName,
                ESI__c = esi,
                Home_Station__c = homestation,
                StageName = 'Prospecting',
                Product__c = '',
                AccountId = account.Id,
                CloseDate = Date.today(),
                Language_preference__c = 'German',
                Primary_Contact_Phone__c = client_number,
                Agree_to_Privacy_Policy__c = true,
                Date_for_Agree_to_Privacy_Policy__c = Datetime.now(),
                E2E__c = true,
                Sec_Channel__c = 'JITB',
                Channel__c = 'POS',
                LeadSource = 'SMS',
                CurrencyIsoCode = 'EUR',
                Type = 'New Business',
                //Device_Type__c = deviceView,
                Eco_Fee__c = true,
                //Visitor_ID__c = ipAddress,
                AGB_Datenschutzhinweise_Richtigkeit__c = false,
                E2E_Form_of_Business__c = 'Form of Business',
                E2E_Active_Step__c = 0,
                E2E_Status__c = 'In progress',
                E2E_Sales_Type__c = 'Fully E2E');
        insert opportunity;

        Datetime to_be_removed_time = Datetime.now().addDays(-4).addHours(1);
        Opportunity opportunity2 = new Opportunity(
                Name = 'LongForm:'+esi+'_123456789',
                E2E_Last_Activity__c = to_be_removed_time,
                ESI__c = esi,
                Home_Station__c = homestation,
                StageName = 'Prospecting',
                Product__c = '',
                AccountId = account.Id,
                CloseDate = Date.today(),
                Language_preference__c = 'German',
                Primary_Contact_Phone__c = client_number,
                Agree_to_Privacy_Policy__c = true,
                Date_for_Agree_to_Privacy_Policy__c = Datetime.now(),
                E2E__c = true,
                Sec_Channel__c = 'JITB',
                Channel__c = 'POS',
                LeadSource = 'Tablet',
                CurrencyIsoCode = 'EUR',
                Type = 'New Business',
                //Device_Type__c = deviceView,
                Eco_Fee__c = true,
                //Visitor_ID__c = ipAddress,
                AGB_Datenschutzhinweise_Richtigkeit__c = false,
                E2E_Form_of_Business__c = 'Form of Business',
                E2E_Active_Step__c = 0,
                E2E_Status__c = 'In progress',
                E2E_Sales_Type__c = 'Fully E2E');
        insert opportunity2;
        Test.setCreatedDate(opportunity2.Id, to_be_removed_time);

        // Contact creation
        Contact contact = new Contact(
                Salutation = 'Mr',
                LastName = tempLongFormName,
                AccountId = account.Id,
                Phone = client_number,
                Authorised_signatory__c = false,
                E2E__c = true,
                MailingCountry = 'Germany');
        insert contact;

        // create contact role
        OpportunityContactRole oppContactRole = new OpportunityContactRole(
                OpportunityId = opportunity.Id,
                ContactId = contact.Id,
                IsPrimary = true);
        insert oppContactRole;

        if (station != null) {
            Partner newPartner = new Partner();
            newPartner.AccountToId = station.Id;
            newPartner.OpportunityId = opportunity.Id;
            newPartner.Role = 'Multiplier';
            insert newPartner;
        }

        opportunity.E2E_Short_Link__c = generateShortId(obnNumberDE, opportunity.Id);
        opportunity.E2E_Encoded_URL__c = LongFormGlobalUtils.generateOppWithEncodedUrl(opportunity, 'E2EForm');
        opportunity.SEPA_Mandate_URL__c = LongFormGlobalUtils.generateOppWithSepaUrl(opportunity, 'E2EForm');
        opportunity.E2E_Last_Activity__c = Datetime.now();
        update opportunity;

        existing_short_urlDE = opportunity.E2E_Short_Link__c;
        existing_encoded_urlDE = opportunity.E2E_Encoded_URL__c;
    }

    private static String generateShortId(String obnNumber, Id oppId) {
        E2E_Short_Url__c e2eShortUrlDetail = E2E_Short_Url__c.getInstance('Germany');
        String shortid = EncodingUtil.urlEncode(
                EncodingUtil.base64Encode(Crypto.encryptWithManagedIV('AES128',
                        Blob.valueOf(e2eShortUrlDetail.Private_Key__c),
                        Blob.valueOf(String.valueOf(obnNumber + oppId)))), 'UTF-8')
                .replace('%', '').substring(1, 7);
        return shortid;
    }
}