default/objects/Account/fields/Gesellschaftsform__c.field-meta.xml
<CustomField>
    <fullName>Gesellschaftsform__c</fullName>
    <label>Gesellschaftsform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>Agency of an Overseas Business</fullName>
            </value>
            <value>
                <fullName>Akciová společnost - a.s.</fullName>
            </value>
            <value>
                <fullName>AöR</fullName>
            </value>
            <value>
                <fullName>Artisans</fullName>
            </value>
            <value>
                <fullName>ASBL</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Association à but lucratif</fullName>
            </value>
            <value>
                <fullName>Association à but non lucratif</fullName>
            </value>
            <value>
                <fullName>Auto entrepreneur</fullName>
            </value>
            <value>
                <fullName>Autres</fullName>
            </value>
            <value>
                <fullName>Behörde</fullName>
            </value>
            <value>
                <fullName>Branch of an Overseas Business</fullName>
            </value>
            <value>
                <fullName>BV</fullName>
            </value>
            <value>
                <fullName>BVBA</fullName>
            </value>
            <value>
                <fullName>Civil Law Partnership</fullName>
            </value>
            <value>
                <fullName>Comm V</fullName>
            </value>
            <value>
                <fullName>Comm VA</fullName>
            </value>
            <value>
                <fullName>Coöperatieve en onderlinge waarborgmaatschappij</fullName>
            </value>
            <value>
                <fullName>Cooperative</fullName>
            </value>
            <value>
                <fullName>CV</fullName>
            </value>
            <value>
                <fullName>CVBA</fullName>
            </value>
            <value>
                <fullName>CVOA</fullName>
            </value>
            <value>
                <fullName>e.K</fullName>
            </value>
            <value>
                <fullName>e.V.</fullName>
            </value>
            <value>
                <fullName>Eenmanszaak</fullName>
            </value>
            <value>
                <fullName>EESV</fullName>
            </value>
            <value>
                <fullName>eG</fullName>
            </value>
            <value>
                <fullName>EI</fullName>
            </value>
            <value>
                <fullName>Einzelfirma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Czech</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Hungarian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Slovak</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/fields/Risk_Category__c.field-meta.xml
<CustomField>
    <fullName>Risk_Category__c</fullName>
    <label>Risk Category</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/SWIFT_BIC__c.field-meta.xml
<CustomField>
    <fullName>SWIFT_BIC__c</fullName>
    <label>SWIFT BIC *</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/UMR__c.field-meta.xml
<CustomField>
    <fullName>UMR__c</fullName>
    <description>Unique Mandate Reference Number</description>
    <formula>RIGHT(Account_Nr__c , 7)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UMR</label>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Umsatzsteuer_ID__c.field-meta.xml
<CustomField>
    <fullName>Umsatzsteuer_ID__c</fullName>
    <inlineHelpText>DE: Umsatzsteuer-ID (DE123456789), NL: Btw-nummer (NL001435784B01), BE: Btw-nummer (NL) / TVA (FR) (BE0123456789), PL: VAT (PL5252584121), HU: Áfa (International VAT) (HU25487970), FR: TVA (FR 83 404833048)</inlineHelpText>
    <label>Umsatzsteuer ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Direct_Debit_Mandate_Type__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_Mandate_Type__c</fullName>
    <label>Direct Debit Mandate Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Zahlungsart__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>B2B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN*</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Language_preference__c.field-meta.xml
<CustomField>
    <fullName>Language_preference__c</fullName>
    <inlineHelpText>Please select the language preference of the contact person.</inlineHelpText>
    <label>Language Preference *</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Czech</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Hungarian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Slovak</fullName>
            </value>
            <value>
                <fullName>Russisch</fullName>
                <label>Russian</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Risk_Category__c.field-meta.xml
<CustomField>
    <fullName>Risk_Category__c</fullName>
    <inlineHelpText>Abhängig von Crefo rating</inlineHelpText>
    <label>Risk Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Very</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/SEPA_Request_Approved__c.field-meta.xml
<CustomField>
    <fullName>SEPA_Request_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SEPA Request Approved</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Total_consumption_l_month__c.field-meta.xml
<CustomField>
    <fullName>Total_consumption_l_month__c</fullName>
    <label>Total consumption (l/month) *</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/UMR__c.field-meta.xml
<CustomField>
    <fullName>UMR__c</fullName>
    <formula>Account.UMR__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UMR</label>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Zahlungsart__c.field-meta.xml
<CustomField>
    <fullName>Zahlungsart__c</fullName>
    <label>Zahlungsart *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lastschrift</fullName>
            </value>
            <value>
                <fullName>Banküberweisung</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Twikey__c/Twikey__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Twikey</label>
</CustomObject>

default/objects/Twikey__c/fields/B2B_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>B2B_Template_Id__c</fullName>
    <label>B2B Template Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/objects/Twikey__c/fields/Core_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Core_Template_Id__c</fullName>
    <label>Core Template Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/classes/SepaDataApprovalRequestCtrl.cls
public with sharing class SepaDataApprovalRequestCtrl {
    public Opportunity currentOpportunity;
    public Contact recipientContact;
    public EmailTemplate emailTemplate;

    public SepaDataApprovalRequestCtrl() {    
    }

    public void init() {
        try {
            String oppId = ApexPages.currentPage().getParameters().get('id');

            if (oppId != null) {
                this.currentOpportunity = [
                    SELECT StageName, SEPA_Request_Approved__c, Send_SEPA_approval_link__c, RecordType.Name, Total_consumption_l_month__c,
                           Zahlungsart__c, Account.BillingCountry, Risk_Category__c, Direct_Debit_Mandate_Type__c, Language_preference__c,
                           IBAN__c, SWIFT_BIC__c, Account.BillingStreet, Account.BillingCity, Account.BillingPostalCode, Account.BillingCountryCode,
                           Account.Umsatzsteuer_ID__c, Account.Gesellschaftsform__c, Account.UMR__c,
                          (SELECT IsPrimary, ContactId FROM OpportunityContactRoles WHERE ContactId != null)
                    FROM Opportunity
                    WHERE Id = :oppId
                    LIMIT 1];
            } else {
                throw new SendingException('Invalid record id. Please try again.');
            }

            if (this.currentOpportunity.Zahlungsart__c == null) throw new SendingException('Please set \'Direct Debit\' payment method. <a href="/' + this.currentOpportunity.Id + '">Back to Opportunity</a>'); 
            if (this.currentOpportunity.Zahlungsart__c != 'Lastschrift') throw new SendingException('Sepa Data Approval Request is available only for \'Direct Debit\' payment method. <a href="/' + this.currentOpportunity.Id + '">Back to Opportunity</a>'); 
            if (this.currentOpportunity.Total_consumption_l_month__c == null) throw new SendingException('Please set total consumption. <a href="/' + this.currentOpportunity.Id + '">Back to Opportunity</a>');         
            if (this.currentOpportunity.Direct_Debit_Mandate_Type__c == null) throw new SendingException('Please set mandate type. <a href="/' + this.currentOpportunity.Id + '">Back to Opportunity</a>');

            String appropriateMandateType = CreditFactoryGlobalUtils.returnAppropriateMandateType(this.currentOpportunity.Account.BillingCountry,
                                                                                              'Very', // the worst case
                                                                                          this.currentOpportunity.Total_consumption_l_month__c);
            if (this.currentOpportunity.Risk_Category__c == null && this.currentOpportunity.Direct_Debit_Mandate_Type__c == 'Core' && appropriateMandateType == 'B2B') {
                throw new SendingException('Please run Credit Factory first to learn the risk level of the Customer.<a href="/' + this.currentOpportunity.Id + '">back to Opportunity</a>');
            }

            String contactId;
            List<OpportunityContactRole> contactRolesList = this.currentOpportunity.OpportunityContactRoles;
            if (! contactRolesList.isEmpty()) {
                for (OpportunityContactRole ocr : contactRolesList) {
                    if (ocr.IsPrimary) {
                        contactId = ocr.ContactId;
                    }
                }
            }

            List<Contact> contactList = [
                SELECT Id, Email, LastName, FirstName, MobilePhone
                FROM Contact
                WHERE Id = :contactId
                LIMIT 1];

            if (! contactList.isEmpty()) {
                this.recipientContact = contactList.get(0);
            }

            this.emailTemplate = chooseTemplate();

            validateRequest();

            String mandateId;
            if ((this.currentOpportunity.Account.BillingCountry == 'Belgium-NL' || this.currentOpportunity.Account.BillingCountry == 'Belgium-FR') &&
                    this.currentOpportunity.Direct_Debit_Mandate_Type__c == 'B2B') {
                TwikeyEntity twikeyEntity = sendTwikeyLink();
                mandateId = twikeyEntity.mndtId;
            }

            if (this.currentOpportunity.Send_SEPA_approval_link__c == false || this.currentOpportunity.SEPA_Request_Approved__c == true) {
                this.currentOpportunity.Send_SEPA_approval_link__c = true;
                this.currentOpportunity.SEPA_Request_Approved__c = false;
                update this.currentOpportunity;
            }

            if (this.currentOpportunity.Account.BillingCountry != 'Belgium-NL' && this.currentOpportunity.Account.BillingCountry != 'Belgium-FR' ||
                    (this.currentOpportunity.Account.BillingCountry == 'Belgium-NL' || this.currentOpportunity.Account.BillingCountry == 'Belgium-FR') &&
                    this.currentOpportunity.Direct_Debit_Mandate_Type__c == 'Core') {
                sendEmail();
            }

            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Approval link has been sent. <a href="/' + this.currentOpportunity.Id + '">Back to Opportunity</a>'));
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, e.getMessage()));
        }
    }


    /*******************************************************************************
    *  Summary         : send Twikey link to the customer
    *  CreatedDate     : 05/10/2020 by Anton Buzak
    *  Parameters      : -
    *  Returns         : twikey entity
    ******************************************************************************/
    public TwikeyEntity sendTwikeyLink() {
        SepaWebTwikey sepaWebTwikey = new SepaWebTwikey();
        Twikey__c twikeySettings;
        Twikey__c twikeySettingsTest = Twikey__c.getInstance('Test');
        Twikey__c twikeySettingsProd = Twikey__c.getInstance('Production');
        if (twikeySettingsProd != null && twikeySettingsProd.Active__c == true) {
            twikeySettings = twikeySettingsProd;
        }
        else if (twikeySettingsTest != null && twikeySettingsTest.Active__c == true) {
            twikeySettings = twikeySettingsTest;
        }

        Map<String, Object> inviteParametersMap = new Map<String, Object>();
        String templateId;
        if (this.currentOpportunity.Direct_Debit_Mandate_Type__c == 'B2B') {
            templateId = twikeySettings.B2B_Template_Id__c;
        }
        else {
            templateId = twikeySettings.Core_Template_Id__c;
        }

        inviteParametersMap.put('ct', templateId);
        String language;
        if (this.currentOpportunity.Language_preference__c == 'Dutch') {
            language = 'nl';
        }
        else if (this.currentOpportunity.Language_preference__c == 'French') {
            language = 'fr';
        }
        else {
            language = 'en';
        }

        inviteParametersMap.put('l', language);
        inviteParametersMap.put('iban', this.currentOpportunity.IBAN__c);
        inviteParametersMap.put('bic', this.currentOpportunity.SWIFT_BIC__c);
        inviteParametersMap.put('mandateNumber', this.currentOpportunity.Account.UMR__c);
        inviteParametersMap.put('email', this.recipientContact.Email);
        inviteParametersMap.put('lastname', this.recipientContact.LastName);
        inviteParametersMap.put('firstname', this.recipientContact.FirstName);
        inviteParametersMap.put('mobile', this.recipientContact.MobilePhone);
        inviteParametersMap.put('address', this.currentOpportunity.Account.BillingStreet);
        inviteParametersMap.put('city', this.currentOpportunity.Account.BillingCity);
        inviteParametersMap.put('zip', this.currentOpportunity.Account.BillingPostalCode);
        inviteParametersMap.put('country', this.currentOpportunity.Account.BillingCountryCode);
        inviteParametersMap.put('vatno', this.currentOpportunity.Account.Umsatzsteuer_ID__c);
        inviteParametersMap.put('form', this.currentOpportunity.Account.Gesellschaftsform__c);
        inviteParametersMap.put('sendInvite', true);

        TwikeyEntity twikeyEntity = sepaWebTwikey.inviteCustomer(twikeySettings, inviteParametersMap);
        return twikeyEntity;
    }


    /*******************************************************************************
    *  Name            : chooseTemplate()
    *  Summary         : choose template based on country
    *  CreatedDate     : 10/09/2017
    *  ModifiedDate    : 10/09/2017
    *  Parameters      : -
    *  Returns         : EmailTemplate
    ******************************************************************************/
    public EmailTemplate chooseTemplate() {
        List<EmailTemplate> templateList = new List<EmailTemplate>();
        if (this.currentOpportunity.Account != null) {
            if (this.currentOpportunity.Account.BillingCountry == 'Germany') {
                templateList = [
                    SELECT Id, Subject, HtmlValue, Body
                    FROM EmailTemplate
                    WHERE DeveloperName = 'SEPA_Approval_Link_for_contact_DE'
                    LIMIT 1];
            } else if (this.currentOpportunity.Account.BillingCountry == 'Netherlands' || this.currentOpportunity.Account.BillingCountry == 'Belgium-NL') {
                templateList = [
                    SELECT Id, Subject, HtmlValue, Body
                    FROM EmailTemplate
                    WHERE DeveloperName = 'SEPA_Approval_Link_for_contact_NL'
                    LIMIT 1];
            } else if (this.currentOpportunity.Account.BillingCountry == 'France' || this.currentOpportunity.Account.BillingCountry == 'Belgium-FR') {
                templateList = [
                    SELECT Id, Subject, HtmlValue, Body
                    FROM EmailTemplate
                    WHERE DeveloperName = 'SEPA_Approval_Link_for_contact_FR'
                    LIMIT 1];
            }

            if (! templateList.isEmpty()) {
                return templateList.get(0);
            }
        }

        return null;
    }


    /*******************************************************************************
    *  Name            : validateRequest()
    *  Summary         : validate data before sending email
    *  CreatedDate     : 07/08/2017
    *  ModifiedDate    : 28/11/2019
    *  Parameters      : -
    *  Returns         : void
    ******************************************************************************/
    public void validateRequest () {
        if (this.recipientContact == null) {
            throw new SendingException('There is either no primary contact or you don\'t have access to it. Please contact your administrator.<a href="/' + this.currentOpportunity.Id + '">back to Opportunity</a>');
        }
        if (this.recipientContact.Email == null) {
            throw new SendingException('SEPA approval link was not sent to the contact. Email address is empty.<a href="/' + this.currentOpportunity.Id + '">back to Opportunity</a>');
        }
        if (this.emailTemplate == null && this.currentOpportunity.Account.BillingCountry != 'Belgium-FR' && this.currentOpportunity.Account.BillingCountry != 'Belgium-NL') {
            throw new SendingException('SEPA approval link was not sent to the contact. There are no email templates.<a href="/' + this.currentOpportunity.Id + '">back to Opportunity</a>');
        }

        String appropriateMandateType = CreditFactoryGlobalUtils.returnAppropriateMandateType(this.currentOpportunity.Account.BillingCountry,
                                                                                          this.currentOpportunity.Risk_Category__c,
                                                                                      this.currentOpportunity.Total_consumption_l_month__c);
        if (this.currentOpportunity.Direct_Debit_Mandate_Type__c == 'Core' && appropriateMandateType == 'B2B') {
            throw new SendingException('Please change the Direct Debit Type Mandate from Core to B2B because the Customer has high Credit risk.<a href="/' + this.currentOpportunity.Id + '">back to Opportunity</a>');
        }
    }


    /*******************************************************************************
    *  Name            : sendEmail()
    *  Summary         : sending letter with SEPA Approval link
    *  CreatedDate     : 07/08/2017
    *  Parameters      : -
    *  Returns         : void
    ******************************************************************************/
    public void sendEmail() {
        List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTemplateID(this.emailTemplate.Id);
        mail.setTargetObjectId(this.recipientContact.Id);
        mail.setWhatId(this.currentOpportunity.Id);
        mail.setSaveAsActivity(false);
        allmsg.add(mail);
        if (! Test.isRunningTest()) {
            Messaging.sendEmail(allmsg);
        }
    }

    public class SendingException extends Exception {}
}