default/objects/Account/fields/GFN_Nr__c.field-meta.xml
<CustomField>
    <fullName>GFN_Nr__c</fullName>
    <description>Unique account identifier generated in GFN (Global FleetNet) system</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique account identifier generated in GFN (Global FleetNet) system</inlineHelpText>
    <label>GFN Nr.</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Credit_Factory_Report__c/Credit_Factory_Report__c.object-meta.xml
<CustomObject>
    <label>Credit Factory Report</label>
    <nameField>
        <label>Credit Factory Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Factory Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Credit_Factory_Report__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Factory Reports</relationshipLabel>
    <relationshipName>Credit_Factory_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Credit_Factory_Report__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Credit Factory Reports</relationshipLabel>
    <relationshipName>Credit_Factory_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Opportunity/fields/bearbeitet_von__c.field-meta.xml
<CustomField>
    <fullName>bearbeitet_von__c</fullName>
    <label>bearbeitet von</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anita Eštóková</fullName>
            </value>
            <value>
                <fullName>Autoprocessed by Sales</fullName>
            </value>
            <value>
                <fullName>CCS Credit</fullName>
            </value>
            <value>
                <fullName>Čermák Petr</fullName>
            </value>
            <value>
                <fullName>Credit UK</fullName>
            </value>
            <value>
                <fullName>Dalma Decsiová</fullName>
            </value>
            <value>
                <fullName>David Witteveen</fullName>
            </value>
            <value>
                <fullName>Jaroslava Polaskova</fullName>
            </value>
            <value>
                <fullName>Jaroslava Pribylova</fullName>
            </value>
            <value>
                <fullName>Katarzyna Sobek</fullName>
            </value>
            <value>
                <fullName>Katarzyna Szuflak</fullName>
            </value>
            <value>
                <fullName>Lucie Cechova</fullName>
            </value>
            <value>
                <fullName>Lucie Konvickova</fullName>
            </value>
            <value>
                <fullName>Martin Elstner</fullName>
            </value>
            <value>
                <fullName>Michal Ulrich</fullName>
            </value>
            <value>
                <fullName>NIzam Boodoo</fullName>
            </value>
            <value>
                <fullName>Petr Hlavac</fullName>
            </value>
            <value>
                <fullName>Radana Benešová</fullName>
            </value>
            <value>
                <fullName>Renata Dvorakova</fullName>
            </value>
            <value>
                <fullName>Romy Stehlinová</fullName>
            </value>
            <value>
                <fullName>Ruben Elgersma</fullName>
            </value>
            <value>
                <fullName>Veronika Coffa</fullName>
            </value>
            <value>
                <fullName>Vincent Coffa</fullName>
            </value>
            <value>
                <fullName>Ewa Szmigowska</fullName>
            </value>
            <value>
                <fullName>Mario Kozik</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/CF_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>CF_Credit_Limit__c</fullName>
    <label>CF Credit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

default/objects/Opportunity/fields/CF_Stage__c.field-meta.xml
<CustomField>
    <fullName>CF_Stage__c</fullName>
    <label>CF Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not launched</fullName>
                <default>true</default>
                <label>Not launched</label>
            </value>
            <value>
                <fullName>Error (Report not generated)</fullName>
            </value>
            <value>
                <fullName>Launched</fullName>
            </value>
            <value>
                <fullName>Error (Report generated)</fullName>
            </value>
            <value>
                <fullName>Report generated</fullName>
            </value>
            <value>
                <fullName>Pending Credit Report - Order was sent</fullName>
            </value>
            <value>
                <fullName>Pending Credit Report - Need information</fullName>
            </value>
            <value>
                <fullName>Pending Credit Report - Additional information was sent</fullName>
            </value>
            <value>
                <fullName>Credit Report Generated</fullName>
            </value>
            <value>
                <fullName>SEPA Confirmation</fullName>
            </value>
            <value>
                <fullName>Pending deposit</fullName>
            </value>
            <value>
                <fullName>Pending Credit - Contract Check</fullName>
            </value>
            <value>
                <fullName>Auto CW</fullName>
            </value>
            <value>
                <fullName>Manual scoring</fullName>
            </value>
            <value>
                <fullName>Pending Credit Report</fullName>
            </value>
            <value>
                <fullName>Credit Report not available</fullName>
            </value>
            <value>
                <fullName>Pending Advance Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Closed_Won_by_CF__c.field-meta.xml
<CustomField>
    <fullName>Closed_Won_by_CF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Closed Won by CF</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Credit_check_date__c.field-meta.xml
<CustomField>
    <fullName>Credit_check_date__c</fullName>
    <label>Credit check date</label>
    <type>Date</type>
</CustomField>

default/objects/Opportunity/fields/Credit_System_Rating__c.field-meta.xml
<CustomField>
    <fullName>Credit_System_Rating__c</fullName>
    <label>Credit System Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>0–EX</fullName>
            </value>
            <value>
                <fullName>5-EX</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Keine Bonität</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/GFN_Nr__c.field-meta.xml
<CustomField>
    <fullName>GFN_Nr__c</fullName>
    <formula>Account.GFN_Nr__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GFN Nr.</label>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Gruende_verloren__c.field-meta.xml
<CustomField>
    <fullName>Gruende_verloren__c</fullName>
    <label>Gründe verloren</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>After Sales - Degussa</fullName>
            </value>
            <value>
                <fullName>AGB nicht aktzeptiert</fullName>
            </value>
            <value>
                <fullName>Already FLEETCOR Customer</fullName>
            </value>
            <value>
                <fullName>Andere Bezahlmethode - Cash</fullName>
            </value>
            <value>
                <fullName>Andere Bezahlmethode - EC/Kreditkarte</fullName>
            </value>
            <value>
                <fullName>Andere Bezahlmethode - Tankkarte</fullName>
            </value>
            <value>
                <fullName>Andere Bezahlmethode - VISA</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - bessere Zahlungsbeding</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - geringere Kosten</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - höheres Kreditlimit</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - keine Garantien</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - mehr Features</fullName>
            </value>
            <value>
                <fullName>Angabenkorrektur nicht möglich</fullName>
            </value>
            <value>
                <fullName>Bearbeitung - Degussa</fullName>
            </value>
            <value>
                <fullName>Bestellprozess zu lange</fullName>
            </value>
            <value>
                <fullName>Black List</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Change his mind</fullName>
            </value>
            <value>
                <fullName>Competitors</fullName>
            </value>
            <value>
                <fullName>Coverage/Acceptance</fullName>
            </value>
            <value>
                <fullName>Credit Report not available</fullName>
            </value>
            <value>
                <fullName>Customer not reached</fullName>
            </value>
            <value>
                <fullName>Deposit – not confirmed</fullName>
            </value>
            <value>
                <fullName>Didn't confirm card order</fullName>
            </value>
            <value>
                <fullName>Direct debit</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Execution</fullName>
            </value>
            <value>
                <fullName>Financial/Credit</fullName>
            </value>
            <value>
                <fullName>Firma zu jung</fullName>
            </value>
            <value>
                <fullName>Gebühren</fullName>
            </value>
            <value>
                <fullName>Refused Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Pending_Deposit_by_CF__c.field-meta.xml
<CustomField>
    <fullName>Pending_Deposit_by_CF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pending Deposit by CF</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Reopen__c.field-meta.xml
<CustomField>
    <fullName>Reopen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reopen</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Reopen_Log__c.field-meta.xml
<CustomField>
    <fullName>Reopen_Log__c</fullName>
    <label>Reopen Log</label>
    <type>TextArea</type>
</CustomField>

default/objects/Opportunity/fields/Security_level_H_he_der_Sicherheit__c.field-meta.xml
<CustomField>
    <fullName>Security_level_H_he_der_Sicherheit__c</fullName>
    <label>Security level/Höhe der Sicherheit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/Opportunity/fields/Zahlungsziel_Credit__c.field-meta.xml
<CustomField>
    <fullName>Zahlungsziel_Credit__c</fullName>
    <label>Zahlungsziel Credit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/SubmitForReopenCtrl.cls
public class SubmitForReopenCtrl {
	public Opportunity currentOpportunity;
	public User currentUser;
    public Integer daysAfterCreditCheck;

    public SubmitForReopenCtrl() {}

    public void init() {
    	try {
    		String userId = UserInfo.getUserId();
    	    String oppId = ApexPages.currentPage().getParameters().get('Id');

    	    this.currentUser = [
	                SELECT UserRole.Name, Profile.Name, Name, UserRoleId
	                FROM User
	                WHERE Id = :userId];

    	    this.currentOpportunity = [
	                SELECT Id, StageName, OwnerId, Name, Reopen__c, Account.GFN_Nr__c, Credit_check_date__c, CreatedDate, Gruende_verloren__c,
                        Security_level_H_he_der_Sicherheit__c, bearbeitet_von__c, Credit_System_Rating__c, Account.BillingCountry,
                                (SELECT Id
                                FROM Credit_Factory_Reports__r),
                                (SELECT Name
                                FROM Attachments)
	                FROM Opportunity
	                WHERE Id = :oppId
	                LIMIT 1];

            calcDiffBetweenDates();
            validate();

            if (this.currentOpportunity.StageName == 'Closed Won' || this.currentOpportunity.StageName == 'Closed Lost' && this.currentOpportunity.Gruende_verloren__c != 'Refused Credit' || 
                    this.currentOpportunity.StageName == 'Pending Sales - SEPA Confirmation') {
                reopenAutomatically();
            } else if (this.currentOpportunity.StageName == 'Closed Lost' && this.currentOpportunity.Gruende_verloren__c == 'Refused Credit' || 
                    this.currentOpportunity.StageName == 'CreditCheck abgelehnt') {
                submitForManualReopen();
            }
    	} catch (Exception e) {
    	    ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, e.getMessage()));
    	}
    }


    /*******************************************************************************
    *  Name            : calcDiffBetweenDates()
    *  Summary         : Calculate difference between 'Credit check date' and 'Today date'    
    *  CreatedDate     : 22/05/2018
    *  ModifiedDate    : 08/07/2019
    *  Parameters      : -
    *  Returns         : void
    ******************************************************************************/
    public void calcDiffBetweenDates() {
        if (this.currentOpportunity.Credit_check_date__c != null) {
            this.daysAfterCreditCheck = (Date.valueOf(this.currentOpportunity.Credit_check_date__c)).daysBetween(Date.today());
        } else {
            this.daysAfterCreditCheck = (Date.valueOf(this.currentOpportunity.CreatedDate)).daysBetween(Date.today());
        }
    }


    /*******************************************************************************
    *  Name            : validate()
    *  Summary         : check current Opporunity StageName    
    *  CreatedDate     : 14/05/2018
    *  ModifiedDate    : 08/07/2019
    *  Parameters      : -
    *  Returns         : void
    ******************************************************************************/
    public void validate() {
        if (this.daysAfterCreditCheck >= 31) {
            throw new StageException('Opportunity can only be reopened in 31 days from the Credit Check Date. Please create a new Opportunity or clone the current one. ' +
                '<a href="/' + this.currentOpportunity.Id + '">Back to Opportunity</a>');
        }
    	if (this.currentOpportunity.StageName != 'Closed Lost' && this.currentOpportunity.StageName != 'CreditCheck abgelehnt' && 
                this.currentOpportunity.StageName != 'Closed Won' && this.currentOpportunity.StageName != 'Pending Sales - SEPA Confirmation') {
            throw new StageException('You can only reopen Opportunities with Opportunity Stage = "Closed Lost", "Closed Won", "Pending Sales - SEPA Confirmation" or "CreditCheck rejected". ' + 
                '<a href="/' + this.currentOpportunity.Id + '">Back to Opportunity</a>');
        }
        if (this.currentOpportunity.Account.GFN_Nr__c != null) {
            throw new StageException('You cannot reopen Opportunities if GFN Number is not empty. Back to Opportunity. <a href="/' + this.currentOpportunity.Id + '">Back to Opportunity</a>');
        }
        if (Approval.isLocked(this.currentOpportunity.Id) && this.currentOpportunity.Reopen__c == true) {
            throw new StageException('This Opportunity is already submitted for reopen. <a href="/' + this.currentOpportunity.Id + '">Back to Opportunity</a>');
        }

        String profileName = [SELECT Profile.Name FROM User WHERE Id = :this.currentUser.Id].Profile.Name;
        if (Submit_for_reopen_profiles__c.getInstance(profileName) == null) {
            throw new StageException('User Profile is not valid. <a href="/' + this.currentOpportunity.Id + '">Back to Opportunity</a>');
        }
    }


    /*******************************************************************************
    *  Name            : reopenAutomatically()
    *  Summary         : Reopen Opportunity without sending for reopen    
    *  CreatedDate     : 08/07/2019
    *  ModifiedDate    : -
    *  Parameters      : -
    *  Returns         : void
    ******************************************************************************/
    public void reopenAutomatically() {
        this.currentOpportunity.Reopen_Log__c = 'Reopened by Sales\nDate of Reopen: ' + Datetime.now() + '\n' + 'Originally requested deposit: ' + 
            (this.currentOpportunity.Security_level_H_he_der_Sicherheit__c != null ? String.valueOf(this.currentOpportunity.Security_level_H_he_der_Sicherheit__c) : '') + 
            '\n' + 'Processed by: ' + (this.currentOpportunity.bearbeitet_von__c != null ? this.currentOpportunity.bearbeitet_von__c : '') + '\n' +
            'Credit Rating: ' + (this.currentOpportunity.Credit_System_Rating__c != null ? this.currentOpportunity.Credit_System_Rating__c : '');
        this.currentOpportunity.StageName = 'Prospecting';
        this.currentOpportunity.Gruende_verloren__c = '';
        this.currentOpportunity.bearbeitet_von__c = '';
        this.currentOpportunity.Closed_Won_by_CF__c = false;
        this.currentOpportunity.Pending_Deposit_by_CF__c = false;
        this.currentOpportunity.CF_Stage__c = 'Not launched';
        this.currentOpportunity.Reopen__c = false;
        this.currentOpportunity.CF_Credit_Limit__c = null;
        this.currentOpportunity.Zahlungsziel_Credit__c = '';
        this.currentOpportunity.Rechnungsperiode__c = '';
        this.currentOpportunity.Credit_check_date__c = null;
        this.currentOpportunity.Kredit_Entscheidung__c = '';
        this.currentOpportunity.Security_To_Pay__c = '';
        this.currentOpportunity.Security_Amount_To_Pay__c = null;
        this.currentOpportunity.Billing_Period_by_Sales__c = false;
        this.currentOpportunity.Max_Credit_Limit__c = null;
        this.currentOpportunity.Security_level_H_he_der_Sicherheit__c = null;
        this.currentOpportunity.Reopened__c = true;

        if (this.currentOpportunity.Account.BillingCountry == 'Netherlands' || this.currentOpportunity.Account.BillingCountry == 'Belgium-NL' || 
                this.currentOpportunity.Account.BillingCountry == 'Belgium-FR' || this.currentOpportunity.Account.BillingCountry == 'France') {
            this.currentOpportunity.Credit_System_Rating__c = null;
        }

        update this.currentOpportunity;

        if ((this.currentOpportunity.Account.BillingCountry == 'Netherlands' || this.currentOpportunity.Account.BillingCountry == 'Belgium-NL' || 
                this.currentOpportunity.Account.BillingCountry == 'Belgium-FR' || this.currentOpportunity.Account.BillingCountry == 'France') && 
                ! this.currentOpportunity.Credit_Factory_Reports__r.isEmpty()) {
            delete this.currentOpportunity.Credit_Factory_Reports__r;
            List<Attachment> attachmentsToDeleteList = new List<Attachment>();
            for (Attachment attachment : this.currentOpportunity.Attachments) {
                if (attachment.Name == 'CreditsafeReport.pdf') {
                    attachmentsToDeleteList.add(attachment);
                }
            }

            if (! attachmentsToDeleteList.isEmpty()) {
                AttachmentTriggerHandler.isCreditFactory = true;
                delete attachmentsToDeleteList;
            }
        }

        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Your opportunity was successfully reopened. ' +
            '<a href="/' + this.currentOpportunity.Id + '">Back to Opportunity</a>'));
    }


    /*******************************************************************************
    *  Name            : submitForManualReopen()
    *  Summary         : Send request for reopen to Credits    
    *  CreatedDate     : 08/07/2019
    *  ModifiedDate    : -
    *  Parameters      : -
    *  Returns         : void
    ******************************************************************************/
    public void submitForManualReopen() {
        this.currentOpportunity.Reopen__c = true;
        update this.currentOpportunity;
        sendEmail();

        Approval.lock(this.currentOpportunity.Id);

        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Your opportunity was successfully submitted for reopen. ' +
            '<a href="/' + this.currentOpportunity.Id + '">Back to Opportunity</a>'));
    }


    /*******************************************************************************
    *  Name            : sendEmail()
    *  Summary         : sending letters by pressing the button    
    *  CreatedDate     : 15/05/2018
    *  ModifiedDate    : 08/07/2019
    *  Parameters      : -
    *  Returns         : void
    ******************************************************************************/
    public void sendEmail() {
        List<Messaging.SingleEmailMessage> emails = preparationEmailsForSending(this.currentOpportunity, 'Petr Cermak');
        if (emails != null && ! Test.isRunningTest()) {
            Messaging.sendEmail(emails);
        }
    }


    /*******************************************************************************
    *  Name            : preparationEmailsForSending(Opportunity currentOpportunity, String customEmailName)
    *  Summary         : prepares to send email    
    *  CreatedDate     : 15/05/2018
    *  ModifiedDate    : 08/07/2019
    *  Parameters      : Opportunity opportunity, String customEmailName
    *  Returns         : all emails
    ******************************************************************************/
    public List<Messaging.SingleEmailMessage> preparationEmailsForSending(Opportunity opportunity, String customEmailName) {
	    Notifications_for_reopening_Opportunity__c emailCustomSetting = Notifications_for_reopening_Opportunity__c.getInstance(customEmailName);
        if (emailCustomSetting.Active__c == false) {
            return null;
        }
	    String headerData = ApexPages.currentPage().getHeaders().get('Host');

    	List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mailToCredit = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {emailCustomSetting.Email__c};
        mailToCredit.setToAddresses(toAddresses);
        mailToCredit.setSubject('Reopen request for ' + opportunity.Name);
        mailToCredit.setHtmlBody('<messaging:emailTemplate> ' +
                '<html> <style type="text/css"> body {size: 12pt;} td { border-width: 1px;  padding: 4px;' +
                'border-style: solid; border-color: #000000; background-color: #FFEECC;}th { color: #000000; border-width: 1px ; padding: 4px ;' +
                'border-style: solid ;  border-color: #000000; background-color: #FFFFF0;}</style>' +
                '<body>' +
                'Dear Credit Team, <br/>' +
                '<br/>' +
                'Please reopen the following Opportunity: https://' + headerData + '/' + opportunity.Id + '<br/>' +
                '<br/>' +
                'Best regards, <br/>' +
                this.currentUser.Name +
                '</body> ' +
                '</html> </messaging:emailTemplate>');
        allmsg.add(mailToCredit);

        return allmsg;
    }

    /*******************************************************************************
    *  Name            : backToOpportunity()
    *  Summary         : back to opportunity  
    *  CreatedDate     : 15/05/2018
    *  Parameters      : -
    *  Returns         : opportunity page
    ******************************************************************************/
    public PageReference backToOpportunity() {
        PageReference page = new PageReference('/' + currentOpportunity.Id);
        return page;
    }

    public class StageException extends Exception {}
}