default/objects/Account/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Идентификационный номер налогоплательщика.
            Должен содержать только цифры:
            12 цифр - ИП;
            10 цифр - юр. лицо.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/E2E_Form_Ru_General_Settings__c/E2E_Form_Ru_General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>E2E Form Ru General Settings</label>
</CustomObject>

default/objects/E2E_Form_Ru_General_Settings__c/fields/Call_Center_Managers__c.field-meta.xml
<CustomField>
    <fullName>Call_Center_Managers__c</fullName>
    <description>Responsible manager from call center department.</description>
    <label>Call Center Managers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Form_Ru_General_Settings__c/fields/External_Call_Center_Managers__c.field-meta.xml
<CustomField>
    <fullName>External_Call_Center_Managers__c</fullName>
    <label>External Call Center Managers</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2E_Form_Ru_General_Settings__c/fields/External_Main_Managers__c.field-meta.xml
<CustomField>
    <fullName>External_Main_Managers__c</fullName>
    <label>External Main Managers</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2E_Form_Ru_General_Settings__c/fields/External_Service_Managers__c.field-meta.xml
<CustomField>
    <fullName>External_Service_Managers__c</fullName>
    <label>External Service Managers</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2E_Form_Ru_General_Settings__c/fields/Main_Managers__c.field-meta.xml
<CustomField>
    <fullName>Main_Managers__c</fullName>
    <label>Main Managers</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2E_Form_Ru_General_Settings__c/fields/Number_Of_Cards__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Cards__c</fullName>
    <description>Maximum number of cards, which client can order without going to inbound department.</description>
    <label>Number Of Cards</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/E2E_Form_Ru_Internal_Notifications__c/E2E_Form_Ru_Internal_Notifications__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>E2E Form Ru Internal Notifications</label>
</CustomObject>

default/objects/E2E_Form_Ru_Internal_Notifications__c/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <description>Name of the Email Template (E2E RU dir)</description>
    <inlineHelpText>Name of the Email Template (E2E RU dir)</inlineHelpText>
    <label>Email Body</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2E_Form_Ru_Internal_Notifications__c/fields/Email_Subject__c.field-meta.xml
<CustomField>
    <fullName>Email_Subject__c</fullName>
    <label>Email Subject</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2E_Form_Ru_Internal_Notifications__c/fields/Recipients__c.field-meta.xml
<CustomField>
    <fullName>Recipients__c</fullName>
    <description>fields of the E2E_Form_Ru_General_Settings__c (E2EFormRu) object separated by the &quot;;&quot;. 
Example: &quot;Call_Center_Managers__c; External_Main_Managers__c&quot;</description>
    <inlineHelpText>fields of the E2E_Form_Ru_General_Settings__c (E2EFormRu) object separated by the &quot;;&quot;. 
Example: &quot;Call_Center_Managers__c; External_Main_Managers__c&quot;</inlineHelpText>
    <label>Recipients</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2EFormData__c/E2EFormData__c.object-meta.xml
<CustomObject>
    <description>Store data from E2E Form</description>
    <label>E2E Form Ru Data</label>
    <nameField>
        <displayFormat>E2ERU{00000000}</displayFormat>
        <label>E2EFormRuData  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>E2E Form Ru Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

default/objects/E2EFormData__c/fields/E2E_Manual_Entry__c.field-meta.xml
<CustomField>
    <fullName>E2E_Manual_Entry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Entry</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Lead/fields/Day_transfer__c.field-meta.xml
<CustomField>
    <fullName>Day_transfer__c</fullName>
    <formula>IF(LastTransferDate&lt;=DATE( 2017, 9, 5) , TransferDate_old_sistem__c, LastTransferDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Day of transfer</label>
    <type>Date</type>
</CustomField>

default/objects/Lead/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Tax identification number
        Must contain only numbers:
        Length 12 symbols for PE;
        Length 10 symbols for legal person.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Day_transfer__c.field-meta.xml
<CustomField>
    <fullName>Day_transfer__c</fullName>
    <formula>DATEVALUE(Last_Owner_Change_Date_RUS__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Дата перевода</label>
    <type>Date</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sub_Status__c</fullName>
    <label>E2E Sub. Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing automation</fullName>
            </value>
            <value>
                <fullName>Switched to manual</fullName>
            </value>
            <value>
                <fullName>Автоматическое письмо</fullName>
            </value>
            <value>
                <fullName>Перевод в ручную обработку</fullName>
            </value>
            <value>
                <fullName>Чёрный список</fullName>
            </value>
            <value>
                <fullName>Дедубликация</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/INN_Opp__c.field-meta.xml
<CustomField>
    <fullName>INN_Opp__c</fullName>
    <formula>Account.INN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>edit on Account</inlineHelpText>
    <label>INN Opp</label>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Number_of_Cards__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Cards__c</fullName>
    <description>Number of Cards</description>
    <inlineHelpText>Number of Cards</inlineHelpText>
    <label>Number of Cards</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/classes/E2E_RU_Internal_NotificationsTest.cls
@isTest
public class E2E_RU_Internal_NotificationsTest {

	@TestSetup
	public static void makeData () {

		List<E2E_Form_Ru_Internal_Notifications__c> listNotifications = new List<E2E_Form_Ru_Internal_Notifications__c>();
		listNotifications.add(new E2E_Form_Ru_Internal_Notifications__c(
				Name = 'Transfer_To_Ko_With_INN',
				Recipients__c = 'External_Main_Managers__c; Main_Managers__c',
				Email_Subject__c = 'Russia E2E Notification',
				Email_Body__c = 'E2E_RU_EMAIL_Transfer_To_KO_With_INN'
		));
		listNotifications.add(new E2E_Form_Ru_Internal_Notifications__c(
				Name = 'Transfer_To_Service',
				Recipients__c = 'External_Service_Managers__c; External_Main_Managers__c; Main_Managers__c',
				Email_Subject__c = 'Russia E2E Notification',
				Email_Body__c = 'E2E_RU_EMAIL_Transfer_To_Service'
		));
		listNotifications.add(new E2E_Form_Ru_Internal_Notifications__c(
				Name = 'Transfer_To_Inbound',
				Recipients__c = 'External_Service_Managers__c; External_Main_Managers__c; Main_Managers__c',
				Email_Subject__c = 'Russia E2E Notification',
				Email_Body__c = 'E2E_RU_EMAIL_Transfer_To_Inbound'
		));
		listNotifications.add(new E2E_Form_Ru_Internal_Notifications__c(
				Name = 'Transfer_To_Ko_With_Email',
				Recipients__c = 'External_Main_Managers__c; Main_Managers__c',
				Email_Subject__c = 'Russia E2E Notification',
				Email_Body__c = 'E2E_RU_EMAIL_Transfer_To_KO_With_Email'
		));
		listNotifications.add(new E2E_Form_Ru_Internal_Notifications__c(
				Name = 'Transfer_To_E2E',
				Recipients__c = 'External_Main_Managers__c; Main_Managers__c',
				Email_Subject__c = 'Russia E2E Отказ Возможности',
				Email_Body__c = 'E2E_RU_EMAIL_Transfer_To_E2E'
		));
		listNotifications.add(new E2E_Form_Ru_Internal_Notifications__c(
				Name = 'Transfer_To_Ko_More_10_Cards',
				Recipients__c = 'External_Main_Managers__c; Main_Managers__c; External_Service_Managers__c',
				Email_Subject__c = 'Russia E2E Перевод в KO',
				Email_Body__c = 'E2E_RU_EMAIL_More_10_Cards'
		));
		listNotifications.add(new E2E_Form_Ru_Internal_Notifications__c(
				Name = 'Transfer_To_Ko_Manual_Entry',
				Recipients__c = 'External_Main_Managers__c; Main_Managers__c; External_Service_Managers__c',
				Email_Subject__c = 'Russia E2E Перевод в KO',
				Email_Body__c = 'E2E_RU_EMAIL_Manual_Entry'
		));
		listNotifications.add(new E2E_Form_Ru_Internal_Notifications__c(
				Name = 'Risk_Management',
				Recipients__c = 'External_Main_Managers__c; Main_Managers__c; External_Service_Managers__c',
				Email_Subject__c = 'Russia E2E Дополнительное согласование',
				Email_Body__c = 'E2E_RU_EMAIL_Risk_Management'
		));
		listNotifications.add(new E2E_Form_Ru_Internal_Notifications__c(
				Name = 'Reseller',
				Recipients__c = 'External_Main_Managers__c; Main_Managers__c; External_Service_Managers__c',
				Email_Subject__c = 'Russia E2E Дополнительное согласование',
				Email_Body__c = 'E2E_RU_EMAIL_Reseller'
		));
		listNotifications.add(new E2E_Form_Ru_Internal_Notifications__c(
				Name = 'Disqualification_Lead',
				Recipients__c = 'External_Call_Center_Managers__c',
				Email_Subject__c = 'Russia E2E Disqualification Lead',
				Email_Body__c = 'E2E_RU_EMAIL_Disqualification_Lead'
		));
		listNotifications.add(new E2E_Form_Ru_Internal_Notifications__c(
				Name = 'Warning_Notification_Call_Center',
				Recipients__c = 'External_Call_Center_Managers__c',
				Email_Subject__c = 'Russia E2E System Error',
				Email_Body__c = 'E2E_RU_EMAIL_Warning_Notification_CC'
		));
		listNotifications.add(new E2E_Form_Ru_Internal_Notifications__c(
				Name = 'Abandonment_Scenario_Queueable',
				Recipients__c = 'Main_Managers__c; Call_Center_Managers__c',
				Email_Subject__c = 'E2E Возможность неактивна',
				Email_Body__c = 'E2E_RU_EMAIL_Abandonment_Scenario'
		));
		INSERT listNotifications;

		E2E_Form_Ru_General_Settings__c generalSettings = new E2E_Form_Ru_General_Settings__c(
				Name = 'E2EFormRu',
				Main_Managers__c = 'test',
				Call_Center_Managers__c = 'test',
				External_Call_Center_Managers__c = 'test'
		);
		INSERT generalSettings;

		Opportunity opp = E2EFormRuTestUtils.createDefaultOpportunity();
		INSERT opp;

		Lead testLead = E2EFormRuTestUtils.createDefaultLead();
		INSERT testLead;
	}



	@isTest
	static void forceUpdateOpportunity () {
		String oppId = [SELECT Id FROM Opportunity LIMIT 1].Id;
		E2E_RU_Internal_Notifications.forceUpdateOpportunity(oppId);
	}

	@isTest
	static void goToCongratulations () {
		String oppId = [SELECT Id FROM Opportunity LIMIT 1].Id;
		E2EFormParams formParams = new E2EFormParams();
		formParams.isManualEntry = true;
		E2E_RU_Internal_Notifications.goToCongratulations(formParams, oppId);
		formParams.isNumberOfCardsLimit = true;
		E2E_RU_Internal_Notifications.goToCongratulations(formParams, oppId);
	}

	@isTest
	static void goToLegalDetails () {
		String oppId = [SELECT Id FROM Opportunity LIMIT 1].Id;
		E2EFormParams formParams = new E2EFormParams();
		formParams.verifiedDecisionCode = '4';
		E2E_RU_Internal_Notifications.goToLegalDetails(formParams, oppId);
		formParams.verifiedDecisionCode = '1';
		E2E_RU_Internal_Notifications.goToLegalDetails(formParams, oppId);
	}

	@isTest
	static void transferToE2E () {
		List<Opportunity> listOpp = [
		    SELECT 	E2E_Sub_Status__c,  Name, Number_of_Cards__c, OwnerId, Owner.ManagerId,
					Probability, INN_Opp__c, Owner.Id, Owner.Name, Owner.UserRole.Name,
					StageName, Day_transfer__c, CloseDate
		    FROM 	Opportunity
		    LIMIT 	10000
		];
		E2E_RU_Internal_Notifications.transferToE2E(listOpp);
	}

	@isTest
	static void abandonmentScenarioQueueable () {
		List<Opportunity> listOpp = [
				SELECT 	E2E_Sub_Status__c,  Name, Number_of_Cards__c, OwnerId, Owner.ManagerId,
						Probability, INN_Opp__c, Owner.Id, Owner.Name, Owner.UserRole.Name,
						StageName, Day_transfer__c, CloseDate
				FROM 	Opportunity
				LIMIT 	1
		];

		Map<Id, E2EFormData__c> opportunityFormDataRelateMap = new Map<Id, E2EFormData__c>();
		E2EFormData__c formData = new E2EFormData__c(E2E_Manual_Entry__c = true);
		opportunityFormDataRelateMap.put(listOpp[0].Id, formData);

		E2E_RU_Internal_Notifications.abandonmentScenarioQueueable(listOpp, opportunityFormDataRelateMap);
	}

	@isTest
	static void duplicateLeadProcess () {
		List<Lead> listLeads = [
		    SELECT OwnerId, Owner.Type, Owner.Name, Name, INN__c, Phone
		    FROM Lead
		    LIMIT 1
		];

		E2E_RU_Internal_Notifications.duplicateLeadProcess(listLeads);
	}

	@isTest
	static void transferToInbound () {
		Account acc = E2EFormRuTestUtils.createDefaultAccount();
		INSERT acc;

		String oppId = [SELECT Id FROM Opportunity LIMIT 1].Id;

		Opportunity opp = E2EFormRuTestUtils.createDefaultOpportunity();
		opp.Probability = 10;
		opp.AccountId = acc.Id;
		INSERT opp;

		acc = [
		    SELECT (SELECT 	E2E_Sub_Status__c,  Name, Number_of_Cards__c, OwnerId, Owner.ManagerId,
							Probability, INN_Opp__c, Owner.Id, Owner.Name, Owner.UserRole.Name,
							StageName, Day_transfer__c, CloseDate
					FROM 	Opportunities),
					INN__c, Name
		    FROM Account
			WHERE id = :acc.Id
		];

		E2E_RU_Internal_Notifications.transferToInbound(acc, oppId);
	}

	@isTest
	static void transferToKO () {
		Account acc = E2EFormRuTestUtils.createDefaultAccount();
		INSERT acc;

		Contact cont = E2EFormRuTestUtils.createDefaultContact();
 		cont.MobilePhone = 'test phone';
 		cont.Email = 'test@test.com';

		String oppId = [SELECT Id FROM Opportunity LIMIT 1].Id;

		Opportunity opp = E2EFormRuTestUtils.createDefaultOpportunity();
		opp.Probability = 10;
		opp.AccountId = acc.Id;
		INSERT opp;

		acc = [
				SELECT (SELECT 	E2E_Sub_Status__c,  Name, Number_of_Cards__c, OwnerId, Owner.ManagerId,
								Probability, INN_Opp__c, Owner.Id, Owner.Name, Owner.UserRole.Name,
								StageName, Day_transfer__c, CloseDate
				FROM 	Opportunities),
						INN__c, Name
				FROM Account
				WHERE id = :acc.Id
		];

		E2E_RU_Internal_Notifications.transferToKO(acc, oppId, true, cont, acc);
		E2E_RU_Internal_Notifications.transferToKO(acc, oppId, false, cont, acc);
	}

	@isTest
	static void transferToService () {
		Account acc = E2EFormRuTestUtils.createDefaultAccount();
		INSERT acc;

		String oppId = [SELECT Id FROM Opportunity LIMIT 1].Id;

		Opportunity opp = E2EFormRuTestUtils.createDefaultOpportunity();
		opp.Probability = 10;
		opp.AccountId = acc.Id;
		INSERT opp;

		acc = [
				SELECT (SELECT 	E2E_Sub_Status__c,  Name, Number_of_Cards__c, OwnerId, Owner.ManagerId,
								Probability, INN_Opp__c, Owner.Id, Owner.Name, Owner.UserRole.Name,
								StageName, Day_transfer__c, CloseDate
				FROM 	Opportunities),
						INN__c, Name
				FROM Account
				WHERE id = :acc.Id
		];

		E2E_RU_Internal_Notifications.transferToService(acc, oppId);
	}
}