default/objects/Account/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Идентификационный номер налогоплательщика.
            Должен содержать только цифры:
            12 цифр - ИП;
            10 цифр - юр. лицо.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Account/fields/Rating_FS__c.field-meta.xml
<CustomField>
    <fullName>Rating_FS__c</fullName>
    <label>Rating_FS</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

default/objects/Account/recordTypes/Russian.recordType-meta.xml
<RecordType>
    <fullName>Russian</fullName>
    <active>true</active>
    <label>Russian</label>
</RecordType>

default/objects/CF_Settings__c/CF_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for scoring and black list services for manual sales</description>
    <label>CF Settings</label>
</CustomObject>

default/objects/CF_Settings__c/fields/Check_on_opportunity_create__c.field-meta.xml
<CustomField>
    <fullName>Check_on_opportunity_create__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks record when it is created</description>
    <inlineHelpText>Checks record when it is created</inlineHelpText>
    <label>Check on opportunity create</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CF_Settings__c/fields/Check_on_opportunity_update__c.field-meta.xml
<CustomField>
    <fullName>Check_on_opportunity_update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks record when it is updated</description>
    <inlineHelpText>Checks record when it is updated</inlineHelpText>
    <label>Check on opportunity update</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Lead/fields/Date_of_First_Contact_Inbound_Outbound__c.field-meta.xml
<CustomField>
    <fullName>Date_of_First_Contact_Inbound_Outbound__c</fullName>
    <description>Date first contact was made with Lead</description>
    <inlineHelpText>Date first contact was made with Lead whether inbound or outbound.</inlineHelpText>
    <label>Date of First Contact: Inbound/Outbound</label>
    <type>Date</type>
</CustomField>

default/objects/Lead/fields/First_Contact_Inbound_Outbound__c.field-meta.xml
<CustomField>
    <fullName>First_Contact_Inbound_Outbound__c</fullName>
    <description>Was first contact inbound from the Lead, or outbound by the sales team?  This is particularly helpful to know when the Lead was included in a marketing campaign.</description>
    <inlineHelpText>Was first contact inbound from the Lead, or outbound by the sales team?  This is particularly helpful to know when the Lead was included in a marketing campaign.</inlineHelpText>
    <label>First Contact: Inbound/Outbound</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Inbound Fax</fullName>
            </value>
            <value>
                <fullName>Inbound Mail</fullName>
            </value>
            <value>
                <fullName>Inbound Website</fullName>
            </value>
            <value>
                <fullName>Onsite Visit</fullName>
            </value>
            <value>
                <fullName>Не контактировали</fullName>
            </value>
            <value>
                <fullName>Inbound SMS</fullName>
            </value>
            <value>
                <fullName>Outbound e-mail</fullName>
            </value>
            <value>
                <fullName>Inbound Banner Ads</fullName>
            </value>
            <value>
                <fullName>Direct App - Fax</fullName>
            </value>
            <value>
                <fullName>Direct App - Web</fullName>
            </value>
            <value>
                <fullName>citypoint</fullName>
            </value>
            <value>
                <fullName>omnicomm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Tax identification number
        Must contain only numbers:
        Length 12 symbols for PE;
        Length 10 symbols for legal person.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Source_of_Lead__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Lead__c</fullName>
    <label>Source of Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Актуализированная БД</fullName>
            </value>
            <value>
                <fullName>Прочая БД</fullName>
                <default>true</default>
                <label>Прочая БД</label>
            </value>
            <value>
                <fullName>Выставка</fullName>
            </value>
            <value>
                <fullName>Найден в Интернете</fullName>
            </value>
            <value>
                <fullName>Реклама Клиента</fullName>
            </value>
            <value>
                <fullName>Рекомендация</fullName>
            </value>
            <value>
                <fullName>Партнерская Программа</fullName>
            </value>
            <value>
                <fullName>Business card</fullName>
            </value>
            <value>
                <fullName>Почтовая рассылка</fullName>
            </value>
            <value>
                <fullName>Реклама на АЗС</fullName>
            </value>
            <value>
                <fullName>Email рассылка</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.ru</fullName>
            </value>
            <value>
                <fullName>Поисковая Система</fullName>
            </value>
            <value>
                <fullName>Реклама в СМИ</fullName>
            </value>
            <value>
                <fullName>Акция Рекомендация</fullName>
            </value>
            <value>
                <fullName>Интернет Источники</fullName>
            </value>
            <value>
                <fullName>Сайт fuel.veb-leasing.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.kz</fullName>
            </value>
            <value>
                <fullName>Petrolcards.ru - АГГРЕГАТОР</fullName>
            </value>
            <value>
                <fullName>АЗС Заявка Shell</fullName>
            </value>
            <value>
                <fullName>Facebook_Lotos</fullName>
            </value>
            <value>
                <fullName>Facebook_CCS</fullName>
            </value>
            <value>
                <fullName>Сайт gpc-store.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Shell Card.ru</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Date_of_First_Contact_Inbound_Outbound__c.field-meta.xml
<CustomField>
    <fullName>Date_of_First_Contact_Inbound_Outbound__c</fullName>
    <label>Date of First Contact: Inbound/Outbound</label>
    <type>Date</type>
</CustomField>

default/objects/Opportunity/fields/First_Contact_Inbound_Outbound__c.field-meta.xml
<CustomField>
    <fullName>First_Contact_Inbound_Outbound__c</fullName>
    <label>CCS_First Contact: Inbound/Outbound</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Inbound Mail</fullName>
            </value>
            <value>
                <fullName>Inbound Website</fullName>
            </value>
            <value>
                <fullName>Outbound e-mail</fullName>
            </value>
            <value>
                <fullName>Incoming SMS</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Last_Owner_Change_Date_RUS__c.field-meta.xml
<CustomField>
    <fullName>Last_Owner_Change_Date_RUS__c</fullName>
    <label>Last Owner Change Date RUS</label>
    <type>DateTime</type>
</CustomField>

default/classes/FieldSalesRouteYandexCtrlTest.cls
@isTest
public with sharing class FieldSalesRouteYandexCtrlTest {

    @isTest
    public static void testMethodInitOpportunity() {
        createCustomSettings();

        List<User> userList = [
                SELECT id
                FROM User
                WHERE Profile.Name = 'Russian Sales Manager'
                AND IsActive = true
                AND UserRole.Name != 'PPR Key Accounts Manager' AND UserRole.Name != 'PPR Teamleader KAM'
                LIMIT 1
        ];
        Id userId = userList.get(0).Id;

        String RecordTypeOpp = [select id from recordtype where name = 'Russian Sales' and SobjectType = 'Opportunity'].id;
        String RecordTypeAcc = [select id from recordtype where name = 'Russian' and SobjectType = 'Account'].id;

        Account account = new Account(Name = 'test12345678910987654321', BillingPostalCode = '123', Rating_FS__c = 1000000,
                Phone = '+71234567890', BillingStreet = 'Санкт-Петербург ул. Пестеля, 15', INN__C = '1234567899999', OwnerId = userId,
                RecordTypeId = RecordTypeAcc);
        insert account;

        Opportunity opportunity = new Opportunity(Name = 'test12345678910987654321', StageName = 'Отказ', Probability = 0, CloseDate = date.today(),
                Last_Owner_Change_Date_RUS__c = system.now().addDays(-50), OwnerId = userId,
                AccountId = account.id, RecordTypeId = RecordTypeOpp);
        insert opportunity;

        PageReference pageRef = Page.FieldSalesRouteYandex;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', opportunity.Id);
        FieldSalesRouteYandexCtrl controller = new FieldSalesRouteYandexCtrl();
        controller.init();
        system.assertNotEquals(controller.address, null);
        system.assertNotEquals(controller.territory, null);
    }

    @isTest
    public static void testMethodInitLead() {
        List<User> userList = [
                SELECT id
                FROM User
                WHERE Profile.Name = 'Russian Sales Manager'
                AND IsActive = true
                AND UserRole.Name != 'PPR Key Accounts Manager' AND UserRole.Name != 'PPR Teamleader KAM'
                LIMIT 1
        ];
        Id userId = userList.get(0).Id;

        String RecordTypeOpp = [select id from recordtype where name = 'Russian Sales' and SobjectType = 'Opportunity'].id;
        String RecordTypeAcc = [select id from recordtype where name = 'Russian' and SobjectType = 'Account'].id;
        String RecordTypeLead = [select id from recordtype where name = 'Russian Sales' and SobjectType = 'Lead'].id;

        Lead lead = new Lead(Phone = '+71234567891', LastName = 'test12345678910987654321', Street = 'Санкт-Петербург ул. Пестеля, 15',
                Company = 'test12345678910987654321', Email = 'Email12345678910@gggmail.ru', Salutation = 'Herr',
                Date_of_First_Contact_Inbound_Outbound__c = date.today(), Country = 'Russia', INN__C = '1234567899999',
                First_Contact_Inbound_Outbound__c = 'Inbound Call', Source_of_lead__c = 'Сайт Petrolplus.ru',
                RecordTypeId = RecordTypeLead, ownerid = userId);
        insert lead;

        PageReference pageRef = Page.FieldSalesRouteYandex;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', lead.Id);
        FieldSalesRouteYandexCtrl controller = new FieldSalesRouteYandexCtrl();
        controller.init();
        system.assertNotEquals(controller.address, null);
        system.assertNotEquals(controller.territory, null);
    }

    private static void createCustomSettings() {
        CF_Settings__c cf_settings = new CF_Settings__c();
        cf_settings.Name = 'Russia';
        cf_settings.Check_on_opportunity_create__c = false;
        cf_settings.Check_on_opportunity_update__c = false;
        insert cf_settings;
    }
}