default/objects/Account/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Идентификационный номер налогоплательщика.
            Должен содержать только цифры:
            12 цифр - ИП;
            10 цифр - юр. лицо.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Credit_Factory_Report__c/Credit_Factory_Report__c.object-meta.xml
<CustomObject>
    <label>Credit Factory Report</label>
    <nameField>
        <label>Credit Factory Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Factory Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Opportunity/fields/Promo_campaign__c.field-meta.xml
<CustomField>
    <fullName>Promo_campaign__c</fullName>
    <label>Promo campaign</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5Г01</fullName>
            </value>
            <value>
                <fullName>9Е06</fullName>
            </value>
            <value>
                <fullName>9Е07</fullName>
            </value>
            <value>
                <fullName>9Е08</fullName>
            </value>
            <value>
                <fullName>9Е09</fullName>
            </value>
            <value>
                <fullName>9Е10</fullName>
            </value>
            <value>
                <fullName>9Е11</fullName>
            </value>
            <value>
                <fullName>9Е12</fullName>
            </value>
            <value>
                <fullName>9Е13</fullName>
            </value>
            <value>
                <fullName>9Е14</fullName>
            </value>
            <value>
                <fullName>9Е19</fullName>
            </value>
            <value>
                <fullName>9Е20</fullName>
            </value>
            <value>
                <fullName>9Е21</fullName>
            </value>
            <value>
                <fullName>PIU5</fullName>
            </value>
            <value>
                <fullName>9Е22</fullName>
            </value>
            <value>
                <fullName>9Е23</fullName>
            </value>
            <value>
                <fullName>9Е24</fullName>
            </value>
            <value>
                <fullName>9Е25</fullName>
            </value>
            <value>
                <fullName>Winback_1</fullName>
            </value>
            <value>
                <fullName>Winback_2</fullName>
            </value>
            <value>
                <fullName>Winback_3</fullName>
            </value>
            <value>
                <fullName>Winback_4</fullName>
            </value>
            <value>
                <fullName>Winback_5</fullName>
            </value>
            <value>
                <fullName>Winback_6</fullName>
            </value>
            <value>
                <fullName>Winback_7</fullName>
            </value>
            <value>
                <fullName>Winback_8</fullName>
            </value>
            <value>
                <fullName>Winback_9</fullName>
            </value>
            <value>
                <fullName>Winback_10</fullName>
            </value>
            <value>
                <fullName>Winback_11</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/OrganizationRequisiteDataManagerTest.cls
@IsTest
public with sharing class OrganizationRequisiteDataManagerTest {
    private final static Account account;
    private final static Opportunity opportunity;
    private final static Contact contact;
    private final static OpportunityContactRole opportunityContactRole;
    private final static Credit_Factory_Report__c creditFactoryReport;

    static {
        account = OrganizationRequisiteTestDataFactory.createAccount('1111111111', 'test', 231111223);
        insert account;

        opportunity = OrganizationRequisiteTestDataFactory.createOpportunity(account);
        insert opportunity;

        contact = OrganizationRequisiteTestDataFactory.createContact(account);
        insert contact;

        opportunityContactRole = OrganizationRequisiteTestDataFactory.createOpportunityContactRole(contact, opportunity);
        insert opportunityContactRole;

        creditFactoryReport = CFTestDataFactory.createCreditFactoryReport(account, opportunity);
        insert creditFactoryReport;
    }

    @IsTest
    public static void findOpportunityByIdTest() {
        List<Opportunity> opp = OrganizationRequisiteDataManager.findOpportunityById(opportunity.Id);
        List<Opportunity> opport = OrganizationRequisiteDataManager.findOpportunityById(null);
        System.assertEquals(0, opport.size());
        System.assertEquals(1, opp.size());
        System.assertEquals(opp[0].Id, opportunity.Id);
        System.assertEquals(opportunity.Promo_campaign__c, opp[0].Promo_campaign__c);
    }

    @IsTest
    public static void findAccountByIdTest() {
        List<Account> acc = OrganizationRequisiteDataManager.findAccountById(opportunity.AccountId);
        List<Account> acct = OrganizationRequisiteDataManager.findAccountById(null);
        System.assertEquals(0, acct.size());
        System.assertEquals(1, acc.size());
        System.assertEquals(acc[0].Id, opportunity.AccountId);
        System.assertEquals(account.INN__c, acc[0].INN__c);
    }

    @IsTest
    public static void findOpportunityContactRolesByOpportunityIdTest() {
        List <OpportunityContactRole> contactRole = OrganizationRequisiteDataManager.findOpportunityContactRolesByOpportunityId(opportunity.Id);
        List <OpportunityContactRole> contRole = OrganizationRequisiteDataManager.findOpportunityContactRolesByOpportunityId(null);
        System.assertEquals(0, contRole.size());
        System.assertEquals(2, contactRole.size());
        System.assertEquals(contact.Title, contactRole[0].Contact.Title);
        System.assertEquals(contact.Email, contactRole[0].Contact.Email);
    }

    @IsTest
    private static void findCreditFactoryReportsByOppIdTest() {
        List <Credit_Factory_Report__c> creditFactoryReports = OrganizationRequisiteDataManager.findCreditFactoryReportsByOppId(opportunity.Id);
        List <Credit_Factory_Report__c> creditFactoryReportsNegative = OrganizationRequisiteDataManager.findCreditFactoryReportsByOppId(null);
        System.assertEquals(0, creditFactoryReportsNegative.size());
        System.assertEquals(1, creditFactoryReports.size());
        System.assertEquals(creditFactoryReports[0].Id, creditFactoryReport.Id);
    }
}