default/objects/Account/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Идентификационный номер налогоплательщика.
            Должен содержать только цифры:
            12 цифр - ИП;
            10 цифр - юр. лицо.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Account/fields/Rating_FS__c.field-meta.xml
<CustomField>
    <fullName>Rating_FS__c</fullName>
    <label>Rating_FS</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

default/objects/Account/recordTypes/Russian.recordType-meta.xml
<RecordType>
    <fullName>Russian</fullName>
    <active>true</active>
    <label>Russian</label>
</RecordType>

default/objects/CF_Settings__c/CF_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for scoring and black list services for manual sales</description>
    <label>CF Settings</label>
</CustomObject>

default/objects/CF_Settings__c/fields/Check_on_opportunity_create__c.field-meta.xml
<CustomField>
    <fullName>Check_on_opportunity_create__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks record when it is created</description>
    <inlineHelpText>Checks record when it is created</inlineHelpText>
    <label>Check on opportunity create</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CF_Settings__c/fields/Check_on_opportunity_update__c.field-meta.xml
<CustomField>
    <fullName>Check_on_opportunity_update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks record when it is updated</description>
    <inlineHelpText>Checks record when it is updated</inlineHelpText>
    <label>Check on opportunity update</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Lead/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Tax identification number
        Must contain only numbers:
        Length 12 symbols for PE;
        Length 10 symbols for legal person.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Last_Owner_Change_Date_RUS__c.field-meta.xml
<CustomField>
    <fullName>Last_Owner_Change_Date_RUS__c</fullName>
    <label>Last Owner Change Date RUS</label>
    <type>DateTime</type>
</CustomField>

default/classes/FieldSalesDeduplicationBatchTest.cls
@IsTest
private class FieldSalesDeduplicationBatchTest {

    @isTest
    static void testBatchMethod() {
        createCustomSettings();
        String recordTypeOpp = [select id from recordtype where name = 'Russian Sales' and SobjectType = 'Opportunity' LIMIT 1].id;
        String recordTypeAcc = [select id from recordtype where name = 'Russian' and SobjectType = 'Account' LIMIT 1].id;
        String recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Russian Sales' AND sObjectType = 'Lead' LIMIT 1].id;

        Lead lead1 = new Lead(LastName = 'test', Company = 'test', Country = 'Russia', Email = 'test@test.com', RecordTypeId = recordTypeLead, Status = 'Open', Inn__c = '1234567890');
        insert lead1;

        Account account = new Account(Name = 'test12345678910987654321', BillingPostalCode = '123', Rating_FS__c = 50,
                INN__C = '1234567890', RecordTypeId = recordTypeAcc);
        insert account;
        Opportunity opportunity = new Opportunity(Name = 'test12345678910987654321', StageName = 'Отказ', Probability = 0, CloseDate = date.today(),
                Last_Owner_Change_Date_RUS__c = system.now().addDays(-50),
                AccountId = account.id, RecordTypeId = recordTypeOpp);
        insert opportunity;

        Test.startTest();
        Database.executeBatch(new FieldSalesDeduplicationBatch(null));
        Test.stopTest();
    }

    @isTest
    static void testBatchMethod2() {
        String recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Russian Sales' AND sObjectType = 'Lead' LIMIT 1].id;

        Lead lead2 = new Lead(LastName = 'test2', Company = 'test2', Country = 'Russia', Email = 'test@test.com', RecordTypeId = recordTypeLead, Status = 'Open', Inn__c = '1234567891');
        insert lead2;

        Lead lead3 = new Lead(LastName = 'test3', Company = 'test3', Country = 'Russia', Email = 'test@test.com', RecordTypeId = recordTypeLead, Status = 'Open', Inn__c = '1234567891');
        insert lead3;

        Test.startTest();
        Database.executeBatch(new FieldSalesDeduplicationBatch(1));
        Test.stopTest();
    }

    private static void createCustomSettings() {
        CF_Settings__c cf_settings = new CF_Settings__c();
        cf_settings.Name = 'Russia';
        cf_settings.Check_on_opportunity_create__c = false;
        cf_settings.Check_on_opportunity_update__c = false;
        insert cf_settings;
    }
}