default/objects/Account/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Идентификационный номер налогоплательщика.
            Должен содержать только цифры:
            12 цифр - ИП;
            10 цифр - юр. лицо.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Account/recordTypes/Russian.recordType-meta.xml
<RecordType>
    <fullName>Russian</fullName>
    <active>true</active>
    <label>Russian</label>
</RecordType>

default/objects/CF_Settings__c/CF_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for scoring and black list services for manual sales</description>
    <label>CF Settings</label>
</CustomObject>

default/objects/CF_Settings__c/fields/Check_on_opportunity_create__c.field-meta.xml
<CustomField>
    <fullName>Check_on_opportunity_create__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks record when it is created</description>
    <inlineHelpText>Checks record when it is created</inlineHelpText>
    <label>Check on opportunity create</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CF_Settings__c/fields/Check_on_opportunity_update__c.field-meta.xml
<CustomField>
    <fullName>Check_on_opportunity_update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks record when it is updated</description>
    <inlineHelpText>Checks record when it is updated</inlineHelpText>
    <label>Check on opportunity update</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Lead/fields/Area_Traveled__c.field-meta.xml
<CustomField>
    <fullName>Area_Traveled__c</fullName>
    <description>Where does your fleet travel?</description>
    <inlineHelpText>Where does your fleet travel?</inlineHelpText>
    <label>Area Traveled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Statewide</fullName>
            </value>
            <value>
                <fullName>Regional</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Date_of_First_Contact_Inbound_Outbound__c.field-meta.xml
<CustomField>
    <fullName>Date_of_First_Contact_Inbound_Outbound__c</fullName>
    <description>Date first contact was made with Lead</description>
    <inlineHelpText>Date first contact was made with Lead whether inbound or outbound.</inlineHelpText>
    <label>Date of First Contact: Inbound/Outbound</label>
    <type>Date</type>
</CustomField>

default/objects/Lead/fields/First_Contact_Inbound_Outbound__c.field-meta.xml
<CustomField>
    <fullName>First_Contact_Inbound_Outbound__c</fullName>
    <description>Was first contact inbound from the Lead, or outbound by the sales team?  This is particularly helpful to know when the Lead was included in a marketing campaign.</description>
    <inlineHelpText>Was first contact inbound from the Lead, or outbound by the sales team?  This is particularly helpful to know when the Lead was included in a marketing campaign.</inlineHelpText>
    <label>First Contact: Inbound/Outbound</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Inbound Fax</fullName>
            </value>
            <value>
                <fullName>Inbound Mail</fullName>
            </value>
            <value>
                <fullName>Inbound Website</fullName>
            </value>
            <value>
                <fullName>Onsite Visit</fullName>
            </value>
            <value>
                <fullName>Не контактировали</fullName>
            </value>
            <value>
                <fullName>Inbound SMS</fullName>
            </value>
            <value>
                <fullName>Outbound e-mail</fullName>
            </value>
            <value>
                <fullName>Inbound Banner Ads</fullName>
            </value>
            <value>
                <fullName>Direct App - Fax</fullName>
            </value>
            <value>
                <fullName>Direct App - Web</fullName>
            </value>
            <value>
                <fullName>citypoint</fullName>
            </value>
            <value>
                <fullName>omnicomm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Tax identification number
        Must contain only numbers:
        Length 12 symbols for PE;
        Length 10 symbols for legal person.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Source_of_Lead__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Lead__c</fullName>
    <label>Source of Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Актуализированная БД</fullName>
            </value>
            <value>
                <fullName>Прочая БД</fullName>
                <default>true</default>
                <label>Прочая БД</label>
            </value>
            <value>
                <fullName>Выставка</fullName>
            </value>
            <value>
                <fullName>Найден в Интернете</fullName>
            </value>
            <value>
                <fullName>Реклама Клиента</fullName>
            </value>
            <value>
                <fullName>Рекомендация</fullName>
            </value>
            <value>
                <fullName>Партнерская Программа</fullName>
            </value>
            <value>
                <fullName>Business card</fullName>
            </value>
            <value>
                <fullName>Почтовая рассылка</fullName>
            </value>
            <value>
                <fullName>Реклама на АЗС</fullName>
            </value>
            <value>
                <fullName>Email рассылка</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.ru</fullName>
            </value>
            <value>
                <fullName>Поисковая Система</fullName>
            </value>
            <value>
                <fullName>Реклама в СМИ</fullName>
            </value>
            <value>
                <fullName>Акция Рекомендация</fullName>
            </value>
            <value>
                <fullName>Интернет Источники</fullName>
            </value>
            <value>
                <fullName>Сайт fuel.veb-leasing.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.kz</fullName>
            </value>
            <value>
                <fullName>Petrolcards.ru - АГГРЕГАТОР</fullName>
            </value>
            <value>
                <fullName>АЗС Заявка Shell</fullName>
            </value>
            <value>
                <fullName>Facebook_Lotos</fullName>
            </value>
            <value>
                <fullName>Facebook_CCS</fullName>
            </value>
            <value>
                <fullName>Сайт gpc-store.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Shell Card.ru</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Area_Traveled__c.field-meta.xml
<CustomField>
    <fullName>Area_Traveled__c</fullName>
    <description>Where does your fleet travel?</description>
    <inlineHelpText>Where does your fleet travel?</inlineHelpText>
    <label>Geography of trips</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Statewide</fullName>
            </value>
            <value>
                <fullName>Regional</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Date_of_First_Contact_Inbound_Outbound__c.field-meta.xml
<CustomField>
    <fullName>Date_of_First_Contact_Inbound_Outbound__c</fullName>
    <label>Date of First Contact: Inbound/Outbound</label>
    <type>Date</type>
</CustomField>

default/objects/Opportunity/fields/First_Contact_Inbound_Outbound__c.field-meta.xml
<CustomField>
    <fullName>First_Contact_Inbound_Outbound__c</fullName>
    <label>CCS_First Contact: Inbound/Outbound</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Inbound Mail</fullName>
            </value>
            <value>
                <fullName>Inbound Website</fullName>
            </value>
            <value>
                <fullName>Outbound e-mail</fullName>
            </value>
            <value>
                <fullName>Incoming SMS</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <label>Insurance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Didn't offer</fullName>
            </value>
            <value>
                <fullName>Agree</fullName>
            </value>
            <value>
                <fullName>Agree, but didn't send the documents</fullName>
            </value>
            <value>
                <fullName>A request with data was received</fullName>
            </value>
            <value>
                <fullName>The current policy expires in more than 2 months</fullName>
            </value>
            <value>
                <fullName>Refusal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Number_of_cars__c.field-meta.xml
<CustomField>
    <fullName>Number_of_cars__c</fullName>
    <inlineHelpText>should not be equal to '0'</inlineHelpText>
    <label>Number of cars</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Primary_Fueling_Method__c.field-meta.xml
<CustomField>
    <fullName>Primary_Fueling_Method__c</fullName>
    <description>Primary Fueling Method</description>
    <inlineHelpText>Primary Fueling Method</inlineHelpText>
    <label>Primary Fueling Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other Issuer Card</fullName>
            </value>
            <value>
                <fullName>Bank Card</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Coupons</fullName>
            </value>
            <value>
                <fullName>House Account</fullName>
            </value>
            <value>
                <fullName>Leasing Company Card</fullName>
            </value>
            <value>
                <fullName>On-Site Tanks</fullName>
            </value>
            <value>
                <fullName>Universal Fleet Card</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Projected_Liters_weekly__c.field-meta.xml
<CustomField>
    <fullName>Projected_Liters_weekly__c</fullName>
    <description>FORMULA FIELD:  Number of liters projected to be fueled per week for this prospect.  Calculated as the number of vehicles times the estimated liters per vehicle per week.
Russia uses liters projected per monthly.</description>
    <inlineHelpText>should not be equal to '0'</inlineHelpText>
    <label>Projected Liters (weekly)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/classes/FindDuplicatesRuControllerTest.cls
@isTest
public class FindDuplicatesRuControllerTest {

    @isTest
    public static void searchTest() {
        createCustomSettings();
        String RecordTypeLead = [select id from recordtype where name = 'Russian Sales' and SobjectType = 'Lead'].id;
        String recordTypeOppId = [select id from recordtype where name = 'Russian Sales' and SobjectType = 'Opportunity'].id;
        String RecordTypeAcc = [select id from recordtype where name = 'Russian' and SobjectType = 'Account'].id;
        String RWL;
        if ([select id from group where name = 'Russian Web Leads'].size() == 1)
            RWL = [select id from group where name = 'Russian Web Leads'].id; else RWL = '0BLANKIDBLANKID';

        Lead lead = new Lead(Phone = '+71234567891', LastName = 'test12345678910987654321',
                Company = 'test12345678910987654321', Email = 'Email12345678910@gggmail.ru', Salutation = 'Herr',
                Date_of_First_Contact_Inbound_Outbound__c = date.today(), Country = 'Russia', INN__C = '1234567899999',
                First_Contact_Inbound_Outbound__c = 'Inbound Call', Source_of_lead__c = 'Сайт Petrolplus.ru',
                RecordTypeId = RecordTypeLead, ownerid = RWL);
        insert lead;
        Account accountt = new Account(Name = 'test12345678910987654321', BillingPostalCode = '123', Phone = '+71234567891',
                INN__C = '1234567899999',
                RecordTypeId = RecordTypeAcc);
        insert accountt;

        Contact contt = new Contact(LastName = 'testcontact12345', Phone = '+71234567890', Email = 'test@testcont.ru', AccountId = accountt.Id);
        insert contt;

        Opportunity opportunity = createOpportunity(accountt, recordTypeOppId);
        insert opportunity;

        Ru_Admin_Approver__c approver = new Ru_Admin_Approver__c(Name = 'test@test.com');
        insert approver;
        FindDuplicatesRuController contr = new FindDuplicatesRuController();

        List<String> fixedSearchResults= new List<String>{ accountt.Id, opportunity.Id, lead.Id };
        Test.setFixedSearchResults(fixedSearchResults);

        ApexPages.currentPage().getParameters().put('id', opportunity.Id);
        FindDuplicatesRuController controller = new FindDuplicatesRuController();
        controller.isCompanySelected = true;
        controller.init();
        controller.searchPage();

        System.assertEquals(controller.matchingAccounts.size(), 1);
        System.assertEquals(controller.matchingOpportunities.size(), 1);

    }
    @isTest
    public static void searchTest2() {
        createCustomSettings();
        String RecordTypeLead = [select id from recordtype where name = 'Russian Sales' and SobjectType = 'Lead'].id;
        String recordTypeOppId = [select id from recordtype where name = 'Russian Sales' and SobjectType = 'Opportunity'].id;
        String RecordTypeAcc = [select id from recordtype where name = 'Russian' and SobjectType = 'Account'].id;

        Lead lead = new Lead(Phone = '+71098765432', LastName = 'pro567verkaAAAAAAA567', Company = 'pro567verkaAAAAAAA567',
                Email = 'mail123456@gmail.com', Salutation = 'Herr', INN__C = '1234567888888',
                Date_of_First_Contact_Inbound_Outbound__c = date.today(), Country = 'Russia',
                First_Contact_Inbound_Outbound__c = 'Inbound Call', Source_of_lead__c = 'Сайт Petrolplus.ru',
                RecordTypeId = RecordTypeLead);
        insert lead;
        Account accountt = new Account(Name = 'pro567verkaAAAAAAA567', BillingPostalCode = '123', Phone = '+71098765432',
                INN__C = '1234567888888',
                RecordTypeiD = RecordTypeAcc);
        insert accountt;

        Opportunity opportunity = createOpportunity(accountt, recordTypeOppId);
        insert opportunity;
        Test.startTest();
        Test.stopTest();

        List<String> fixedSearchResults= new List<String>{ accountt.Id, opportunity.Id, lead.Id };
        Test.setFixedSearchResults(fixedSearchResults);

        ApexPages.currentPage().getParameters().put('id', lead.Id);
        FindDuplicatesRuController controller = new FindDuplicatesRuController();
        controller.isCompanySelected = true;
        controller.init();
        controller.searchPage();

        System.assertEquals(controller.matchingAccounts.size(), 1);
        System.assertEquals(controller.matchingOpportunities.size(), 1);
    }

    @IsTest
    public static void searchForE2EOpportunityTest() {
        createCustomSettings();
        String RecordTypeLead = [select id from recordtype where name = 'Russian Sales' and SobjectType = 'Lead'].id;
        String recordTypeOppId = [select id from recordtype where name = 'Russian Sales' and SobjectType = 'Opportunity'].id;
        String RecordTypeAcc = [select id from recordtype where name = 'Russian' and SobjectType = 'Account'].id;
        String RWL;
        if ([select id from group where name = 'Russian Web Leads'].size() == 1)
            RWL = [select id from group where name = 'Russian Web Leads'].id; else
                RWL = '0BLANKIDBLANKID';

        Lead lead = new Lead(Phone = '+71234567891', LastName = 'test12345678910987654321',
                Company = 'test12345678910987654321', Email = 'Email12345678910@gggmail.ru', Salutation = 'Herr',
                Date_of_First_Contact_Inbound_Outbound__c = Date.today(), Country = 'Russia', INN__C = '1234567899999',
                First_Contact_Inbound_Outbound__c = 'Inbound Call', Source_of_lead__c = 'E2E Form RU',
                RecordTypeId = RecordTypeLead, ownerid = RWL);
        insert lead;
        Account accountt = new Account(Name = 'test12345678910987654321', BillingPostalCode = '123', Phone = '+71234567891',
                INN__C = '1234567899999',
                RecordTypeId = RecordTypeAcc);
        insert accountt;

        Contact contt = new Contact(LastName = 'testcontact12345', Phone = '+71234567890', Email = 'test@testcont.ru', AccountId = accountt.Id);
        insert contt;

        Opportunity opportunity = createOpportunity(accountt, recordTypeOppId);
        insert opportunity;
        Ru_Admin_Approver__c approver = new Ru_Admin_Approver__c(Name = 'test@test.com');
        insert approver;
        FindDuplicatesRuController contr = new FindDuplicatesRuController();

        List<String> fixedSearchResults= new List<String>{ accountt.Id, opportunity.Id, lead.Id };
        Test.setFixedSearchResults(fixedSearchResults);

        ApexPages.currentPage().getParameters().put('id', opportunity.Id);
        FindDuplicatesRuController controller = new FindDuplicatesRuController();
        controller.isCompanySelected = true;
        controller.init();
        controller.searchPage();

        System.assertEquals(controller.matchingAccounts.size(), 1);
        System.assertEquals(controller.matchingOpportunities.size(), 1);
    }

    private static void createCustomSettings() {
        CF_Settings__c cf_settings = new CF_Settings__c();
        cf_settings.Name = 'Russia';
        cf_settings.Check_on_opportunity_create__c = false;
        cf_settings.Check_on_opportunity_update__c = false;
        insert cf_settings;
    }

    public static Opportunity createOpportunity(Account account, Id recordTypeId) {
        Opportunity opportunity = new Opportunity(
                Name = 'TEST',
                CloseDate = Date.today()+1,
                CreatedDate = Date.today()-1,
                AccountId = account.Id,
                StageName = GlobalUtils.getOpportunityStageName(GlobalUtils.OpportunityStage.Qualified_Lead),
                Projected_Liters_weekly__c = 1000,
                Primary_Fueling_Method__c = 'Cash',
                Insurance__c = 'Agree',
                Area_Traveled__c = 'Local',
                Number_of_cars__c = 10,
                Source_of_Lead_o__c = 'E2E Form RU',
                RecordTypeId = recordTypeId
        );
        return opportunity;
    }
}