default/objects/Account/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Идентификационный номер налогоплательщика.
            Должен содержать только цифры:
            12 цифр - ИП;
            10 цифр - юр. лицо.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Account/recordTypes/Russian.recordType-meta.xml
<RecordType>
    <fullName>Russian</fullName>
    <active>true</active>
    <label>Russian</label>
</RecordType>

default/objects/Lead/fields/Area_Traveled__c.field-meta.xml
<CustomField>
    <fullName>Area_Traveled__c</fullName>
    <description>Where does your fleet travel?</description>
    <inlineHelpText>Where does your fleet travel?</inlineHelpText>
    <label>Area Traveled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Statewide</fullName>
            </value>
            <value>
                <fullName>Regional</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Tax identification number
        Must contain only numbers:
        Length 12 symbols for PE;
        Length 10 symbols for legal person.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Most_Important_Feature__c.field-meta.xml
<CustomField>
    <fullName>Most_Important_Feature__c</fullName>
    <description>What is the most important feature in a fleet card for the prospect?</description>
    <inlineHelpText>What is the most important feature in a fleet card for the prospect?</inlineHelpText>
    <label>Most Important Feature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Controls</fullName>
            </value>
            <value>
                <fullName>Locations</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>Terms</fullName>
            </value>
            <value>
                <fullName>Volume Growth</fullName>
            </value>
            <value>
                <fullName>Eliminate AR Risk</fullName>
            </value>
            <value>
                <fullName>Simplicity</fullName>
            </value>
            <value>
                <fullName>Cost Savings</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Отсрочка, кредит</fullName>
            </value>
            <value>
                <fullName>Условия договора</fullName>
            </value>
            <value>
                <fullName>Конкретные АЗС</fullName>
            </value>
            <value>
                <fullName>Сервис</fullName>
            </value>
            <value>
                <fullName>НДС</fullName>
            </value>
            <value>
                <fullName>Тендер</fullName>
            </value>
            <value>
                <fullName>Рекомендация</fullName>
            </value>
            <value>
                <fullName>Налив</fullName>
            </value>
            <value>
                <fullName>ГАЗовые АЗС</fullName>
            </value>
            <value>
                <fullName>Бренд</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Naumen_Autocall_Case_UUID__c.field-meta.xml
<CustomField>
    <fullName>Naumen_Autocall_Case_UUID__c</fullName>
    <description>UUID of the autocall case in Naumen predictive dialing outbound project</description>
    <externalId>true</externalId>
    <label>Naumen Autocall Case UUID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Lead/fields/Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Vehicles__c</fullName>
    <description>Number of vehicles</description>
    <inlineHelpText>Number of vehicles</inlineHelpText>
    <label>Number of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Lead/fields/Source_of_Lead__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Lead__c</fullName>
    <label>Source of Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Актуализированная БД</fullName>
            </value>
            <value>
                <fullName>Прочая БД</fullName>
                <default>true</default>
                <label>Прочая БД</label>
            </value>
            <value>
                <fullName>Выставка</fullName>
            </value>
            <value>
                <fullName>Найден в Интернете</fullName>
            </value>
            <value>
                <fullName>Реклама Клиента</fullName>
            </value>
            <value>
                <fullName>Рекомендация</fullName>
            </value>
            <value>
                <fullName>Партнерская Программа</fullName>
            </value>
            <value>
                <fullName>Business card</fullName>
            </value>
            <value>
                <fullName>Почтовая рассылка</fullName>
            </value>
            <value>
                <fullName>Реклама на АЗС</fullName>
            </value>
            <value>
                <fullName>Email рассылка</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.ru</fullName>
            </value>
            <value>
                <fullName>Поисковая Система</fullName>
            </value>
            <value>
                <fullName>Реклама в СМИ</fullName>
            </value>
            <value>
                <fullName>Акция Рекомендация</fullName>
            </value>
            <value>
                <fullName>Интернет Источники</fullName>
            </value>
            <value>
                <fullName>Сайт fuel.veb-leasing.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.kz</fullName>
            </value>
            <value>
                <fullName>Petrolcards.ru - АГГРЕГАТОР</fullName>
            </value>
            <value>
                <fullName>АЗС Заявка Shell</fullName>
            </value>
            <value>
                <fullName>Facebook_Lotos</fullName>
            </value>
            <value>
                <fullName>Facebook_CCS</fullName>
            </value>
            <value>
                <fullName>Сайт gpc-store.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Shell Card.ru</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/The_region__c.field-meta.xml
<CustomField>
    <fullName>The_region__c</fullName>
    <label>The region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Area_Traveled__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>г. Санкт-Петербург</fullName>
            </value>
            <value>
                <fullName>г. Москва</fullName>
            </value>
            <value>
                <fullName>Республика Адыгея</fullName>
            </value>
            <value>
                <fullName>Ханты-Мансийский автономный округ - Югра</fullName>
            </value>
            <value>
                <fullName>Ямало-Ненецкий автономный округ</fullName>
            </value>
            <value>
                <fullName>Республика Башкортостан</fullName>
            </value>
            <value>
                <fullName>Республика Бурятия</fullName>
            </value>
            <value>
                <fullName>Республика Алтай</fullName>
            </value>
            <value>
                <fullName>Севастополь</fullName>
            </value>
            <value>
                <fullName>Республика Дагестан</fullName>
            </value>
            <value>
                <fullName>Республика Ингушетия</fullName>
            </value>
            <value>
                <fullName>Кабардино-Балкарская Республика</fullName>
            </value>
            <value>
                <fullName>Республика Калмыкия</fullName>
            </value>
            <value>
                <fullName>Республика Карачаево-Черкесия</fullName>
            </value>
            <value>
                <fullName>Республика Карелия</fullName>
            </value>
            <value>
                <fullName>Республика Коми</fullName>
            </value>
            <value>
                <fullName>Республика Марий Эл</fullName>
            </value>
            <value>
                <fullName>Республика Мордовия</fullName>
            </value>
            <value>
                <fullName>Республика Саха (Якутия)</fullName>
            </value>
            <value>
                <fullName>Республика Северная Осетия - Алания</fullName>
            </value>
            <value>
                <fullName>Республика Татарстан</fullName>
            </value>
            <value>
                <fullName>Республика Тыва</fullName>
            </value>
            <value>
                <fullName>Удмуртская Республика</fullName>
            </value>
            <value>
                <fullName>Республика Хакасия</fullName>
            </value>
            <value>
                <fullName>Чеченская республика</fullName>
            </value>
            <value>
                <fullName>Чувашская Республика</fullName>
            </value>
            <value>
                <fullName>Алтайский край</fullName>
            </value>
            <value>
                <fullName>Краснодарский край</fullName>
            </value>
            <value>
                <fullName>Красноярский край</fullName>
            </value>
            <value>
                <fullName>Приморский край</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/recordTypes/Russian_Sales.recordType-meta.xml
<RecordType>
    <fullName>Russian_Sales</fullName>
    <active>true</active>
    <businessProcess>Russian Sales</businessProcess>
    <label>Russian Sales</label>
</RecordType>

default/objects/Opportunity/fields/Area_Traveled__c.field-meta.xml
<CustomField>
    <fullName>Area_Traveled__c</fullName>
    <description>Where does your fleet travel?</description>
    <inlineHelpText>Where does your fleet travel?</inlineHelpText>
    <label>Geography of trips</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Statewide</fullName>
            </value>
            <value>
                <fullName>Regional</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Most_Important_Feature__c.field-meta.xml
<CustomField>
    <fullName>Most_Important_Feature__c</fullName>
    <description>What is the most important feature in a fleet card for the prospect?</description>
    <inlineHelpText>What is the most important feature in a fleet card for the prospect?</inlineHelpText>
    <label>Most Important Feature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Controls</fullName>
            </value>
            <value>
                <fullName>Locations</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>Terms</fullName>
            </value>
            <value>
                <fullName>Volume Growth</fullName>
            </value>
            <value>
                <fullName>Reduce Accounts Receivable</fullName>
            </value>
            <value>
                <fullName>Simplicity</fullName>
            </value>
            <value>
                <fullName>Cost Savings</fullName>
            </value>
            <value>
                <fullName>Отсрочка, кредит</fullName>
            </value>
            <value>
                <fullName>Условия договора</fullName>
            </value>
            <value>
                <fullName>Конкретные АЗС</fullName>
            </value>
            <value>
                <fullName>Сервис</fullName>
            </value>
            <value>
                <fullName>НДС</fullName>
            </value>
            <value>
                <fullName>Тендер</fullName>
            </value>
            <value>
                <fullName>Рекомендация</fullName>
            </value>
            <value>
                <fullName>Налив</fullName>
            </value>
            <value>
                <fullName>ГАЗовые АЗС</fullName>
            </value>
            <value>
                <fullName>Бренд</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Vehicles__c</fullName>
    <description>Number of vehicles</description>
    <inlineHelpText>Number of vehicles</inlineHelpText>
    <label>Number of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/recordTypes/Russian_Sales.recordType-meta.xml
<RecordType>
    <fullName>Russian_Sales</fullName>
    <active>true</active>
    <businessProcess>Russian Sales</businessProcess>
    <label>Russian Sales</label>

</RecordType>

default/classes/Naumen_SoftphoneControllerTest.cls
@isTest
private class Naumen_SoftphoneControllerTest {

    @isTest
    private static void mainTest_Lead() {
        Lead lead = new Lead(
                LastName = 'testLead1', 
                Phone = '+79851110001', 
                Naumen_Autocall_Case_UUID__c = 'ocpcas00000000000n2m8r5hv5a2p7mk',
                Company = 'testLeadCompany1', 
                Email = 'testlead1@test.ru', 
                INN__C = '1234567899999',
                Source_of_lead__c = 'Сайт Petrolplus.ru',
                RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Russian_Sales').getRecordTypeId()
        );
        insert lead;

        Test.startTest();
            Map <String, Object> result;
            String recordId;
            String recordNaumenUUID;
            String phoneNumber;
            String callDataJSON;
        // test lead
            recordId = lead.Id;
            recordNaumenUUID = lead.Naumen_Autocall_Case_UUID__c;
            phoneNumber = lead.Phone;
            // get record
            result = Naumen_SoftphoneController.getRecord (recordNaumenUUID, phoneNumber);
            system.assertEquals('ok', String.valueOf(result.get('status')));
            Naumen_RecordsHelper.LeadWrap recordResult = (Naumen_RecordsHelper.LeadWrap) result.get('record');
            system.assertEquals(recordId, recordResult.recordId);
            system.assertEquals(recordId, recordResult.callCustomerId);
           /* not used now since we use naumen softphone on ccspeedup page only 
            // save call data
            callDataJSON = '{"recordId":"' + recordId + '","phoneNumber":"' + phoneNumber + '"}';
            result = Naumen_SoftphoneController.saveCallData (callDataJSON);
            system.assertEquals('ok', String.valueOf(result.get('status')));
            */
        Test.stopTest();
    }

    @isTest
    private static void mainTest_Opportunity() {
        insert CFUtilsTest.createCFSettingsForRussia(false);
        Account acc = new Account(
                Name = 'testAcc1', 
                BillingCountry = 'Russia',
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Russian').getRecordTypeId()
        );
        insert acc;
        Opportunity opp = new Opportunity (
                Name = 'testOpp1',
                AccountId = acc.Id,
                Naumen_Autocall_Case_UUID__c = 'ocpcas00000000000n2m8r5hv5a2p000',
                Number_of_Vehicles__c = 1,
                StageName = 'Qualified Lead',
                CloseDate = Date.today().addDays(10),
                Most_Important_Feature__c = 'Reporting',
                Area_Traveled__c = 'Regional',
                The_region__c = 'г. Санкт-Петербург',
                Travel_Pattern__c = 'Regular Route',
                Primary_Fueling_Method__c = 'Coupons',
                PPR_First_Contact_Inbound_Outbound__c = 'Inbound call',
                Source_of_Lead_o__c = 'Выставка',
                RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Russian_Sales').getRecordTypeId()
        );
        insert opp;
        String con_extensionNumber = '4445';
        Contact con = new Contact(
                LastName='testCon1', 
                AccountId = acc.Id,
                Phone = '+7987 3334 445' + '# ' + con_extensionNumber,
                MobilePhone = '+79017770002',
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Russian').getRecordTypeId()
        );
        Contact con_primary = new Contact(
                LastName='testConPrimary', 
                AccountId = acc.Id,
                Phone = '+79017770001',
                MobilePhone = '+79017770002',
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Russian').getRecordTypeId()
        );
    insert new List <Contact> {con, con_primary};

    OpportunityContactRole oppContactRole_primary = new OpportunityContactRole (
        ContactId = con_primary.Id,
        OpportunityId = opp.Id,
        Role = 'Decision Maker',
        IsPrimary = true
    );
    insert oppContactRole_primary;

        Test.startTest();
            Map <String, Object> result;
            String recordId;
            String mainContactId;
            String callContactId;
            String recordNaumenUUID;
            String phoneNumber;
            String callDataJSON;
        // 1) test contact without contact role
            recordId = opp.Id;
            mainContactId = con_primary.Id;
            callContactId = con.Id;
            recordNaumenUUID = opp.Naumen_Autocall_Case_UUID__c;
            phoneNumber = con.Phone;     
            // get record
            result = Naumen_SoftphoneController.getRecord (recordNaumenUUID, phoneNumber);
            system.assertEquals('ok', String.valueOf(result.get('status')));
            Naumen_RecordsHelper.OpportunityWrap recordResult = (Naumen_RecordsHelper.OpportunityWrap) result.get('record');
            system.assertEquals(recordId, recordResult.recordId);
            system.assertEquals(mainContactId, recordResult.mainContactId);
            system.assertEquals(callContactId, recordResult.callCustomerId);
            system.assertEquals(con_extensionNumber, recordResult.extensionNumber);
            /* not used now since we use naumen softphone on ccspeedup page only
            // save call data
            callDataJSON = '{"recordId":"' + recordId + '","phoneNumber":"' + phoneNumber + '"}';
            result = Naumen_SoftphoneController.saveCallData (callDataJSON);
            system.assertEquals('ok', String.valueOf(result.get('status')));
            */

        // 2) test contact with primary contact role
            recordId = opp.Id;
            mainContactId = con_primary.Id;
            callContactId = con_primary.Id;
            recordNaumenUUID = opp.Naumen_Autocall_Case_UUID__c;
            phoneNumber = con_primary.MobilePhone;
            // get record
            result = Naumen_SoftphoneController.getRecord (recordNaumenUUID, phoneNumber);
            system.assertEquals('ok', String.valueOf(result.get('status')));
            Naumen_RecordsHelper.OpportunityWrap recordResult_primaryCon = (Naumen_RecordsHelper.OpportunityWrap) result.get('record');
            system.assertEquals(recordId, recordResult_primaryCon.recordId);
            system.assertEquals(mainContactId, recordResult_primaryCon.mainContactId);
            system.assertEquals(callContactId, recordResult_primaryCon.callCustomerId);
            system.assertEquals('', recordResult_primaryCon.extensionNumber);
            // set contact as a call customer
            Map<String,Object> setCallCustomerResult = Naumen_SoftphoneController.setCallCustomer(con.Id, con.Phone);
            system.assertEquals('ok', setCallCustomerResult.get('status'));
            Naumen_RecordsHelper.ContactWrap callCustomerWrap = (Naumen_RecordsHelper.ContactWrap) setCallCustomerResult.get('callCustomer');
            system.assertEquals('Phone', callCustomerWrap.phoneFieldAPI);
            system.assertEquals(con_extensionNumber, callCustomerWrap.extensionNumber);
            /* not used now since we use naumen softphone on ccspeedup page only
            // save call data
            callDataJSON = '{"recordId":"' + recordId + '","phoneNumber":"' + phoneNumber + '"}';
            result = Naumen_SoftphoneController.saveCallData (callDataJSON);
            system.assertEquals('ok', String.valueOf(result.get('status')));
            */
        Test.stopTest();
    }
}