default/objects/Account/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Идентификационный номер налогоплательщика.
            Должен содержать только цифры:
            12 цифр - ИП;
            10 цифр - юр. лицо.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <formula>IF(
            OR (
            CONTAINS( BillingStreet, 'ЕКАТЕРИНБУРГ'),
            CONTAINS( BillingStreet, 'Екатеринбург'),
            CONTAINS( Region__c, 'ЕКАТЕРИНБУРГ'),
            CONTAINS( Region__c, 'Екатеринбург'),
            CONTAINS( BillingCity, 'Екатеринбург'),
            CONTAINS( BillingCity, 'ЕКАТЕРИНБУРГ')
            ),
            'Екатеринбург',
            IF(
            OR (
            CONTAINS( BillingStreet, 'г. Оренбург'),
            CONTAINS( BillingStreet, 'Г. ОРЕНБУРГ'),
            CONTAINS( BillingStreet, 'г Оренбург'),
            CONTAINS( BillingStreet, 'Г ОРЕНБУРГ'),
            BillingCity = 'ОРЕНБУРГ',
            BillingCity = 'Оренбург',
            AND ( LEFT(BillingStreet, 4)='4600',
            OR( CONTAINS(BillingStreet,'Оренбург'),
            CONTAINS(BillingStreet,'ОРЕНБУРГ')))
            ),
            'Оренбургская область',
            IF(
            OR (
            CONTAINS( BillingStreet, 'г. Владимир.'),
            CONTAINS( BillingStreet, 'Г. ВЛАДИМИР.'),
            CONTAINS( BillingStreet, 'г Владимир.'),
            CONTAINS( BillingStreet, 'Г ВЛАДИМИР.'),
            BillingCity = 'ВЛАДИМИР',
            BillingCity = 'Владимир',
            AND ( LEFT(BillingStreet, 4)='6000',
            OR( CONTAINS(BillingStreet,'Владимир'),
            CONTAINS(BillingStreet,'ВЛАДИМИР')))
            ),
            'Владимирская область',
            IF(
            OR (
            CONTAINS( BillingStreet, 'САНКТ-ПЕТЕРБУРГ'),
            CONTAINS( BillingStreet, 'Санкт-Петербург'),
            CONTAINS( Region__c, 'Санкт-Петербург'),
            CONTAINS( Region__c, 'САНКТ-ПЕТЕРБУРГ'),
            CONTAINS( BillingCity, 'Санкт-Петербург'),
            CONTAINS( BillingCity, 'САНКТ-ПЕТЕРБУРГ'),
            AND ( LEFT(BillingStreet, 4)='1910',
            OR( CONTAINS(BillingStreet,'Петербург'),
            CONTAINS(BillingStreet,'ПЕТЕРБУРГ')))
            ),
            'Ленинградская область',
            IF(
            OR (
            CONTAINS( BillingStreet, 'СВЕРДЛОВСКАЯ ОБ'),
            CONTAINS( BillingStreet, 'Свердловская об'),
            CONTAINS( Region__c, 'СВЕРДЛОВСКАЯ'),
            CONTAINS( Region__c, 'Свердловская'),
            AND(LEFT(BillingStreet, 2) = '62',
            OR (
            CONTAINS( BillingStreet, 'СВЕРДЛОВСКАЯ'),
            CONTAINS( BillingStreet, 'Свердловская')
            )
            )
            ),
            'Свердловская область', ''
            )
            ))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Territory</label>
    <type>Text</type>
</CustomField>

default/objects/Account/recordTypes/Russian.recordType-meta.xml
<RecordType>
    <fullName>Russian</fullName>
    <active>true</active>
    <label>Russian</label>
</RecordType>

default/objects/Lead/fields/Duplicate_Record_Mark__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Record_Mark__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Флаг того что запись помечена как "Дубликат" (есть более актуальный аналог)</description>
    <label>Duplicate Record Mark</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Lead/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax Identification Number - For use in Russia</description>
    <inlineHelpText>Tax identification number
        Must contain only numbers:
        Length 12 symbols for PE;
        Length 10 symbols for legal person.</inlineHelpText>
    <label>INN</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <formula>IF(
OR (
CONTAINS(City,'ЕКАТЕРИНБУРГ'),
CONTAINS(City,'Екатеринбург'),
CONTAINS(Street,'ЕКАТЕРИНБУРГ'),
CONTAINS(Street,'Екатеринбург')
), 'Екатеринбург',
IF(
OR (
CONTAINS(Street,'г. Оренбург'),
CONTAINS(Street,'Г. ОРЕНБУРГ'),
CONTAINS(Street,'г Оренбург'),
CONTAINS(Street,'Г ОРЕНБУРГ'),
AND ( LEFT(Street, 4)='4600',
OR( CONTAINS(Street,'Оренбург'),
CONTAINS(Street,'ОРЕНБУРГ')))
), 'Оренбургская область',
IF(
OR (
CONTAINS(Street,'г. Владимир.'),
CONTAINS(Street,'Г. ВЛАДИМИР.'),
CONTAINS(Street,'г Владимир.'),
CONTAINS(Street,'Г ВЛАДИМИР.'),
AND ( LEFT(Street, 4)='6000',
OR( CONTAINS(Street,'Владимир'),
CONTAINS(Street,'ВЛАДИМИР')))
), 'Владимирская область',
IF(
OR (
CONTAINS(City,'САНКТ-ПЕТЕРБУРГ'),
CONTAINS(City,'Санкт-Петербург'),
CONTAINS(Street,'САНКТ-ПЕТЕРБУРГ'),
CONTAINS(Street,'Санкт-Петербург') ,
AND ( LEFT(Street, 4)='1910',
OR( CONTAINS(Street,'Петербург'),
CONTAINS(Street,'ПЕТЕРБУРГ')))
) ,'Ленинградская область',
IF(
OR (
CONTAINS(TEXT(Region__c),'Свердловская'),
CONTAINS(TEXT(Region__c),'СВЕРДЛОВСКАЯ'),
CONTAINS(Street,'СВЕРДЛОВСКАЯ ОБ'),
CONTAINS(Street,'Свердловская об'),
AND ( LEFT(Street, 2)='62',
OR( CONTAINS(Street,'СВЕРДЛОВСКАЯ'),
CONTAINS(Street,'Свердловская')
)
)), 'Свердловская область','')
))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Territory</label>
    <type>Text</type>
</CustomField>

default/classes/FieldSalesDeduplicationBatch.cls
global class FieldSalesDeduplicationBatch  implements Database.Batchable<SObject>{

    private String query;

    public FieldSalesDeduplicationBatch(Integer limitRecords) {
        String recordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Lead' and Name = 'Russian Sales' LIMIT 1].Id;
        String limitFilter = (limitRecords != null) ? ' LIMIT ' + limitRecords : '';
        query = 'SELECT Id, Inn__c, CreatedDate, Duplicate_Record_Mark__c FROM Lead WHERE INN__c != null AND RecordTypeId = \'' + recordType + '\' ' + limitFilter;
    }

    global Database.QueryLocator start(Database.BatchableContext context){
        return Database.getQueryLocator(this.query);
    }

    global void execute(Database.BatchableContext context, List<sObject> listRecords){
        Map<Id, String> recordMap = new Map<Id, String>();
        for(SObject sObj : listRecords){
            recordMap.put(id.valueOf(String.valueof(sObj.get('Id'))), String.valueOf(sObj.get('Inn__c')));
        }

        Map<String, List<Lead>> allOtherLeadsByInn = new Map<String, List<Lead>>();
        for(Lead lead : [SELECT id, INN__c, Territory__c, Createddate FROM Lead WHERE INN__c in :recordMap.values() AND Id not in :recordMap.keySet()]){
            if(!allOtherLeadsByInn.containsKey(lead.INN__c)){
                allOtherLeadsByInn.put(lead.INN__c, new List<Lead>());
            }
            allOtherLeadsByInn.get(lead.INN__c).add(lead);
        }

        Set<String> accountsByInn = new Set<String>();
        for(Account account : [SELECT Id, INN__c FROM Account WHERE INN__c in :recordMap.values()]){
            accountsByInn.add(account.INN__c);
        }

        List<SObject> listToUpdate = new List<SObject>();
        for(SObject lead : listRecords){
            String inn = String.valueOf(lead.get('INN__c'));
            if(accountsByInn.contains(inn)){
                lead.put('Duplicate_Record_Mark__c', true);
                listToUpdate.add(lead);
            }
            else if(allOtherLeadsByInn.containsKey(inn)){
                for(Lead leadByInn : allOtherLeadsByInn.get(inn)){
                    if(Datetime.valueOf(lead.get('CreatedDate')) < leadByInn.CreatedDate){
                        lead.put('Duplicate_Record_Mark__c', true);
                        listToUpdate.add(lead);
                        break;
                    }
                }
            }
        }

        if(listToUpdate.size() != 0){
            update listToUpdate;
        }
    }

    global void finish(Database.BatchableContext context){}

}