default/objects/Account/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Czech</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Hungarian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Slovak</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>DO Markenpartner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Anruf</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Form_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Form_of_Payment__c</fullName>
    <label>Order Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer - after delivery</fullName>
            </value>
            <value>
                <fullName>Advanced payment</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Language_preference__c.field-meta.xml
<CustomField>
    <fullName>Language_preference__c</fullName>
    <inlineHelpText>Please select the language preference of the contact person.</inlineHelpText>
    <label>Language Preference *</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Czech</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Hungarian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Slovak</fullName>
            </value>
            <value>
                <fullName>Russisch</fullName>
                <label>Russian</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>You don't have any Contacts under your Account!</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Opportunity/fields/Primary_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Phone__c</fullName>
    <label>Primary Contact Phone</label>
    <type>Phone</type>
</CustomField>

default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product *</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BE-FR 2,5 Cent</fullName>
            </value>
            <value>
                <fullName>Carnet OBD</fullName>
            </value>
            <value>
                <fullName>Carnet Standard 2019</fullName>
            </value>
            <value>
                <fullName>Fuel Vehicle</fullName>
            </value>
            <value>
                <fullName>HOME 1</fullName>
            </value>
            <value>
                <fullName>Home Station offer (v.1)</fullName>
            </value>
            <value>
                <fullName>Inbound Typ B</fullName>
            </value>
            <value>
                <fullName>Inbound Typ C</fullName>
            </value>
            <value>
                <fullName>LOCAL - RED</fullName>
            </value>
            <value>
                <fullName>LOCAL - YELLOW</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes No fee</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes Standard</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>Sales no fee promo Feb 2016</fullName>
            </value>
            <value>
                <fullName>Shell Basic 2020</fullName>
            </value>
            <value>
                <fullName>Shell No fee 2020</fullName>
            </value>
            <value>
                <fullName>Shell Outbound 2020</fullName>
            </value>
            <value>
                <fullName>Shell Universal Card</fullName>
            </value>
            <value>
                <fullName>Smart</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + % fee)</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + fixed fee)</fullName>
            </value>
            <value>
                <fullName>Sonderangebot (s. Notizen)</fullName>
            </value>
            <value>
                <fullName>Swiss Pro</fullName>
            </value>
            <value>
                <fullName>Swiss Pro 5</fullName>
            </value>
            <value>
                <fullName>Swiss Star</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Total_number_of_vehicles__c.field-meta.xml
<CustomField>
    <fullName>Total_number_of_vehicles__c</fullName>
    <label>Total number of vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/recordTypes/Carnet.recordType-meta.xml
<RecordType>
    <fullName>Carnet</fullName>
    <active>true</active>
    <businessProcess>Carnet</businessProcess>
    <description>Record Type for Carnet records.</description>
    <label>Carnet</label>
</RecordType>

default/classes/CarnetE2EService.cls
/**
 * Created by eugene on 10/1/19.
 */

public class CarnetE2EService {
    @future
    public static void createCarnetOpportunity(String opportunityId) {
        RecordType carnetRecordType = [SELECT Id FROM RecordType WHERE Name = 'Carnet' AND SObjectType = 'Opportunity'];
        Opportunity opportunity = [
                SELECT AccountId, Account.Name, Sec_Channel__c, Channel__c, Primary_Contact__c,
                       LeadSource, Product__c, Primary_Contact_Phone__c, Total_number_of_vehicles__c,
                       (SELECT ContactId FROM OpportunityContactRoles WHERE IsPrimary = TRUE)
                FROM Opportunity
                WHERE Id = :opportunityId
        ];
        List<User> userRobert = [SELECT Id FROM User WHERE Name = 'Robert Kobrynski'];
        Opportunity carnetOpportunity = new Opportunity(
                RecordTypeId = carnetRecordType.Id,
                AccountId = opportunity.AccountId,
                Name = opportunity.Account.Name + '-Carnet',
                Type = 'Existing GFN',
                Language_preference__c = 'Polish',
                Sec_Channel__c = opportunity.Sec_Channel__c,
                Channel__c = opportunity.Channel__c,
                LeadSource = opportunity.LeadSource,
                Product__c = 'Carnet Standard 2019',
                CloseDate = Date.today().addMonths(3),
                StageName = 'Qualify',
                Form_of_Payment__c = 'Bank Transfer - after delivery',
                Primary_Contact_Phone__c = opportunity.Primary_Contact_Phone__c,
                Total_number_of_vehicles__c = opportunity.Total_number_of_vehicles__c
        );
        if (!opportunity.OpportunityContactRoles.isEmpty()) {
            carnetOpportunity.Primary_Contact__c = opportunity.OpportunityContactRoles.get(0).ContactId;
        }
        if (!userRobert.isEmpty()) {
            carnetOpportunity.OwnerId = userRobert.get(0).Id;
        }
        insert carnetOpportunity;

        if (!opportunity.OpportunityContactRoles.isEmpty()) {
            OpportunityContactRole newContactRole = new OpportunityContactRole(
                    ContactId = opportunity.OpportunityContactRoles.get(0).ContactId,
                    OpportunityId = carnetOpportunity.Id,
                    IsPrimary = true
            );
            insert newContactRole;
        }
    }
}