default/objects/Account/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Czech</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Hungarian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Slovak</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>DO Markenpartner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/recordTypes/Endkunde.recordType-meta.xml
<RecordType>
    <fullName>Endkunde</fullName>
    <active>true</active>
    <label>Endkunde</label>
</RecordType>

default/objects/Contact/fields/Customer_IP_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_IP_Address__c</fullName>
    <description>Field used for storing IP adresses of users coming through website (Web-to-Lead, web orders). GDPR Regulation.</description>
    <label>Customer IP Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/E2E_Data_Object__c.object-meta.xml
<CustomObject>
    <label>E2E Data Object</label>
    <nameField>
        <label>E2E Data Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Object__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>de</fullName>
            </value>
            <value>
                <fullName>at</fullName>
            </value>
            <value>
                <fullName>nl</fullName>
            </value>
            <value>
                <fullName>pl</fullName>
            </value>
            <value>
                <fullName>hu</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>befr</fullName>
            </value>
            <value>
                <fullName>benl</fullName>
            </value>
            <value>
                <fullName>chde</fullName>
            </value>
            <value>
                <fullName>chfr</fullName>
            </value>
            <value>
                <fullName>sk</fullName>
            </value>
            <value>
                <fullName>cz</fullName>
            </value>
            <value>
                <fullName>lu</fullName>
            </value>
            <value>
                <fullName>be_fr</fullName>
                <isActive>false</isActive>
                <label>be_fr</label>
            </value>
            <value>
                <fullName>be_nl</fullName>
                <isActive>false</isActive>
                <label>be_nl</label>
            </value>
            <value>
                <fullName>ch_de</fullName>
                <isActive>false</isActive>
                <label>ch_de</label>
            </value>
            <value>
                <fullName>ch_fr</fullName>
                <isActive>false</isActive>
                <label>ch_fr</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Current_Language__c.field-meta.xml
<CustomField>
    <fullName>Current_Language__c</fullName>
    <label>Current Language</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Current_Step__c</fullName>
    <label>Current Step</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Customer_IP_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_IP_Address__c</fullName>
    <label>Customer IP Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Type__c</fullName>
    <label>Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desktop</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Direct_Debit_Mandate_Type__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_Mandate_Type__c</fullName>
    <label>Direct Debit Mandate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>B2B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Object__c/fields/E2E_Last_Activity__c.field-meta.xml
<CustomField>
    <fullName>E2E_Last_Activity__c</fullName>
    <label>E2E Last Activity</label>
    <type>DateTime</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/E2E_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Status__c</fullName>
    <label>E2E Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Registered_Country__c.field-meta.xml
<CustomField>
    <fullName>Registered_Country__c</fullName>
    <label>Registered Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Selected_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Selected_Company_Name__c</fullName>
    <label>Selected Company Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/StageName__c.field-meta.xml
<CustomField>
    <fullName>StageName__c</fullName>
    <label>StageName</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospecting</fullName>
            </value>
            <value>
                <fullName>Pending Sales – Information</fullName>
            </value>
            <value>
                <fullName>Pending Sales – Deposit</fullName>
            </value>
            <value>
                <fullName>Credit Approved</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Qualify</fullName>
            </value>
            <value>
                <fullName>Propose</fullName>
            </value>
            <value>
                <fullName>Negotiate</fullName>
            </value>
            <value>
                <fullName>Pending Credit Report</fullName>
            </value>
            <value>
                <fullName>Pending Credit - E2E Check</fullName>
            </value>
            <value>
                <fullName>Credit Report Generated</fullName>
            </value>
            <value>
                <fullName>finish</fullName>
                <isActive>false</isActive>
                <label>finish</label>
            </value>
            <value>
                <fullName>pending deposit</fullName>
                <isActive>false</isActive>
                <label>pending deposit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Bevollmaechtigung__c.field-meta.xml
<CustomField>
    <fullName>Bevollmaechtigung__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Ich/wir bestätigen, dass ich/wir rechtlich bevollmächtigt bin/sind, im Namen und auf Rechnung der im Antrag genannten Firma zu handeln.</inlineHelpText>
    <label>Bevollmächtigung</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Direct_Debit_Mandate_Type__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_Mandate_Type__c</fullName>
    <label>Direct Debit Mandate Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Zahlungsart__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>B2B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/E2E_2__c.field-meta.xml
<CustomField>
    <fullName>E2E_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>E2E 2</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Data_Object__c.field-meta.xml
<CustomField>
    <fullName>E2E_Data_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E2E Data Object</label>
    <referenceTo>E2E_Data_Object__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Encoded_URL__c.field-meta.xml
<CustomField>
    <fullName>E2E_Encoded_URL__c</fullName>
    <label>E2E Encoded URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Last_Activity__c.field-meta.xml
<CustomField>
    <fullName>E2E_Last_Activity__c</fullName>
    <label>E2E Last Activity</label>
    <type>DateTime</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Status__c</fullName>
    <label>E2E Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Abandoned (soft)</fullName>
            </value>
            <value>
                <fullName>Abandoned (hard)</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Клиент Активен</fullName>
            </value>
            <value>
                <fullName>Клиент не активен</fullName>
            </value>
            <value>
                <fullName>Отказ от E2E</fullName>
            </value>
            <value>
                <fullName>Клиент завершил</fullName>
            </value>
            <value>
                <fullName>Introduction</fullName>
            </value>
            <value>
                <fullName>Drop off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/E2E_Step__c.field-meta.xml
<CustomField>
    <fullName>E2E_Step__c</fullName>
    <label>E2E Step</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Eco_Fee__c.field-meta.xml
<CustomField>
    <fullName>Eco_Fee__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Tick to set, to choose if the Customer want to take Eco Fee or not.</description>
    <label>Eco Fee</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Language_preference__c.field-meta.xml
<CustomField>
    <fullName>Language_preference__c</fullName>
    <inlineHelpText>Please select the language preference of the contact person.</inlineHelpText>
    <label>Language Preference *</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Czech</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Hungarian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Slovak</fullName>
            </value>
            <value>
                <fullName>Russisch</fullName>
                <label>Russian</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Registered_Country__c.field-meta.xml
<CustomField>
    <fullName>Registered_Country__c</fullName>
    <formula>IF(Account.BillingCountry = "", TEXT(Account.Land_E__c) , Account.BillingCountry)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registered Country</label>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Visitor_ID__c.field-meta.xml
<CustomField>
    <fullName>Visitor_ID__c</fullName>
    <label>Visitor_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/recordTypes/Euroshell.recordType-meta.xml
<RecordType>
    <fullName>Euroshell</fullName>
    <active>true</active>
    <businessProcess>Euroshell</businessProcess>
    <label>Euroshell</label>
</RecordType>

default/classes/ETEBusinessObjectsHandler.cls
public virtual class ETEBusinessObjectsHandler implements ETEBusinessObjectsInterface {

    public virtual E2E_Data_Object__c initDataObject(List<String> availableStepsList, String countryCode, String implKey) {
        String recordTypeId = Schema.SObjectType.E2E_Data_Object__c.getRecordTypeInfosByName().get(implKey).getRecordTypeId();
        E2E_Data_Object__c dataObject = new E2E_Data_Object__c();
        dataObject.Name = 'NEW E2E CUSTOMER';
        dataObject.Selected_Company_Name__c = 'NEW E2E CUSTOMER';
        dataObject.StageName__c = 'Prospecting';
        dataObject.E2E_Status__c = 'In progress';
        dataObject.RecordTypeId = recordTypeId;
        dataObject.Country_Code__c = countryCode;
        dataObject.Current_Step__c = availableStepsList.get(0);
        dataObject.Current_Language__c = ETEGlobalUtils.returnDefaultLanguage(countryCode);
        dataObject.CurrencyIsoCode = ETEGlobalUtils.returnCurrencyCode(countryCode);
        dataObject.E2E_Last_Activity__c = Datetime.now();
        dataObject.Registered_Country__c = ETEGlobalUtils.returnCountry(countryCode);
        return dataObject;
    }


    public virtual Opportunity initOpportunity(E2E_Data_Object__c dataObject, String priceBookId) {
        String recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Euroshell').getRecordTypeId();
        Opportunity newOppty = new Opportunity(
                RecordTypeId = recordTypeId,
                Name = dataObject.Selected_Company_Name__c,
                E2E_Data_Object__c = dataObject.Id,
                StageName = 'Prospecting',
                CloseDate = Date.today(),
                Last_Owner_Change_Date__c = Datetime.now(),
                Language_preference__c = ETEGlobalUtils.returnLanguagePreference(dataObject.Current_Language__c),
                E2E_Step__c = dataObject.Current_Step__c,
                E2E_Encoded_URL__c = ETEGlobalUtils.doEncryptParams(dataObject.Id, dataObject.Country_Code__c),
                Device_Type__c = dataObject.Device_Type__c,
                Visitor_ID__c = dataObject.Customer_IP_Address__c,
                E2E_Last_Activity__c = dataObject.E2E_Last_Activity__c,
                E2E_2__c = true,
                Eco_Fee__c = false,
                LeadSource = 'E2E Form',
                Direct_Debit_Mandate_Type__c = '',
                Bevollmaechtigung__c = false,
                Sec_Channel__c = 'Inbound',
                Channel__c = 'Internet',
                Product__c = '',
                CurrencyIsoCode = ETEGlobalUtils.returnCurrencyCode(dataObject.Country_Code__c),
                Type = 'New Business',
                AGB_Datenschutzhinweise_Richtigkeit__c = false,
                E2E_Status__c = 'In progress',
                E2E_Sales_Type__c = 'Fully E2E',
                Utm_campaign__c = dataObject.Utm_Campaign__c,
                Utm_content__c = dataObject.Utm_Content__c,
                Utm_medium__c = dataObject.Utm_Medium__c,
                Utm_placement__c = dataObject.Utm_Placement__c,
                Utm_source__c = dataObject.Utm_Source__c,
                Utm_term__c = dataObject.Utm_Term__c,
                Utm_url__c = dataObject.Utm_Url__c,
                PriceBook2Id = priceBookId
        );
        return newOppty;
    }


    public virtual CreditFactoryCompany getCFReport(CreditFactory creditFactory, String opptyId) {
        CreditFactoryReportsItem reportsItem = creditFactory.selectCompanyReports(opptyId);
        CreditFactoryCompany creditFactoryCompany;
        for (CreditFactoryCompany cfCompany : reportsItem.companiesList) {
            if (cfCompany != null && cfCompany.recordType == 'Default') {
                creditFactoryCompany = cfCompany;
            }
        }

        if (creditFactoryCompany != null && creditFactoryCompany.name == null) {
            for (CreditFactoryCompany cfCompany : reportsItem.companiesList) {
                if (cfCompany != null && cfCompany.recordType == 'Company Info') {
                    creditFactoryCompany = cfCompany;
                }
            }
        }

        return creditFactoryCompany;
    }


    public virtual Account initAccount(String country, E2E_Data_Object__c dataObject) {
        String recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Endkunde').getRecordTypeId();
        Account account = new Account(
                Name = dataObject.Selected_Company_Name__c,
                RecordTypeId = recordTypeId,
                Type = 'Customer',
                E2E__c = true,
                Sec_Channel__c = 'Inbound',
                Sec_Channel_Acc__c = 'Inbound',
                AccountSource = 'E2E Form',
                BillingCountry = country
        );
        return account;
    }


    public virtual Contact initContact() {
        String recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact layout').getRecordTypeId();
        Contact contact = new Contact(
                RecordTypeId = recordTypeId,
                Authorised_signatory__c = false,
                E2E__c = true
        );
        return contact;
    }


    public virtual OpportunityContactRole initOpportunityContactRole() {
        OpportunityContactRole ocr = new OpportunityContactRole(
                IsPrimary = true
        );
        return ocr;
    }
}