default/objects/Account/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Czech</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Hungarian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Slovak</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Gruende_verloren__c.field-meta.xml
<CustomField>
    <fullName>Gruende_verloren__c</fullName>
    <label>Gründe verloren</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>After Sales - Degussa</fullName>
            </value>
            <value>
                <fullName>AGB nicht aktzeptiert</fullName>
            </value>
            <value>
                <fullName>Already FLEETCOR Customer</fullName>
            </value>
            <value>
                <fullName>Andere Bezahlmethode - Cash</fullName>
            </value>
            <value>
                <fullName>Andere Bezahlmethode - EC/Kreditkarte</fullName>
            </value>
            <value>
                <fullName>Andere Bezahlmethode - Tankkarte</fullName>
            </value>
            <value>
                <fullName>Andere Bezahlmethode - VISA</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - bessere Zahlungsbeding</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - geringere Kosten</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - höheres Kreditlimit</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - keine Garantien</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - mehr Features</fullName>
            </value>
            <value>
                <fullName>Angabenkorrektur nicht möglich</fullName>
            </value>
            <value>
                <fullName>Bearbeitung - Degussa</fullName>
            </value>
            <value>
                <fullName>Bestellprozess zu lange</fullName>
            </value>
            <value>
                <fullName>Black List</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Change his mind</fullName>
            </value>
            <value>
                <fullName>Competitors</fullName>
            </value>
            <value>
                <fullName>Coverage/Acceptance</fullName>
            </value>
            <value>
                <fullName>Credit Report not available</fullName>
            </value>
            <value>
                <fullName>Customer not reached</fullName>
            </value>
            <value>
                <fullName>Deposit – not confirmed</fullName>
            </value>
            <value>
                <fullName>Didn't confirm card order</fullName>
            </value>
            <value>
                <fullName>Direct debit</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Execution</fullName>
            </value>
            <value>
                <fullName>Financial/Credit</fullName>
            </value>
            <value>
                <fullName>Firma zu jung</fullName>
            </value>
            <value>
                <fullName>Gebühren</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Language_preference__c.field-meta.xml
<CustomField>
    <fullName>Language_preference__c</fullName>
    <inlineHelpText>Please select the language preference of the contact person.</inlineHelpText>
    <label>Language Preference *</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Czech</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Hungarian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Slovak</fullName>
            </value>
            <value>
                <fullName>Russisch</fullName>
                <label>Russian</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Total_consumption_l_month__c.field-meta.xml
<CustomField>
    <fullName>Total_consumption_l_month__c</fullName>
    <label>Total consumption (l/month) *</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Zahlungsart__c.field-meta.xml
<CustomField>
    <fullName>Zahlungsart__c</fullName>
    <label>Zahlungsart *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lastschrift</fullName>
            </value>
            <value>
                <fullName>Banküberweisung</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/recordTypes/Euroshell.recordType-meta.xml
<RecordType>
    <fullName>Euroshell</fullName>
    <active>true</active>
    <businessProcess>Euroshell</businessProcess>
    <label>Euroshell</label>
</RecordType>

default/classes/BatchCloseOpportunitiesTest.cls
@IsTest
public class BatchCloseOpportunitiesTest {

     /*******************************************************************************
     *  Summary         : test close inactive opportunities
     *  Created         : 02/11/2020
     *  Parameters      : -
     *  Returns         : void
    ******************************************************************************/
    @IsTest
    static void testCloseOpportunities() {
        Account account = new Account(
                Name = 'Test',
                BillingCountry = 'Poland'
        );
        insert account;

        RecordType recordType = [SELECT Id FROM RecordType WHERE Name = 'Euroshell' AND sObjectType = 'Opportunity' LIMIT 1];

        Opportunity opportunity = new Opportunity(
                AccountId = account.Id,
                Name = 'Test',
                RecordTypeId = recordType.Id,
                StageName = 'Prospecting',
                Language_preference__c = 'Polish',
                Total_consumption_l_month__c = 100,
                Zahlungsart__c = 'Lastschrift',
                CloseDate = Date.today().addDays(14)
        );
        insert opportunity;
        Test.setCreatedDate(opportunity.Id, Date.today().addMonths(-5));


        OpportunityFieldHistory fieldHistory = new OpportunityFieldHistory(
                OpportunityId = opportunity.Id,
                Field = 'StageName'
        );
        insert fieldHistory;

        Test.startTest();
            BatchCloseOpportunities batchCloseOpportunities = new BatchCloseOpportunities();
            Database.executeBatch(batchCloseOpportunities);
        Test.stopTest();

        Opportunity opp = [SELECT StageName, Gruende_verloren__c from Opportunity where Id = :opportunity.Id];
        System.assertEquals('Closed Lost', opp.StageName);
        System.assertEquals('No activity', opp.Gruende_verloren__c);
    }
}