default/objects/Account/fields/Merged_in_E2E__c.field-meta.xml
<CustomField>
    <fullName>Merged_in_E2E__c</fullName>
    <inlineHelpText>Merged In E2E</inlineHelpText>
    <label>Merged in E2E</label>
    <type>DateTime</type>
</CustomField>

default/objects/Account/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Возможность</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Организации</relationshipLabel>
    <relationshipName>Account6VaS</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Account/recordTypes/CCS.recordType-meta.xml
<RecordType>
    <fullName>CCS</fullName>
    <active>true</active>
    <label>CCS</label>
</RecordType>

default/objects/Credit_Factory_Report__c/Credit_Factory_Report__c.object-meta.xml
<CustomObject>
    <label>Credit Factory Report</label>
    <nameField>
        <label>Credit Factory Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Factory Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Credit_Factory_Report__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

default/objects/Credit_Factory_Report__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Credit Factory Reports</relationshipLabel>
    <relationshipName>Credit_Factory_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Credit_Factory_Report__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Credit_Factory_Report__c/fields/Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Tax_Id__c</fullName>
    <label>Tax Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Contact__c/E2E_Data_Contact__c.object-meta.xml
<CustomObject>
    <label>E2E Data Contact</label>
    <nameField>
        <label>E2E Data Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Contact__c/fields/E2E_Data_Object__c.field-meta.xml
<CustomField>
    <fullName>E2E_Data_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E2E Data Object</label>
    <referenceTo>E2E_Data_Object__c</referenceTo>
    <relationshipLabel>E2E Data Contacts</relationshipLabel>
    <relationshipName>E2E_Data_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2E_Data_Contact__c/fields/isPrimary__c.field-meta.xml
<CustomField>
    <fullName>isPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPrimary</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2E_Data_Object__c/E2E_Data_Object__c.object-meta.xml
<CustomObject>
    <label>E2E Data Object</label>
    <nameField>
        <label>E2E Data Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Object__c/fields/E2E_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Status__c</fullName>
    <label>E2E Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Registered_Country__c.field-meta.xml
<CustomField>
    <fullName>Registered_Country__c</fullName>
    <label>Registered Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID__c</fullName>
    <label>Tax ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/recordTypes/Germany.recordType-meta.xml
<RecordType>
    <fullName>Germany</fullName>
    <active>true</active>
    <label>Germany</label>
</RecordType>

default/objects/E2E_Data_Object__c/recordTypes/Slovakia.recordType-meta.xml
<RecordType>
    <fullName>Slovakia</fullName>
    <active>true</active>
    <label>Slovakia</label>
</RecordType>

default/objects/E2E_Form_General_Settings__c/E2E_Form_General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>E2E Form General Settings</label>
</CustomObject>

default/objects/E2E_Form_General_Settings__c/fields/Abandonment_User__c.field-meta.xml
<CustomField>
    <fullName>Abandonment_User__c</fullName>
    <label>Abandonment User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/E2E_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Status__c</fullName>
    <label>E2E Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Drop off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/recordTypes/Lotos.recordType-meta.xml
<RecordType>
    <fullName>Lotos</fullName>
    <active>true</active>
    <businessProcess>Datensatztyp</businessProcess>
    <label>Lotos</label>
</RecordType>

default/objects/Opportunity/fields/Credit_Stage__c.field-meta.xml
<CustomField>
    <fullName>Credit_Stage__c</fullName>
    <label>Credit Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Credit Report</fullName>
            </value>
            <value>
                <fullName>Pending Sales – Deposit</fullName>
            </value>
            <value>
                <fullName>Pending Sales – Information</fullName>
            </value>
            <value>
                <fullName>CreditCheck</fullName>
            </value>
            <value>
                <fullName>Pending Credit - Contract Check</fullName>
            </value>
            <value>
                <fullName>Credit Check - Pending Credit</fullName>
            </value>
            <value>
                <fullName>CreditCheck rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/E2E_Data_Object__c.field-meta.xml
<CustomField>
    <fullName>E2E_Data_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E2E Data Object</label>
    <referenceTo>E2E_Data_Object__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Status__c</fullName>
    <label>E2E Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Abandoned (soft)</fullName>
            </value>
            <value>
                <fullName>Abandoned (hard)</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Клиент Активен</fullName>
            </value>
            <value>
                <fullName>Клиент не активен</fullName>
            </value>
            <value>
                <fullName>Отказ от E2E</fullName>
            </value>
            <value>
                <fullName>Клиент завершил</fullName>
            </value>
            <value>
                <fullName>Introduction</fullName>
            </value>
            <value>
                <fullName>Drop off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Gruende_verloren__c.field-meta.xml
<CustomField>
    <fullName>Gruende_verloren__c</fullName>
    <label>Gründe verloren</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>After Sales - Degussa</fullName>
            </value>
            <value>
                <fullName>AGB nicht aktzeptiert</fullName>
            </value>
            <value>
                <fullName>Already FLEETCOR Customer</fullName>
            </value>
            <value>
                <fullName>Andere Bezahlmethode - Cash</fullName>
            </value>
            <value>
                <fullName>Andere Bezahlmethode - EC/Kreditkarte</fullName>
            </value>
            <value>
                <fullName>Andere Bezahlmethode - Tankkarte</fullName>
            </value>
            <value>
                <fullName>Andere Bezahlmethode - VISA</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - bessere Zahlungsbeding</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - geringere Kosten</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - höheres Kreditlimit</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - keine Garantien</fullName>
            </value>
            <value>
                <fullName>Anderes Produkt - mehr Features</fullName>
            </value>
            <value>
                <fullName>Angabenkorrektur nicht möglich</fullName>
            </value>
            <value>
                <fullName>Bearbeitung - Degussa</fullName>
            </value>
            <value>
                <fullName>Bestellprozess zu lange</fullName>
            </value>
            <value>
                <fullName>Black List</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Change his mind</fullName>
            </value>
            <value>
                <fullName>Competitors</fullName>
            </value>
            <value>
                <fullName>Coverage/Acceptance</fullName>
            </value>
            <value>
                <fullName>Credit Report not available</fullName>
            </value>
            <value>
                <fullName>Customer not reached</fullName>
            </value>
            <value>
                <fullName>Deposit – not confirmed</fullName>
            </value>
            <value>
                <fullName>Didn't confirm card order</fullName>
            </value>
            <value>
                <fullName>Direct debit</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Execution</fullName>
            </value>
            <value>
                <fullName>Financial/Credit</fullName>
            </value>
            <value>
                <fullName>Firma zu jung</fullName>
            </value>
            <value>
                <fullName>Gebühren</fullName>
            </value>
            <value>
                <fullName>Refused Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Kredit_Entscheidung__c.field-meta.xml
<CustomField>
    <fullName>Kredit_Entscheidung__c</fullName>
    <label>Kredit Entscheidung</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Genehmigt</fullName>
            </value>
            <value>
                <fullName>Sicherheit verlangt</fullName>
            </value>
            <value>
                <fullName>Abgelehnt</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Genehmigt, Sicherheit geliefert</fullName>
            </value>
            <value>
                <fullName>Pending mit Kredit</fullName>
            </value>
            <value>
                <fullName>falscher Empfang</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Для определения # возможности</description>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>#Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Registered_Country__c.field-meta.xml
<CustomField>
    <fullName>Registered_Country__c</fullName>
    <formula>IF(Account.BillingCountry = "", TEXT(Account.Land_E__c) , Account.BillingCountry)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registered Country</label>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/recordTypes/Lotos.recordType-meta.xml
<RecordType>
    <fullName>Lotos</fullName>
    <active>true</active>
    <businessProcess>Carnet</businessProcess>
    <label>Lotos</label>
</RecordType>

default/objects/Starts_Settings__c/Starts_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Starts Settings</label>
</CustomObject>

default/objects/Starts_Settings__c/fields/Notifications_Email__c.field-meta.xml
<CustomField>
    <fullName>Notifications_Email__c</fullName>
    <label>Notifications Email</label>
    <type>Email</type>
</CustomField>

default/classes/ETEDeduplicationService.cls
public class ETEDeduplicationService {
    private Account dupAccount;
    private Contact primaryDupContact;
    private Contact dupContact;
    private E2E_Data_Object__c dataObject;
    private List<E2E_Data_Contact__c> eteDataContacts;
    private Opportunity eteOpportunity;
    private Opportunity existingOpportunity;
    private String dupCase;


    public ETEDeduplicationService(E2E_Data_Object__c dataObject, List<E2E_Data_Contact__c> existingETEDataContacts) {
        this.dataObject = dataObject;
        this.eteDataContacts = existingETEDataContacts;
        this.eteOpportunity = [SELECT Name, AccountId, StageName, Registered_Country__c FROM Opportunity WHERE E2E_Data_Object__c = :this.dataObject.Id];
    }


    public void findDuplicates() {
        E2E_Data_Object__c e2EDataObject = this.dataObject;
        this.dupAccount = findDupAccount(e2EDataObject, eteOpportunity, null);
        this.primaryDupContact = selectDupContact(eteOpportunity, true);
        this.dupContact = selectDupContact(eteOpportunity, false);
    }


    public Opportunity getOpportunity() {
        return this.eteOpportunity;
    }


    public Account getAccount() {
        return this.dupAccount;
    }


    public Contact getPrimaryContact() {
        return this.primaryDupContact;
    }


    public Contact getContact() {
        return this.dupContact;
    }


    public void updateDupContactAsMergedInE2E(String accountId) {
        List<Contact> contactsToUpdate = new List<Contact>();
        for (E2E_Data_Contact__c dataContact : this.eteDataContacts) {
            if (accountId != null) {
                this.primaryDupContact.AccountId = accountId;
            }
            if (dataContact.isPrimary__c) {
                this.primaryDupContact.Merged_in_E2E__c = Datetime.now();
                this.primaryDupContact.Email = dataContact.Email__c;
                this.primaryDupContact.Phone = dataContact.Phone__c;
                this.primaryDupContact.FirstName = dataContact.First_name__c;
                this.primaryDupContact.LastName = dataContact.Last_name__c;
                this.primaryDupContact.Merged_in_E2E__c = Datetime.now();
                contactsToUpdate.add(this.primaryDupContact);
            } else if (this.dupContact != null) {
                this.dupContact.Merged_in_E2E__c = Datetime.now();
                this.dupContact.Email = dataContact.Email__c;
                this.dupContact.Phone = dataContact.Phone__c;
                this.dupContact.FirstName = dataContact.First_name__c;
                this.dupContact.LastName = dataContact.Last_name__c;
                this.dupContact.Merged_in_E2E__c = Datetime.now();
                contactsToUpdate.add(this.dupContact);
            }
        }
        update contactsToUpdate;
    }


    public void updateDupAccountAsMergedInE2E() {
        this.dupAccount.Merged_in_E2E__c = Datetime.now();
        update this.dupAccount;
    }


    public void generateCase() {
        List<Opportunity> opps = [
                SELECT RecordType.Name, E2E_Status__c, StageName, IsClosed, CloseDate, Gruende_verloren__c, Owner.FirstName,
                        Owner.LastName, Owner.Email, Credit_Stage__c, Registered_Country__c
                FROM Opportunity
                WHERE AccountId = :dupAccount.Id AND
                      Id != :this.eteOpportunity.Id];
        for (Opportunity opp : opps) {
            if (opp.StageName == 'Closed Won') {
                this.dupCase = 'already_a_customer';
                this.existingOpportunity = opp;
            } else if (((opp.RecordType.Name == 'Lotos' || opp.RecordType.Name == 'CCS Opportunity Layout') &&
                        (opp.Credit_Stage__c == 'CreditCheck' ||
                        opp.Credit_Stage__c == 'Pending Sales – Information' ||
                        opp.Credit_Stage__c == 'Pending Sales – Deposit' ||
                        opp.Credit_Stage__c == 'Pending Credit Report' ||
                        opp.Credit_Stage__c == 'Pending Credit - Contract Check' ||
                        opp.Credit_Stage__c == 'Credit Check - Pending Credit' ||
                        (opp.Credit_Stage__c == 'CreditCheck rejected' && opp.CloseDate.daysBetween(Date.today()) < 90))) ||
                    opp.StageName == 'CreditCheck' ||
                    opp.StageName == 'Pending Sales – Information' ||
                    opp.StageName == 'Pending Sales – Deposit' ||
                    opp.StageName == 'Pending Credit' ||
                    opp.StageName == 'Pending Sales - SEPA Confirmation' ||
                    (opp.StageName == 'Closed Lost' && opp.Gruende_verloren__c == 'Refused Credit' &&
                            opp.CloseDate.daysBetween(Date.today()) < 90) ||
                    (opp.StageName == 'CreditCheck abgelehnt' && opp.CloseDate.daysBetween(Date.today()) < 90)) {
                this.existingOpportunity = opp;
                this.dupCase = 'already_in_process';
            } else if (((opp.RecordType.Name == 'Lotos' || opp.RecordType.Name == 'CCS Opportunity Layout') &&
                        opp.IsClosed == false &&
                        (opp.StageName == 'Qualify' || opp.Credit_Stage__c == 'Credit approved')) ||
                    opp.StageName == 'Prospecting' || opp.StageName == 'Credit approved') {
                this.existingOpportunity = opp;
                this.dupCase = 'switched_to_e2e';
            } else if (opp.StageName == 'Closed Lost' && opp.Gruende_verloren__c == 'Refused Credit' && opp.CloseDate.daysBetween(Date.today()) >= 90) {
                this.existingOpportunity = opp;
                this.dupCase = 'credit_notification';
            } else if (((opp.RecordType.Name == 'Lotos' || opp.RecordType.Name == 'CCS Opportunity Layout') &&
                opp.Credit_Stage__c == 'CreditCheck rejected' && opp.CloseDate.daysBetween(Date.today()) >= 90) ||
                opp.StageName == 'CreditCheck abgelehnt' && opp.CloseDate.daysBetween(Date.today()) >= 90) {
                this.existingOpportunity = opp;
                this.dupCase = 'credit_switched_to_e2e';
            }
        }
    }


    public void processCase() {
        if (dupCase == null) return;
        if (dupCase == 'already_a_customer') {
            String country = this.eteOpportunity.Registered_Country__c;
            if (country == null) country = 'Germany';
            E2E_Form_General_Settings__c settings = E2E_Form_General_Settings__c.getInstance(country);
            if (settings != null && settings.Abandonment_User__c != null) {
                this.eteOpportunity.OwnerId = settings.Abandonment_User__c;
                update this.eteOpportunity;
            }

            String body = generateBodyForStarts();
            Starts_Settings__c startsSetting = Starts_Settings__c.getInstance(country);
            if (startsSetting != null &&  startsSetting.Notifications_Email__c != null) {
                sendSingleEmail(body, startsSetting.Notifications_Email__c);
            }
        }
        else if (dupCase == 'already_in_process') {
            this.eteOpportunity.Gruende_verloren__c = 'Duplicate';
            this.eteOpportunity.Kredit_Entscheidung__c = 'Abgelehnt';
            update this.eteOpportunity;

            String body = generateBodyForSales();
            sendSingleEmail(body, this.existingOpportunity.Owner.Email);
        }
        else if (dupCase == 'switched_to_e2e') {
            this.existingOpportunity.StageName = 'Closed Lost';
            this.existingOpportunity.Gruende_verloren__c = 'Switched to E2E';
            this.existingOpportunity.E2E_Status__c = 'Finished';
            update this.existingOpportunity;
            EmarsysSenderEuropeanService.sendE2EOpportunityToEmarsys(this.existingOpportunity.Id);
            String body = generateBodyForSalesSwitchedToE2E();
            sendSingleEmail(body, this.existingOpportunity.Owner.Email);
        }
        else if (dupCase == 'credit_notification') {
            String body = generateBodyForCreditDepartment();
            User user = [SELECT Email FROM User WHERE Name = 'Credit' LIMIT 1];
            sendSingleEmail(body, user.Email);
        }
        else if (dupCase == 'credit_switched_to_e2e') {
            this.existingOpportunity.StageName = 'Closed Lost';
            this.existingOpportunity.Gruende_verloren__c = 'Switched to E2E';
            update existingOpportunity;
            EmarsysSenderEuropeanService.sendE2EOpportunityToEmarsys(this.existingOpportunity.Id);
            String body = generateBodyForCreditDepartment();
            User user = [SELECT Email FROM User WHERE Name = 'Credit' LIMIT 1];
            sendSingleEmail(body, user.Email);

            String body2 = generateBodyForSalesSwitchedToE2E();
            sendSingleEmail(body2, this.existingOpportunity.Owner.Email);
        }
    }


    public String getStopProcess() {
        if (dupCase == 'already_a_customer') {
            return 'Already a customer';
        }
        else if (dupCase == 'already_in_process') {
            return 'Already in process';
        }

        return null;
    }


    private String generateBodyForStarts() {
        String body = 'Dear Start Team,<br/><br/>' +
                'New visitor started e2e Application and seems to be our current customer.<br/>' +
                'Please, check manually, if this is existing customer, who has transactions or if this customer has to be considered as a new one (>6 Months).<br/>' +
                '<a href="' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + this.existingOpportunity.Id + '" target="_blank">Link to Opportunity</a><br/><br/>' +
                '<a href="' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + this.eteOpportunity.Id + '" target="_blank">Link to E2E Opportunity</a><br/><br/>' +
                'Thanks and best regards.';
        return body;
    }


    private String generateBodyForSales() {
        String body = 'Dear ' + this.existingOpportunity.Owner.FirstName + ' ' + this.existingOpportunity.Owner.FirstName + ',<br/><br/>' +
                'Your customer ' + opportunity.Name + ' started e2e Application and tries to order cards online.<br/>' +
                '<a href="' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + this.existingOpportunity.Id + '" target="_blank">Current Opportunity</a><br/><br/>' +
                'Please, contact this customer as soon as possible to close the deal.<br/><br/>' +
                'Thanks and best regards.';
        return body;
    }


    private String generateBodyForCreditDepartment() {
        String body = 'Dear Credit Manager,<br/>' +
                'New visitor started e2e Application and is trying to order card online.<br/><br/>' +
                'This customer is already in SF:<br/>' +
                'Opportunity Stage: Credit Check Rejected OR Closed Lost (Reason Lost: Refused Credit)<br/>' +
                '<a href="' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + this.existingOpportunity.Id + '" target="_blank">Link to Opportunity</a><br/><br/>' +
                'Since more than 3 Months passed it will be allowed to run a Credit Score again.<br/>' +
                '<a href="' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + this.eteOpportunity.Id + '" target="_blank">Link to E2E Opportunity</a><br/><br/>' +
                'No actions are required at the moment.<br/><br/>' +
                'Thanks and best regards.';
        return body;
    }


    public String generateBodyForSalesSwitchedToE2E() {
        String body = 'Dear ' + this.existingOpportunity.Owner.FirstName + ' ' + this.existingOpportunity.Owner.LastName + ',<br/><br/>' +
                'Stage of your opportunity was changed to Closed Lost ' +
                'because your customer started e2e Application and tries to order cards online.<br/>' +
                '<a href="' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + this.existingOpportunity.Id + '" target="_blank">Link to Opportunity</a><br/><br/>' +
                '<a href="' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + this.eteOpportunity.Id + '" target="_blank">Link to E2E Opportunity</a><br/><br/>' +
                'No actions are required at the moment.<br/><br/>' +
                'Thanks and best regards.';
        return body;
    }


    private void sendSingleEmail(String body, String emailToSend) {
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setSubject('E2E Notification');
        message.setHtmlBody(body);
        message.setToAddresses(new List<String>{emailToSend});
        if ( ! Test.isRunningTest() ) {
            Messaging.sendEmail(new List<Messaging.Email>{message});
        }
    }


    public static Account findDupAccount(E2E_Data_Object__c e2EDataObject, Opportunity opportunity, Lead lead) {
        String taxId;
        String companyName;
        String country;
        if (opportunity != null) {
            List<Credit_Factory_Report__c> report = [
                    SELECT Tax_Id__c, Name__c
                    FROM Credit_Factory_Report__c
                    WHERE Opportunity__c = :opportunity.Id
            ];
            if (report.isEmpty()) {
                return null;
            }

            taxId = report.get(0).Tax_Id__c;
            companyName = String.escapeSingleQuotes(report.get(0).Name__c);
            country = ETEGlobalUtils.returnCountry(e2EDataObject.Country_Code__c);
        } else {
            taxId = lead.Steuernummer__c;
            companyName = String.escapeSingleQuotes(lead.Company);
            country = lead.Country;
        }

        String accountId;
        if (opportunity != null && opportunity.AccountId != null) {
            accountId = opportunity.AccountId;
        }

        String accountDupsQuery;
        if (e2EDataObject.RecordType.Name == 'Czech Republic CCS' || e2EDataObject.RecordType.Name == 'Slovakia CCS') {
            accountDupsQuery = generateCCSAccountDupQuery(taxId, accountId, country);
        } else {
            accountDupsQuery = generateAccountDupQuery(taxId, companyName, accountId, country);
        }
        List<Account> accountsDupsList = Database.query(accountDupsQuery);

        if ( ! accountsDupsList.isEmpty() ) {
            return accountsDupsList.get(0);
        }

        return null;
    }


    private static String generateAccountDupQuery(String taxId, String companyName, String accountId, String country) {
        RecordType recordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'CCS' LIMIT 1];
        String recordTypeId = recordType.Id;
        String accountDupsQuery =
                ' SELECT OwnerId, Owner.FirstName, Owner.LastName, Steuernummer__c, Owner.Email, Name ' +
                        ' FROM Account  ' +
                        ' WHERE RecordTypeId != \'' + recordTypeId + '\'' + ' AND Steuernummer__c != NULL AND (Name = \'' + companyName + '\' ';
        if (taxId != null && taxId != '' && taxId != 'unbekannt' && taxId != 'nicht bekannt' && taxId != '0') {
            accountDupsQuery += ' OR Steuernummer__c = \'' + taxId + '\' ';
        }
        accountDupsQuery += ')';
        if (accountId != null) {
            accountDupsQuery += ' AND Id != \'' + accountId + '\'';
        }
        accountDupsQuery += ' AND BillingCountry = \'' + country + '\'' +
                ' ORDER BY CreatedDate DESC ' +
                ' LIMIT 1';

        return accountDupsQuery;
    }


    private static String generateCCSAccountDupQuery(String taxId, String accountId, String country) {
        RecordType recordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'CCS' LIMIT 1];
        String accountDupQuery = 'SELECT OwnerId, Owner.FirstName, Owner.LastName, Steuernummer__c, Owner.Email, Name ' +
                                 'FROM Account ' +
                                 'WHERE RecordTypeId = \'' + recordType.Id + '\' AND Steuernummer__c = \'' + taxId + '\' ';
        if (accountId != null) {
            accountDupQuery += ' AND Id != \'' + accountId + '\'';
        }
        accountDupQuery += ' AND BillingCountry = \'' + country + '\'' +
                ' ORDER BY CreatedDate DESC ' +
                ' LIMIT 1';

        return accountDupQuery;
    }


    private Contact selectDupContact(Opportunity opportunity, Boolean isPrimary) {
        String ocrQuery = 'SELECT ContactId, IsPrimary FROM OpportunityContactRole WHERE OpportunityId = \'' + opportunity.Id + '\'';
        if (isPrimary) {
            ocrQuery += ' AND IsPrimary = ' + isPrimary + '';
        }
        List<OpportunityContactRole> opportunityContactRoles = Database.query(ocrQuery);

        String contactDevName;
        if (this.dataObject.RecordType.Name == 'Czech Republic CCS' || this.dataObject.RecordType.Name == 'Slovakia CCS') {
            contactDevName = 'CCS_Contact_layout';
        } else {
            contactDevName = 'Contact_layout';
        }
        RecordType recordType = [
                SELECT Id
                FROM RecordType
                WHERE SobjectType = 'Contact' AND
                      DeveloperName = :contactDevName
                LIMIT 1];
        String email;
        String phone;
        String firstName;
        String lastName;
        for (E2E_Data_Contact__c e2EDataContact : this.eteDataContacts) {
            if (e2EDataContact.isPrimary__c == isPrimary) {
                email = e2EDataContact.Email__c;
                phone = e2EDataContact.Phone__c.replaceAll(' ', '').replaceAll('-', '');
                firstName = e2EDataContact.First_Name__c;
                lastName = e2EDataContact.Last_Name__c;
            }
        }

        String country = ETEGlobalUtils.returnCountry(this.dataObject.Country_Code__c);

        String contactsQuery;
        if (this.dataObject.RecordType.Name == 'Czech Republic CCS' || this.dataObject.RecordType.Name == 'Slovakia CCS') {
            contactsQuery = generateCCSContactDupQuery(email, phone, firstName, lastName, recordType, opportunityContactRoles, country);
        } else {
            contactsQuery = generateContactDupQuery(email, phone, recordType, opportunityContactRoles, country);
        }
        List<Contact> duplicateContactList = Database.query(contactsQuery);
        if ( ! duplicateContactList.isEmpty() ) {
            return duplicateContactList.get(0);
        }

        return null;
    }


    private static String generateContactDupQuery(String email, String phone, RecordType recordType, List<OpportunityContactRole> contactRoles, String country) {
        String contactDupQuery =
                'SELECT Account.AccountSource, AccountId ' +
                'FROM Contact ' +
                'WHERE (Email = \'' + email + '\'' + ' OR Phone = \'' + phone + '\'' + ') AND ' +
                'MailingCountry = \'' + country + '\'' + ' AND RecordTypeId = \'' + recordType.Id + '\'';
        if ( ! contactRoles.isEmpty() ) {
            contactDupQuery += ' AND Id != \'' + contactRoles.get(0).ContactId + '\'';
        }
        contactDupQuery = contactDupQuery + ' ORDER BY CreatedDate DESC LIMIT 1';

        return contactDupQuery;
    }


    private static String generateCCSContactDupQuery(String email, String phone, String firstName, String lastName, RecordType recordType, List<OpportunityContactRole> contactRoles, String country) {
        String contactDupQuery =
                'SELECT Account.AccountSource, AccountId ' +
                        'FROM Contact ' +
                        'WHERE Email = \'' + email + '\'' + ' AND Phone = \'' + phone + '\'' + ' AND FirstName = \'' + firstName + '\'' + ' AND LastName = \'' + lastName + '\'' + ' AND ' +
                        'MailingCountry = \'' + country + '\'' + ' AND RecordTypeId = \'' + recordType.Id + '\'';
        if ( ! contactRoles.isEmpty() ) {
            contactDupQuery += ' AND Id != \'' + contactRoles.get(0).ContactId  + '\'';
        }
        contactDupQuery = contactDupQuery + ' ORDER BY CreatedDate DESC LIMIT 1';

        return contactDupQuery;
    }
}