default/objects/Account/fields/OBN__c.field-meta.xml
<CustomField>
    <fullName>OBN__c</fullName>
    <label>OBN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Partner_OBN__c.field-meta.xml
<CustomField>
    <fullName>Partner_OBN__c</fullName>
    <label>Partner-OBN</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

default/objects/Account/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>DO Markenpartner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/recordTypes/AllStar.recordType-meta.xml
<RecordType>
    <fullName>AllStar</fullName>
    <active>true</active>
    <label>AllStar</label>
</RecordType>

default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Record type for Partner Accounts of Fleetcor EU</description>
    <label>Partner</label>
</RecordType>

default/objects/Lead/fields/Anzahl_der_Fahrzeuge__c.field-meta.xml
<CustomField>
    <fullName>Anzahl_der_Fahrzeuge__c</fullName>
    <label>Anzahl der Fahrzeuge?</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Lead/fields/CCS_number_of_cards__c.field-meta.xml
<CustomField>
    <fullName>CCS_number_of_cards__c</fullName>
    <label>CCS_number_of_cards</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Первый контакт по inbound</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Anruf</fullName>
            </value>
            <value>
                <fullName>FLMT_Form</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Lead_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Type__c</fullName>
    <label>Lead Source Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Number_of_Cards_facebook__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Cards_facebook__c</fullName>
    <description>Field for the facebook form integration.</description>
    <label>Number of Cards (facebook)</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner-Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.OBN__c</field>
            <operation>notEqual</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Lead/fields/Partner_OBN__c.field-meta.xml
<CustomField>
    <fullName>Partner_OBN__c</fullName>
    <label>Partner-OBN</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Source_of_Lead__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Lead__c</fullName>
    <label>Source of Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Актуализированная БД</fullName>
            </value>
            <value>
                <fullName>Прочая БД</fullName>
                <default>true</default>
                <label>Прочая БД</label>
            </value>
            <value>
                <fullName>Выставка</fullName>
            </value>
            <value>
                <fullName>Найден в Интернете</fullName>
            </value>
            <value>
                <fullName>Реклама Клиента</fullName>
            </value>
            <value>
                <fullName>Рекомендация</fullName>
            </value>
            <value>
                <fullName>Партнерская Программа</fullName>
            </value>
            <value>
                <fullName>Business card</fullName>
            </value>
            <value>
                <fullName>Почтовая рассылка</fullName>
            </value>
            <value>
                <fullName>Реклама на АЗС</fullName>
            </value>
            <value>
                <fullName>Email рассылка</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.ru</fullName>
            </value>
            <value>
                <fullName>Поисковая Система</fullName>
            </value>
            <value>
                <fullName>Реклама в СМИ</fullName>
            </value>
            <value>
                <fullName>Акция Рекомендация</fullName>
            </value>
            <value>
                <fullName>Интернет Источники</fullName>
            </value>
            <value>
                <fullName>Сайт fuel.veb-leasing.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.kz</fullName>
            </value>
            <value>
                <fullName>Petrolcards.ru - АГГРЕГАТОР</fullName>
            </value>
            <value>
                <fullName>АЗС Заявка Shell</fullName>
            </value>
            <value>
                <fullName>Facebook_Lotos</fullName>
            </value>
            <value>
                <fullName>Facebook_CCS</fullName>
            </value>
            <value>
                <fullName>Сайт gpc-store.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Shell Card.ru</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/recordTypes/AllStar.recordType-meta.xml
<RecordType>
    <fullName>AllStar</fullName>
    <active>true</active>
    <businessProcess>Datensatztyp</businessProcess>
    <label>AllStar</label>
</RecordType>

default/objects/Lead_Switched_To_E2E__c/Lead_Switched_To_E2E__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Lead Switched To E2E</label>
</CustomObject>

default/objects/Lead_Switched_To_E2E__c/fields/Max_Cards__c.field-meta.xml
<CustomField>
    <fullName>Max_Cards__c</fullName>
    <label>Max Cards</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Lead_Switched_To_E2E__c/fields/Min_Cards__c.field-meta.xml
<CustomField>
    <fullName>Min_Cards__c</fullName>
    <label>Min Cards</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/LeadRelocationSettings__c/LeadRelocationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>LeadRelocationSettings</label>
</CustomObject>

default/objects/LeadRelocationSettings__c/fields/EU_Enabled__c.field-meta.xml
<CustomField>
    <fullName>EU_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enables relocation of EU Leads in LeadRelocationBatch</description>
    <label>EU Enabled</label>
    <type>Checkbox</type>
</CustomField>

default/classes/LeadRelocationServiceTest.cls
@isTest
private class LeadRelocationServiceTest {
	@isTest
	public static void testService() {
		createCustomSettings();
		List<Lead> leadsToInsert = new List<Lead>();

		Lead l = new Lead(
			LastName = 'test',
			CountryCode = 'AT',
			Sec_Channel__c = 'Inbound',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l);

		Lead l2 = new Lead(
			LastName = 'test',
			CountryCode = 'DE',
			Sec_Channel__c = 'Inbound',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l2);

		Lead l3 = new Lead(
			LastName = 'test',
			CountryCode = 'PL',
			Sec_Channel__c = 'Inbound',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l3);

		Lead l4 = new Lead(
			LastName = 'test',
			CountryCode = 'FR',
			Sec_Channel__c = 'Inbound',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l4);

		Lead l5 = new Lead(
			LastName = 'test',
			CountryCode = 'HU',
			Sec_Channel__c = 'Inbound',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l5);

		Lead l6 = new Lead(
			LastName = 'test',
			CountryCode = 'NL',
			Sec_Channel__c = 'Inbound',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l6);

		Lead l7 = new Lead(
			LastName = 'test',
			CountryCode = 'BEFR',
			Sec_Channel__c = 'Inbound',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l7);

		Lead l9 = new Lead(
			LastName = 'test',
			CountryCode = 'CHDE',
			Sec_Channel__c = 'Inbound',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l9);

		Lead l10 = new Lead(
			LastName = 'test',
			CountryCode = 'CHIT',
			Sec_Channel__c = 'Inbound',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l10);

		Lead l10chit = new Lead(
			LastName = 'test',
			CountryCode = 'CHIT',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l10chit);

		Lead l10chfr = new Lead(
			LastName = 'test',
			CountryCode = 'CHFR',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l10chfr);

		Lead l10lu = new Lead(
			LastName = 'test',
			CountryCode = 'LU',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l10lu);

		Lead l10cz = new Lead(
			LastName = 'test',
			CountryCode = 'CZ',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l10cz);

		Lead l11 = new Lead(
			LastName = 'test',
			CountryCode = 'CHFR',
			Sec_Channel__c = 'Inbound',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l11);

		Lead l12 = new Lead(
			LastName = 'test',
			CountryCode = 'LU',
			Sec_Channel__c = 'Inbound',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l12);

		Lead l13 = new Lead(
			LastName = 'test',
			CountryCode = 'CZ',
			Sec_Channel__c = 'Inbound',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l13);

		Lead l14 = new Lead(
			LastName = 'test',
			CountryCode = 'SK',
			Sec_Channel__c = 'Inbound',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l14);

		Lead l15 = new Lead(
			LastName = 'test',
			CountryCode = 'BENL',
			Sec_Channel__c = 'JITB',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l15);

		Lead l16 = new Lead(
			LastName = 'test',
			CountryCode = 'BEFR',
			Sec_Channel__c = 'JITB',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l16);

		Lead l17 = new Lead(
			LastName = 'test',
			CountryCode = 'FR',
			Sec_Channel__c = 'JITB',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l17);

		Lead l18 = new Lead(
			LastName = 'test',
			CountryCode = 'NL',
			Sec_Channel__c = 'JITB',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l18);

		Lead l19 = new Lead(
			LastName = 'test',
			CountryCode = 'CZ',
			Sec_Channel__c = 'JITB',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l19);

		Lead l20 = new Lead(
			LastName = 'test',
			CountryCode = 'SK',
			Sec_Channel__c = 'JITB',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l20);

		Lead l21 = new Lead(
			LastName = 'test',
			CountryCode = 'HU',
			Sec_Channel__c = 'JITB',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l21);

		Lead l22 = new Lead(
			LastName = 'test',
			CountryCode = 'PL',
			Sec_Channel__c = 'JITB',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l22);

		Lead l22CHDE = new Lead(
				LastName = 'test',
				CountryCode = 'CHDE',
				Sec_Channel__c = 'JITB',
				Channel__c = 'Internet',
				Phone = '1231231231',
				Company = 'test');
		leadsToInsert.add(l22CHDE);

		Lead l22CHFR = new Lead(
				LastName = 'test',
				CountryCode = 'CHFR',
				Sec_Channel__c = 'JITB',
				Channel__c = 'Internet',
				Phone = '1231231231',
				Company = 'test');
		leadsToInsert.add(l22CHFR);

		Lead l23 = new Lead(
			LastName = 'test',
			CountryCode = 'SK',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l23);

		Lead l24 = new Lead(
			LastName = 'test',
			CountryCode = 'HU',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l24);

		Lead l25 = new Lead(
			LastName = 'test',
			CountryCode = 'PL',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l25);

		Lead l26 = new Lead(
			LastName = 'test',
			CountryCode = 'DE',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l26);

		Lead l27 = new Lead(
			LastName = 'test',
			CountryCode = 'AT',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l27);

		Lead l28 = new Lead(
			LastName = 'test',
			CountryCode = 'CHDE',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l28);

		Lead l29 = new Lead(
			LastName = 'test',
			CountryCode = 'BENL',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l29);

		Lead l30 = new Lead(
			LastName = 'test',
			CountryCode = 'NL',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l30);

		Lead l31 = new Lead(
			LastName = 'test',
			CountryCode = 'BEFR',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l31);

		Lead l32 = new Lead(
				LastName = 'test',
				CountryCode = 'RU',
				Country = 'Russia',
				Lead_Source_Type__c = 'Webform',
				Phone = '+71231231231',
				Company = 'test');
		leadsToInsert.add(l32);

		Lead l33 = new Lead(
				LastName = 'test',
				CountryCode = 'RU',
				Country = 'Russia',
				Lead_Source_Type__c = 'Email',
				Phone = '+71231231231',
				Company = 'test');
		leadsToInsert.add(l33);

		Lead l34 = new Lead(
				LastName = 'test',
				CountryCode = 'RU',
				Country = 'Russia',
				Lead_Source_Type__c = 'Chat',
				Phone = '+71231231231',
				Company = 'test');
		leadsToInsert.add(l34);

		Lead l35 = new Lead(
				LastName = 'test',
				CountryCode = 'RU',
				Country = 'Russia',
				Lead_Source_Type__c = 'Popup',
				Phone = '+71231231231',
				Company = 'test');
		leadsToInsert.add(l35);
		Lead l36 = new Lead(
				LastName = 'test',
				CountryCode = 'RU',
				Country = 'Russia',
				Lead_Source_Type__c = 'Webform',
				Phone = '+71231231231',
				Company = 'test',
				Source_of_Lead__c = 'Сайт Petrolplus.ru');
		leadsToInsert.add(l36);

		RecordType allstarLeadRecordType = [
                SELECT Id
                FROM RecordType
                WHERE Name = 'AllStar' AND SobjectType = 'Lead'
                LIMIT 1];

        Lead l37 = new Lead(
			LastName = 'test',
			CountryCode = 'BEFR',
			Sec_Channel__c = 'Partner',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test',
			RecordTypeId = allstarLeadRecordType.Id);
		leadsToInsert.add(l37);

		Lead l38 = new Lead(
			LastName = 'test',
			CountryCode = 'PL',
			Sec_Channel__c = 'JITB',
			Channel__c = 'Internet',
			Phone = '1231231231',
			Company = 'test');
		leadsToInsert.add(l38);

		insert leadsToInsert;

		Datetime dd = Datetime.now().addMinutes(-15);
		for (Lead ll : leadsToInsert) {
			Test.setCreatedDate(ll.Id, dd);
		}

		Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
		User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
		EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
		LocaleSidKey='en_US', ProfileId = p.Id,
		TimeZoneSidKey='America/Los_Angeles', UserName='standarduser-flt123@testorg.com');
		insert u;

		for (Lead ll : leadsToInsert) {
			ll.OwnerId = u.Id;
		}

		update leadsToInsert;
	}

	@isTest
	public static void testAdoptionDeals() {
		createCustomSettings();
		// do not add next leads to list cause need to test adoption deals
		Test.startTest();
			Lead shellEmailLead = new Lead(
					Sec_Channel__c = 'Inbound',
					Channel__c = 'E-mail',
					LeadSource = 'Shell Email',
					Phone = '32132132',
					Email = 'fook@floyd.com',
					Company = 'YOLO',
					Country = 'Belgium-FR',
					CountryCode = 'BEFR',
					Salutation = 'Mr',
					FirstName = 'fook',
					LastName = 'floyd',
					CCS_number_of_cards__c = 2
			);
			insert shellEmailLead;

			Lead facebookLead = new Lead(
					Sec_Channel__c = 'Inbound',
					Channel__c = 'E-mail',
					LeadSource = 'Facebook',
					Phone = '32132132',
					Email = 'fook@floyd.com',
					Company = 'YOLO',
					Country = 'Belgium-NL',
					CountryCode = 'BENL',
					Salutation = 'Mr',
					FirstName = 'fook',
					LastName = 'floyd',
					Number_of_Cards_facebook__c = '2'
			);
			insert facebookLead;

			Lead tabletFormLead = new Lead(
					Sec_Channel__c = 'Inbound',
					Channel__c = 'E-mail',
					LeadSource = 'Tablet Short Form',
					Phone = '32132132',
					Email = 'fook@floyd.com',
					Company = 'YOLO',
					Country = 'Germany',
					CountryCode = 'DE',
					Salutation = 'Mr',
					FirstName = 'fook',
					LastName = 'floyd',
					CCS_number_of_cards__c = 2
			);
			insert tabletFormLead;

			Account partnerAccount = new Account(
					Name = 'test',
					OBN__c = '9897',
					BillingCountry = 'Germany');
			insert partnerAccount;

			Lead partnerJITBLeadDE = new Lead(
					Sec_Channel__c = 'JITB',
					Channel__c = 'Internet',
					LeadSource = 'Partner',
					Phone = '32132132',
					Email = 'fook@floyd.com',
					Company = 'YOLO',
					Country = 'Germany',
					CountryCode = 'DE',
					Salutation = 'Mr',
					FirstName = 'fook',
					LastName = 'floyd',
					Anzahl_der_Fahrzeuge__c = 2,
					Partner__c = partnerAccount.Id,
					Partner_OBN__c = '9897'
			);
			insert partnerJITBLeadDE;

			Lead partnerJITBLeadCHDE = new Lead(
					Sec_Channel__c = 'JITB',
					Channel__c = 'Internet',
					LeadSource = 'Partner',
					Phone = '32132132',
					Email = 'fook@floyd.com',
					Company = 'YOLO',
					Country = 'Switzerland-DE',
					CountryCode = 'CHDE',
					Salutation = 'Mr',
					FirstName = 'fook',
					LastName = 'floyd',
					CCS_number_of_cards__c = 2,
					Partner__c = partnerAccount.Id,
					Partner_OBN__c = '9897'
			);
			insert partnerJITBLeadCHDE;
		Test.stopTest();
	}

	public static void createCustomSettings() {
		List<Lead_Switched_To_E2E__c> leadSwitchedToE2EList = new List<Lead_Switched_To_E2E__c>();
		for (String country : GlobalUtils.countryCodeToCountryMap.values()) {
			Lead_Switched_To_E2E__c switchedToE2ESettings = new Lead_Switched_To_E2E__c(
					Name = country,
					Min_Cards__c = 1,
					Max_Cards__c = 2);
			leadSwitchedToE2EList.add(switchedToE2ESettings);

			Lead_Switched_To_E2E__c switchedToE2EJITBSettings = new Lead_Switched_To_E2E__c(
					Name = country + 'JITB',
					Min_Cards__c = 1,
					Max_Cards__c = 2);
			leadSwitchedToE2EList.add(switchedToE2EJITBSettings);
		}
		insert leadSwitchedToE2EList;

		LeadRelocationSettings__c leadRelocationSettings = new LeadRelocationSettings__c(EU_Enabled__c = true);
		insert leadRelocationSettings;
	}
}