default/objects/Account/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Возможность</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Организации</relationshipLabel>
    <relationshipName>Account6VaS</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Client_Offer_Additional_Service__c/Client_Offer_Additional_Service__c.object-meta.xml
<CustomObject>
    <label>Client Offer Additional Service</label>
    <nameField>
        <displayFormat>COAS-{0000000}</displayFormat>
        <label>Client Offer Additional Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Offer Additional Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Client_Offer_Additional_Service__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Offer Additional Services</relationshipLabel>
    <relationshipName>Client_Offer_Additional_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Client_Offer_Additional_Service__c/fields/Additional_Service__c.field-meta.xml
<CustomField>
    <fullName>Additional_Service__c</fullName>
    <label>Additional Service</label>
    <referenceTo>Additional_Service__c</referenceTo>
    <relationshipLabel>Client Offer Additional Services</relationshipLabel>
    <relationshipName>Client_Offer_Additional_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Opportunity/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Belgium-FR</fullName>
            </value>
            <value>
                <fullName>Belgium-NL</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Lithuania</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
            <value>
                <fullName>Switzerland-DE</fullName>
            </value>
            <value>
                <fullName>Switzerland-FR</fullName>
            </value>
            <value>
                <fullName>Switzerland-IT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/E2E_2__c.field-meta.xml
<CustomField>
    <fullName>E2E_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>E2E 2</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Для определения # возможности</description>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>#Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Product2/fields/Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Name__c</fullName>
    <label>Integration Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/classes/TemporaryBatchTest.cls
@IsTest
private class TemporaryBatchTest {
    @TestSetup
    static void makeData () {
        Account account = new Account(
                Name = 'test',
                BillingCountry = 'Poland'
        );
        insert account;

        Opportunity opp = new Opportunity(
                AccountId = account.Id,
                StageName = 'Prospecting',
                CloseDate = Date.today(),
                Name = 'test opp',
                E2E_2__c = true,
                Pricebook2Id = Test.getStandardPricebookId(),
                CurrencyIsoCode = 'PLN'
        );
        insert opp;

        Map<String, Product2> productsMap = new Map<String, Product2>();
        productsMap.put('Shell Basic 2020', new Product2(
                Name = 'Shell Basic 2020',
                Integration_Name__c = 'shellpl',
                IsActive = true,
                Family = 'Shell'
        ));
        insert productsMap.values();

        Map<String, PricebookEntry> priceBookEntryMap = new Map<String, PricebookEntry>();
        priceBookEntryMap.put('Shell PBE', new PricebookEntry(
                Pricebook2Id = Test.getStandardPricebookId(),
                Product2Id = productsMap.get('Shell Basic 2020').Id,
                UnitPrice = 0,
                CurrencyIsoCode = 'PLN',
                IsActive = true
        ));
        insert priceBookEntryMap.values();

        Map<String, OpportunityLineItem> opportunityLineItemsMap = new Map<String, OpportunityLineItem>();
        opportunityLineItemsMap.put('Shell OLI', new OpportunityLineItem(
                OpportunityId = opp.Id,
                Product2Id = productsMap.get('Shell Basic 2020').Id,
                PricebookEntryId = priceBookEntryMap.get('Shell PBE').Id,
                Quantity = 2,
                UnitPrice = 0
        ));
        insert opportunityLineItemsMap.values();

        Additional_Service__c addService = new Additional_Service__c(
                Type__c = 'Eco Fee',
                Amount__c = 10,
                Country__c = 'Poland',
                Integration_Name__c = 'ecofeepl'
        );
        insert addService;

        Client_Offer_Additional_Service__c oas = new Client_Offer_Additional_Service__c(
                Opportunity__c = opp.Id,
                Selected__c = true,
                Additional_Service__c = addService.Id
        );
        insert oas;
    }

    @IsTest
    static void testTemporaryBatchToUpdateOppLineItems () {
        OpportunityLineItem lineItem = [SELECT Account__c FROM OpportunityLineItem];
        Account acc = [SELECT Id FROM Account];
        System.assertEquals(acc.Id, lineItem.Account__c);

        lineItem.Account__c = null;
        update lineItem;
        System.assertEquals(null, [SELECT Account__c FROM OpportunityLineItem].Account__c);

        Test.startTest();
        Database.executeBatch(new TemporaryBatchToUpdateOppLineItems(), 1);
        Test.stopTest();

        System.assertEquals(acc.Id, [SELECT Account__c FROM OpportunityLineItem].Account__c);
    }

    @IsTest
    static void testTemporaryBatchToUpdateClientOfferAS () {
        Client_Offer_Additional_Service__c addService = [SELECT Account__c FROM Client_Offer_Additional_Service__c];
        Account acc = [SELECT Id FROM Account];
        System.assertEquals(acc.Id, addService.Account__c);

        ClientOfferAddServiceHandler.enablesTrigger = false;
        addService.Account__c = null;
        update addService;
        ClientOfferAddServiceHandler.enablesTrigger = true;
        System.assertEquals(null, [SELECT Account__c FROM Client_Offer_Additional_Service__c].Account__c);

        Test.startTest();
        Database.executeBatch(new TemporaryBatchToUpdateClientOfferAS(), 1);
        Test.stopTest();

        System.assertEquals(acc.Id, [SELECT Account__c FROM Client_Offer_Additional_Service__c].Account__c);
    }
}