default/objects/Account/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Возможность</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Организации</relationshipLabel>
    <relationshipName>Account6VaS</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Account/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>DO Markenpartner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/recordTypes/Russian.recordType-meta.xml
<RecordType>
    <fullName>Russian</fullName>
    <active>true</active>
    <label>Russian</label>
</RecordType>

default/objects/CF_Settings__c/CF_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for scoring and black list services for manual sales</description>
    <label>CF Settings</label>
</CustomObject>

default/objects/CF_Settings__c/fields/Check_on_opportunity_create__c.field-meta.xml
<CustomField>
    <fullName>Check_on_opportunity_create__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks record when it is created</description>
    <inlineHelpText>Checks record when it is created</inlineHelpText>
    <label>Check on opportunity create</label>
    <type>Checkbox</type>
</CustomField>

default/objects/CF_Settings__c/fields/Check_on_opportunity_update__c.field-meta.xml
<CustomField>
    <fullName>Check_on_opportunity_update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks record when it is updated</description>
    <inlineHelpText>Checks record when it is updated</inlineHelpText>
    <label>Check on opportunity update</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Emarsys_Contact_Subscriptions__c/Emarsys_Contact_Subscriptions__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Emarsys Contact Subscriptions</label>
</CustomObject>

default/objects/Emarsys_Contact_Subscriptions__c/fields/Email_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Name__c</fullName>
    <description>Emarsys email category / email name</description>
    <label>Email Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

default/objects/Emarsys_Contact_Subscriptions__c/fields/Subscription_Name__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Name__c</fullName>
    <label>Subscription Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Emarsys_Contact_Subscriptions__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

default/objects/Emarsys_Log__c/Emarsys_Log__c.object-meta.xml
<CustomObject>
    <label>Emarsys Log</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Emarsys Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emarsys Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Emarsys_Log__c/fields/Email_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Name__c</fullName>
    <label>Email Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Emarsys_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Emarsys Logs</relationshipLabel>
    <relationshipName>Emarsys_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Emarsys_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Emarsys Logs</relationshipLabel>
    <relationshipName>Emarsys_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Emarsys_Log__c/fields/Owner_Manager_Email__c.field-meta.xml
<CustomField>
    <fullName>Owner_Manager_Email__c</fullName>
    <label>Owner Manager Email</label>
    <type>Email</type>
</CustomField>

default/objects/Emarsys_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reaction Open or Click</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Clicked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Первый контакт по inbound</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Anruf</fullName>
            </value>
            <value>
                <fullName>FLMT_Form</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Emarsys_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Emarsys_Contact_Id__c</fullName>
    <label>Emarsys Contact Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Carnet Standard 2019</fullName>
            </value>
            <value>
                <fullName>Shell Universal Card</fullName>
            </value>
            <value>
                <fullName>Carnet OBD</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes Standard</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes No fee</fullName>
            </value>
            <value>
                <fullName>Shell Basic 2020</fullName>
            </value>
            <value>
                <fullName>Shell No fee 2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Angebotsdauer__c.field-meta.xml
<CustomField>
    <fullName>Angebotsdauer__c</fullName>
    <label>Angebotsdauer</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3 Monate</fullName>
            </value>
            <value>
                <fullName>4 Monate</fullName>
            </value>
            <value>
                <fullName>5 Monate</fullName>
            </value>
            <value>
                <fullName>6 Monate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Anruf</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Для определения # возможности</description>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>#Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product *</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BE-FR 2,5 Cent</fullName>
            </value>
            <value>
                <fullName>Carnet OBD</fullName>
            </value>
            <value>
                <fullName>Carnet Standard 2019</fullName>
            </value>
            <value>
                <fullName>Fuel Vehicle</fullName>
            </value>
            <value>
                <fullName>HOME 1</fullName>
            </value>
            <value>
                <fullName>Home Station offer (v.1)</fullName>
            </value>
            <value>
                <fullName>Inbound Typ B</fullName>
            </value>
            <value>
                <fullName>Inbound Typ C</fullName>
            </value>
            <value>
                <fullName>LOCAL - RED</fullName>
            </value>
            <value>
                <fullName>LOCAL - YELLOW</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes No fee</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes Standard</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>Sales no fee promo Feb 2016</fullName>
            </value>
            <value>
                <fullName>Shell Basic 2020</fullName>
            </value>
            <value>
                <fullName>Shell No fee 2020</fullName>
            </value>
            <value>
                <fullName>Shell Outbound 2020</fullName>
            </value>
            <value>
                <fullName>Shell Universal Card</fullName>
            </value>
            <value>
                <fullName>Smart</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + % fee)</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + fixed fee)</fullName>
            </value>
            <value>
                <fullName>Sonderangebot (s. Notizen)</fullName>
            </value>
            <value>
                <fullName>Swiss Pro</fullName>
            </value>
            <value>
                <fullName>Swiss Pro 5</fullName>
            </value>
            <value>
                <fullName>Swiss Star</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/EmarsysReactionLogsScheduleTest.cls
@isTest
private class EmarsysReactionLogsScheduleTest {

    /*******************************************************************************
    *  Name            : createLeadLogsTest()
    *  Summary         : test creating logs
    *  CreatedDate     : 21/08/2017
    *  Parameters      : -
    *  Returns         : void
    ******************************************************************************/
    @isTest
    static void createLeadLogsTest() {
        List<RecordType> rtList = [
                SELECT Id
                FROM RecordType
                WHERE Name = 'Russian Sales' AND SobjectType = 'Lead'
                LIMIT 1
        ];

        Profile p = [SELECT Id FROM Profile WHERE Name = 'API Only'];

        User user = new User(Username = 'usertest123@fleetcor.de', ProfileId = p.Id, Alias = 'uset@fl', Email = 'usertes64t@fleetcor.de',
                EmailEncodingKey = 'UTF-8', Lastname = 'usertest', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', TimeZoneSidKey = 'America/Chicago');
        insert user;

        Lead lead = new Lead(
                Status = 'Contacted',
                LastName = 'test',
                Company = 'test',
                Phone = '+491234567890',
                Country = 'Germany',
                CountryCode = 'DE',
                State = 'Bavaria',
                Email = 'test@test.com',
                OwnerId = user.Id,
                Channel__c = 'Inbound',
                RecordTypeId = rtList.get(0).Id,
                Sec_Channel__c = 'Fax',
                Emarsys_Contact_Id__c = '393615693');
        insert lead;

        Test.setCreatedDate(lead.Id, Date.today().addDays(-5));
        Emarsys_Contact_Subscriptions__c leadSubscription = new Emarsys_Contact_Subscriptions__c(
                Name = 'Lead Test Subscription',
                Subscription_Name__c = 'Lead Subscription',
                Type__c = 'Lead');
        insert leadSubscription;

        Test.StartTest();

        Test.setMock(HttpCalloutMock.class, new ListingContactsHttpResponseGenerator());
        EmarsysReactionLogsSchedule schedule = new EmarsysReactionLogsSchedule();
        schedule.execute(null);

        Test.stopTest();

        List<Emarsys_Log__c> leadLogsList = [
                SELECT Email_Name__c, Owner_Manager_Email__c
                FROM Emarsys_Log__c
                WHERE Lead__c = :lead.Id
        ];
        System.assertEquals(leadLogsList.size(), 1);
    }


    /*******************************************************************************
     *  Name            : createOpportunityLogsTest()
     *  Summary         : test creating logs
     *  CreatedDate     : 21/08/2017
     *  Parameters      : -
     *  Returns         : void
     ******************************************************************************/
    @isTest
    static void createOpportunityLogsTest() {

        createCustomSettings();

        List<RecordType> rtList = [
                SELECT Id
                FROM RecordType
                WHERE Name = 'Russian Sales' AND SobjectType = 'Opportunity'
                LIMIT 1
        ];


        Profile p = [SELECT Id FROM Profile WHERE Name = 'API Only'];

        User user = new User(Username = 'usertest123@fleetcor.de', ProfileId = p.Id, Alias = 'uset@fl', Email = 'usertes64t@fleetcor.de',
                EmailEncodingKey = 'UTF-8', Lastname = 'usertest', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', TimeZoneSidKey = 'America/Chicago');
        insert user;

        Account account = new Account(
                Name = 'Test',
                BillingCountry = 'Germany');
        insert account;

        Opportunity opportunity = new Opportunity(
                Name = 'Test', StageName = 'Prospecting',
                AccountID = account.Id,
                CloseDate = date.today().addMonths(1),
                Product__c = 'Home Station offer (v.1)',
                Angebotsdauer__c = '3 Monate',
                RecordTypeId = rtList.get(0).Id,
                OwnerId = user.Id,
                Emarsys_Contact_Id__c = '393615693');
        insert opportunity;

        Emarsys_Contact_Subscriptions__c leadSubscription = new Emarsys_Contact_Subscriptions__c(
                Name = 'Opportunity Test Subscription',
                Subscription_Name__c = 'Opportunity Subscription',
                Type__c = 'Opportunity');
        insert leadSubscription;

        Test.StartTest();

        Test.setMock(HttpCalloutMock.class, new ListingContactsHttpResponseGenerator());
        EmarsysReactionLogsSchedule schedule = new EmarsysReactionLogsSchedule();
        schedule.execute(null);

        Test.stopTest();

        List<Emarsys_Log__c> opportunityLogsList = [
                SELECT Email_Name__c, Owner_Manager_Email__c
                FROM Emarsys_Log__c
                WHERE Opportunity__c = :opportunity.Id
        ];
        System.assertEquals(opportunityLogsList.size(), 1);
    }

    private static void createCustomSettings() {
        CF_Settings__c cf_settings = new CF_Settings__c();
        cf_settings.Name = 'Russia';
        cf_settings.Check_on_opportunity_create__c = false;
        cf_settings.Check_on_opportunity_update__c = false;
        insert cf_settings;
    }
}