default/objects/Account/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Возможность</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Организации</relationshipLabel>
    <relationshipName>Account6VaS</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Client_Offer_Additional_Service__c/Client_Offer_Additional_Service__c.object-meta.xml
<CustomObject>
    <label>Client Offer Additional Service</label>
    <nameField>
        <displayFormat>COAS-{0000000}</displayFormat>
        <label>Client Offer Additional Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Offer Additional Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Client_Offer_Additional_Service__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Offer Additional Services</relationshipLabel>
    <relationshipName>Client_Offer_Additional_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Client_Offer_Additional_Service__c/fields/Additional_Service__c.field-meta.xml
<CustomField>
    <fullName>Additional_Service__c</fullName>
    <label>Additional Service</label>
    <referenceTo>Additional_Service__c</referenceTo>
    <relationshipLabel>Client Offer Additional Services</relationshipLabel>
    <relationshipName>Client_Offer_Additional_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Opportunity/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Belgium-FR</fullName>
            </value>
            <value>
                <fullName>Belgium-NL</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Lithuania</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
            <value>
                <fullName>Switzerland-DE</fullName>
            </value>
            <value>
                <fullName>Switzerland-FR</fullName>
            </value>
            <value>
                <fullName>Switzerland-IT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Eco_Fee__c.field-meta.xml
<CustomField>
    <fullName>Eco_Fee__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Tick to set, to choose if the Customer want to take Eco Fee or not.</description>
    <label>Eco Fee</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Для определения # возможности</description>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>#Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Papierrechnung__c.field-meta.xml
<CustomField>
    <fullName>Papierrechnung__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Papierrechnung</label>
    <type>Checkbox</type>
</CustomField>

default/classes/ClientOfferAddServiceTriggerTest.cls
@IsTest
private class ClientOfferAddServiceTriggerTest {
    @IsTest
    static void testAddAdditionalServicesToOpp() {
        Opportunity opp = new Opportunity(
                StageName = 'Prospecting',
                CloseDate = Date.today(),
                Name = 'test opp'
        );
        insert opp;

        List<Additional_Service__c> addservices = new List<Additional_Service__c>();
        Additional_Service__c addService = new Additional_Service__c(
                Type__c = 'Eco Fee',
                Amount__c = 10,
                Country__c = 'Poland',
                Integration_Name__c = 'ecofeepl'
        );
        Additional_Service__c addService2 = new Additional_Service__c(
                Type__c = 'Paper Invoice',
                Amount__c = 10,
                Country__c = 'Poland',
                Integration_Name__c = 'paperinvoicepl'
        );
        Additional_Service__c addService3 = new Additional_Service__c(
                Type__c = 'VAT Refund',
                Amount__c = 10,
                Country__c = 'Poland',
                Integration_Name__c = 'vatrefundpl'
        );
        addservices.add(addService);
        addservices.add(addService2);
        addservices.add(addService3);
        insert addservices;

        List<Client_Offer_Additional_Service__c> oasList = new List<Client_Offer_Additional_Service__c>();
        Client_Offer_Additional_Service__c oas = new Client_Offer_Additional_Service__c(
                Opportunity__c = opp.Id,
                Selected__c = true,
                Additional_Service__c = addService.Id
        );
        Client_Offer_Additional_Service__c oas2 = new Client_Offer_Additional_Service__c(
                Opportunity__c = opp.Id,
                Selected__c = true,
                Additional_Service__c = addService2.Id
        );
        Client_Offer_Additional_Service__c oas3 = new Client_Offer_Additional_Service__c(
                Opportunity__c = opp.Id,
                Selected__c = true,
                Additional_Service__c = addService3.Id
        );
        oasList.add(oas);
        oasList.add(oas2);
        oasList.add(oas3);
        insert oasList;

        Opportunity testOpp = [
                SELECT Eco_Fee__c, VAT_Recovery__c, Papierrechnung__c
                FROM Opportunity
                WHERE Id = :opp.Id
        ];
        System.assert(testOpp.Eco_Fee__c == true);
        System.assert(testOpp.VAT_Recovery__c == true);
        System.assert(testOpp.Papierrechnung__c == true);

        for (Client_Offer_Additional_Service__c oasitem : oasList) {
            oasitem.Selected__c = false;
        }
        update oasList;

        Opportunity testOpp2 = [
                SELECT Eco_Fee__c, VAT_Recovery__c, Papierrechnung__c
                FROM Opportunity
                WHERE Id = :opp.Id
        ];
        System.assert(testOpp2.Eco_Fee__c == false);
        System.assert(testOpp2.VAT_Recovery__c == false);
        System.assert(testOpp2.Papierrechnung__c == false);
    }


    @IsTest
    static void testRemoveServicesFromOpp() {
        Opportunity opp = new Opportunity(
                StageName = 'Prospecting',
                CloseDate = Date.today(),
                Name = 'test opp'
        );
        insert opp;

        List<Additional_Service__c> addservices = new List<Additional_Service__c>();
        Additional_Service__c addService = new Additional_Service__c(
                Type__c = 'Eco Fee',
                Amount__c = 10,
                Country__c = 'Poland',
                Integration_Name__c = 'ecofeepl'
        );
        Additional_Service__c addService2 = new Additional_Service__c(
                Type__c = 'Paper Invoice',
                Amount__c = 10,
                Country__c = 'Poland',
                Integration_Name__c = 'pipl'
        );
        Additional_Service__c addService3 = new Additional_Service__c(
                Type__c = 'VAT Refund',
                Amount__c = 10,
                Country__c = 'Poland',
                Integration_Name__c = 'vatpl'
        );
        addservices.add(addService);
        addservices.add(addService2);
        addservices.add(addService3);
        insert addservices;

        List<Client_Offer_Additional_Service__c> oasList = new List<Client_Offer_Additional_Service__c>();
        Client_Offer_Additional_Service__c oas = new Client_Offer_Additional_Service__c(
                Opportunity__c = opp.Id,
                Additional_Service__c = addService.Id,
                Selected__c = true
        );
        Client_Offer_Additional_Service__c oas2 = new Client_Offer_Additional_Service__c(
                Opportunity__c = opp.Id,
                Additional_Service__c = addService2.Id
        );
        Client_Offer_Additional_Service__c oas3 = new Client_Offer_Additional_Service__c(
                Opportunity__c = opp.Id,
                Additional_Service__c = addService3.Id
        );
        oasList.add(oas);
        oasList.add(oas2);
        oasList.add(oas3);
        insert oasList;

        Test.startTest();
        delete oasList;

        Opportunity testOpp = [
                SELECT Eco_Fee__c, VAT_Recovery__c, Papierrechnung__c
                FROM Opportunity
                WHERE Id = :opp.Id
        ];
        System.assert(testOpp.Eco_Fee__c == false);
        System.assert(testOpp.VAT_Recovery__c == false);
        System.assert(testOpp.Papierrechnung__c == false);
        Test.stopTest();
    }


    @IsTest
    static void testPrefillAccountLookup () {
        Account account = new Account(
                Name = 'test',
                BillingCountry = 'Poland'
        );
        insert account;

        Opportunity opp = new Opportunity(
                AccountId = account.Id,
                StageName = 'Prospecting',
                CloseDate = Date.today(),
                Name = 'test opp'
        );
        insert opp;

        List<Additional_Service__c> addservices = new List<Additional_Service__c>();
        Additional_Service__c addService = new Additional_Service__c(
                Type__c = 'Eco Fee',
                Amount__c = 10,
                Country__c = 'Poland',
                Integration_Name__c = 'ecofeepl'
        );
        Additional_Service__c addService2 = new Additional_Service__c(
                Type__c = 'Paper Invoice',
                Amount__c = 10,
                Country__c = 'Poland',
                Integration_Name__c = 'pipl'
        );
        Additional_Service__c addService3 = new Additional_Service__c(
                Type__c = 'VAT Refund',
                Amount__c = 10,
                Country__c = 'Poland',
                Integration_Name__c = 'vatpl'
        );
        addservices.add(addService);
        addservices.add(addService2);
        addservices.add(addService3);
        insert addservices;

        List<Client_Offer_Additional_Service__c> oasList = new List<Client_Offer_Additional_Service__c>();
        Client_Offer_Additional_Service__c oas = new Client_Offer_Additional_Service__c(
                Opportunity__c = opp.Id,
                Additional_Service__c = addService.Id,
                Selected__c = true
        );
        Client_Offer_Additional_Service__c oas2 = new Client_Offer_Additional_Service__c(
                Opportunity__c = opp.Id,
                Additional_Service__c = addService2.Id
        );
        Client_Offer_Additional_Service__c oas3 = new Client_Offer_Additional_Service__c(
                Additional_Service__c = addService3.Id
        );
        oasList.add(oas);
        oasList.add(oas2);
        oasList.add(oas3);
        insert oasList;

        oas3.Opportunity__c = opp.Id;
        update oas3;

        Test.startTest();
        {
            for (Client_Offer_Additional_Service__c nextClientOfferAdditionalService : [SELECT Account__c FROM Client_Offer_Additional_Service__c]) {
                System.assertEquals(account.Id, nextClientOfferAdditionalService.Account__c);
            }
        }
        Test.stopTest();
    }
}