default/objects/Account/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Возможность</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Организации</relationshipLabel>
    <relationshipName>Account6VaS</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Для определения # возможности</description>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>#Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Tankkarten__c/Tankkarten__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <displayFormat>TK-{000000}</displayFormat>
        <label>Tankkarten</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Tankkarten__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tankkarten</relationshipLabel>
    <relationshipName>Tankkarten</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Tankkarten__c/fields/Firmenname_auf_der_Karte__c.field-meta.xml
<CustomField>
    <fullName>Firmenname_auf_der_Karte__c</fullName>
    <label>Firmenname auf der Karte (maximal 25 Zei</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

default/objects/Tankkarten__c/fields/KFZ_Kennzeichen_oder_Fahrername__c.field-meta.xml
<CustomField>
    <fullName>KFZ_Kennzeichen_oder_Fahrername__c</fullName>
    <label>KFZ- Kennzeichen</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

default/objects/Tankkarten__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Tankkarten</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/classes/TankkartenTriggerTest.cls
@isTest
private class TankkartenTriggerTest {
    @isTest
    public static void testTankkartenName() {
    	Account a = new Account(Name = 'test', BillingCountry = 'Germany');
    	insert a;
		
		Opportunity op = new Opportunity(
				AccountId = a.Id,
				Name = 'test',
				StageName = 'Prospecting',
				CloseDate = Date.today());
		insert op;

    	Tankkarten__c t = new Tankkarten__c(
    		Account__c = a.Id,
			Opportunity__c = op.Id,
    		Firmenname_auf_der_Karte__c = 'test',
            KFZ_Kennzeichen_oder_Fahrername__c = 'test');
    	insert t;

    	t.Firmenname_auf_der_Karte__c = 'test12';
    	update t;

    	Tankkarten__c testCard = [SELECT Firmenname_auf_der_Karte__c FROM Tankkarten__c WHERE Id = :t.Id LIMIT 1];
    	system.assertEquals('TEST12', testCard.Firmenname_auf_der_Karte__c);
    }
}