default/objects/Account/fields/Partnertyp__c.field-meta.xml
<CustomField>
    <fullName>Partnertyp__c</fullName>
    <label>Partnertyp</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Lotos partner</fullName>
            </value>
            <value>
                <fullName>Markenpartner</fullName>
            </value>
            <value>
                <fullName>Marketing Partner</fullName>
            </value>
            <value>
                <fullName>Retailer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/recordTypes/Endkunde.recordType-meta.xml
<RecordType>
    <fullName>Endkunde</fullName>
    <active>true</active>
    <label>Endkunde</label>
</RecordType>

default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Record type for Partner Accounts of Fleetcor EU</description>
    <label>Partner</label>
</RecordType>

default/objects/E2E_Data_Contact__c/E2E_Data_Contact__c.object-meta.xml
<CustomObject>
    <label>E2E Data Contact</label>
    <nameField>
        <label>E2E Data Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Contact__c/fields/E2E_Data_Object__c.field-meta.xml
<CustomField>
    <fullName>E2E_Data_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E2E Data Object</label>
    <referenceTo>E2E_Data_Object__c</referenceTo>
    <relationshipLabel>E2E Data Contacts</relationshipLabel>
    <relationshipName>E2E_Data_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2E_Data_Log__c/E2E_Data_Log__c.object-meta.xml
<CustomObject>
    <label>E2E Data Log</label>
    <nameField>
        <label>E2E Data Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Log__c/fields/E2E_Data_Object__c.field-meta.xml
<CustomField>
    <fullName>E2E_Data_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E2E Data Object</label>
    <referenceTo>E2E_Data_Object__c</referenceTo>
    <relationshipLabel>E2E Data Logs</relationshipLabel>
    <relationshipName>E2E_Data_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2E_Data_Log__c/recordTypes/Exception.recordType-meta.xml
<RecordType>
    <fullName>Exception</fullName>
    <active>true</active>
    <label>Exception</label>
</RecordType>

default/objects/E2E_Data_Log__c/recordTypes/Job_Status.recordType-meta.xml
<RecordType>
    <fullName>Job_Status</fullName>
    <active>true</active>
    <label>Job Status</label>
</RecordType>

default/objects/E2E_Data_Object__c/E2E_Data_Object__c.object-meta.xml
<CustomObject>
    <label>E2E Data Object</label>
    <nameField>
        <label>E2E Data Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Short_Url__c/E2E_Short_Url__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>E2E Short Url</label>
</CustomObject>

default/objects/E2E_Short_Url__c/fields/E2E_Form_Url__c.field-meta.xml
<CustomField>
    <fullName>E2E_Form_Url__c</fullName>
    <label>E2E Form Url</label>
    <type>Url</type>
</CustomField>

default/objects/E2E_Short_Url__c/fields/Short_Url__c.field-meta.xml
<CustomField>
    <fullName>Short_Url__c</fullName>
    <label>Short Url</label>
    <type>Url</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Data_Object__c.field-meta.xml
<CustomField>
    <fullName>E2E_Data_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E2E Data Object</label>
    <referenceTo>E2E_Data_Object__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Short_Link__c.field-meta.xml
<CustomField>
    <fullName>E2E_Short_Link__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>E2E Short Link</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Opportunity/recordTypes/Euroshell.recordType-meta.xml
<RecordType>
    <fullName>Euroshell</fullName>
    <active>true</active>
    <businessProcess>Euroshell</businessProcess>
    <label>Euroshell</label>
</RecordType>

default/objects/Opportunity/recordTypes/Lotos.recordType-meta.xml
<RecordType>
    <fullName>Lotos</fullName>
    <active>true</active>
    <businessProcess>Carnet</businessProcess>
    <label>Lotos</label>
</RecordType>

default/classes/TwilioSMSHookController.cls
@RestResource(urlMapping = '/twiliohook/*')
global class TwilioSMSHookController {
    @HttpPost
    global static String getPost() {
        RestRequest req = RestContext.request;
        System.debug(req);
        String sms_from = req.params.get('from').replace('%2B', '+');
        String sms_body = req.params.get('body');
        String country = req.params.get('country');
        System.debug(Datetime.now().format() + ': got sms from ' + sms_from + ':   ' + sms_body);
        try {
            sms_body = sms_body.toUpperCase();
            String obn_number = sms_body.replaceAll('[^a-zA-Z0-9\\s+]', '').deleteWhitespace();
            String shortLink = prepareCustomerToETEProcess(obn_number, country, sms_from);
            GeneratedLink generatedLink = new GeneratedLink(shortLink, country);
            return JSON.serialize(generatedLink);
        } catch (Exception e) {
            System.debug('error creating entities in response to sms!\n' + e.getMessage() + ': ' + e.getStackTraceString());
            return JSON.serialize(new GeneratedLink(null, country));
        }
    }

    private static Set<String> stationNamesSet = new Set<String> {
            'SHELL',
            'SHEL',
            'SHALL',
            'LOTOS',
            'LOTUS'
    };


    private static String prepareCustomerToETEProcess(String obn_number, String country, String clientNumber) {
        String source;
        String obn = obn_number;
        for (String stationName : stationNamesSet) {
            if (obn.contains(stationName)) {
                obn = obn.substringAfter(stationName);
            }
        }
        List<Account> retailerAccount = ETEDataGenerator.getRetailerAccount(country, obn);
        String typeOfStation = 'JITB';
        if ( ! retailerAccount.isEmpty() && retailerAccount.get(0).Type == 'Partner') {
            typeOfStation = retailerAccount.get(0).Type;
        }
        String businessName;
        if (obn_number.startsWith('SHELL')) {
            businessName = 'SHELL';
        } else if (obn_number.startsWith('LOTOS')) {
            businessName = 'LOTOS';
        }
        if (businessName == null && ! retailerAccount.isEmpty()) {
            String partnerType = retailerAccount.get(0).Partnertyp__c;
            if (partnerType == 'Lotos partner') {
                businessName = 'LOTOS';
            } else {
                businessName = 'SHELL';
            }
        }
        String dataObjectRecordTypeName = country.replace('-', '_');
        String stageName = 'Prospecting';
        String opportunityRecordTypeName = 'Euroshell';
        if (businessName == 'LOTOS') {
            dataObjectRecordTypeName = country + '_Lotos';
            stageName = 'Qualify';
            opportunityRecordTypeName = 'Lotos';
        }

        String countryCode = ETEGlobalUtils.returnTwoLettersCountry(country);

        if (businessName != null) {
            String formName = ETEDataGenerator.getETEFormName(clientNumber, obn);
            Account account = ETEDataGenerator.insertAccount('Endkunde', country, formName);
            E2E_Data_Object__c e2EDataObject = ETEDataGenerator.insertE2EDataObject('products_and_services', stageName, dataObjectRecordTypeName, 'jitb', 'sms', obn, countryCode, countryCode, null, null, clientNumber);
            E2E_Data_Log__c dataLog = ETEDataGenerator.insertE2EDataLog('Job_Status', e2EDataObject.Id, 'Completed', 'checkBusinessObjects');
            Opportunity opportunity = ETEDataGenerator.insertOpportunity(formName, retailerAccount, account.Id, opportunityRecordTypeName, stageName, country, clientNumber, ETEDataGenerator.sourceSMS, obn, e2EDataObject.Id, typeOfStation);
            Contact contact = ETEDataGenerator.insertContact(formName, 'Contact layout', account.Id, clientNumber, country);
            E2E_Data_Contact__c e2EDataContact = ETEDataGenerator.insertE2EDataContact(e2EDataObject, clientNumber, null, contact);
            ETEDataGenerator.insertOpportunityContactRole(opportunity.Id, contact.Id);
            ETEDataGenerator.setPartnerRelationship(retailerAccount, opportunity.Id);
            source = opportunity.E2E_Short_Link__c;
        }
        return source;
    }


    public class GeneratedLink {
        public String link;

        public GeneratedLink(String link, String country) {
            E2E_Short_Url__c e2eShortUrlDetail = E2E_Short_Url__c.getInstance(country);
            if (link != null) {
                this.link = e2eShortUrlDetail.Short_Url__c + '?s' + link;
            } else {
                this.link = e2eShortUrlDetail.E2E_Form_Url__c;
            }
        }
    }
}