default/objects/Account/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>DO Markenpartner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/fields/Sec_Channel_Acc__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel_Acc__c</fullName>
    <label>Sec. Channel</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

default/objects/Account/recordTypes/Endkunde.recordType-meta.xml
<RecordType>
    <fullName>Endkunde</fullName>
    <active>true</active>
    <label>Endkunde</label>
</RecordType>

default/objects/Contact/fields/E2E__c.field-meta.xml
<CustomField>
    <fullName>E2E__c</fullName>
    <defaultValue>false</defaultValue>
    <label>E2E</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2E_Data_Contact__c/E2E_Data_Contact__c.object-meta.xml
<CustomObject>
    <label>E2E Data Contact</label>
    <nameField>
        <label>E2E Data Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Contact__c/fields/E2E_Data_Object__c.field-meta.xml
<CustomField>
    <fullName>E2E_Data_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E2E Data Object</label>
    <referenceTo>E2E_Data_Object__c</referenceTo>
    <relationshipLabel>E2E Data Contacts</relationshipLabel>
    <relationshipName>E2E_Data_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2E_Data_Object__c/E2E_Data_Object__c.object-meta.xml
<CustomObject>
    <label>E2E Data Object</label>
    <nameField>
        <label>E2E Data Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Object__c/fields/Company_Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Short_Name__c</fullName>
    <label>Company Short Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>de</fullName>
            </value>
            <value>
                <fullName>at</fullName>
            </value>
            <value>
                <fullName>nl</fullName>
            </value>
            <value>
                <fullName>pl</fullName>
            </value>
            <value>
                <fullName>hu</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>befr</fullName>
            </value>
            <value>
                <fullName>benl</fullName>
            </value>
            <value>
                <fullName>chde</fullName>
            </value>
            <value>
                <fullName>chfr</fullName>
            </value>
            <value>
                <fullName>sk</fullName>
            </value>
            <value>
                <fullName>cz</fullName>
            </value>
            <value>
                <fullName>lu</fullName>
            </value>
            <value>
                <fullName>be_fr</fullName>
                <isActive>false</isActive>
                <label>be_fr</label>
            </value>
            <value>
                <fullName>be_nl</fullName>
                <isActive>false</isActive>
                <label>be_nl</label>
            </value>
            <value>
                <fullName>ch_de</fullName>
                <isActive>false</isActive>
                <label>ch_de</label>
            </value>
            <value>
                <fullName>ch_fr</fullName>
                <isActive>false</isActive>
                <label>ch_fr</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>E2E Data Objects</relationshipLabel>
    <relationshipName>E2E_Data_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2E_Form_General_Settings__c/E2E_Form_General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>E2E Form General Settings</label>
</CustomObject>

default/objects/E2E_Form_General_Settings__c/fields/Integration_Admin_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Admin_Id__c</fullName>
    <label>Integration Admin Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

default/objects/Emarsys_Log__c/Emarsys_Log__c.object-meta.xml
<CustomObject>
    <label>Emarsys Log</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Emarsys Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emarsys Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Emarsys_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Emarsys Logs</relationshipLabel>
    <relationshipName>Emarsys_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Lead/fields/E2E_Adoption_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Adoption_Status__c</fullName>
    <defaultValue>'Manual Process'</defaultValue>
    <label>E2E Adoption Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manual Process</fullName>
                <default>true</default>
                <label>Manual Process</label>
            </value>
            <value>
                <fullName>Adoption Email Sent</fullName>
            </value>
            <value>
                <fullName>Successful Adoption</fullName>
            </value>
            <value>
                <fullName>Returned to Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/E2E_Assistant__c.field-meta.xml
<CustomField>
    <fullName>E2E_Assistant__c</fullName>
    <label>E2E Assistant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Last_Owner_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Owner_Change_Date__c</fullName>
    <label>Last Owner Change Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Carnet Standard 2019</fullName>
            </value>
            <value>
                <fullName>Shell Universal Card</fullName>
            </value>
            <value>
                <fullName>Carnet OBD</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes Standard</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes No fee</fullName>
            </value>
            <value>
                <fullName>Shell Basic 2020</fullName>
            </value>
            <value>
                <fullName>Shell No fee 2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Sec_Channel_Acc__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel_Acc__c</fullName>
    <formula>TEXT(Sec_Channel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sec. Channel_Acc</label>
    <type>Text</type>
</CustomField>

default/objects/Lead/recordTypes/Endkunde.recordType-meta.xml
<RecordType>
    <fullName>Endkunde</fullName>
    <active>true</active>
    <businessProcess>Datensatztyp</businessProcess>
    <label>Endkunde</label>
</RecordType>

default/objects/Opportunity/fields/E2E_2__c.field-meta.xml
<CustomField>
    <fullName>E2E_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>E2E 2</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Active_Step__c.field-meta.xml
<CustomField>
    <fullName>E2E_Active_Step__c</fullName>
    <defaultValue>0</defaultValue>
    <label>E2E Active Step</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Adoption_Date__c.field-meta.xml
<CustomField>
    <fullName>E2E_Adoption_Date__c</fullName>
    <label>E2E Adoption Date</label>
    <type>Date</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Adoption_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Adoption_Status__c</fullName>
    <defaultValue>'Manual Process'</defaultValue>
    <label>E2E Adoption Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual Process</fullName>
                <default>true</default>
                <label>Manual Process</label>
            </value>
            <value>
                <fullName>Adoption Email Sent</fullName>
            </value>
            <value>
                <fullName>Successful Adoption</fullName>
            </value>
            <value>
                <fullName>Returned to Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/E2E_Data_Object__c.field-meta.xml
<CustomField>
    <fullName>E2E_Data_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E2E Data Object</label>
    <referenceTo>E2E_Data_Object__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Encoded_URL__c.field-meta.xml
<CustomField>
    <fullName>E2E_Encoded_URL__c</fullName>
    <label>E2E Encoded URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Manual_Adoption_Date__c.field-meta.xml
<CustomField>
    <fullName>E2E_Manual_Adoption_Date__c</fullName>
    <label>E2E Manual Adoption Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Opportunity/fields/E2E_Step__c.field-meta.xml
<CustomField>
    <fullName>E2E_Step__c</fullName>
    <label>E2E Step</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Primary_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Phone__c</fullName>
    <label>Primary Contact Phone</label>
    <type>Phone</type>
</CustomField>

default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product *</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BE-FR 2,5 Cent</fullName>
            </value>
            <value>
                <fullName>Carnet OBD</fullName>
            </value>
            <value>
                <fullName>Carnet Standard 2019</fullName>
            </value>
            <value>
                <fullName>Fuel Vehicle</fullName>
            </value>
            <value>
                <fullName>HOME 1</fullName>
            </value>
            <value>
                <fullName>Home Station offer (v.1)</fullName>
            </value>
            <value>
                <fullName>Inbound Typ B</fullName>
            </value>
            <value>
                <fullName>Inbound Typ C</fullName>
            </value>
            <value>
                <fullName>LOCAL - RED</fullName>
            </value>
            <value>
                <fullName>LOCAL - YELLOW</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes No fee</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes Standard</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>Sales no fee promo Feb 2016</fullName>
            </value>
            <value>
                <fullName>Shell Basic 2020</fullName>
            </value>
            <value>
                <fullName>Shell No fee 2020</fullName>
            </value>
            <value>
                <fullName>Shell Outbound 2020</fullName>
            </value>
            <value>
                <fullName>Shell Universal Card</fullName>
            </value>
            <value>
                <fullName>Smart</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + % fee)</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + fixed fee)</fullName>
            </value>
            <value>
                <fullName>Sonderangebot (s. Notizen)</fullName>
            </value>
            <value>
                <fullName>Swiss Pro</fullName>
            </value>
            <value>
                <fullName>Swiss Pro 5</fullName>
            </value>
            <value>
                <fullName>Swiss Star</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/recordTypes/Euroshell.recordType-meta.xml
<RecordType>
    <fullName>Euroshell</fullName>
    <active>true</active>
    <businessProcess>Euroshell</businessProcess>
    <label>Euroshell</label>
</RecordType>

default/classes/ETEAdoptionBaseImpl.cls
public virtual class ETEAdoptionBaseImpl implements ETEAdoptionInterface {


    public virtual Database.LeadConvertResult convertLeadToE2E(E2E_Data_Object__c e2eDataObject, Account account, Opportunity opportunity, Contact contact) {
        Database.LeadConvertResult lcr;
        try {
            LeadHandler.enablesTrigger = false;
            OpportunityTriggerHandler.enablesTrigger = false;
            Database.LeadConvert lc = new Database.LeadConvert();
            LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted = true LIMIT 1];
            lc.setConvertedStatus(convertStatus.MasterLabel);
            lc.setLeadId(e2eDataObject.Lead__c);
            lc.setAccountId(account.Id);
            lc.setOpportunityId(opportunity.Id);
            lc.setContactId(contact.Id);
            lcr = Database.convertLead(lc);
        } catch (Exception e) {
            ExceptionLogger.sendException(String.valueOf('ETEAdoptionBaseImpl, lead Id: ' + e2eDataObject.Lead__c + ', ' + e.getMessage()), String.valueOf(e.getStackTraceString()));
        }
        return lcr;
    }


    public virtual Lead updateLead(Lead lead) {
        E2E_Form_General_Settings__c settings = E2E_Form_General_Settings__c.getInstance(lead.Country);
        if ( settings != null ) {
            lead.OwnerId = settings.Integration_Admin_Id__c;
            if (lead.E2E_Manual_Adoption_Date__c != null) {
                lead.E2E_Assistant__c = lead.Owner.Name;
            }
        }
        lead.E2E_Adoption_Status__c = 'Successful Adoption';

        update lead;
        return lead;
    }


    public virtual Account insertAccount(E2E_Data_Object__c e2eDataObject, Lead lead) {
        String recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Endkunde').getRecordTypeId();
        Account account = new Account(
                Name = e2eDataObject.Company_Short_Name__c,
                RecordTypeId = recordTypeId,
                CurrencyIsoCode = ETEGlobalUtils.returnCurrencyCode(e2eDataObject.Country_Code__c),
                Type = 'Customer',
                E2E__c = true,
                Sec_Channel__c = lead.Sec_Channel__c,
                Sec_Channel_Acc__c = lead.Sec_Channel__c,
                AccountSource = lead.LeadSource,
                BillingCountry = lead.Country
        );
        insert account;
        return account;
    }


    public virtual Opportunity insertOpportunity(E2E_Data_Object__c e2eDataObject, Lead lead, Account account) {
        String recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Euroshell').getRecordTypeId();
        String language = ETEGlobalUtils.returnDefaultLanguage(lead.CountryCode.toLowerCase());
        String pricebookId;
        if (Test.isRunningTest()) {
            pricebookId = Test.getStandardPricebookId();
        } else {
            pricebookId = [SELECT Id FROM Pricebook2 WHERE Name = 'Standard Price Book'].Id;
        }
        Opportunity opportunity = new Opportunity(
            Name = e2eDataObject.Company_Short_Name__c,
            CurrencyIsoCode = ETEGlobalUtils.returnCurrencyCode(e2eDataObject.Country_Code__c),
            AccountId = account.Id,
            Pricebook2Id = pricebookId,
            E2E_Adoption_Status__c = 'Successful Adoption',
            E2E_Adoption_Date__c = Date.today(),
            StageName = 'Prospecting',
            RecordTypeId = recordTypeId,
            Primary_Contact_Phone__c = lead.Phone,
            CloseDate = Date.today(),
            Last_Owner_Change_Date__c = Datetime.now(),
            Product__c = null,
            E2E_Data_Object__c = e2EDataObject.Id,
            E2E_2__c = true,
            E2E_Step__c = 'products_and_services',
            E2E_Encoded_URL__c = ETEGlobalUtils.doEncryptParams(e2EDataObject.Id, lead.CountryCode.toLowerCase()),
            E2E_Active_Step__c = 0,
            E2E_Sales_Type__c = 'Fully E2E',
            E2E_Status__c = 'Introduction',
            E2E_Sub_Status__c = 'Marketing automation',
            AGB_Datenschutzhinweise_Richtigkeit__c = false,
            E2E_Form_of_Business__c = 'Company',
            Description = lead.Description,
            Language_preference__c = ETEGlobalUtils.returnLanguagePreference(language),
            Agree_to_telephone_contact__c = lead.Agree_to_telephone_contact__c,
            Agree_to_receive_comm_info_by_email__c = lead.Agree_to_receive_comm_info_by_email__c,
            Agree_to_process_pers_data_for_marketing__c = lead.Agree_to_process_pers_data_for_marketing__c
        );

        insert opportunity;
        return opportunity;
    }


    public virtual Contact insertContact(E2E_Data_Object__c e2eDataObject, Account account, E2E_Data_Contact__c e2EDataContact) {
        String recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact layout').getRecordTypeId();
        Contact contact = new Contact(
            RecordTypeId = recordTypeId,
            Authorised_signatory__c = false,
            CurrencyIsoCode = ETEGlobalUtils.returnCurrencyCode(e2eDataObject.Country_Code__c),
            E2E__c = true,
            FirstName = e2EDataContact.First_Name__c,
            LastName = e2EDataContact.Last_Name__c,
            Salutation = e2EDataContact.Salutation__c,
            Phone = e2EDataContact.Phone__c,
            Email = e2EDataContact.Email__c,
            AccountId = account.Id
        );

        insert contact;
        return contact;
    }


    public virtual void insertOpportunityContactRole(Opportunity opportunity, Contact contact) {
        OpportunityContactRole oppConRole = new OpportunityContactRole(
            IsPrimary = true,
            OpportunityId = opportunity.Id,
            ContactId = contact.Id
        );
        insert oppConRole;
    }


    public virtual List<Emarsys_Log__c> setFieldsToUpdateEmarsysLogs(List<Emarsys_Log__c> emarsysLogs, Opportunity opportunity) {
        for (Emarsys_Log__c emarsysLog : emarsysLogs) {
            emarsysLog.Opportunity__c = opportunity.Id;
        }
        return emarsysLogs;
    }
}