default/objects/Account/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>DO Markenpartner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Account/recordTypes/CCS.recordType-meta.xml
<RecordType>
    <fullName>CCS</fullName>
    <active>true</active>
    <label>CCS</label>
</RecordType>

default/objects/Account/recordTypes/Russian.recordType-meta.xml
<RecordType>
    <fullName>Russian</fullName>
    <active>true</active>
    <label>Russian</label>
</RecordType>

default/objects/Opportunity/fields/CF_checking__c.field-meta.xml
<CustomField>
    <fullName>CF_checking__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CF checking</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Product_Solicited__c.field-meta.xml
<CustomField>
    <fullName>Product_Solicited__c</fullName>
    <description>Name of the product the Customer Applied for</description>
    <inlineHelpText>Select the product the customer applied for.</inlineHelpText>
    <label>Product Solicited</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCS Aukce</fullName>
            </value>
            <value>
                <fullName>CCS Bonus</fullName>
            </value>
            <value>
                <fullName>CCS Bonus+</fullName>
            </value>
            <value>
                <fullName>CCS Bonus Fleet</fullName>
            </value>
            <value>
                <fullName>CCS Carnet</fullName>
            </value>
            <value>
                <fullName>CCS Limit</fullName>
            </value>
            <value>
                <fullName>CCS Limit+</fullName>
            </value>
            <value>
                <fullName>CCS Limit+ mini</fullName>
            </value>
            <value>
                <fullName>CCS Toll</fullName>
            </value>
            <value>
                <fullName>CCS Trucks</fullName>
            </value>
            <value>
                <fullName>UTA/CCS</fullName>
            </value>
            <value>
                <fullName>CCS Limit M4</fullName>
            </value>
            <value>
                <fullName>CCS Limit PRIM</fullName>
            </value>
            <value>
                <fullName>CCS Limit NP</fullName>
            </value>
            <value>
                <fullName>CCS Carnet NP</fullName>
            </value>
            <value>
                <fullName>CCS_Handy Card</fullName>
                <label>CCS Handy Card</label>
            </value>
            <value>
                <fullName>CCS LIMIT Exclusive</fullName>
            </value>
            <value>
                <fullName>E-shop</fullName>
            </value>
            <value>
                <fullName>ERV insurance</fullName>
            </value>
            <value>
                <fullName>OMV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/recordTypes/CCS_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>CCS_Opportunity</fullName>
    <active>true</active>
    <businessProcess>CCS Sales Process</businessProcess>
    <label>CCS Opportunity Layout</label>
</RecordType>

default/classes/CFRuBatchTest.cls
@IsTest
public without sharing class CFRuBatchTest {

    private static final Id RU_OPP_RECORD_TYPE = OpportunityTriggerHandler.RUSSIAN_RECORD_TYPE_ID;
    private static final Id RU_ACCOUNT_RECORD_TYPE = GlobalUtils.getRecordTypeId(Account.class.getName(), 'Russian');

    @IsTest
    static void testBehavior() {
        insert CFUtilsTest.createCFSettingsForRussia(false);
        Account account = new Account(
                Name = 'test',
                RecordTypeId = RU_ACCOUNT_RECORD_TYPE
        );
        insert account;
        Opportunity opp1 = new Opportunity(
                RecordTypeId = RU_OPP_RECORD_TYPE,
                Name = 'test 1',
                StageName = GlobalUtils.getOpportunityStageName(GlobalUtils.OpportunityStage.Qualified_Lead),
                CloseDate = Date.today(),
                AccountId = account.Id,
                CF_checking__c = true
        );
        Opportunity opp2 = new Opportunity(
                RecordTypeId = RU_OPP_RECORD_TYPE,
                Name = 'test 2',
                StageName = GlobalUtils.getOpportunityStageName(GlobalUtils.OpportunityStage.Qualified_Lead),
                CloseDate = Date.today(),
                AccountId = account.Id,
                CF_checking__c = true
        );
        Opportunity opp3 = new Opportunity(
                RecordTypeId = RU_OPP_RECORD_TYPE,
                Name = 'test 3',
                StageName = GlobalUtils.getOpportunityStageName(GlobalUtils.OpportunityStage.Qualified_Lead),
                CloseDate = Date.today(),
                AccountId = account.Id,
                CF_checking__c = false
        );
        Opportunity opp4 = new Opportunity(
                AccountId = account.Id,
                Name = 'test 4',
                CF_checking__c = true,
                Type = 'New GFN',
                StageName = 'Qualify',
                CloseDate = Date.today(),
                Product_Solicited__c = 'CCS Limit',
                Sec_Channel__c = 'Inbound',
                RecordTypeId = Schema.getGlobalDescribe().get(Opportunity.class.getName())
                        .getDescribe().getRecordTypeInfosByDeveloperName()
                        .get(GlobalUtils.OpportunityRecordTypes.CCS_Opportunity.name()).recordTypeId
        );
        List<Opportunity> opportunities = new List<Opportunity>{
                opp1, opp2, opp3, opp4
        };
        insert opportunities;
        Test.startTest();
        Database.executeBatch(new CFRuBatch());
        Test.stopTest();

        opp1 = ([
                SELECT Id, CF_checking__c, Name
                FROM Opportunity
                WHERE Id = :opp1.Id
                LIMIT 1
        ]);
        System.assertEquals(false, opp1.CF_checking__c);
        System.assertEquals('TEST 1', opp1.Name);
        opp2 = ([
                SELECT Id, CF_checking__c
                FROM Opportunity
                WHERE Id = :opp2.Id
                LIMIT 1
        ]);
        System.assertEquals(false, opp2.CF_checking__c);
        opp3 = ([
                SELECT Id, CF_checking__c
                FROM Opportunity
                WHERE Id = :opp3.Id
                LIMIT 1
        ]);
        System.assertEquals(false, opp3.CF_checking__c);
        opp4 = ([
                SELECT Id, CF_checking__c
                FROM Opportunity
                WHERE Id = :opp4.Id
                LIMIT 1
        ]);
        System.assertEquals(true, opp4.CF_checking__c);
    }
}