default/objects/Custom_log__c/Custom_log__c.object-meta.xml
<CustomObject>
    <description>contains log of the process</description>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Custom_log__c/fields/E2E_Form_Ru_Data__c.field-meta.xml
<CustomField>
    <fullName>E2E_Form_Ru_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>reference to Form data object with business data</description>
    <inlineHelpText>reference to Form data object with business data</inlineHelpText>
    <label>E2E Form Ru Data</label>
    <referenceTo>E2EFormData__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Custom_log__c/fields/External_user__c.field-meta.xml
<CustomField>
    <fullName>External_user__c</fullName>
    <description>User that made API call from another system</description>
    <inlineHelpText>User that made API call from another system</inlineHelpText>
    <label>External user</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Custom_log__c/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax identification number</description>
    <inlineHelpText>Tax identification number</inlineHelpText>
    <label>INN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Custom_log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>datasource</description>
    <inlineHelpText>datasource</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Promocodes__c/E2E_Promocodes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>list of promocedes</description>
    <label>E2E Promocodes</label>
</CustomObject>

default/objects/E2E_Promocodes__c/fields/Apply_to_tariffs__c.field-meta.xml
<CustomField>
    <fullName>Apply_to_tariffs__c</fullName>
    <label>Apply to tariffs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Promocodes__c/fields/Enable_Main_Promo__c.field-meta.xml
<CustomField>
    <fullName>Enable_Main_Promo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Main Promo</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2E_Promocodes__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Promocodes__c/fields/Promocode_Additional_Field__c.field-meta.xml
<CustomField>
    <fullName>Promocode_Additional_Field__c</fullName>
    <label>Promocode Additional Field</label>
    <type>TextArea</type>
</CustomField>

default/objects/E2E_Promocodes__c/fields/Promocode_Label__c.field-meta.xml
<CustomField>
    <fullName>Promocode_Label__c</fullName>
    <label>Promocode Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Promocodes__c/fields/Report_Identifiers__c.field-meta.xml
<CustomField>
    <fullName>Report_Identifiers__c</fullName>
    <label>Report Identifiers</label>
    <type>TextArea</type>
</CustomField>

default/objects/LongForm_Fleetcor_Product__c/LongForm_Fleetcor_Product__c.object-meta.xml
<CustomObject>
    <label>LongForm Fleetcor Product</label>
    <nameField>
        <label>LongForm Fleetcor Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LongForm Fleetcor Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/LongForm_Fleetcor_Product__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Switzerland-DE</fullName>
            </value>
            <value>
                <fullName>Switzerland-FR</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/LongForm_Fleetcor_Product__c/fields/Long_Form_Offer__c.field-meta.xml
<CustomField>
    <fullName>Long_Form_Offer__c</fullName>
    <label>Long Form Offer</label>
    <referenceTo>LongForm_Offer__c</referenceTo>
    <relationshipName>Long_Form_Fleetcor_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/LongForm_Offer__c/LongForm_Offer__c.object-meta.xml
<CustomObject>
    <label>LongForm Offer</label>
    <nameField>
        <displayFormat>LFOFR-{00000}</displayFormat>
        <label>LongForm Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LongForm Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/LongForm_Offer__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Belgium-NL</fullName>
            </value>
            <value>
                <fullName>Belgium-FR</fullName>
            </value>
            <value>
                <fullName>Switzerland-DE</fullName>
            </value>
            <value>
                <fullName>Switzerland-FR</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/LongForm_Offer__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inbound Typ B</fullName>
            </value>
            <value>
                <fullName>Inbound Typ C</fullName>
            </value>
            <value>
                <fullName>HOME 1</fullName>
            </value>
            <value>
                <fullName>Home Station offer (v.1)</fullName>
            </value>
            <value>
                <fullName>Shell Promo 2019</fullName>
            </value>
            <value>
                <fullName>Shell Summer 2019</fullName>
            </value>
            <value>
                <fullName>Swiss Pro 5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/LongForm_Tariff__c/LongForm_Tariff__c.object-meta.xml
<CustomObject>
    <label>LongForm Tariff</label>
    <nameField>
        <label>LongForm Tariff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LongForm Tariffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/LongForm_Tariff__c/fields/LongForm_Fleetcor_Product__c.field-meta.xml
<CustomField>
    <fullName>LongForm_Fleetcor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LongForm Fleetcor Product</label>
    <referenceTo>LongForm_Fleetcor_Product__c</referenceTo>
    <relationshipLabel>LongForm Tariffs</relationshipLabel>
    <relationshipName>LongForm_Tariffs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/PPR_API_Settings__c/PPR_API_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for PPR API Controllers, Services, etc</description>
    <label>PPR_API_Settings</label>
</CustomObject>

default/objects/PPR_API_Settings__c/fields/Block_API_Actions__c.field-meta.xml
<CustomField>
    <fullName>Block_API_Actions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Block API Actions</label>
    <type>Checkbox</type>
</CustomField>

default/objects/PPR_API_Settings__c/fields/Callback_URI__c.field-meta.xml
<CustomField>
    <fullName>Callback_URI__c</fullName>
    <label>Callback URI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/PPR_API_Settings__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <inlineHelpText>Job Type in Tp3 for Overdraft</inlineHelpText>
    <label>Contract Type</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/PPR_API_Settings__c/fields/Credit_days_ppr__c.field-meta.xml
<CustomField>
    <fullName>Credit_days_ppr__c</fullName>
    <inlineHelpText>Job Type in Salesforce for Overdraft</inlineHelpText>
    <label>Credit days ppr</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/PPR_API_Settings__c/fields/Due_date__c.field-meta.xml
<CustomField>
    <fullName>Due_date__c</fullName>
    <inlineHelpText>Due date in Tp3 for Overdraft</inlineHelpText>
    <label>Due date</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/PPR_API_Settings__c/fields/Prepay_sum__c.field-meta.xml
<CustomField>
    <fullName>Prepay_sum__c</fullName>
    <label>Prepay sum</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/classes/PPR_API_DataTestFactory.cls
@isTest
public with sharing class PPR_API_DataTestFactory {

    public static LongForm_Offer__c createOffer() {
        LongForm_Offer__c offer = new LongForm_Offer__c(
                Country__c = 'Russia',
                Product__c = 'PetrolPlus'
        );

        return offer;
    }
    
    public static LongForm_Fleetcor_Product__c createProductOffer(Id offerId) {
        LongForm_Fleetcor_Product__c productOffer = new LongForm_Fleetcor_Product__c(
                Name = 'PetrolPlus_Rover',
                Active__c = true,
                Long_Form_Offer__c = offerId,
                Label__c = 'Вездеход Online'
        );

        return productOffer;
    }

    public static LongForm_Tariff__c createLongFormTariff() {
        LongForm_Tariff__c tariffProduct = new LongForm_Tariff__c(
            Name = '1OPTIMAL_CONTRACT',
            Label__c = 'Оптимальный'
        );

        return tariffProduct;
    }

    public static PPR_API_Settings__c createPPR_API_Settings() {
        return new PPR_API_Settings__c(
            Name = 'europlan',
            Block_API_Actions__c = false,
            Callback_URI__c = 'https://webhook.site/8e0cfe31-db8a-4447-905d-7be72f7749a3',
            Contract_Type__c = 14,
            Due_date__c = 3,
            Credit_days_ppr__c = 'к14д',
            Prepay_sum__c = '100'
        );
    }

    public static E2E_Promocodes__c createPromocode(String name, String additionalField, String reportIdentifiers) {
        return new E2E_Promocodes__c(
            Name = name,
            Promocode_Additional_Field__c = additionalField,
            Report_Identifiers__c = reportIdentifiers,
            Apply_to_tariffs__c = '1OPTIMAL_CARDS;1OPTIMAL_CONTRACT;2CHOOSEN_CARDS;2CHOOSEN_CONTRACT;1CARDS_CARDS;2CONTRACT_CARDS;',
            Enable_Main_Promo__c = true,
            Product_Name__c = 'Вездеход Online',
            Promocode_Label__c = 'Отмена ИУ на 3М + цена стелы ГПН+ГЭС на 3М'
        );
    }

    public static Custom_log__c createCustomLog(Id formDataId, String inn) {
        return new Custom_log__c(
                E2E_Form_Ru_Data__c = formDataId,
                External_user__c = 'Dobrynia Nikitich',
                INN__c = inn,
                Source__c = 'europlan'
        );
    }

    public static DadataBank setDadataBankInfo() {
        DadataBank dataBank = new DadataBank();
        dataBank.name = '';
        dataBank.nameShort = '';
        dataBank.bic = '';
        dataBank.correspondentAccount = '';
        dataBank.okpo = '';
        dataBank.town = '';
        dataBank.address = '';

        return dataBank;
    }

    public static List<Map<String, Object>> setCardsData() {
        return new List<Map<String, Object>> {
            new Map<String, Object> {
                'id' => '1337f71a-81b2-11ea-a527-6bba62241005',
                'number' => '4000100001',
                'is_active'  => true,
                'is_issued' => false,
                'CardPartners' => new List<Object> {
                    new Map<String, Object> {
                        'partner_id' => '1337f71a-81b2-11ea-a527-6bba62248004',
                        'id' => '3dbb3658-8214-11ea-8e0c-f35a8f317e5a',
                        'card_id' => '1337f71a-81b2-11ea-a527-6bba62241005',
                        'Partner' => new Map<String, Object> {
                                'name' => 'Европлан',
                                'alias' => 'europlan',
                                'id' => '1337f71a-81b2-11ea-a527-6bba62248004'
                        }
                    }
                }
            }, new Map<String, Object> {
                'id' => '1337f71a-81b2-11ea-a527-6bba62241002',
                'number' => '3005553535',
                'is_active'  => true,
                'is_issued' => false,
                'CardPartners' => new List<Object> {
                        new Map<String, Object> {
                                'partner_id' => '1337f71a-81b2-11ea-a527-6bba62248004',
                                'id' => '1337f71a-81b2-11ea-a527-6bba62241006',
                                'card_id' => '1337f71a-81b2-11ea-a527-6bba62241002',
                                'Partner' => new Map<String, Object> {
                                        'name' => 'Европлан',
                                        'alias' => 'europlan',
                                        'id' => '1337f71a-81b2-11ea-a527-6bba62248004'
                                }
                        }
                }
            }
        };
    }

    public static Map<String, Object> generateTestRequest(String formDataId, String inn) {
        String testId = (formDataId == null) ? 'a5H0O000000TRY6' : formDataId;

        return new Map<String, Object> {
            'metadata' => new Map<String, Object> {
                'source' => 'europlan',
                'id' => testId,
                'user' => 'Dobrynia Nikitich'
            },
            'customerInfo' => new Map<String, Object> {
                'legalInfo' => new Map<String, Object> {
                    'inn' => inn,
                    'codeWord' => 'кодовоеслово',
                    'emails' => new List<Object> {
                        new Map<String, Object> {
                            'value' => 'ya@krevedko.ru',
                            'type' => new List<Object> {
                                'Web portal',
                                'Documents',
                                'Reports',
                                'Reports(TCI)',
                                'Invoices',
                                'Mail',
                                'First PIN delivery',
                                'LK accesses'
                            }
                        }
                    },
                    'phones' => new List<Object> {
                        new Map<String, Object> {
                            'value' => new Map<String, Object> {
                                'code' => '7',
                                'numberStr' => '8002553535',
                                'ext' => '-'
                            },
                            'type' => new List<Object> {
                                'Financial Notification',
                                'Advertisement',
                                'Private',
                                'Mobile',
                                'Main',
                                'Pin recovery',
                                'SMS Notifications',
                                'Print on post envelope'
                            }
                        }
                    },
                    'agreements' => new List<Object> {
                        'PersonalData',
                        'MarketingProgram'
                    }
                },
                'additionalInfo' => new Map<String, Object>{ 
                    'courierServiceComments' => 'для идентификации сказать пароль: пароль'
                },
                'orderInfo' => new Map<String, Object> {
                    'product' => 'PetrolPlus_Rover',
                    'tariff' => '2CHOOSEN_cards',
                    'orderType' => 'Overdraft',
                    'overdraftSum' => '100000',
                    'services' => new List<Object> {
                        'PersonalManager',
                        'ExpressDocDelivery'
                    },
                    'promos' => new List<Object> {
                        '9E15',
                        '9E25'
                    },
                    'cards' => new List<Object> {
                        '4000100001',
                        '3005553535'
                    }
                },
                'bankInfo' => new Map<String, Object> {
                    'bik' => '044030843',
                    'accountNum' => '40817810099910004312'
                },
                'addresses' => new List<Object> {
                    new Map<String, Object> {
                        'countryCode' => '643',
                        'addressId' => '5ee84ac0-eb9a-4b42-b814-2f5f7c27c255',
                        'zipCode' => '644119',
                        'country' => 'Russia',
                        'state' => 'Областная обл.',
                        'city' => 'г. Грёз',
                        'street' => 'ул. Пушкина',
                        'house' => 'дом Колотушкина',
                        'apartment' => 'офис 404',
                        'type' => new List<Object> {
                            'Billing'
                        }
                    },
                    new Map<String, Object> {
                        'countryCode' => '643',
                        'addressId' => '5ee84ac0-eb9a-4b42-b814-2f5f7c27c255',
                        'zipCode' => '644119',
                        'country' => 'Russia',
                        'state' => 'Областная обл.',
                        'city' => 'г. Грёз',
                        'street' => 'ул. Пушкина',
                        'house' => 'дом Колотушкина',
                        'apartment' => 'офис 404',
                        'type' => new List<Object> {
                            'Shipping'
                        }
                    }
                },
                'staff' => new List<Object> {
                    new Map<String, Object> {
                        'firstName' => 'Василий',
                        'lastName' => 'Пупкин',
                        'Surname' => 'Васильевич',
                        'email' => 'vasily.pupkin@emal.ru',
                        'role' => 'Decision Maker',
                        'position' => 'генеральный директор',
                        'phones' => new List<Object> {
                            new Map<String, Object> {
                                'value' => new Map<String, Object> {
                                    'code' => '7',
                                    'numberStr' => '8002553535',
                                    'ext' => '-'
                                },
                                'type' => new List<Object> {
                                    'phone',
                                    'Mobile',
                                    'Additional phone'
                                }
                            }
                        }
                    }
                }
            }
        };
    }

    public static Map<String, Object> generateTestRequestMandatoryFields(String formDataId, String inn) {
        String testId = (formDataId == null) ? 'a5H0O000000TRY6' : formDataId;

        return new Map<String, Object> {
            'metadata' => new Map<String, Object> {
                'source' => 'europlan',
                'id' => testId
            },
            'customerInfo' => new Map<String, Object> {
                'legalInfo' => new Map<String, Object> {
                    'inn' => inn,
                    'codeWord' => 'кодовоеслово',
                    'emails' => new List<Object> {
                        new Map<String, Object> {
                            'value' => 'ya@krevedko.ru',
                            'type' => new List<Object> {
                                'Web portal',
                                'Documents',
                                'Reports',
                                'Reports(TCI)',
                                'Invoices',
                                'Mail',
                                'First PIN delivery',
                                'LK accesses'
                            }
                        }
                    },
                    'phones' => new List<Object> {
                        new Map<String, Object> {
                            'value' => new Map<String, Object> {
                                'code' => '7',
                                'numberStr' => '8002553535',
                                'ext' => '-'
                            },
                            'type' => new List<Object> {
                                'Financial Notification',
                                'Advertisement',
                                'Private',
                                'Mobile',
                                'Main',
                                'Pin recovery',
                                'SMS Notifications',
                                'Print on post envelope'
                            }
                        }
                    },
                    'agreements' => new List<Object> {
                        'PersonalData',
                        'MarketingProgram'
                    }
                },
                'orderInfo' => new Map<String, Object> {
                    'overdraftSum' => '100000',
                    'cards' => new List<Object> {
                        '4000100001'
                    },
                    'promos' => new List<Object> {
                        '9E15',
                        '9E25'
                    }
                },
                'bankInfo' => new Map<String, Object> {
                    'bik' => '044030843',
                    'accountNum' => '40817810099910004312'
                }
            }
        };
    }
}