default/objects/Custom_log__c/Custom_log__c.object-meta.xml
<CustomObject>
    <description>contains log of the process</description>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Custom_log__c/fields/E2E_Form_Ru_Data__c.field-meta.xml
<CustomField>
    <fullName>E2E_Form_Ru_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>reference to Form data object with business data</description>
    <inlineHelpText>reference to Form data object with business data</inlineHelpText>
    <label>E2E Form Ru Data</label>
    <referenceTo>E2EFormData__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Custom_log__c/fields/Errors__c.field-meta.xml
<CustomField>
    <fullName>Errors__c</fullName>
    <description>Errors and exceptions</description>
    <inlineHelpText>Errors and exceptions</inlineHelpText>
    <label>Errors</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/Custom_log__c/fields/External_user__c.field-meta.xml
<CustomField>
    <fullName>External_user__c</fullName>
    <description>User that made API call from another system</description>
    <inlineHelpText>User that made API call from another system</inlineHelpText>
    <label>External user</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Custom_log__c/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax identification number</description>
    <inlineHelpText>Tax identification number</inlineHelpText>
    <label>INN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Custom_log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>datasource</description>
    <inlineHelpText>datasource</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Custom_log_archivation_settings__c/Custom_log_archivation_settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>settings for object Custom_log__c archivation</description>
    <label>Custom log archivation settings</label>
</CustomObject>

default/objects/Custom_log_archivation_settings__c/fields/Days_logs_to_archive__c.field-meta.xml
<CustomField>
    <fullName>Days_logs_to_archive__c</fullName>
    <description>Number of days to pass logs to be archived</description>
    <inlineHelpText>Number of days to pass logs to be archived</inlineHelpText>
    <label>Days logs to archive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Custom_log_archivation_settings__c/fields/Notification_recipients__c.field-meta.xml
<CustomField>
    <fullName>Notification_recipients__c</fullName>
    <description>Emails of the users who will be notified once operation is complete. Must be separated by ;</description>
    <inlineHelpText>Emails of the users who will be notified once operation is complete. Must be separated by ;</inlineHelpText>
    <label>Notification recipients</label>
    <type>TextArea</type>
</CustomField>

default/objects/Custom_log_archivation_settings__c/fields/Sources__c.field-meta.xml
<CustomField>
    <fullName>Sources__c</fullName>
    <description>List of sources. Must be separated by ;</description>
    <inlineHelpText>List of sources. Must be separated by ;</inlineHelpText>
    <label>Sources</label>
    <type>TextArea</type>
</CustomField>

default/classes/ArchiveCustomLogBatchTest.cls
@IsTest
public with sharing class ArchiveCustomLogBatchTest {

    @IsTest
    private static void test() {
        insert new Custom_log__c(
                Source__c = 'EUP',
                External_user__c = 'test',
                INN__c = '12354',
                Errors__c = '1'
        );
        Long startTime = Datetime.now().getTime();
        Long finishTime = Datetime.now().getTime();
        while ((finishTime - startTime) < 2000) {
            //sleep for 2s
            finishTime = Datetime.now().getTime();
        }
        insert new Custom_log_archivation_settings__c(
                Name = 'PPR_API',
                Days_logs_to_archive__c = 0,
                Sources__c = 'EUP; test;',
                Notification_recipients__c = 'test@fsdf.rg'
        );
        insert new List<Custom_log__c>{
                new Custom_log__c(
                        Source__c = 'EUP',
                        External_user__c = 'test',
                        INN__c = '12354',
                        Errors__c = '2'
                ),
                new Custom_log__c(
                        Source__c = 'test',
                        External_user__c = 'test',
                        INN__c = '12354',
                        Errors__c = '3'
                ),
                new Custom_log__c(
                        Source__c = 'sdfdf',
                        External_user__c = 'test',
                        INN__c = '12354',
                        Errors__c = '4'
                )
        };

        Test.startTest();
        Database.executeBatch(new ArchiveCustomLogBatch(Custom_log_archivation_settings__c.getValues('PPR_API')));
        Test.stopTest();

        List<Custom_log__c> logs = ([
                SELECT Id, Source__c, CreatedDate, Errors__c, External_user__c, E2E_Form_Ru_Data__c, INN__c
                FROM Custom_log__c
        ]);
        for (Custom_log__c log : logs) {
            System.debug(log.CreatedDate.getTime());
        }
        System.assertEquals(3, logs.size());
        Boolean flag = false;
        for (Custom_log__c log : logs) {
            flag = log.Errors__c.equals('1');
        }
        System.assertEquals(false, flag);
    }

    @IsTest
    private static void testException() {
        try {
            insert new Custom_log_archivation_settings__c(
                    Name = 'PPR_API'
            );

            Test.startTest();
            Database.executeBatch(new ArchiveCustomLogBatch(Custom_log_archivation_settings__c.getValues('PPR_API')));
            Test.stopTest();
        } catch (Exception e) {
            System.assert(e != null);
        }

    }



}