default/objects/Custom_log__c/Custom_log__c.object-meta.xml
<CustomObject>
    <description>contains log of the process</description>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Custom_log__c/fields/E2E_Form_Ru_Data__c.field-meta.xml
<CustomField>
    <fullName>E2E_Form_Ru_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>reference to Form data object with business data</description>
    <inlineHelpText>reference to Form data object with business data</inlineHelpText>
    <label>E2E Form Ru Data</label>
    <referenceTo>E2EFormData__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Custom_log__c/fields/Errors__c.field-meta.xml
<CustomField>
    <fullName>Errors__c</fullName>
    <description>Errors and exceptions</description>
    <inlineHelpText>Errors and exceptions</inlineHelpText>
    <label>Errors</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/Custom_log__c/fields/External_user__c.field-meta.xml
<CustomField>
    <fullName>External_user__c</fullName>
    <description>User that made API call from another system</description>
    <inlineHelpText>User that made API call from another system</inlineHelpText>
    <label>External user</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Custom_log__c/fields/INN__c.field-meta.xml
<CustomField>
    <fullName>INN__c</fullName>
    <description>Tax identification number</description>
    <inlineHelpText>Tax identification number</inlineHelpText>
    <label>INN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/E2EFormData__c/E2EFormData__c.object-meta.xml
<CustomObject>
    <description>Store data from E2E Form</description>
    <label>E2E Form Ru Data</label>
    <nameField>
        <displayFormat>E2ERU{00000000}</displayFormat>
        <label>E2EFormRuData  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>E2E Form Ru Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

default/objects/E2EFormData__c/fields/E2E_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>E2E_Contract_Number__c</fullName>
    <label>Contract number</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

default/objects/E2EFormData__c/fields/E2E_OGRN__c.field-meta.xml
<CustomField>
    <fullName>E2E_OGRN__c</fullName>
    <label>OGRN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

default/objects/E2EFormData__c/fields/E2E_Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>E2E_Opportunity_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>E2E Form Ru Data</relationshipLabel>
    <relationshipName>E2EFormRuData</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2EFormData__c/fields/E2E_Process_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Process_Status__c</fullName>
    <description>Статусы успешно пройденных процессов по форме E2E</description>
    <label>Process status</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/E2EFormData__c/fields/Last_deduplication_time__c.field-meta.xml
<CustomField>
    <fullName>Last_deduplication_time__c</fullName>
    <description>Date &amp; time of last deduplication process</description>
    <inlineHelpText>Date &amp; time of last deduplication process</inlineHelpText>
    <label>Last deduplication time</label>
    <type>DateTime</type>
</CustomField>

default/objects/Opportunity/fields/Agreement_Date__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Date__c</fullName>
    <label>Agreement Date</label>
    <type>Date</type>
</CustomField>

default/classes/ResponseBodyBuilder.cls
public class ResponseBodyBuilder {

    /*******************************************************************************
    *  Name            : constructPPR_API_responseBody(String inn, String source)
    *  Summary         : builds response body for PPR API by INN and source (method with DB operations)
    *  CreatedDate     : 11/02/2020
    *  ModifiedDate    : -
    *  Parameters      : String inn, String source
    *  Returns         : PPR_API_ResponseBody
    ******************************************************************************/
    public static PPR_API_ResponseBody constructPPR_API_responseBody(String inn, String source) {
        String dateFormat = 'dd.MM.yyyy';
        E2EFormRuDao formRuDao = new E2EFormRuDaoImpl();
        Custom_log__c log = PPR_API_LogService.getLogByInnAndSource(inn, source);
        PPR_API_ResponseBody responseBody = new PPR_API_ResponseBody();
        if (log != null) {
            responseBody.metadata = new PPR_API_ResponseBody.Metadata();
            responseBody.customerInfo = new PPR_API_ResponseBody.CustomerInfo();
            responseBody.metadata.user = log.External_user__c;
            responseBody.message = log.Errors__c;
            responseBody.customerInfo.inn = log.INN__c;

            E2EFormData__c formData = formRuDao.getFormDataById(log.E2E_Form_Ru_Data__c);
            if (formData != null) {
                responseBody.metadata.id = formData.Id;
                responseBody.customerInfo.customerStatus = formData.E2E_Process_Status__c;
                responseBody.customerInfo.customerStatusId = (String) PPR_Mapping_Utils.customerStatusMap.get(formData.E2E_Process_Status__c);
                responseBody.customerInfo.checkDate = formData.Last_deduplication_time__c == null ? null : formData.Last_deduplication_time__c.format(dateFormat);
                responseBody.customerInfo.ogrn = formData.E2E_OGRN__c;
                responseBody.customerInfo.contractNum = formData.E2E_Contract_Number__c;

                Opportunity opportunity = getOpportunity(formData.E2E_Opportunity_Id__c);
                if (opportunity != null) {
                    responseBody.customerInfo.contractDate = opportunity.Agreement_Date__c == null ? null :
                            Datetime.newInstance(
                                    opportunity.Agreement_Date__c.year(),
                                    opportunity.Agreement_Date__c.month(),
                                    opportunity.Agreement_Date__c.day()
                            ).format(dateFormat);
                    if (opportunity.StageName.equals(GlobalUtils.getOpportunityStageName(GlobalUtils.OpportunityStage.MovedToStart))
                            && opportunity.CloseDate != null) {
                        responseBody.customerInfo.invoicePaymentDate =
                                Datetime.newInstance(
                                        opportunity.CloseDate.year(),
                                        opportunity.CloseDate.month(),
                                        opportunity.CloseDate.day()
                                ).format(dateFormat);
                    }
                }
            }
        } else {
            responseBody.message = 'Internal server error. Response source is empty';
        }
        return responseBody;
    }

    /*******************************************************************************
    *  Name            : constructPPR_API_responseBody(String inn, String source)
    *  Summary         : builds response body for PPR API by INN and source with short body (method with DB operations)
    *  CreatedDate     : 11/02/2020
    *  ModifiedDate    : -
    *  Parameters      : String inn, String source
    *  Returns         : PPR_API_ResponseBody
    ******************************************************************************/
    public static PPR_API_ResponseBody constructPPR_API_responseBodyShort(String inn, String source) {
        String dateFormat = 'dd.MM.yyyy';
        E2EFormRuDao formRuDao = new E2EFormRuDaoImpl();
        Custom_log__c log = PPR_API_LogService.getLogByInnAndSource(inn, source);
        PPR_API_ResponseBody responseBody = new PPR_API_ResponseBody();
        if (log != null) {
            responseBody.metadata = new PPR_API_ResponseBody.Metadata();
            responseBody.customerInfo = new PPR_API_ResponseBody.CustomerInfo();
            responseBody.metadata.user = log.External_user__c;
            responseBody.message = log.Errors__c;
            responseBody.customerInfo.inn = log.INN__c;

            E2EFormData__c formData = formRuDao.getFormDataById(log.E2E_Form_Ru_Data__c);
            if (formData != null) {
                responseBody.metadata.id = formData.Id;
                responseBody.customerInfo.customerStatus = formData.E2E_Process_Status__c;
                responseBody.customerInfo.customerStatusId = (String) PPR_Mapping_Utils.customerStatusMap.get(formData.E2E_Process_Status__c);
                responseBody.customerInfo.checkDate = formData.Last_deduplication_time__c == null ? null : formData.Last_deduplication_time__c.format(dateFormat);
            }
        } else {
            responseBody.message = 'Internal server error. Response source is empty';
        }
        return responseBody;
    }

    /*******************************************************************************
    *  Name            : constructPPR_API_responseBody(E2EFormParams formParams)
    *  Summary         : builds response body for PPR API with short body (method without DB operations)
    *  CreatedDate     : 11/02/2020
    *  ModifiedDate    : -
    *  Parameters      : E2EFormParams formParams
    *  Returns         : PPR_API_ResponseBody
    ******************************************************************************/
    public static PPR_API_ResponseBody constructPPR_API_responseBody(E2EFormParams formParams) {
        String dateFormat = 'dd.MM.yyyy';
        PPR_API_ResponseBody responseBody = new PPR_API_ResponseBody();
        if (formParams != null) {
            responseBody.metadata = new PPR_API_ResponseBody.Metadata();
            responseBody.customerInfo = new PPR_API_ResponseBody.CustomerInfo();
            responseBody.metadata.id = formParams.formDataId;
            responseBody.metadata.user = formParams.externalUser;
            responseBody.customerInfo.customerStatus = formParams.processStatus;
            responseBody.customerInfo.customerStatusId = (String) PPR_Mapping_Utils.customerStatusMap.get(formParams.processStatus);
            responseBody.customerInfo.inn = formParams.companyInn;
            responseBody.message = formParams.errors;
            responseBody.customerInfo.checkDate = formParams.deduplicationDatetime == null ? null : formParams.deduplicationDatetime.format(dateFormat);
        } else {
            responseBody.message = 'Internal server error. Response source is empty';
        }
        return responseBody;
    }

    private static Opportunity getOpportunity(Id opportunityId) {
        List<Opportunity> opportunities = ([
                SELECT Id, Agreement_Date__c, CloseDate, StageName
                FROM Opportunity
                WHERE Id = :opportunityId
                LIMIT 1
        ]);
        return opportunities.size() == 1 ? opportunities.get(0) : null;
    }

    /*******************************************************************************
    *  Name            : constructPPR_API_responseBody(Exception e)
    *  Summary         : builds response body for PPR API with exception
    *  CreatedDate     : 11/02/2020
    *  ModifiedDate    : -
    *  Parameters      : Exception e
    *  Returns         : PPR_API_ResponseBody
    ******************************************************************************/
    public static PPR_API_ResponseBody constructPPR_API_ResponseBodyException(Exception e) {
        PPR_API_ResponseBody responseBody = new PPR_API_ResponseBody();
        responseBody.message = e == null ? 'Internal server error. Response source is empty' : e.getMessage();
        return responseBody;
    }


    /*******************************************************************************
    *  Name            : constructPPR_API_responseBody()
    *  Summary         : builds response body for PPR API with error message
    *  CreatedDate     : 11/02/2020
    *  ModifiedDate    : -
    *  Parameters      : String error
    *  Returns         : PPR_API_ResponseBody
    ******************************************************************************/
    public static PPR_API_ResponseBody constructPPR_API_ResponseBodyError(String error) {
        PPR_API_ResponseBody responseBody = new PPR_API_ResponseBody();
        responseBody.message = error == null ? 'Internal server error. Response source is empty' : error;
        return responseBody;
    }

}