default/objects/Custom_log__c/Custom_log__c.object-meta.xml
<CustomObject>
    <description>contains log of the process</description>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Promocodes__c/E2E_Promocodes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>list of promocedes</description>
    <label>E2E Promocodes</label>
</CustomObject>

default/objects/E2EFormData__c/E2EFormData__c.object-meta.xml
<CustomObject>
    <description>Store data from E2E Form</description>
    <label>E2E Form Ru Data</label>
    <nameField>
        <displayFormat>E2ERU{00000000}</displayFormat>
        <label>E2EFormRuData  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>E2E Form Ru Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

default/objects/E2EFormData__c/fields/E2E_Manual_Entry__c.field-meta.xml
<CustomField>
    <fullName>E2E_Manual_Entry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Entry</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2EFormData__c/fields/E2E_Process_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Process_Status__c</fullName>
    <description>Статусы успешно пройденных процессов по форме E2E</description>
    <label>Process status</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/LongForm_Fleetcor_Product__c/LongForm_Fleetcor_Product__c.object-meta.xml
<CustomObject>
    <label>LongForm Fleetcor Product</label>
    <nameField>
        <label>LongForm Fleetcor Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LongForm Fleetcor Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/LongForm_Fleetcor_Product__c/fields/Long_Form_Offer__c.field-meta.xml
<CustomField>
    <fullName>Long_Form_Offer__c</fullName>
    <label>Long Form Offer</label>
    <referenceTo>LongForm_Offer__c</referenceTo>
    <relationshipName>Long_Form_Fleetcor_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/LongForm_Offer__c/LongForm_Offer__c.object-meta.xml
<CustomObject>
    <label>LongForm Offer</label>
    <nameField>
        <displayFormat>LFOFR-{00000}</displayFormat>
        <label>LongForm Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LongForm Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/LongForm_Tariff__c/LongForm_Tariff__c.object-meta.xml
<CustomObject>
    <label>LongForm Tariff</label>
    <nameField>
        <label>LongForm Tariff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LongForm Tariffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/LongForm_Tariff__c/fields/LongForm_Fleetcor_Product__c.field-meta.xml
<CustomField>
    <fullName>LongForm_Fleetcor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LongForm Fleetcor Product</label>
    <referenceTo>LongForm_Fleetcor_Product__c</referenceTo>
    <relationshipLabel>LongForm Tariffs</relationshipLabel>
    <relationshipName>LongForm_Tariffs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/PPR_API_Settings__c/PPR_API_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for PPR API Controllers, Services, etc</description>
    <label>PPR_API_Settings</label>
</CustomObject>

default/classes/PPR_API_CreateClient_Test.cls
@isTest
public with sharing class PPR_API_CreateClient_Test {

    private static void initTestData() {
        E2EFormRuTestUtils.initCustomSettings();

        List<E2E_Promocodes__c> promocodes = new List<E2E_Promocodes__c>();
        promocodes.add(PPR_API_DataTestFactory.createPromocode('9Е06', '@159;', '159@19,9;'));
        promocodes.add(PPR_API_DataTestFactory.createPromocode('9Е07', '@160;', '160@19,17;'));
        insert promocodes;

        PPR_API_Settings__c settingEuroplan = PPR_API_DataTestFactory.createPPR_API_Settings();
        insert settingEuroplan;
    }
    
    @isTest
    public static void doPostCreateClientTest() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/DemoUrl/PPR_API/v1/CreateClient';
        req.httpMethod = 'POST';

        initTestData();
        E2EFormData__c formData = E2EFormRuTestUtils.createDefaultFormData();
        formData.E2E_Process_Status__c = 'New';
        insert formData;
        Map<String, Object> testRequest = PPR_API_DataTestFactory.generateTestRequest(formData.Id, '1234567890');

        req.requestBody = Blob.valueof(JSON.serialize(testRequest));
        RestContext.request = req;
        RestContext.response = res;
        LongForm_Tariff__c tarif = new LongForm_Tariff__c(Name = '2CHOOSEN_cards');
        insert tarif;
        LongForm_Offer__c offer = new LongForm_Offer__c();
        insert offer;
        LongForm_Fleetcor_Product__c product = new LongForm_Fleetcor_Product__c(Name = 'PetrolPlus_Rover', Long_Form_Offer__c = offer.Id);
        insert product;

        Custom_log__c newLog = PPR_API_DataTestFactory.createCustomLog(formData.Id, '1234567890');
        insert newLog;

        Test.startTest();
        PPR_API_CreateClient.doPost();
        Test.stopTest();

        String testBlob = RestContext.response.responseBody.toString();
        PPR_API_ResponseBody responce = (PPR_API_ResponseBody) JSON.deserializeStrict(testBlob, PPR_API_ResponseBody.class);

        System.assertNotEquals(null, responce);
        System.assertEquals(null, responce.message);
        System.assertEquals('Processing', responce.customerInfo.customerStatus);
    }

    @isTest
    public static void doPostSendToInboundTest() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/DemoUrl/PPR_API/v1/CreateClient';
        req.httpMethod = 'POST';

        initTestData();
        E2EFormData__c formData = E2EFormRuTestUtils.createDefaultFormData();
        formData.E2E_Manual_Entry__c = true;
        formData.E2E_Process_Status__c = 'New';
        insert formData;
        Map<String, Object> testRequest = PPR_API_DataTestFactory.generateTestRequest(formData.Id, '1234567891');

        req.requestBody = Blob.valueof(JSON.serialize(testRequest));
        RestContext.request = req;
        RestContext.response = res;
        LongForm_Tariff__c tarif = new LongForm_Tariff__c(Name = '2CHOOSEN_cards');
        insert tarif;
        LongForm_Offer__c offer = new LongForm_Offer__c();
        insert offer;
        LongForm_Fleetcor_Product__c product = new LongForm_Fleetcor_Product__c(Name = 'PetrolPlus_Rover', Long_Form_Offer__c = offer.Id);
        insert product;

        Custom_log__c newLog = PPR_API_DataTestFactory.createCustomLog(formData.Id, '1234567891');
        insert newLog;

        Test.startTest();
        PPR_API_CreateClient.doPost();
        Test.stopTest();

        String testBlob = RestContext.response.responseBody.toString();
        PPR_API_ResponseBody responce = (PPR_API_ResponseBody) JSON.deserializeStrict(testBlob, PPR_API_ResponseBody.class);

        System.assertNotEquals(null, responce);
        System.assertEquals(null, responce.message);
        System.assertEquals('Processing', responce.customerInfo.customerStatus);
    }

    @isTest
    public static void doPostErrorSourceTest() {
        initTestData();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/DemoUrl/PPR_API/v1/CreateClient';
        req.httpMethod = 'POST';
        Map<String, Object> testRequest = PPR_API_DataTestFactory.generateTestRequest(null, '1234567892');
        req.requestBody = Blob.valueof(JSON.serialize(testRequest));
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        PPR_API_CreateClient.doPost();
        Test.stopTest();

        String testBlob = RestContext.response.responseBody.toString();
        PPR_API_ResponseBody responce = (PPR_API_ResponseBody) JSON.deserializeStrict(testBlob, PPR_API_ResponseBody.class);
        System.assertEquals('Validation error. Invalid product: PetrolPlus_Rover', responce.message);
    }

    @isTest
    public static void doPostErrorTest() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/DemoUrl/PPR_API/v1/CreateClient';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        insert CFTestDataFactory.createCustomSettings();

        Test.startTest();
        PPR_API_CreateClient.doPost();
        Test.stopTest();

        String testBlob = RestContext.response.responseBody.toString();
        PPR_API_ResponseBody responce = (PPR_API_ResponseBody) JSON.deserializeStrict(testBlob, PPR_API_ResponseBody.class);
        System.assertEquals('System.NullPointerException: Argument cannot be null.', responce.message);
    }

    @isTest
    public static void createClientOnlyRequiredDataTest() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/DemoUrl/PPR_API/v1/CreateClient';
        req.httpMethod = 'POST';

        initTestData();
        E2EFormData__c formData = E2EFormRuTestUtils.createDefaultFormData();
        formData.E2E_Process_Status__c = 'New';
        insert formData;
        Map<String, Object> testRequest = PPR_API_DataTestFactory.generateTestRequestMandatoryFields(formData.Id, '1234567893');

        req.requestBody = Blob.valueof(JSON.serialize(testRequest));
        RestContext.request = req;
        RestContext.response = res;
        LongForm_Tariff__c tarif = new LongForm_Tariff__c(Name = '2CHOOSEN_cards');
        insert tarif;
        LongForm_Offer__c offer = new LongForm_Offer__c();
        insert offer;
        LongForm_Fleetcor_Product__c product = new LongForm_Fleetcor_Product__c(Name = 'PetrolPlus_Rover', Long_Form_Offer__c = offer.Id);
        insert product;

        Custom_log__c newLog = PPR_API_DataTestFactory.createCustomLog(formData.Id, '1234567893');
        insert newLog;

        Test.startTest();
        PPR_API_CreateClient.doPost();
        Test.stopTest();

        String testBlob = RestContext.response.responseBody.toString();
        PPR_API_ResponseBody responce = (PPR_API_ResponseBody) JSON.deserializeStrict(testBlob, PPR_API_ResponseBody.class);

        System.assertNotEquals(null, responce);
        System.assertEquals(null, responce.message);
        System.assertEquals('Processing', responce.customerInfo.customerStatus);
    }
}