default/objects/Emarsys_Log__c/Emarsys_Log__c.object-meta.xml
<CustomObject>
    <label>Emarsys Log</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Emarsys Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emarsys Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Emarsys_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Emarsys Logs</relationshipLabel>
    <relationshipName>Emarsys_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Первый контакт по inbound</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Anruf</fullName>
            </value>
            <value>
                <fullName>FLMT_Form</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/E2E_Adoption_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Adoption_Status__c</fullName>
    <defaultValue>'Manual Process'</defaultValue>
    <label>E2E Adoption Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manual Process</fullName>
                <default>true</default>
                <label>Manual Process</label>
            </value>
            <value>
                <fullName>Adoption Email Sent</fullName>
            </value>
            <value>
                <fullName>Successful Adoption</fullName>
            </value>
            <value>
                <fullName>Returned to Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Number_of_Cards_facebook__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Cards_facebook__c</fullName>
    <description>Field for the facebook form integration.</description>
    <label>Number of Cards (facebook)</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/EmarsysLogTriggerTest.cls
@isTest
public class EmarsysLogTriggerTest {

    @isTest
    private static void testUpdateLeadStaus() {
        Lead lead = new Lead(
                LastName = 'test name',
                Company = 'test company',
                Sec_Channel__c = 'Inbound',
                Number_of_Cards_facebook__c = '1',
                Country='Germany',
                CountryCode='DE',
                Channel__c = 'Internet',
                Email='test@test.com',
                Phone ='111111111111');
        insert lead;
        Test.startTest();
        Emarsys_Log__c log = new Emarsys_Log__c(
            Lead__c = lead.Id
        );
        insert log;
        Test.stopTest();
        Lead updatedLead = [SELECT E2E_Adoption_Status__c FROM Lead WHERE Id =: lead.Id];
        System.assertEquals('Adoption Email Sent', updatedLead.E2E_Adoption_Status__c);
    }
}