default/objects/Account/recordTypes/Russian.recordType-meta.xml
<RecordType>
    <fullName>Russian</fullName>
    <active>true</active>
    <label>Russian</label>
</RecordType>

default/objects/Contact/fields/Additional_Phones__c.field-meta.xml
<CustomField>
    <fullName>Additional_Phones__c</fullName>
    <description>List of additional phones</description>
    <label>Additional Phones</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Contact/fields/PPR_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>PPR_Contact_Phone__c</fullName>
    <label>PPR Contact Phone</label>
    <type>Phone</type>
</CustomField>

default/objects/Contact/recordTypes/Russian.recordType-meta.xml
<RecordType>
    <fullName>Russian</fullName>
    <active>true</active>
    <label>Russian</label>
</RecordType>

default/objects/Lead/fields/Naumen_Autocall_Case_UUID__c.field-meta.xml
<CustomField>
    <fullName>Naumen_Autocall_Case_UUID__c</fullName>
    <description>UUID of the autocall case in Naumen predictive dialing outbound project</description>
    <externalId>true</externalId>
    <label>Naumen Autocall Case UUID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Lead/fields/PPR_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>PPR_Contact_Phone__c</fullName>
    <label>PPR Contact Phone</label>
    <type>Phone</type>
</CustomField>

default/objects/Lead/fields/Source_of_Lead__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Lead__c</fullName>
    <label>Source of Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Актуализированная БД</fullName>
            </value>
            <value>
                <fullName>Прочая БД</fullName>
                <default>true</default>
                <label>Прочая БД</label>
            </value>
            <value>
                <fullName>Выставка</fullName>
            </value>
            <value>
                <fullName>Найден в Интернете</fullName>
            </value>
            <value>
                <fullName>Реклама Клиента</fullName>
            </value>
            <value>
                <fullName>Рекомендация</fullName>
            </value>
            <value>
                <fullName>Партнерская Программа</fullName>
            </value>
            <value>
                <fullName>Business card</fullName>
            </value>
            <value>
                <fullName>Почтовая рассылка</fullName>
            </value>
            <value>
                <fullName>Реклама на АЗС</fullName>
            </value>
            <value>
                <fullName>Email рассылка</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.ru</fullName>
            </value>
            <value>
                <fullName>Поисковая Система</fullName>
            </value>
            <value>
                <fullName>Реклама в СМИ</fullName>
            </value>
            <value>
                <fullName>Акция Рекомендация</fullName>
            </value>
            <value>
                <fullName>Интернет Источники</fullName>
            </value>
            <value>
                <fullName>Сайт fuel.veb-leasing.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Petrolplus.kz</fullName>
            </value>
            <value>
                <fullName>Petrolcards.ru - АГГРЕГАТОР</fullName>
            </value>
            <value>
                <fullName>АЗС Заявка Shell</fullName>
            </value>
            <value>
                <fullName>Facebook_Lotos</fullName>
            </value>
            <value>
                <fullName>Facebook_CCS</fullName>
            </value>
            <value>
                <fullName>Сайт gpc-store.ru</fullName>
            </value>
            <value>
                <fullName>Сайт Shell Card.ru</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/recordTypes/Russian_Sales.recordType-meta.xml
<RecordType>
    <fullName>Russian_Sales</fullName>
    <active>true</active>
    <businessProcess>Russian Sales</businessProcess>
    <label>Russian Sales</label>
</RecordType>

default/objects/Naumen_Settings__c/Naumen_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for integration with Naumen CTI</description>
    <label>Naumen Settings</label>
</CustomObject>

default/objects/Naumen_Settings__c/fields/Admin_Emails__c.field-meta.xml
<CustomField>
    <fullName>Admin_Emails__c</fullName>
    <description>Admin Emails who will get errors notifications.</description>
    <inlineHelpText>example: &quot;test1@test.com,test2@test.com&quot;</inlineHelpText>
    <label>Admin Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Naumen_Settings__c/fields/REST_Passw__c.field-meta.xml
<CustomField>
    <fullName>REST_Passw__c</fullName>
    <description>Credentials for Naumen REST API</description>
    <label>REST Passw</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Naumen_Settings__c/fields/REST_URL__c.field-meta.xml
<CustomField>
    <fullName>REST_URL__c</fullName>
    <label>REST URL</label>
    <type>Url</type>
</CustomField>

default/objects/Naumen_Settings__c/fields/REST_Username__c.field-meta.xml
<CustomField>
    <fullName>REST_Username__c</fullName>
    <description>Credentials for Naumen REST API</description>
    <label>REST Username</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Naumen_Settings__c/fields/Supervisor_Emails__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_Emails__c</fullName>
    <description>Supervisor Emails who will get info notifications in certain cases.</description>
    <inlineHelpText>example: &quot;test1@test.com,test2@test.com&quot;</inlineHelpText>
    <label>Supervisor Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Naumen_Settings__c/fields/UploadResultsRecievers_Emails__c.field-meta.xml
<CustomField>
    <fullName>UploadResultsRecievers_Emails__c</fullName>
    <description>Emails to which upload results will be sent while uploading SF records to naumen autocall cases (Naumen Supervisor Panel uploading functionality)</description>
    <inlineHelpText>example: &quot;test1@test.com,test2@test.com&quot;</inlineHelpText>
    <label>Upload Results Recievers Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/fields/Naumen_Autocall_Project_UUID__c.field-meta.xml
<CustomField>
    <fullName>Naumen_Autocall_Project_UUID__c</fullName>
    <description>UUID of the predictive dialing Naumen autocall project</description>
    <label>Naumen Autocall Project UUID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Opportunity/recordTypes/Russian_Sales.recordType-meta.xml
<RecordType>
    <fullName>Russian_Sales</fullName>
    <active>true</active>
    <businessProcess>Russian Sales</businessProcess>
    <label>Russian Sales</label>

</RecordType>

default/classes/CreateCSVBatchTest.cls
@IsTest
private class CreateCSVBatchTest {
    @TestSetup
    private static void testSetup(){
// ---- settings----
        // cf settings
        insert CFUtilsTest.createCFSettingsForRussia(false);
        // naumen settings
        Naumen_Settings__c naumenSettings = new Naumen_Settings__c();
        naumenSettings.Admin_Emails__c = 'test@test.ru';
        naumenSettings.Supervisor_Emails__c = 'test1@test.ru';
        naumenSettings.UploadResultsRecievers_Emails__c = 'test2@test.ru';
        naumenSettings.REST_Passw__c = 'testpassw';
        naumenSettings.REST_URL__c = 'https://test.ru';
        naumenSettings.REST_Username__c = 'testusername';
        insert naumenSettings;
        // cc speed up settings
        RecordAssignCheckRuTest.testSetupMethod();
// ---- create lead data----
        Id rtLeadRU = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Russian_Sales').getRecordTypeId();
        Id rtOppRU = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Russian_Sales').getRecordTypeId();
        Id rtConRU = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Russian').getRecordTypeId();
        Id rtAccRU = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Russian').getRecordTypeId();
        Lead lead0 = new Lead(
            LastName = 'test 0',
            Source_of_Lead__c = 'E2E Form RU',
            Country = 'Russia',
            Company = 'test acc',
            RecordTypeId = rtLeadRU,
            Phone = '+79291111111',
            MobilePhone = '+79292222222',
            ppr_contact_phone__c = '+79293333333',
            Additional_Phones__c = '+70932093208!New!!2307202304.+79320749387!New!!2307202305'
        );
        Lead lead1 = new Lead(
                LastName = 'test 1',
                Source_of_Lead__c = 'E2E Form RU',
                Country = 'Russia',
                Company = 'test acc',
                RecordTypeId = rtLeadRU,
                Phone = '+79291111111',
                MobilePhone = '+79292222222',
                ppr_contact_phone__c = '+79293333333',
                Additional_Phones__c = '+70932093208!New!!2307202304.+79320749387!New!!2307202305',
                Naumen_Autocall_Project_UUID__c = 'corebo00000000000mtu5ka4v3jcrj6c',
                Naumen_Autocall_Case_UUID__c = 'hdh6786aadhkjadhksd7s78'
        );
        insert new List <Lead> {lead0, lead1};

// ---- create opportunity data----
        Account newAccount = new Account(
                Name = 'test1',
                BillingCountry = 'Russia',
                RecordTypeId = rtAccRU);
        insert newAccount;

        Opportunity newOpp = new Opportunity(
                StageName = 'Qualify',
                Name = 'test opp1',
                CloseDate = Date.today(),
                RecordTypeId = rtOppRU,
                AccountId = newAccount.Id);
        insert newOpp;

        Contact conWithOppRole = new Contact(
                FirstName = 'Test2',
                LastName = 'Testov',
                Email = 'test@example.com',
                Phone = '+75554445551',
                RecordTypeId = rtConRU,
                AccountId = newAccount.Id);
        Contact con = new Contact(
                FirstName = 'Test1',
                LastName = 'Testov',
                Email = 'test@example.com',
                Phone = '+75554445552',
                RecordTypeId = rtConRU,
                AccountId = newAccount.Id);
        insert new List <Contact> {conWithOppRole, con};

        OpportunityContactRole testRole = new OpportunityContactRole(
                ContactId = conWithOppRole.Id,
                OpportunityId = newOpp.Id,
                isPrimary = true);
        insert testRole;
    }
    @IsTest
    private static void testBatch_Leads() {
        String endQuery = ' ORDER BY LastModifiedDate desc limit 2';
        List <String> emailRecievers = new List <String> {'test@example.com'};
        String emailSubject = 'Email subject';
        String emailBody = 'Email body';
        String fileName = 'test.csv';
        Test.startTest();
            Naumen_RecordsHelper.RecordsTableParams recordsTableParams = Naumen_SupervisorPanelCtrl.createTableRecordsParams('Lead');
            CreateCSVBatch  batch = new CreateCSVBatch (recordsTableParams, endQuery, false, true, emailRecievers, emailSubject, emailBody, fileName);
            Database.executeBatch(batch, 100);
        Test.stopTest(); 
        system.assertEquals(2, CreateCSVBatch.csvRowsCount); // 2 leads
    }
    @IsTest
    private static void testBatch_Opportunities() {
        String endQuery = ' ORDER BY LastModifiedDate desc limit 2';
        List <String> emailRecievers = new List <String> {'test@example.com'};
        String emailSubject = 'Email subject';
        String emailBody = 'Email body';
        String fileName = 'test.csv';
        Test.startTest();
            Naumen_RecordsHelper.RecordsTableParams recordsTableParams = Naumen_SupervisorPanelCtrl.createTableRecordsParams('Opportunity');
            system.debug('fieldsList : ' + recordsTableParams.fieldsList);
            CreateCSVBatch  batch = new CreateCSVBatch (recordsTableParams, endQuery, false, true, emailRecievers, emailSubject, emailBody, fileName);
            Database.executeBatch(batch, 100);
        Test.stopTest(); 
        system.assertEquals(1, CreateCSVBatch.csvRowsCount); // 1 opp
    }
    @IsTest
    private static void testBatch_CCSpeedUpCheck() {
        String endQuery = ' ORDER BY LastModifiedDate desc limit 2';
        List <String> emailRecievers = new List <String> {'test@example.com'};
        String emailSubject = 'Email subject';
        String emailBody = 'Email body';
        String fileName = 'test.csv';
        Test.startTest();
            Naumen_RecordsHelper.RecordsTableParams recordsTableParams = Naumen_SupervisorPanelCtrl.createTableRecordsParams('Opportunity');
            system.debug('fieldsList : ' + recordsTableParams.fieldsList);
            CreateCSVBatch  batch = new CreateCSVBatch (recordsTableParams, endQuery, true, true, emailRecievers, emailSubject, emailBody, fileName);
            Database.executeBatch(batch, 100);
        Test.stopTest(); 
        system.assertEquals(0, CreateCSVBatch.csvRowsCount); // 0 free opps
    }
}