default/objects/Emarsys_Contact_Subscriptions__c/Emarsys_Contact_Subscriptions__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Emarsys Contact Subscriptions</label>
</CustomObject>

default/objects/Emarsys_Contact_Subscriptions__c/fields/Contact_List_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_List_Id__c</fullName>
    <label>Contact List Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Emarsys_Contact_Subscriptions__c/fields/Last_Update_Segment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Update_Segment_Date__c</fullName>
    <label>Last Update Segment Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Emarsys_Contact_Subscriptions__c/fields/Segment_Id__c.field-meta.xml
<CustomField>
    <fullName>Segment_Id__c</fullName>
    <label>Segment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

default/classes/EmarsysContactIdsGathererSchedule.cls
global class EmarsysContactIdsGathererSchedule implements Schedulable {
    public static final String JOB_NAME = 'Emarsys Gahter Contact Ids';
    public static final String FIRST_RUN_CRON = '0 0 2 ? * MON-FRI';

    /*******************************************************************************
     *  Name            : execute(SchedulableContext sc)
     *  Summary         : run job for get contact list in EmarsysContactIdsGatherer
     *  CreatedDate     : 07/10/2020
     *  Parameters      : Schedulable sc - object to track the schedulable job
     *  Returns         : void
     ******************************************************************************/
    global void execute(SchedulableContext sc) {
        String emarsysAccount = GlobalUtils.getEmarsysAccount(GlobalUtils.EmarsysAccounts.AccountRus.name());
        Datetime yesterdayEndDate = Datetime.newInstance(Date.today().addDays(-1), Time.newInstance(18, 0, 0, 0));

        List<Emarsys_Contact_Subscriptions__c> conSubList = [
                SELECT Id, Contact_list_id__c, Segment_Id__c
                FROM Emarsys_Contact_Subscriptions__c
                WHERE Contact_list_id__c != NULL AND Last_Update_Segment_Date__c < :yesterdayEndDate
        ];

        Boolean fisrtRun = EmarsysContactsJobService.checkIsFirstLaunch(JOB_NAME, FIRST_RUN_CRON);

        if (conSubList.isEmpty()) {
            EmarsysContactsJobService.scheduleJob(JOB_NAME, 0, fisrtRun ? 3 : 2, EmarsysContactsJobService.JobTypes.JOB_CONT_RETRIEV);
        } else {
            EmarsysContactIdsGatherer conIdGatherer = new EmarsysContactIdsGatherer(conSubList, emarsysAccount);
            System.enqueueJob(conIdGatherer);
        }
    }
}