default/objects/E2E_Form_General_Settings__c/E2E_Form_General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>E2E Form General Settings</label>
</CustomObject>

default/objects/E2E_Form_General_Settings__c/fields/Integration_Admin_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Admin_Id__c</fullName>
    <label>Integration Admin Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Short_Url__c/E2E_Short_Url__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>E2E Short Url</label>
</CustomObject>

default/objects/E2E_Short_Url__c/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <label>Private Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/CCS_number_of_cards__c.field-meta.xml
<CustomField>
    <fullName>CCS_number_of_cards__c</fullName>
    <label>CCS_number_of_cards</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Lead/fields/Contact_Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Body__c</fullName>
    <label>Contact Email Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

default/objects/Lead/fields/E2E_Adoption_Status__c.field-meta.xml
<CustomField>
    <fullName>E2E_Adoption_Status__c</fullName>
    <defaultValue>'Manual Process'</defaultValue>
    <label>E2E Adoption Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manual Process</fullName>
                <default>true</default>
                <label>Manual Process</label>
            </value>
            <value>
                <fullName>Adoption Email Sent</fullName>
            </value>
            <value>
                <fullName>Successful Adoption</fullName>
            </value>
            <value>
                <fullName>Returned to Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Partner_OBN__c.field-meta.xml
<CustomField>
    <fullName>Partner_OBN__c</fullName>
    <label>Partner-OBN</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Quali_Status__c.field-meta.xml
<CustomField>
    <fullName>Quali_Status__c</fullName>
    <label>Quali-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>-</fullName>
            </value>
            <value>
                <fullName>Already Allstar Customer</fullName>
            </value>
            <value>
                <fullName>Already CCS customer</fullName>
            </value>
            <value>
                <fullName>Already Lotos Customer</fullName>
            </value>
            <value>
                <fullName>Anwahllimit erreicht</fullName>
            </value>
            <value>
                <fullName>Bereits Kunde - FleetCor</fullName>
            </value>
            <value>
                <fullName>Bereits Kunde - Shell</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Centrally decided</fullName>
            </value>
            <value>
                <fullName>Company ceased to exist</fullName>
            </value>
            <value>
                <fullName>Competitor´s customer - CS request</fullName>
            </value>
            <value>
                <fullName>Competitor - request</fullName>
            </value>
            <value>
                <fullName>Competitors</fullName>
            </value>
            <value>
                <fullName>Coverage/Acceptance</fullName>
            </value>
            <value>
                <fullName>Customer reached – additional information required</fullName>
            </value>
            <value>
                <fullName>Customer reached – call later</fullName>
            </value>
            <value>
                <fullName>Customer reached – didn’t talk to decision maker</fullName>
            </value>
            <value>
                <fullName>Customer reached – email sent</fullName>
            </value>
            <value>
                <fullName>Customer reached – first meeting</fullName>
            </value>
            <value>
                <fullName>Customer reached – follow up (seasonality)</fullName>
            </value>
            <value>
                <fullName>Customer reached – forwarded to Field</fullName>
            </value>
            <value>
                <fullName>Customer reached – next meeting(s)</fullName>
            </value>
            <value>
                <fullName>Do Not Contact</fullName>
            </value>
            <value>
                <fullName>Dublette</fullName>
            </value>
            <value>
                <fullName>Financial/Credit</fullName>
            </value>
            <value>
                <fullName>Follow UP</fullName>
            </value>
            <value>
                <fullName>Follow up email #1 sent</fullName>
            </value>
            <value>
                <fullName>Follow up email #2 sent</fullName>
            </value>
            <value>
                <fullName>Forwarded</fullName>
            </value>
            <value>
                <fullName>Forwarded internally</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/SwitchLeadToE2EQueueable.cls
global class SwitchLeadToE2EQueueable implements Queueable {
    private String leadId;
    private Boolean isSwitchToE2E;

    global SwitchLeadToE2EQueueable(String leadId, Boolean isSwitchToE2E) {
        this.leadId = leadId;
        this.isSwitchToE2E = isSwitchToE2E;
    }

    /*******************************************************************************
     *  Summary         : Find duplicate lead and automatically switch to e2e
     *  Created         : 13/02/2020 by Artem Voitik
     *  Parameters      : QueueableContext context
     *  Returns         : void
    ******************************************************************************/
    global void execute(QueueableContext context) {
        try {
            Lead lead = [SELECT Salutation, RecordType.Name, Partner_OBN__c, LeadSource, CCS_number_of_cards__c, Status, Contact_Email_Body__c, Country, Company, LastName, FirstName, Phone, Email, (SELECT NewValue FROM Histories LIMIT 100) FROM Lead WHERE Id = :this.leadId LIMIT 1];
            System.debug(lead);

            List<Lead> checkDuplicatesList = [
                    SELECT Id
                    FROM Lead
                    WHERE ((FirstName = :lead.FirstName AND LastName = :lead.LastName AND Email = :lead.Email) OR
                    (FirstName = :lead.FirstName AND LastName = :lead.LastName AND Phone = :lead.Phone) OR
                    (Company = :lead.Company AND Phone = :lead.Phone) OR
                    (Company = :lead.Company AND Email = :lead.Email)) AND
                    Country = :lead.Country AND
                    (Quali_Status__c != 'Auto-detect (E2E)' OR Quali_Status__c != 'Auto-detect') AND
                    Status != 'Disqualified' AND
                    Id != :lead.Id
                    LIMIT 1];
            if ( ! checkDuplicatesList.isEmpty() ) {
                this.isSwitchToE2E = false;
                lead.Status = 'Disqualified';
                lead.Quali_Status__c = 'Auto-detect (E2E)';
                update lead;

                return;
            }

            for (LeadHistory leadhistory : lead.Histories) {
                if (String.valueOf(leadhistory.NewValue) == 'Switched to E2E') {
                    return;
                }
            }

            E2E_Form_General_Settings__c e2eGeneralSettings = E2E_Form_General_Settings__c.getInstance(lead.Country);
            if (e2eGeneralSettings == null) {
                return;
            }
            if (lead.Salutation == null || lead.Salutation == '') {
                lead.Salutation = 'Mr.';
            }
            lead.OwnerId = e2eGeneralSettings.Integration_Admin_Id__c;
            lead.E2E_Short_Link__c = generateShortId(lead.Id, lead.Country);
            lead.Quali_Status__c = 'Switched to E2E';
            lead.E2E_Adoption_Status__c = 'Adoption Email Sent';
            lead.E2E_Adoption_Date__c = Date.today();

            if (lead.Company != null && lead.Company.containsIgnoreCase('[nicht vorhanden]') || lead.Company == null) {
                lead.Company = 'LONGFORM: ' + (lead.FirstName != null ? lead.FirstName + ' ' : '') + lead.LastName;
            }
            update lead;
        } catch (Exception e) {
            ExceptionLogger.sendException('SwitchLeadToE2EQueueable.execute line of the error: ', String.valueOf(e.getStackTraceString()) + ', message: ' + e.getMessage());
        }
    }

    private static String generateShortId(String leadId, String country) {
        E2E_Short_Url__c e2eShortUrlDetail = E2E_Short_Url__c.getInstance(country);
        String finalParam = String.valueOf(leadId);
        String shortid = EncodingUtil.urlEncode(
                EncodingUtil.base64Encode(Crypto.encryptWithManagedIV('AES128',
                        Blob.valueOf(e2eShortUrlDetail.Private_Key__c),
                        Blob.valueOf(finalParam))), 'UTF-8')
                .replace('%', '').substring(1, 7);
        return shortid;
    }
}