default/objects/E2EFormData__c/E2EFormData__c.object-meta.xml
<CustomObject>
    <description>Store data from E2E Form</description>
    <label>E2E Form Ru Data</label>
    <nameField>
        <displayFormat>E2ERU{00000000}</displayFormat>
        <label>E2EFormRuData  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>E2E Form Ru Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

default/objects/E2EFormData__c/fields/E2E_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>E2E_Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>E2E Form Ru Data</relationshipLabel>
    <relationshipName>E2EFormRuData</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2EFormData__c/fields/E2E_Billing_City__c.field-meta.xml
<CustomField>
    <fullName>E2E_Billing_City__c</fullName>
    <label>Billing city</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2EFormData__c/fields/E2E_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>E2E_Contact_Email__c</fullName>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

default/objects/E2EFormData__c/fields/E2E_Legal_Address__c.field-meta.xml
<CustomField>
    <fullName>E2E_Legal_Address__c</fullName>
    <label>Legal address</label>
    <length>1300</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/E2EFormData__c/fields/E2E_Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>E2E_Opportunity_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>E2E Form Ru Data</relationshipLabel>
    <relationshipName>E2EFormRuData</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2EFormData__c/fields/E2E_Post_Address__c.field-meta.xml
<CustomField>
    <fullName>E2E_Post_Address__c</fullName>
    <label>Shipping Address</label>
    <length>1300</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/E2EFormData__c/fields/E2E_Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>E2E_Shipping_City__c</fullName>
    <label>Shipping city</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2EFormData__c/fields/E2E_Shipping_House__c.field-meta.xml
<CustomField>
    <fullName>E2E_Shipping_House__c</fullName>
    <label>Shipping House</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/classes/PPR_API_ServiceImplHelperTest.cls
@isTest
public with sharing class PPR_API_ServiceImplHelperTest {

    @isTest
    public static void createStreetStringTest() {
        String street = null;
        String house = null;
        String apartment = null;
        String housePrefix = null;

        PPR_API_ServiceImplHelper serviceHelper = new PPR_API_ServiceImplHelper();
        String streetString = serviceHelper.createStreetString(street, house, apartment, housePrefix);

        System.assertEquals('', streetString);

        street = 'street name';
        streetString = serviceHelper.createStreetString(street, house, apartment, housePrefix);

        System.assertEquals('street name ', streetString);

        house = 'house number';
        streetString = serviceHelper.createStreetString(street, house, apartment, housePrefix);

        System.assertEquals('street name house number', streetString);

        housePrefix = 'housePrefix';
        streetString = serviceHelper.createStreetString(street, house, apartment, housePrefix);

        System.assertEquals('street name housePrefix house number', streetString);

        apartment = 'apartment number';
        streetString = serviceHelper.createStreetString(street, house, apartment, housePrefix);

        System.assertEquals('street name housePrefix house number apartment number', streetString);
    }

    @isTest
    public static void saveReferencesInFormDataTest() {
        E2EFormParams formParams = null;
        E2EFormData__c formData = null;
        String formdataId = null;
        PPR_API_ResponseBody response = null;
        PPR_API_ServiceImplHelper serviceHelper = new PPR_API_ServiceImplHelper();

        PPR_API_ResponseBody responseFromMethod = serviceHelper.saveReferencesInFormData(formParams, formData, formdataId, response);

        /** Error check */
        System.assertEquals('FormData updation error', responseFromMethod.message);

        formData = E2EFormRuTestUtils.createDefaultFormData();
        insert formData;
        formData.E2E_Contact_Email__c = 'invalid_email';
        response = ResponseBodyBuilder.constructPPR_API_ResponseBodyError('Error');

        responseFromMethod = serviceHelper.saveReferencesInFormData(formParams, formData, formdataId, response);

        System.assertEquals('Error', responseFromMethod.message);

        /** Logic check  */
        formdataId = formData.Id;
        formData = null;

        responseFromMethod = serviceHelper.saveReferencesInFormData(formParams, formData, formdataId, response);

        System.assertEquals('Error', responseFromMethod.message);

        formParams =  new E2EFormParams();

        responseFromMethod = serviceHelper.saveReferencesInFormData(formParams, formData, formdataId, response);

        System.assertEquals('Error', responseFromMethod.message);

        Account acc = E2EFormRuTestUtils.createDefaultAccount();
        insert acc;
        Opportunity opp = E2EFormRuTestUtils.createOpportunity(acc.Id);
        insert opp;

        formParams.accountId = acc.Id;
        formParams.opportunityId = opp.Id;

        responseFromMethod = serviceHelper.saveReferencesInFormData(formParams, formData, formdataId, response);

        E2EFormData__c updatedRecord = [SELECT E2E_Account_Id__c, E2E_Opportunity_Id__c FROM E2EFormData__c WHERE Id =: formdataId];

        System.assertEquals('Error', responseFromMethod.message);
        System.assertEquals(acc.Id, updatedRecord.E2E_Account_Id__c);
        System.assertEquals(opp.Id, updatedRecord.E2E_Opportunity_Id__c);
    }

    @IsTest
    public static void processAddressTest() {
        E2EFormData__c formData = E2EFormRuTestUtils.createDefaultFormData();
        E2EFormParams formParams = E2EFormRuTestUtils.createDefaultFormParams();
        formParams.legalAddressSpark = 'legal';
        PPR_API_CreateClientTestDataBuilder builder = new PPR_API_CreateClientTestDataBuilder();
        builder.baseRequest(null, null, null);

        PPR_API_ServiceImplHelper helper = new PPR_API_ServiceImplHelper();
        helper.processAddresses(builder.build().customerInfo.addresses, formParams, formData);
        System.assertEquals(formParams.legalAddressSpark, formData.E2E_Legal_Address__c);
        System.assertEquals(formParams.legalAddressSpark, formData.E2E_Post_Address__c);
        System.assertEquals(formParams.legalAddressSpark, formParams.companyLegalAddress);
        System.assertEquals(formParams.legalAddressSpark, formParams.postalAddress);

        builder.appendAddress(new List<String>{'Billing'});
        helper.processAddresses(builder.build().customerInfo.addresses, formParams, formData);
        System.assertEquals('Первомайское', formData.E2E_Billing_City__c);
        System.assertEquals('Первомайское', formData.E2E_Shipping_City__c);

        builder.appendAddress(new List<String>{'Shipping'});
        helper.processAddresses(builder.build().customerInfo.addresses, formParams, formData);
        System.assertEquals('Первомайское', formData.E2E_Billing_City__c);
        System.assertEquals('6', formData.E2E_Shipping_House__c);

        builder.clean().baseRequest(null, null, null).appendAddress(new List<String>{'Shipping'});
        helper.processAddresses(builder.build().customerInfo.addresses, formParams, formData);
        System.assertEquals(formParams.legalAddressSpark, formData.E2E_Legal_Address__c);
        System.assertEquals('6', formData.E2E_Shipping_House__c);
    }

    @IsTest
    public static void processAddressTest2() {
        Account account = E2EFormRuTestUtils.createDefaultAccount();
        E2EFormParams formParams = E2EFormRuTestUtils.createDefaultFormParams();
        formParams.legalAddressSpark = 'legal';
        PPR_API_CreateClientTestDataBuilder builder = new PPR_API_CreateClientTestDataBuilder();
        builder.baseRequest(null, null, null);

        PPR_API_ServiceImplHelper helper = new PPR_API_ServiceImplHelper();
        helper.processAddresses(builder.build().customerInfo.addresses, formParams, account);
        System.assertEquals(formParams.citySpark, account.BillingCity);
        System.assertEquals(formParams.citySpark, account.ShippingCity);

        account.BillingCountry = null;
        account.ShippingCountry = null;
        builder.appendAddress(new List<String>{'Billing'});
        helper.processAddresses(builder.build().customerInfo.addresses, formParams, account);
        System.assertEquals('Первомайское', account.BillingCity);
        System.assertEquals('Первомайское', account.ShippingCity);

        account.BillingCountry = null;
        account.ShippingCountry = null;
        builder.appendAddress(new List<String>{'Shipping'});
        helper.processAddresses(builder.build().customerInfo.addresses, formParams, account);
        System.assertEquals('Первомайское', account.BillingCity);
        System.assertEquals('659607', account.ShippingPostalCode);

        account.BillingCountry = null;
        account.ShippingCountry = null;
        builder.clean().baseRequest(null, null, null).appendAddress(new List<String>{'Shipping'});
        helper.processAddresses(builder.build().customerInfo.addresses, formParams, account);
        System.assertEquals(formParams.citySpark, account.BillingCity);
        System.assertEquals('Первомайское', account.ShippingCity);
    }
}