default/objects/Case/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <businessProcess>Support</businessProcess>
    <description>the record type for cases handling by Shell Service Agents</description>
    <label>Support</label>
</RecordType>

default/objects/Case/recordTypes/Support_CCS.recordType-meta.xml
<RecordType>
    <fullName>Support_CCS</fullName>
    <active>true</active>
    <businessProcess>Support</businessProcess>
    <description>the record type for cases handling by CCS managers</description>
    <label>Support CCS</label>
</RecordType>

default/objects/Case_management_settings__c/Case_management_settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings for Case management</description>
    <label>Case management settings</label>
</CustomObject>

default/objects/Case_management_settings__c/fields/Case_expired_days__c.field-meta.xml
<CustomField>
    <fullName>Case_expired_days__c</fullName>
    <description>The number of days after which the case becomes Closed from Resolved</description>
    <inlineHelpText>The number of days after which the case becomes Closed from Resolved</inlineHelpText>
    <label>Case expired days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/classes/BatchCloseResolvedCases.cls
public class BatchCloseResolvedCases implements Database.Batchable<SObject>{

    private final String STATUS_CLOSED;
    private final String STATUS_RESOLVED;
    private final String RECORD_TYPE;
    private final String RECORD_TYPE_CCS;
    private final Date CASE_EXPIRED_DATE;
    private final String QUERY;

    public BatchCloseResolvedCases() {
        try {
            STATUS_CLOSED = GlobalUtils.getSupportCaseStatus(GlobalUtils.SupportCaseStatus.closed);
            STATUS_RESOLVED = GlobalUtils.getSupportCaseStatus(GlobalUtils.SupportCaseStatus.resolved);
            RECORD_TYPE = GlobalUtils.CaseRecordTypes.Support.name();
            RECORD_TYPE_CCS = GlobalUtils.CaseRecordTypes.Support_CCS.name();
            if (Test.isRunningTest()) {
                CASE_EXPIRED_DATE = Date.today();
            } else {
                CASE_EXPIRED_DATE = Date.today() - Case_management_settings__c.getInstance('SettingsEU').Case_expired_days__c.intValue();
            }
            QUERY = 'SELECT Status ' +
                    'FROM Case ' +
                    'WHERE (RecordType.DeveloperName = :RECORD_TYPE OR RecordType.DeveloperName = :RECORD_TYPE_CCS) ' +
                    'AND Status = :STATUS_RESOLVED ' +
                    'AND DAY_ONLY(ClosedDate) <= :CASE_EXPIRED_DATE';
        } catch (Exception e) {
            ExceptionLogger.sendException(e.getMessage(), e.getStackTraceString());
        }
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator(QUERY);
    }

    public void execute(Database.BatchableContext context, List<Case> resolvedCases) {
        try {
            if ( !resolvedCases.isEmpty()) {
                for (Case resolvedCase : resolvedCases) {
                    resolvedCase.Status = STATUS_CLOSED;
                }
                //update cases with partial success
                String errors = '';
                for (Database.SaveResult saveResult : Database.update(resolvedCases, false)) {
                    if ( !saveResult.isSuccess()) {
                        errors += String.valueOf(saveResult.getErrors()) + '\n';
                    }
                }
                if ( !String.isEmpty(errors)) ExceptionLogger.sendException(errors, 'in method BatchCloseResolvedCases.execute()\n');
            }
        } catch (Exception e) {
            ExceptionLogger.sendException(e.getMessage(), e.getStackTraceString());
        }
    }

    public void finish(Database.BatchableContext context) {}
}