default/objects/Opportunity/fields/Additional_Fueling_Methods__c.field-meta.xml
<CustomField>
    <fullName>Additional_Fueling_Methods__c</fullName>
    <label>Additional Fueling Methods</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other Issuer Card</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Bank Card</fullName>
            </value>
            <value>
                <fullName>Universal Fleet Card</fullName>
            </value>
            <value>
                <fullName>House Account</fullName>
            </value>
            <value>
                <fullName>Oil Company Card</fullName>
            </value>
            <value>
                <fullName>On-Site Tanks</fullName>
            </value>
            <value>
                <fullName>Wet Hosing</fullName>
            </value>
            <value>
                <fullName>Leasing Company Card</fullName>
            </value>
            <value>
                <fullName>Unattended Commercial Fueling</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Area_Traveled__c.field-meta.xml
<CustomField>
    <fullName>Area_Traveled__c</fullName>
    <description>Where does your fleet travel?</description>
    <inlineHelpText>Where does your fleet travel?</inlineHelpText>
    <label>Geography of trips</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Statewide</fullName>
            </value>
            <value>
                <fullName>Regional</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Fleet_Type__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Type__c</fullName>
    <label>Fleet Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Легковой</fullName>
            </value>
            <value>
                <fullName>Грузовой</fullName>
            </value>
            <value>
                <fullName>Автобус</fullName>
            </value>
            <value>
                <fullName>Газель - микроавтобус</fullName>
            </value>
            <value>
                <fullName>Спецтехника</fullName>
            </value>
            <value>
                <fullName>Другое - указать в Описании</fullName>
            </value>
            <value>
                <fullName>Cars and vans up to 3.5 t</fullName>
            </value>
            <value>
                <fullName>Vans and trucks up to 12 t</fullName>
            </value>
            <value>
                <fullName>Trucks over 12 t</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Heathcare</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Machinery</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Not For Profit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Recreation</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Vehicles__c</fullName>
    <description>Number of vehicles</description>
    <inlineHelpText>Number of vehicles</inlineHelpText>
    <label>Number of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/PPR_EDM_No__c.field-meta.xml
<CustomField>
    <fullName>PPR_EDM_No__c</fullName>
    <label>PPR EDM No</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Не использует ЭДО</fullName>
            </value>
            <value>
                <fullName>Не подходит наш оператор</fullName>
            </value>
            <value>
                <fullName>Не готов сейчас подключать</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/PPR_Electronic_document_management__c.field-meta.xml
<CustomField>
    <fullName>PPR_Electronic_document_management__c</fullName>
    <label>PPR Electronic document management</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>diadoc</fullName>
                <label>Контур Диадок</label>
            </value>
            <value>
                <fullName>sbis</fullName>
                <label>Тензор СБИС</label>
            </value>
            <value>
                <fullName>not_using</fullName>
                <label>Не Использует ЭДО</label>
            </value>
            <value>
                <fullName>not_suitable</fullName>
                <label>Не подходит наш оператор</label>
            </value>
            <value>
                <fullName>not_ready</fullName>
                <label>Не готов сейчас подключать</label>
            </value>
            <value>
                <fullName>ДА</fullName>
                <isActive>false</isActive>
                <label>ДА</label>
            </value>
            <value>
                <fullName>НЕТ</fullName>
                <isActive>false</isActive>
                <label>НЕТ</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Primary_Fueling_Method__c.field-meta.xml
<CustomField>
    <fullName>Primary_Fueling_Method__c</fullName>
    <description>Primary Fueling Method</description>
    <inlineHelpText>Primary Fueling Method</inlineHelpText>
    <label>Primary Fueling Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other Issuer Card</fullName>
            </value>
            <value>
                <fullName>Bank Card</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Coupons</fullName>
            </value>
            <value>
                <fullName>House Account</fullName>
            </value>
            <value>
                <fullName>Leasing Company Card</fullName>
            </value>
            <value>
                <fullName>On-Site Tanks</fullName>
            </value>
            <value>
                <fullName>Universal Fleet Card</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Primary_Fueling_Method_specific__c.field-meta.xml
<CustomField>
    <fullName>Primary_Fueling_Method_specific__c</fullName>
    <description>The specific payment method drivers use to purchase fuel.</description>
    <inlineHelpText>The specific payment method drivers use to purchase fuel.</inlineHelpText>
    <label>Primary Fueling Method (specific)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Fueling_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Licard</fullName>
            </value>
            <value>
                <fullName>Rosneft</fullName>
            </value>
            <value>
                <fullName>Gazpromneft'</fullName>
            </value>
            <value>
                <fullName>Shell</fullName>
            </value>
            <value>
                <fullName>Tatneft</fullName>
            </value>
            <value>
                <fullName>Inforkom</fullName>
            </value>
            <value>
                <fullName>EKA-Processing</fullName>
            </value>
            <value>
                <fullName>Surgutneftegas</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Expense reimbursement</fullName>
            </value>
            <value>
                <fullName>Petty cash</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Projected_Liters_weekly__c.field-meta.xml
<CustomField>
    <fullName>Projected_Liters_weekly__c</fullName>
    <description>FORMULA FIELD:  Number of liters projected to be fueled per week for this prospect.  Calculated as the number of vehicles times the estimated liters per vehicle per week.
Russia uses liters projected per monthly.</description>
    <inlineHelpText>should not be equal to '0'</inlineHelpText>
    <label>Projected Liters (weekly)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/The_region__c.field-meta.xml
<CustomField>
    <fullName>The_region__c</fullName>
    <label>The region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Area_Traveled__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>г. Санкт-Петербург</fullName>
            </value>
            <value>
                <fullName>г. Москва</fullName>
            </value>
            <value>
                <fullName>Республика Адыгея</fullName>
            </value>
            <value>
                <fullName>Республика Башкортостан</fullName>
            </value>
            <value>
                <fullName>Республика Бурятия</fullName>
            </value>
            <value>
                <fullName>Республика Алтай</fullName>
            </value>
            <value>
                <fullName>Республика Дагестан</fullName>
            </value>
            <value>
                <fullName>Республика Ингушетия</fullName>
            </value>
            <value>
                <fullName>Кабардино-Балкарская Республика</fullName>
            </value>
            <value>
                <fullName>Республика Калмыкия</fullName>
            </value>
            <value>
                <fullName>Республика Карачаево-Черкесия</fullName>
            </value>
            <value>
                <fullName>Республика Карелия</fullName>
            </value>
            <value>
                <fullName>Республика Коми</fullName>
            </value>
            <value>
                <fullName>Республика Марий Эл</fullName>
            </value>
            <value>
                <fullName>Республика Мордовия</fullName>
            </value>
            <value>
                <fullName>Республика Саха (Якутия)</fullName>
            </value>
            <value>
                <fullName>Республика Северная Осетия-Алания</fullName>
            </value>
            <value>
                <fullName>Республика Татарстан</fullName>
            </value>
            <value>
                <fullName>Республика Тыва</fullName>
            </value>
            <value>
                <fullName>Удмуртская Республика</fullName>
            </value>
            <value>
                <fullName>Республика Хакасия</fullName>
            </value>
            <value>
                <fullName>Чеченская республика</fullName>
            </value>
            <value>
                <fullName>Чувашская Республика</fullName>
            </value>
            <value>
                <fullName>Алтайский край</fullName>
            </value>
            <value>
                <fullName>Краснодарский край</fullName>
            </value>
            <value>
                <fullName>Красноярский край</fullName>
            </value>
            <value>
                <fullName>Приморский край</fullName>
            </value>
            <value>
                <fullName>Ставропольский край</fullName>
            </value>
            <value>
                <fullName>Хабаровский край</fullName>
            </value>
            <value>
                <fullName>Амурская область</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/OpportunityCheckFieldsCtrl.cls
public with sharing class OpportunityCheckFieldsCtrl {
    public Opportunity currentOpportunity { get; set; }
    public String opportunityId;
    public String opportunityPageTitle { get; private set; }
    public List<Opportunity> listOpportunities { get; set; }
    public String base64Value { get; set; }
    public Boolean isOpportunitySaved { get; set; }

    public OpportunityCheckFieldsCtrl(ApexPages.StandardController controller) {
        this.currentOpportunity = new Opportunity();
        this.listOpportunities = new List<Opportunity>();
        this.isOpportunitySaved = true;
    }

    /***************************************************************************************************
	*  Name            : init()
	*  Summary         : initializes Visualforce page for the controller
	*  CreatedDate     : 16/01/2018
	*  Parameters      : -
	*  Returns         : void
	****************************************************************************************************/
    public void init() {
        this.opportunityPageTitle = 'Проверка заполнености полей перед стартом';
        this.opportunityId = ApexPages.CurrentPage().getParameters().get('Id');
        this.listOpportunities = [
                SELECT Id, Name, StageName, Account.Name, Industry__c, Primary_Fueling_Method__c, Primary_Fueling_Method_specific__c,
                        Additional_Fueling_Methods__c, Fleet_Type__c, Number_of_Vehicles__c, Projected_Liters_weekly__c,
                        Area_Traveled__c, The_region__c, Description, PPR_Electronic_document_management__c,
                        PPR_EDM_No__c, PPR_Operator__c, Traffic_tickets_monitoring_service__c, Paid_personal_manager__c,
                        UPD__c, Extra_terms__c, High_season__c, High_season_months__c, Product_PPR__c,
                        General_Projected_Liters_w__c, Percentage_of_General_projected_liters__c, INN_Opp__c
                FROM Opportunity
                WHERE Id = :this.opportunityId
        ];
        if (this.opportunityId != null && !(this.listOpportunities.isEmpty())) {
            this.currentOpportunity = listOpportunities.get(0);
            if (currentOpportunity.Industry__c != null && 
                currentOpportunity.Fleet_Type__c != null && 
                currentOpportunity.Number_of_Vehicles__c != null && 
                currentOpportunity.Area_Traveled__c != null && 
                currentOpportunity.The_region__c != null && 
                currentOpportunity.Projected_Liters_weekly__c != null && 
                currentOpportunity.General_Projected_Liters_w__c != null && 
                currentOpportunity.Primary_Fueling_Method__c != null && 
                currentOpportunity.Primary_Fueling_Method_specific__c != null && 
                ((currentOpportunity.PPR_Electronic_document_management__c == 'НЕТ' && currentOpportunity.PPR_EDM_No__c != null) ||
                (currentOpportunity.PPR_Electronic_document_management__c == 'ДА' && currentOpportunity.PPR_Operator__c != null)) &&
                currentOpportunity.Traffic_tickets_monitoring_service__c != null && 
                currentOpportunity.UPD__c != null && 
                ((currentOpportunity.High_season__c == 'ДА' && currentOpportunity.High_season_months__c != null) ||
                currentOpportunity.High_season__c == 'НЕТ') &&
                currentOpportunity.Product_PPR__c != null) {
                this.isOpportunitySaved = false;
            }
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, 'Некорректный Opportunity ID! Обратитесь к Администратору!'));
        }
    }

    /***************************************************************************************************
	*  Name            : save()
	*  Summary         : checks and saves Opportunity record if all required fields are filled in with data
	*  CreatedDate     : 16/01/2018
	*  Parameters      : -
	*  Returns         : PageReference
	*****************************************************************************************************/
    public PageReference save() {
        try {
            update currentOpportunity;
            this.isOpportunitySaved = false;
            Blob beforeBlob = constructBlob();
            base64value = EncodingUtil.base64Encode(beforeBlob);
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Пожалуйста, обратитесь к администратору!\n' + e.getMessage()));
        }
        return null;
    }

    /***************************************************************************************************
	*  Name            : back()
	*  Summary         : redirects to an Opportunity main page
	*  CreatedDate     : 16/01/2018
	*  Parameters      : -
	*  Returns         : PageReference
	*****************************************************************************************************/
    public PageReference back() {
        this.opportunityId = ApexPages.CurrentPage().getParameters().get('Id');
        return new PageReference('/' + this.opportunityId);
    }

    /***************************************************************************************************
	*  Name            : constructBlob()
	*  Summary         : constructs Blob in the form of a HTML table
	*  CreatedDate     : 21/03/2018
	*  Parameters      : -
	*  Returns         : Blob
	*****************************************************************************************************/
    private Blob constructBlob() {
        String header = '<html><head><meta charset=\"utf-8\"></head><body> \n' +
                '<table class="table"> <thead> <tr>' +
                '<th>Имя организации</th> ' +
                '<th>ИНН</th> ' +
                '<th>ID возможности</th> ' +
                '<th>Вид деятельности</th> ' +
                '<th>Тип автопарка</th> ' +
                '<th>Кол-во автотранспорта</th> ' +
                '<th>География поездок</th>' +
                '<th>География поездок (детали)</th> ' +
                '<th>Прогнозные литры в месяц</th> ' +
                '<th>Общая прокачка</th> ' +
                '<th>Процент от общей прокачки</th>' +
                '<th>Способ приобретения топлива</th> ' +
                '<th>Способ приобретения топлива (детали)</th> ' +
                '<th>Дополнительные способы заправки</th>' +
                '<th>ЭДО</th> ' +
                '<th>ЭДО - НЕТ</th> ' +
                '<th>Оператор ЭДО</th> ' +
                '<th>Платный персональный менеджер</th>' +
                '<th>Услуга мониторинга штрафов</th> ' +
                '<th>УПД</th> ' +
                '<th>Высокий сезон</th> ' +
                '<th>Высокий сезон: выбор</th> ' +
                '<th>Дополнительные договоренности с клиентом</th> ' +
                '<th>Продукт</th> ' +
                '</tr> </thead>';
        String finalString = header;
        finalString += '<tbody> <tr> ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).Account.Name) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).INN_Opp__c) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).Id) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(GlobalUtils.getPicklistValueTranslation(Opportunity.Industry__c.getDescribe(), listOpportunities.get(0).Industry__c)) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).Fleet_Type__c) + '</td> ' +
                '<td>' + GlobalUtils.blankDecimalIfNull(listOpportunities.get(0).Number_of_Vehicles__c) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(GlobalUtils.getPicklistValueTranslation(Opportunity.Area_Traveled__c.getDescribe(), listOpportunities.get(0).Area_Traveled__c)) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).The_region__c) + '</td> ' +
                '<td>' + GlobalUtils.blankDecimalIfNull(listOpportunities.get(0).Projected_Liters_weekly__c) + '</td>' +
                '<td>' + GlobalUtils.blankDecimalIfNull(listOpportunities.get(0).General_Projected_Liters_w__c) + '</td> ' +
                '<td>' + GlobalUtils.blankDecimalIfNull(listOpportunities.get(0).Percentage_of_General_projected_liters__c) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(GlobalUtils.getPicklistValueTranslation(Opportunity.Primary_Fueling_Method__c.getDescribe(), listOpportunities.get(0).Primary_Fueling_Method__c)) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(GlobalUtils.getPicklistValueTranslation(Opportunity.Primary_Fueling_Method_specific__c.getDescribe(), listOpportunities.get(0).Primary_Fueling_Method_specific__c)) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(GlobalUtils.getPicklistValueTranslation(Opportunity.Additional_Fueling_Methods__c.getDescribe(), listOpportunities.get(0).Additional_Fueling_Methods__c)) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).PPR_Electronic_document_management__c) + '</td>  ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).PPR_EDM_No__c) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).PPR_Operator__c) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).Paid_personal_manager__c + '</td> ') +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).Traffic_tickets_monitoring_service__c) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).UPD__c) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).High_season__c) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).High_season_months__c) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).Extra_terms__c) + '</td> ' +
                '<td>' + GlobalUtils.blankStringIfNull(listOpportunities.get(0).Product_PPR__c) + '</td> ' +
                '</tr> </tbody> </table>';
        finalString += '</body></html>';
        return Blob.valueOf(finalString);
    }
}