default/objects/Opportunity/fields/Angebotsdauer__c.field-meta.xml
<CustomField>
    <fullName>Angebotsdauer__c</fullName>
    <label>Angebotsdauer</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3 Monate</fullName>
            </value>
            <value>
                <fullName>4 Monate</fullName>
            </value>
            <value>
                <fullName>5 Monate</fullName>
            </value>
            <value>
                <fullName>6 Monate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Anzahl_der_Karten__c.field-meta.xml
<CustomField>
    <fullName>Anzahl_der_Karten__c</fullName>
    <label>Anzahl der Karten*</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Credit_check_date__c.field-meta.xml
<CustomField>
    <fullName>Credit_check_date__c</fullName>
    <label>Credit check date</label>
    <type>Date</type>
</CustomField>

default/objects/Opportunity/fields/Derzeitige_Zahlungsmethode__c.field-meta.xml
<CustomField>
    <fullName>Derzeitige_Zahlungsmethode__c</fullName>
    <label>Derzeitige Zahlungsmethode *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bankkarte</fullName>
            </value>
            <value>
                <fullName>Barzahlung</fullName>
            </value>
            <value>
                <fullName>Kreditkarte</fullName>
            </value>
            <value>
                <fullName>Stationskarte</fullName>
            </value>
            <value>
                <fullName>Tankkarte</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Disable_for_KPI__c.field-meta.xml
<CustomField>
    <fullName>Disable_for_KPI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable for KPI</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Opportunity/fields/Kraftstoffverbrauch_Liter_Monat__c.field-meta.xml
<CustomField>
    <fullName>Kraftstoffverbrauch_Liter_Monat__c</fullName>
    <label>Kraftstoffverbrauch Liter/Monat *</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Opportunity/fields/Kundensegment__c.field-meta.xml
<CustomField>
    <fullName>Kundensegment__c</fullName>
    <label>Kundensegment *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Campaign_1</fullName>
            </value>
            <value>
                <fullName>Segment 10+</fullName>
            </value>
            <value>
                <fullName>Segment 1-3</fullName>
            </value>
            <value>
                <fullName>Segment 4-10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product *</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BE-FR 2,5 Cent</fullName>
            </value>
            <value>
                <fullName>Carnet OBD</fullName>
            </value>
            <value>
                <fullName>Carnet Standard 2019</fullName>
            </value>
            <value>
                <fullName>Fuel Vehicle</fullName>
            </value>
            <value>
                <fullName>HOME 1</fullName>
            </value>
            <value>
                <fullName>Home Station offer (v.1)</fullName>
            </value>
            <value>
                <fullName>Inbound Typ B</fullName>
            </value>
            <value>
                <fullName>Inbound Typ C</fullName>
            </value>
            <value>
                <fullName>LOCAL - RED</fullName>
            </value>
            <value>
                <fullName>LOCAL - YELLOW</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes No fee</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes Standard</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>Sales no fee promo Feb 2016</fullName>
            </value>
            <value>
                <fullName>Shell Basic 2020</fullName>
            </value>
            <value>
                <fullName>Shell No fee 2020</fullName>
            </value>
            <value>
                <fullName>Shell Outbound 2020</fullName>
            </value>
            <value>
                <fullName>Shell Universal Card</fullName>
            </value>
            <value>
                <fullName>Smart</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + % fee)</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + fixed fee)</fullName>
            </value>
            <value>
                <fullName>Sonderangebot (s. Notizen)</fullName>
            </value>
            <value>
                <fullName>Swiss Pro</fullName>
            </value>
            <value>
                <fullName>Swiss Pro 5</fullName>
            </value>
            <value>
                <fullName>Swiss Star</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Zahlungsart__c.field-meta.xml
<CustomField>
    <fullName>Zahlungsart__c</fullName>
    <label>Zahlungsart *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lastschrift</fullName>
            </value>
            <value>
                <fullName>Banküberweisung</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Zahlungsziel__c.field-meta.xml
<CustomField>
    <fullName>Zahlungsziel__c</fullName>
    <label>Zahlungsziel *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>30</fullName>
                <default>true</default>
                <label>30</label>
            </value>
            <value>
                <fullName>keines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/ReopenOppByCreditCtrlTest.cls
@isTest
private class ReopenOppByCreditCtrlTest {
    public Static User u;
	public Static Opportunity newOpp;
	public Static Opportunity newOpp2;
	public Static EmailTemplate emailTemplateReject;
	public Static EmailTemplate emailTemplateApprove;

	@isTest
    static void testApproveReopen() {
        Test.startTest();
			createUser();
		Test.stopTest();

		System.runAs(u) {
			createOpps();
			createEmailTemplate();
					
			ReopenOppByCreditCtrl controller = new ReopenOppByCreditCtrl();
			ApexPages.currentPage().getParameters().put('Id', newOpp.Id);
			Approval.lock(newOpp.Id);
			controller.init();
			controller.approveReopen();

			List<Opportunity> oppList = [SELECT StageName FROM Opportunity WHERE Id = :newOpp.Id];
			System.assertEquals('Prospecting', oppList.get(0).StageName);
		}
    }


    @isTest
    static void testRejectReopen() {
        Test.startTest();
			createUser();
		Test.stopTest();

		System.runAs(u) {
			createOpps();
			createEmailTemplate();
					
			ReopenOppByCreditCtrl controller = new ReopenOppByCreditCtrl();
			ApexPages.currentPage().getParameters().put('Id', newOpp.Id);
			controller.init();
			controller.rejectReopen();

			List<Opportunity> oppList = [SELECT StageName FROM Opportunity WHERE Id = :newOpp.Id];
			System.assertEquals('Closed Lost', oppList.get(0).StageName);
		}
    }


    @isTest
    static void testValidateFirstException() {
        Test.startTest();
			createUser();
		Test.stopTest();

		System.runAs(u) {
			try {
				createOpps();
				createEmailTemplate();
					
				ReopenOppByCreditCtrl controller = new ReopenOppByCreditCtrl();
				ApexPages.currentPage().getParameters().put('Id', newOpp.Id);
				Approval.lock(newOpp.Id);
				controller.init();
				controller.approveReopen();
				controller.backToOpportunity();
            } catch (Exception e) {
                Boolean expectedExceptionThrown =  e.getMessage().contains('There was no request for reopen.') ? true : false;
                System.AssertEquals(true, expectedExceptionThrown);
            } 
		}
    }


    @isTest
    static void testValidateSecondException() {
        Test.startTest();
			createUser();
		Test.stopTest();

		System.runAs(u) {
			try {
				createOpps();
				createEmailTemplate();
					
				ReopenOppByCreditCtrl controller = new ReopenOppByCreditCtrl();
				ApexPages.currentPage().getParameters().put('Id', newOpp2.Id);
				Approval.lock(newOpp2.Id);
				controller.init();
				controller.approveReopen();
            } catch (Exception e) {
                Boolean expectedExceptionThrown =  e.getMessage().contains('This action is available for Closed Lost and CreditCheck rejected Opportunity Stage only.') ? true : false;
                System.AssertEquals(true, expectedExceptionThrown);
            } 
		}
    }

    @future
	private static void createUser() {
		Profile p = [SELECT Id FROM Profile WHERE Name = 'API Only'];
		
		u = new User(
			ProfileId = p.Id,
			isActive = TRUE,
			Username = System.now().millisecond() + '_233121_test2@test.com',
		   	Alias = 'kam',
			Email = 'manager.test@test.com',
			EmailEncodingKey = 'UTF-8',
			Firstname = 'test',
			Lastname = 'test',
			LanguageLocaleKey = 'en_US',
			LocaleSidKey = 'en_US',
			TimeZoneSidKey = 'America/Chicago');

		Database.insert(u);	   
	}

	private static void createOpps() {
		List<Opportunity> opportunitiesToInsertList = new List<Opportunity>();
		newOpp = new Opportunity(
			Kraftstoffverbrauch_Liter_Monat__c = 2,
			Anzahl_der_Karten__c = 5,
			Derzeitige_Zahlungsmethode__c = 'Bank',
			Kundensegment__c = 'Campaign_1',
			Zahlungsart__c = 'Lastschrift',
			Zahlungsziel__c = '7',
			Angebotsdauer__c = 'test',
			StageName = 'Closed Lost',
			Credit_check_date__c = Date.today().addDays(-30),
			Name = 'test opp',
			Product__c = 'None',
			Disable_for_KPI__c = FALSE,
			Last_Owner_Change_Date__c = Date.newinstance(2017, 12, 21),
			CloseDate = Date.newinstance(2017, 12, 28)
		);
		opportunitiesToInsertList.add(newOpp);

		newOpp2 = new Opportunity(
			Kraftstoffverbrauch_Liter_Monat__c = 2,
			Anzahl_der_Karten__c = 5,
			Derzeitige_Zahlungsmethode__c = 'Bank',
			Kundensegment__c = 'Campaign_1',
			Zahlungsart__c = 'Lastschrift',
			Zahlungsziel__c = '7',
			Angebotsdauer__c = 'test',
			StageName = 'Prospecting',
			Name = 'test opp',
			Product__c = 'None',
			Disable_for_KPI__c = FALSE,
			Last_Owner_Change_Date__c = Date.newinstance(2017, 12, 21),
			CloseDate = Date.newinstance(2017, 12, 28)
		);
		opportunitiesToInsertList.add(newOpp2);

		insert opportunitiesToInsertList;
	}

	private static void createEmailTemplate() {
		List<EmailTemplate> emailtemplatesToInsert = new List<EmailTemplate>();
		emailTemplateReject = new EmailTemplate(
			Name = 'test name',
			Subject = 'Reject Reopen',
			Body = 'test',
			TemplateType = 'Text',
			FolderId = u.Id,
			DeveloperName = 'Reject_reopen'
		);
		emailtemplatesToInsert.add(emailTemplateReject);

		emailTemplateApprove = new EmailTemplate(
			Name = 'test name',
			Subject = 'Approve Reopen',
			Body = 'test',
			TemplateType = 'Text',
			FolderId = u.Id,
			DeveloperName = 'Approve_reopen'
		);
		emailtemplatesToInsert.add(emailTemplateApprove);

		insert emailtemplatesToInsert;
	}
}