default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product *</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BE-FR 2,5 Cent</fullName>
            </value>
            <value>
                <fullName>Carnet OBD</fullName>
            </value>
            <value>
                <fullName>Carnet Standard 2019</fullName>
            </value>
            <value>
                <fullName>Fuel Vehicle</fullName>
            </value>
            <value>
                <fullName>HOME 1</fullName>
            </value>
            <value>
                <fullName>Home Station offer (v.1)</fullName>
            </value>
            <value>
                <fullName>Inbound Typ B</fullName>
            </value>
            <value>
                <fullName>Inbound Typ C</fullName>
            </value>
            <value>
                <fullName>LOCAL - RED</fullName>
            </value>
            <value>
                <fullName>LOCAL - YELLOW</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes No fee</fullName>
            </value>
            <value>
                <fullName>LOTOS Biznes Standard</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>Sales no fee promo Feb 2016</fullName>
            </value>
            <value>
                <fullName>Shell Basic 2020</fullName>
            </value>
            <value>
                <fullName>Shell No fee 2020</fullName>
            </value>
            <value>
                <fullName>Shell Outbound 2020</fullName>
            </value>
            <value>
                <fullName>Shell Universal Card</fullName>
            </value>
            <value>
                <fullName>Smart</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + % fee)</fullName>
            </value>
            <value>
                <fullName>SME (BNF 0,025 € + fixed fee)</fullName>
            </value>
            <value>
                <fullName>Sonderangebot (s. Notizen)</fullName>
            </value>
            <value>
                <fullName>Swiss Pro</fullName>
            </value>
            <value>
                <fullName>Swiss Pro 5</fullName>
            </value>
            <value>
                <fullName>Swiss Star</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Opportunity/recordTypes/Carnet.recordType-meta.xml
<RecordType>
    <fullName>Carnet</fullName>
    <active>true</active>
    <businessProcess>Carnet</businessProcess>
    <description>Record Type for Carnet records.</description>
    <label>Carnet</label>
</RecordType>

default/classes/ChooseCarnetUnitctrl.cls
public class ChooseCarnetUnitctrl {
    public Opportunity opportunity {get; set;}
    public String opportunityId;

    public PageReference init() {
        try {
            this.opportunityId = ApexPages.CurrentPage().getparameters().get('id');

            List<Opportunity> OpportunityList = [
                    SELECT Name, Product__c, Sec_Channel__c
                    FROM Opportunity
                    WHERE Id = :this.opportunityId
                    LIMIT 1
            ];

            if (!OpportunityList.isEmpty()) {
                this.opportunity = OpportunityList.get(0);
                Boolean CarnetStandard = opportunity.Product__c.contains('Carnet Standard');
                Boolean CarnetOBD = opportunity.Product__c.contains('Carnet OBD');

                if (CarnetStandard == true) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'You are about to create New <b>Carnet Standard</b> Order. Click Next or Cancel.'));
                    return null;
                }
                else if(CarnetOBD == true) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'You are about to create New <b>Carnet OBD</b> Order. Click Next or Cancel.'));
                    return null;
                }

            }
            return null;
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, e.getMessage()));
            return null;
        }
    }
    public PageReference cancel() {
        return new PageReference('/' + this.opportunity.Id);
    }

    public PageReference next() {
        Boolean CarnetStandard = opportunity.Product__c.contains('Carnet Standard');
        Boolean CarnetOBD = opportunity.Product__c.contains('Carnet OBD');
        String Apex = '';

        if (CarnetStandard == true) {
            Apex = '/apex/NewCarnetUnit?id=';
        }
        else if(CarnetOBD == true) {
            Apex = '/apex/NewCarnetOBD?id=';
        }
        return new PageReference(Apex + this.opportunity.Id);
    }

    public class MessageException extends Exception {}
}