default/objects/Credit_Factory_Calculation__c/Credit_Factory_Calculation__c.object-meta.xml
<CustomObject>
    <label>Credit Factory Calculation</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Credit Factory Calculation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Factory Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Credit_Factory_Calculation__c/fields/Class_Rating__c.field-meta.xml
<CustomField>
    <fullName>Class_Rating__c</fullName>
    <label>Class Rating</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/objects/Credit_Factory_Calculation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Credit_Factory_Calculation__c/fields/Date_of_Foundation_month__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Foundation_month__c</fullName>
    <label>Date of Foundation (month)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/objects/Credit_Factory_Calculation__c/fields/Number_of_Cards__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Cards__c</fullName>
    <label>Number of Cards</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/objects/Credit_Factory_Calculation__c/fields/Payment_Detail__c.field-meta.xml
<CustomField>
    <fullName>Payment_Detail__c</fullName>
    <label>Payment Detail</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7+7</fullName>
            </value>
            <value>
                <fullName>15+7</fullName>
            </value>
            <value>
                <fullName>15+14</fullName>
            </value>
            <value>
                <fullName>30+7</fullName>
            </value>
            <value>
                <fullName>30+14</fullName>
            </value>
            <value>
                <fullName>30+27</fullName>
            </value>
            <value>
                <fullName>*</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Credit_Factory_Calculation__c/fields/Total_Consumption_Max_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Consumption_Max_Value__c</fullName>
    <label>Total Consumption Max Value</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/objects/Credit_Factory_Calculation__c/fields/Total_Consumption_Min_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Consumption_Min_Value__c</fullName>
    <label>Total Consumption Min Value</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

default/classes/CreditFactoryCalculationCtrlTest.cls
@IsTest
private class CreditFactoryCalculationCtrlTest {

    /*******************************************************************************
    *  Summary         : create test data for all methods
    *  Created         : 29/03/2021 by Ivan Kulinkovich
    *  Parameters      : -
    *  Returns         : -
    ******************************************************************************/
    @TestSetup
    static void createDataForAllTests() {
        List<Credit_Factory_Calculation__c> calculations = CreditFactoryTestUtils.generateCreditFactoryCalculationsDE();
        insert calculations;
    }


    /*******************************************************************************
    *  Summary         : test get calculation records
    *  Created         : 29/03/2021 by Ivan Kulinkovich
    *  Parameters      : -
    *  Returns         : -
    ******************************************************************************/
    @IsTest
    static void testGetCalculations() {
        Map<String, List<Credit_Factory_Calculation__c>> calculationsMap = CreditFactoryCalculationCtrl.getCalculations();
        System.assertEquals(5, calculationsMap.get('Germany').size());
    }


    /*******************************************************************************
    *  Summary         : test upsert calculation records
    *  Created         : 29/03/2021 by Ivan Kulinkovich
    *  Parameters      : -
    *  Returns         : -
    ******************************************************************************/
    @IsTest
    static void testUpsertCalculations() {
        List<Credit_Factory_Calculation__c> calculations = [
                SELECT Id, Date_of_Foundation_month__c
                FROM Credit_Factory_Calculation__c
                ORDER BY Order__c
        ];

        calculations.get(0).Date_of_Foundation_month__c = '<=36';
        calculations.add(new Credit_Factory_Calculation__c(
                Country__c = 'Germany',
                Class_Rating__c = '2',
                Date_of_Foundation_month__c = '<=18',
                Number_of_Cards__c = '<=1',
                Total_Consumption_Min_Value__c = '0',
                Total_Consumption_Max_Value__c = '600',
                Order__c = 9,
                Payment_Detail__c = '15+7'
        ));

        Map<String, List<Credit_Factory_Calculation__c>> calculationsMap = new Map<String, List<Credit_Factory_Calculation__c>>();
        calculationsMap.put('Germany', calculations);

        CreditFactoryCalculationCtrl.upsertCalculations(calculationsMap);
        calculations = [
                SELECT Id, Date_of_Foundation_month__c
                FROM Credit_Factory_Calculation__c
                ORDER BY Order__c
        ];

        System.assertEquals(calculations.get(0).Date_of_Foundation_month__c, '<=36');
        System.assertEquals(6, calculations.size());
    }


    /*******************************************************************************
    *  Summary         : test delete calculation records
    *  Created         : 29/03/2021 by Ivan Kulinkovich
    *  Parameters      : -
    *  Returns         : -
    ******************************************************************************/
    @IsTest
    static void testDeleteCalculations() {
        List<Credit_Factory_Calculation__c> calculations = [
                SELECT Id, Date_of_Foundation_month__c
                FROM Credit_Factory_Calculation__c
                ORDER BY Order__c
        ];

        List<String> calculationsIdSet = new List<String>();
        calculationsIdSet.add(calculations.get(0).Id);
        CreditFactoryCalculationCtrl.deleteCalculations(calculationsIdSet);

        calculations = [
                SELECT Id, Date_of_Foundation_month__c
                FROM Credit_Factory_Calculation__c
                ORDER BY Order__c
        ];

        System.assertEquals(4, calculations.size());
    }
}