default/objects/Unify_CC_LogStorage__b/Unify_CC_LogStorage__b.object-meta.xml
<CustomObject>
    <label>Unify CC LogStorage</label>
    <pluralLabel>Unify CC LogStorages</pluralLabel>
</CustomObject>

default/objects/Unify_CC_LogStorage__b/fields/Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Entity_ID__c</fullName>
    <label>Entity ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Unify_CC_LogStorage__b/fields/Message__c.field-meta.xml
<CustomField>
	<fullName>Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/Unify_CC_LogStorage__b/fields/RecordDateTime__c.field-meta.xml
<CustomField>
	<fullName>RecordDateTime__c</fullName>
    <label>RecordDateTime</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/ScheduleBatchCleanupUnifyLogTest.cls
@isTest
public class ScheduleBatchCleanupUnifyLogTest {
    @isTest
    public static void test_schedule(){
        String CRON_EXP = '0 0 0 3 9 ? 2032';
      
        Test.startTest();
        String jobId = System.schedule('UnifyCCTest', CRON_EXP, new ScheduleBatchCleanupUnifyLog());
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(0, ct.TimesTriggered);
        System.assertEquals('2032-09-03 00:00:00', String.valueOf(ct.NextFireTime));   

        Test.stopTest();       
    }

    @isTest
    public static void test_delete(){
        Test.startTest();
            ScheduleBatchCleanupUnifyLog.deleteLogs();
        Test.stopTest();
        system.debug([SELECT Entity_ID__c, Message__c, RecordDateTime__c FROM Unify_CC_LogStorage__b]);

    }
}