default/objects/BR_case__c/BR_case__c.object-meta.xml
<CustomObject>
    <description>set of conditions for passing business regulations check</description>
    <label>BR case</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BR cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/BR_case__c/fields/BR_Setting__c.field-meta.xml
<CustomField>
    <fullName>BR_Setting__c</fullName>
    <description>parent setting record</description>
    <inlineHelpText>parent setting record</inlineHelpText>
    <label>BR Setting</label>
    <referenceTo>BR_Setting__c</referenceTo>
    <relationshipLabel>BR cases</relationshipLabel>
    <relationshipName>BR_cases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

default/objects/BR_case__c/fields/Filter_logic__c.field-meta.xml
<CustomField>
    <fullName>Filter_logic__c</fullName>
    <label>Filter logic</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/BR_filter__c/BR_filter__c.object-meta.xml
<CustomObject>
    <description>filter settings for business regulations check</description>
    <label>BR filter</label>
    <nameField>
        <displayFormat>BR Filter - {00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/BR_filter__c/fields/BR_case__c.field-meta.xml
<CustomField>
    <fullName>BR_case__c</fullName>
    <label>BR case</label>
    <referenceTo>BR_case__c</referenceTo>
    <relationshipLabel>BR filters</relationshipLabel>
    <relationshipName>BR_filters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

default/objects/BR_filter__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Field_type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
                <label>=</label>
            </value>
            <value>
                <fullName>not_equals</fullName>
                <label>≠</label>
            </value>
            <value>
                <fullName>less_than</fullName>
                <label>&lt;</label>
            </value>
            <value>
                <fullName>greater_than</fullName>
                <label>&gt;</label>
            </value>
            <value>
                <fullName>less_than_or_equals</fullName>
                <label>⩽</label>
            </value>
            <value>
                <fullName>greater_than_or_equals</fullName>
                <label>⩾</label>
            </value>
            <value>
                <fullName>includes</fullName>
            </value>
            <value>
                <fullName>starts_with</fullName>
                <label>starts with</label>
            </value>
            <value>
                <fullName>ends_with</fullName>
                <label>ends with</label>
            </value>
            <value>
                <fullName>interval_including_left_right</fullName>
                <label>[ ; ]</label>
            </value>
            <value>
                <fullName>interval_including_right</fullName>
                <label>( ; ]</label>
            </value>
            <value>
                <fullName>interval_including_left</fullName>
                <label>[ ; )</label>
            </value>
            <value>
                <fullName>interval</fullName>
                <label>( ; )</label>
            </value>
            <value>
                <fullName>excludes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/BR_filter__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>Filteting field</description>
    <inlineHelpText>Filteting field</inlineHelpText>
    <label>Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/BR_filter__c/fields/Field_type__c.field-meta.xml
<CustomField>
    <fullName>Field_type__c</fullName>
    <label>Field type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BOOLEAN</fullName>
                <label>Checkbox</label>
            </value>
            <value>
                <fullName>DATE</fullName>
                <label>Date</label>
            </value>
            <value>
                <fullName>DATETIME</fullName>
                <label>Date/Time</label>
            </value>
            <value>
                <fullName>TIME</fullName>
                <label>Time</label>
            </value>
            <value>
                <fullName>DOUBLE</fullName>
                <label>Number</label>
            </value>
            <value>
                <fullName>PICKLIST</fullName>
                <label>Picklist</label>
            </value>
            <value>
                <fullName>MULTIPICKLIST</fullName>
                <label>Multi picklist</label>
            </value>
            <value>
                <fullName>STRING</fullName>
                <label>Text</label>
            </value>
            <value>
                <fullName>TEXTAREA</fullName>
                <label>Text area</label>
            </value>
            <value>
                <fullName>REFERENCE</fullName>
                <label>Reference</label>
            </value>
            <value>
                <fullName>PHONE</fullName>
                <label>Phone</label>
            </value>
            <value>
                <fullName>ENCRYPTEDSTRING</fullName>
                <label>Encrypted text</label>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
            <value>
                <fullName>EMAIL</fullName>
                <label>Email</label>
            </value>
            <value>
                <fullName>ID</fullName>
                <label>Record ID</label>
            </value>
            <value>
                <fullName>PERCENT</fullName>
                <label>Percent</label>
            </value>
            <value>
                <fullName>CURRENCY</fullName>
                <label>Currency</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/BR_filter__c/fields/Field_value__c.field-meta.xml
<CustomField>
    <fullName>Field_value__c</fullName>
    <label>Field value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/BR_filter__c/fields/Filter_number__c.field-meta.xml
<CustomField>
    <fullName>Filter_number__c</fullName>
    <description>Number of the filter for filter logic in the case</description>
    <inlineHelpText>Number of the filter for filter logic in the case</inlineHelpText>
    <label>Filter Number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/BR_Setting__c/BR_Setting__c.object-meta.xml
<CustomObject>
    <description>Settings for business regulations check</description>
    <label>BR Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BR Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/BR_Setting__c/fields/Is_active__c.field-meta.xml
<CustomField>
    <fullName>Is_active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is active</label>
    <type>Checkbox</type>
</CustomField>

default/objects/BR_Setting__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>the sObject for which the settings are applied</description>
    <inlineHelpText>the sObject for which the settings are applied</inlineHelpText>
    <label>SObject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/BR_Setting__c/fields/SObject_status__c.field-meta.xml
<CustomField>
    <fullName>SObject_status__c</fullName>
    <description>the sObject status for which the settings are applied</description>
    <inlineHelpText>the sObject status for which the settings are applied</inlineHelpText>
    <label>SObject status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Moved to start</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/BRSettingsService.cls
public with sharing class BRSettingsService {
    public static final String SAVE_FAILED = 'Error. Save failed.';
    public static final String DELETE_FAILED = 'Error. Delete failed.';
    public static final String LOGGER_TYPE_NAME = 'Business regulation';

    private BRSettingsManager manager = new BRSettingsManager();
    private Logger logger = new Logger(LOGGER_TYPE_NAME);

    public void saveSetting(String settingData) {
        if (String.isEmpty(settingData)) {
            return;
        }

        BRSettingWrapper settingWrapper = (BRSettingWrapper) JSON.deserialize(settingData, BRSettingWrapper.class);
        Map<Id, BR_case__c> oldCasesMap = new Map<Id, BR_case__c>(manager.getCasesAndDependedFiltersBySettingId(settingWrapper.id));

        BR_Setting__c newSetting = new BR_Setting__c(
            Id = settingWrapper.id,
            Name = settingWrapper.name,
            Is_active__c = settingWrapper.isActive,
            SObject__c = settingWrapper.sObjectName,
            SObject_status__c = settingWrapper.sObjectStatus
        );

        Savepoint savepoint = Database.setSavepoint();

        try {
            upsert newSetting;

            if (settingWrapper.cases != null) {
                Map<Integer, BR_case__c> newCasesMap = new Map<Integer, BR_case__c>();
                Integer caseCounter = 0;
                for (BRSettingWrapper.BRCase brCase : settingWrapper.cases) {
                    BR_case__c caseRecord = new BR_case__c(
                            Id = brCase.id,
                            Name = brCase.name,
                            BR_Setting__c = newSetting.Id,
                            Filter_logic__c = brCase.filterLogic
                    );
                    brCase.caseNumber = caseCounter;
                    newCasesMap.put(brCase.caseNumber, caseRecord);
                    oldCasesMap.remove(brCase.id);
                }

                upsert newCasesMap.values();

                Map<Id, BR_filter__c> oldFiltersMap = prepareOldFiltersMap(oldCasesMap.values());
                upsertFilters(settingWrapper.cases, newCasesMap, oldFiltersMap);
            }

            delete oldCasesMap.values();
        } catch (Exception e) {
            Database.rollback(savepoint);
            processErrorLogging('saveSetting', e);
            throw new GlobalException(SAVE_FAILED);
        }
    }

    public void deleteSetting(Id settingId) {
        try {
            delete new BR_Setting__c(Id = settingId);
        } catch(Exception e) {
            processErrorLogging('deleteSetting', e);
            throw new GlobalException(DELETE_FAILED);
        }
    }

    private void upsertFilters(List<BRSettingWrapper.BRCase> caseWrappers, Map<Integer, BR_case__c> newCasesMap, Map<Id, BR_filter__c> oldFiltersMap) {
        List<BR_filter__c> newFilters = new List<BR_filter__c>();
        for (BRSettingWrapper.BRCase brCase : caseWrappers) {
            if (brCase.filters != null) {
                for (BRSettingWrapper.BRFilter filter : brCase.filters) {
                    newFilters.add(
                            new BR_filter__c(
                                    Id = filter.id,
                                    BR_case__c = newCasesMap.get(brCase.caseNumber).Id,
                                    Condition__c = filter.condition,
                                    Field__c = filter.field,
                                    Field_type__c = filter.fieldType,
                                    Field_value__c = filter.fieldValue,
                                    Filter_number__c = Decimal.valueOf(filter.filterNumber)
                            )
                    );
                    oldFiltersMap.remove(filter.id);
                }
            }
        }

        upsert newFilters;
        delete oldFiltersMap.values();
    }

    private Map<Id, BR_filter__c> prepareOldFiltersMap(List<BR_case__c> oldCases) {
        Map<Id, BR_filter__c> oldFiltersMap = new Map<Id, BR_filter__c>();
        for (BR_case__c oldCase : oldCases) {
            if (!oldCase.BR_filters__r.isEmpty()) {
                oldFiltersMap.putAll(new Map<Id, BR_filter__c>(oldCase.BR_filters__r));
            }
        }

        return oldFiltersMap;
    }

    private void processErrorLogging(String methodName, Exception e) {
        String errorMessage = 'Line number: ' + e.getLineNumber() + '. Message: ' + e.getMessage();
        System.debug(LoggingLevel.ERROR, errorMessage);
        logger.fatal('BRSettingsService.' + methodName, errorMessage);
        logger.saveLogs();
    }
}