default/objects/BR_case__c/BR_case__c.object-meta.xml
<CustomObject>
    <description>set of conditions for passing business regulations check</description>
    <label>BR case</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BR cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/BR_case__c/fields/BR_Setting__c.field-meta.xml
<CustomField>
    <fullName>BR_Setting__c</fullName>
    <description>parent setting record</description>
    <inlineHelpText>parent setting record</inlineHelpText>
    <label>BR Setting</label>
    <referenceTo>BR_Setting__c</referenceTo>
    <relationshipLabel>BR cases</relationshipLabel>
    <relationshipName>BR_cases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

default/objects/BR_filter__c/BR_filter__c.object-meta.xml
<CustomObject>
    <description>filter settings for business regulations check</description>
    <label>BR filter</label>
    <nameField>
        <displayFormat>BR Filter - {00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/BR_filter__c/fields/BR_case__c.field-meta.xml
<CustomField>
    <fullName>BR_case__c</fullName>
    <label>BR case</label>
    <referenceTo>BR_case__c</referenceTo>
    <relationshipLabel>BR filters</relationshipLabel>
    <relationshipName>BR_filters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

default/objects/BR_Setting__c/BR_Setting__c.object-meta.xml
<CustomObject>
    <description>Settings for business regulations check</description>
    <label>BR Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BR Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/BR_Setting__c/fields/Is_active__c.field-meta.xml
<CustomField>
    <fullName>Is_active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is active</label>
    <type>Checkbox</type>
</CustomField>

default/objects/BR_Setting__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>the sObject for which the settings are applied</description>
    <inlineHelpText>the sObject for which the settings are applied</inlineHelpText>
    <label>SObject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/BR_Setting__c/fields/SObject_status__c.field-meta.xml
<CustomField>
    <fullName>SObject_status__c</fullName>
    <description>the sObject status for which the settings are applied</description>
    <inlineHelpText>the sObject status for which the settings are applied</inlineHelpText>
    <label>SObject status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Moved to start</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/BRSettingsManager.cls
public with sharing class BRSettingsManager {

    public List<BR_Setting__c> getAllBRSettings() {
        return ([
                SELECT
                Id,
                Is_active__c,
                Name,
                SObject__c,
                SObject_status__c
                FROM BR_Setting__c
        ]);
    }

    public List<BR_case__c> getCasesAndDependedFiltersBySettingId(Id settingId) {
        if (settingId == null) {
            return new List<BR_case__c>();
        }
        return [
                SELECT Id, (SELECT Id FROM BR_filters__r)
                FROM BR_case__c
                WHERE BR_Setting__c = :settingId
        ];
    }
}