default/objects/BR_case__c/BR_case__c.object-meta.xml
<CustomObject>
    <description>set of conditions for passing business regulations check</description>
    <label>BR case</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BR cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/BR_case__c/fields/BR_Setting__c.field-meta.xml
<CustomField>
    <fullName>BR_Setting__c</fullName>
    <description>parent setting record</description>
    <inlineHelpText>parent setting record</inlineHelpText>
    <label>BR Setting</label>
    <referenceTo>BR_Setting__c</referenceTo>
    <relationshipLabel>BR cases</relationshipLabel>
    <relationshipName>BR_cases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

default/objects/BR_case__c/fields/Filter_logic__c.field-meta.xml
<CustomField>
    <fullName>Filter_logic__c</fullName>
    <label>Filter logic</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/BR_filter__c/BR_filter__c.object-meta.xml
<CustomObject>
    <description>filter settings for business regulations check</description>
    <label>BR filter</label>
    <nameField>
        <displayFormat>BR Filter - {00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/BR_filter__c/fields/BR_case__c.field-meta.xml
<CustomField>
    <fullName>BR_case__c</fullName>
    <label>BR case</label>
    <referenceTo>BR_case__c</referenceTo>
    <relationshipLabel>BR filters</relationshipLabel>
    <relationshipName>BR_filters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

default/objects/BR_filter__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Field_type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
                <label>=</label>
            </value>
            <value>
                <fullName>not_equals</fullName>
                <label>≠</label>
            </value>
            <value>
                <fullName>less_than</fullName>
                <label>&lt;</label>
            </value>
            <value>
                <fullName>greater_than</fullName>
                <label>&gt;</label>
            </value>
            <value>
                <fullName>less_than_or_equals</fullName>
                <label>⩽</label>
            </value>
            <value>
                <fullName>greater_than_or_equals</fullName>
                <label>⩾</label>
            </value>
            <value>
                <fullName>includes</fullName>
            </value>
            <value>
                <fullName>starts_with</fullName>
                <label>starts with</label>
            </value>
            <value>
                <fullName>ends_with</fullName>
                <label>ends with</label>
            </value>
            <value>
                <fullName>interval_including_left_right</fullName>
                <label>[ ; ]</label>
            </value>
            <value>
                <fullName>interval_including_right</fullName>
                <label>( ; ]</label>
            </value>
            <value>
                <fullName>interval_including_left</fullName>
                <label>[ ; )</label>
            </value>
            <value>
                <fullName>interval</fullName>
                <label>( ; )</label>
            </value>
            <value>
                <fullName>excludes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/BR_filter__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>Filteting field</description>
    <inlineHelpText>Filteting field</inlineHelpText>
    <label>Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/BR_filter__c/fields/Field_type__c.field-meta.xml
<CustomField>
    <fullName>Field_type__c</fullName>
    <label>Field type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BOOLEAN</fullName>
                <label>Checkbox</label>
            </value>
            <value>
                <fullName>DATE</fullName>
                <label>Date</label>
            </value>
            <value>
                <fullName>DATETIME</fullName>
                <label>Date/Time</label>
            </value>
            <value>
                <fullName>TIME</fullName>
                <label>Time</label>
            </value>
            <value>
                <fullName>DOUBLE</fullName>
                <label>Number</label>
            </value>
            <value>
                <fullName>PICKLIST</fullName>
                <label>Picklist</label>
            </value>
            <value>
                <fullName>MULTIPICKLIST</fullName>
                <label>Multi picklist</label>
            </value>
            <value>
                <fullName>STRING</fullName>
                <label>Text</label>
            </value>
            <value>
                <fullName>TEXTAREA</fullName>
                <label>Text area</label>
            </value>
            <value>
                <fullName>REFERENCE</fullName>
                <label>Reference</label>
            </value>
            <value>
                <fullName>PHONE</fullName>
                <label>Phone</label>
            </value>
            <value>
                <fullName>ENCRYPTEDSTRING</fullName>
                <label>Encrypted text</label>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
            <value>
                <fullName>EMAIL</fullName>
                <label>Email</label>
            </value>
            <value>
                <fullName>ID</fullName>
                <label>Record ID</label>
            </value>
            <value>
                <fullName>PERCENT</fullName>
                <label>Percent</label>
            </value>
            <value>
                <fullName>CURRENCY</fullName>
                <label>Currency</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/BR_filter__c/fields/Field_value__c.field-meta.xml
<CustomField>
    <fullName>Field_value__c</fullName>
    <label>Field value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/BR_filter__c/fields/Filter_number__c.field-meta.xml
<CustomField>
    <fullName>Filter_number__c</fullName>
    <description>Number of the filter for filter logic in the case</description>
    <inlineHelpText>Number of the filter for filter logic in the case</inlineHelpText>
    <label>Filter Number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/BR_Setting__c/BR_Setting__c.object-meta.xml
<CustomObject>
    <description>Settings for business regulations check</description>
    <label>BR Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BR Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/BR_Setting__c/fields/Is_active__c.field-meta.xml
<CustomField>
    <fullName>Is_active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is active</label>
    <type>Checkbox</type>
</CustomField>

default/objects/BR_Setting__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>the sObject for which the settings are applied</description>
    <inlineHelpText>the sObject for which the settings are applied</inlineHelpText>
    <label>SObject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/BR_Setting__c/fields/SObject_status__c.field-meta.xml
<CustomField>
    <fullName>SObject_status__c</fullName>
    <description>the sObject status for which the settings are applied</description>
    <inlineHelpText>the sObject status for which the settings are applied</inlineHelpText>
    <label>SObject status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Moved to start</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/BRTestDataFactory.cls
@IsTest
public with sharing class BRTestDataFactory {
    public static List<Schema.PicklistEntry> conditionPEList = GlobalUtils.getPicklistValues(BR_filter__c.getSObjectType(), 'Condition__c');
    public static List<Schema.PicklistEntry> fieldTypePEList = GlobalUtils.getPicklistValues(BR_filter__c.getSObjectType(), 'Field_type__c');

    public static BR_Setting__c createSetting() {
        return new BR_Setting__c(
                Name = 'Test setting',
                Is_active__c = true,
                SObject_status__c = 'Free',
                SObject__c = 'Opportunity'
        );
    }

    public static BR_case__c createCase(Id settingId) {
        return new BR_case__c(
                Name = 'test case',
                BR_Setting__c = settingId,
                Filter_logic__c = 'test logic'
        );
    }

    public static BR_filter__c createFilter(Id caseId) {
        return new BR_filter__c(
                BR_case__c = caseId,
                Condition__c = conditionPEList.get(0).getValue(),
                Field__c = 'test',
                Field_type__c = fieldTypePEList.get(0).getValue(),
                Field_value__c = 'test',
                Filter_number__c = 1
        );
    }

    public static BRSettingWrapper createSettingWrapper() {
        BRSettingWrapper settingWrapper = new BRSettingWrapper();
        settingWrapper.name = 'test from wrapper';
        settingWrapper.sObjectName = 'Opportunity';
        settingWrapper.isActive = true;
        List<Schema.PicklistEntry> sObjectStatusPEList = GlobalUtils.getPicklistValues(BR_Setting__c.getSObjectType(), 'SObject_status__c');
        settingWrapper.sObjectStatus = sObjectStatusPEList.get(0).getValue();

        return settingWrapper;
    }

    public static BRSettingWrapper.BRCase createCaseWrapper() {
        BRSettingWrapper.BRCase brCase = new BRSettingWrapper.BRCase();
        brCase.name = 'test case';
        brCase.filterLogic = 'test';

        return brCase;
    }

    public static BRSettingWrapper.BRFilter createFilterWrapper() {
        BRSettingWrapper.BRFilter filter = new BRSettingWrapper.BRFilter();
        filter.condition = conditionPEList.get(0).getValue();
        filter.fieldType = fieldTypePEList.get(0).getValue();
        filter.field = 'test';
        filter.fieldValue = 'test';
        filter.filterNumber = '1';

        return filter;
    }
}