default/objects/E2E_Google_Speed_Analyst_Settings__c/E2E_Google_Speed_Analyst_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>E2E Google Speed Analyst Settings</label>
</CustomObject>

default/objects/E2E_Google_Speed_Analyst_Settings__c/fields/Desktop_Site_Url__c.field-meta.xml
<CustomField>
    <fullName>Desktop_Site_Url__c</fullName>
    <label>Desktop Site Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Google_Speed_Analyst_Settings__c/fields/End_Point__c.field-meta.xml
<CustomField>
    <fullName>End_Point__c</fullName>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Google_Speed_Analyst_Settings__c/fields/Mobile_Site_Url__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Site_Url__c</fullName>
    <label>Mobile Site Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Health_Check__c/Health_Check__c.object-meta.xml
<CustomObject>
    <label>Health Check</label>
    <nameField>
        <label>Health Check Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Health Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Health_Check__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Belgium-FR</fullName>
            </value>
            <value>
                <fullName>Belgium-NL</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Switzerland-DE</fullName>
            </value>
            <value>
                <fullName>Switzerland-FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Health_Check__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>Device</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desktop</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Health_Check__c/fields/First_Contentful_Paint__c.field-meta.xml
<CustomField>
    <fullName>First_Contentful_Paint__c</fullName>
    <label>First Contentful Paint</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Health_Check__c/fields/Performance_Score__c.field-meta.xml
<CustomField>
    <fullName>Performance_Score__c</fullName>
    <label>Performance Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Health_Check__c/fields/Speed_Index__c.field-meta.xml
<CustomField>
    <fullName>Speed_Index__c</fullName>
    <label>Speed Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/classes/GoogleSpeedAnalystBatch.cls
global class GoogleSpeedAnalystBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    private String query;

    public GoogleSpeedAnalystBatch() {
        this.query = 'SELECT Name, Key__c, End_Point__c, Desktop_Site_Url__c, Mobile_Site_Url__c ' +
                     'FROM E2E_Google_Speed_Analyst_Settings__c ';
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(this.query);
    }

    global void execute(Database.BatchableContext BC, List<SObject> settings) {
        List<Health_Check__c> healthChecksToInsertList = new List<Health_Check__c>();
        for (SObject sobj : settings) {
            E2E_Google_Speed_Analyst_Settings__c googleSpeedSettings = (E2E_Google_Speed_Analyst_Settings__c) sobj;
            List<String> endPointsList = new List<String>{
                googleSpeedSettings.End_Point__c + '?key=' + googleSpeedSettings.Key__c +
                '&strategy=desktop' + '&url=' + googleSpeedSettings.Desktop_Site_Url__c,

                googleSpeedSettings.End_Point__c + '?key=' + googleSpeedSettings.Key__c +
                '&strategy=mobile' + '&url=' + googleSpeedSettings.Mobile_Site_Url__c
            };
            for (String endPoint : endPointsList) {
                HttpRequest req = new HttpRequest();
                req.setMethod('GET');
                req.setEndPoint(endPoint);
                req.setTimeout(120000);
                req.setCompressed(true);
                Http http = new Http();
                HTTPResponse resp = http.send(req);
                if (resp.getStatusCode() == 200) {
                    GoogleSpeedAnalystParser desirializedResponse = (GoogleSpeedAnalystParser)JSON.deserialize(resp.getBody(), GoogleSpeedAnalystParser.class);
                    Health_Check__c healthCheck = createHealthCheck(googleSpeedSettings.Name, desirializedResponse);
                    healthChecksToInsertList.add(healthCheck);
                }
            }
        }
        if (healthChecksToInsertList.size() != 0) {
            insert healthChecksToInsertList;
        }
    }

    private Health_Check__c createHealthCheck(String country, GoogleSpeedAnalystParser response) {
        if (response != null) {
            GoogleSpeedAnalystParser.Items_T item = response.lighthouseResult.audits.metrics.details.items.get(0);
            Health_Check__c hc = new Health_Check__c(
                Name = 'E2E Google Speed Analytics',
                Performance_Score__c = response.lighthouseResult.categories.performance.score * 100,
                First_Contentful_Paint__c = item.firstContentfulPaint,
                Speed_Index__c = item.speedIndex,
                Country__c = country
            );
            if (response.lighthouseResult.configSettings.emulatedFormFactor == 'desktop') {
                hc.Device__c = 'Desktop';
            } else if (response.lighthouseResult.configSettings.emulatedFormFactor == 'mobile') {
                hc.Device__c = 'Mobile';
            }
            return hc;
        }
        return null;
    }

    global void finish(Database.BatchableContext BC) {}
}