default/objects/E2E_Data_Contact__c/E2E_Data_Contact__c.object-meta.xml
<CustomObject>
    <label>E2E Data Contact</label>
    <nameField>
        <label>E2E Data Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Contact__c/fields/E2E_Data_Object__c.field-meta.xml
<CustomField>
    <fullName>E2E_Data_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E2E Data Object</label>
    <referenceTo>E2E_Data_Object__c</referenceTo>
    <relationshipLabel>E2E Data Contacts</relationshipLabel>
    <relationshipName>E2E_Data_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2E_Data_Contact__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/E2E_Data_Contact__c/fields/isPrimary__c.field-meta.xml
<CustomField>
    <fullName>isPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPrimary</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2E_Data_Contact__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Authorised signatory</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Contact__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Log__c/E2E_Data_Log__c.object-meta.xml
<CustomObject>
    <label>E2E Data Log</label>
    <nameField>
        <label>E2E Data Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Log__c/fields/E2E_Data_Object__c.field-meta.xml
<CustomField>
    <fullName>E2E_Data_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E2E Data Object</label>
    <referenceTo>E2E_Data_Object__c</referenceTo>
    <relationshipLabel>E2E Data Logs</relationshipLabel>
    <relationshipName>E2E_Data_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2E_Data_Log__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Restart</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/E2E_Data_Log__c/recordTypes/Exception.recordType-meta.xml
<RecordType>
    <fullName>Exception</fullName>
    <active>true</active>
    <label>Exception</label>
</RecordType>

default/objects/E2E_Data_Log__c/recordTypes/Job_Status.recordType-meta.xml
<RecordType>
    <fullName>Job_Status</fullName>
    <active>true</active>
    <label>Job Status</label>
</RecordType>

default/objects/E2E_Data_Object__c/E2E_Data_Object__c.object-meta.xml
<CustomObject>
    <label>E2E Data Object</label>
    <nameField>
        <label>E2E Data Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E2E Data Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/E2E_Data_Object__c/fields/Agree_to_process_pers_data_for_marketing__c.field-meta.xml
<CustomField>
    <fullName>Agree_to_process_pers_data_for_marketing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agree to process pers data for marketing</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Agreement_To_Phone_Contact__c.field-meta.xml
<CustomField>
    <fullName>Agreement_To_Phone_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agreement To Phone Contact</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Agreement_To_Receive_Info_By_Email__c.field-meta.xml
<CustomField>
    <fullName>Agreement_To_Receive_Info_By_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agreement To Receive Info By Email</label>
    <type>Checkbox</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Company_Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Short_Name__c</fullName>
    <label>Company Short Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>E2E Data Objects</relationshipLabel>
    <relationshipName>E2E_Data_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Utm_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Utm_Campaign__c</fullName>
    <label>Utm Campaign</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Utm_Content__c.field-meta.xml
<CustomField>
    <fullName>Utm_Content__c</fullName>
    <label>Utm Content</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Utm_Medium__c.field-meta.xml
<CustomField>
    <fullName>Utm_Medium__c</fullName>
    <label>Utm Medium</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Utm_Placement__c.field-meta.xml
<CustomField>
    <fullName>Utm_Placement__c</fullName>
    <label>Utm Placement</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Utm_Products__c.field-meta.xml
<CustomField>
    <fullName>Utm_Products__c</fullName>
    <label>Utm Products</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Utm_Source__c.field-meta.xml
<CustomField>
    <fullName>Utm_Source__c</fullName>
    <label>Utm Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Utm_Term__c.field-meta.xml
<CustomField>
    <fullName>Utm_Term__c</fullName>
    <label>Utm Term</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/fields/Utm_Url__c.field-meta.xml
<CustomField>
    <fullName>Utm_Url__c</fullName>
    <label>Utm Url</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/E2E_Data_Object__c/recordTypes/Poland.recordType-meta.xml
<RecordType>
    <fullName>Poland</fullName>
    <active>true</active>
    <label>Poland</label>
</RecordType>

default/objects/E2E_Form_General_Settings__c/E2E_Form_General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>E2E Form General Settings</label>
</CustomObject>

default/objects/E2E_Form_General_Settings__c/fields/Integration_Admin_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Admin_Id__c</fullName>
    <label>Integration Admin Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

default/objects/E2EKeysAPI__c/E2EKeysAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Key values for e2e form</description>
    <label>E2EKeysAPI</label>
</CustomObject>

default/objects/E2EKeysAPI__c/fields/AES256_Key__c.field-meta.xml
<CustomField>
    <fullName>AES256_Key__c</fullName>
    <label>AES256_Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Agree_to_process_pers_data_for_marketing__c.field-meta.xml
<CustomField>
    <fullName>Agree_to_process_pers_data_for_marketing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Customer agrees that his personal information can be processed for marketing purposes</inlineHelpText>
    <label>Agree to process pers data for marketing</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Lead/fields/Anzahl_der_Fahrzeuge__c.field-meta.xml
<CustomField>
    <fullName>Anzahl_der_Fahrzeuge__c</fullName>
    <label>Anzahl der Fahrzeuge?</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Lead/fields/CCS_number_of_cards__c.field-meta.xml
<CustomField>
    <fullName>CCS_number_of_cards__c</fullName>
    <label>CCS_number_of_cards</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Первый контакт по inbound</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sec_Channel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Anruf</fullName>
            </value>
            <value>
                <fullName>FLMT_Form</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/E2E_Assistant__c.field-meta.xml
<CustomField>
    <fullName>E2E_Assistant__c</fullName>
    <label>E2E Assistant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Number_of_Cards_facebook__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Cards_facebook__c</fullName>
    <description>Field for the facebook form integration.</description>
    <label>Number of Cards (facebook)</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Partner_OBN__c.field-meta.xml
<CustomField>
    <fullName>Partner_OBN__c</fullName>
    <label>Partner-OBN</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/fields/Sec_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sec_Channel__c</fullName>
    <label>Sec. Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JITB</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Lead/fields/Utm_term__c.field-meta.xml
<CustomField>
    <fullName>Utm_term__c</fullName>
    <label>Utm_term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lead/recordTypes/Endkunde.recordType-meta.xml
<RecordType>
    <fullName>Endkunde</fullName>
    <active>true</active>
    <businessProcess>Datensatztyp</businessProcess>
    <label>Endkunde</label>
</RecordType>

default/objects/Lead/recordTypes/Lotos.recordType-meta.xml
<RecordType>
    <fullName>Lotos</fullName>
    <active>true</active>
    <businessProcess>Datensatztyp</businessProcess>
    <label>Lotos</label>
</RecordType>

default/objects/User/fields/role__c.field-meta.xml
<CustomField>
    <fullName>role__c</fullName>
    <formula>UserRole.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>role</label>
    <type>Text</type>
</CustomField>

default/classes/SwitchLeadToE2EController.cls
public class SwitchLeadToE2EController {
    public Boolean isError {get; set;}

    public SwitchLeadToE2EController() {}

    public PageReference init() {
        try {
            this.isError = false;
            String leadId;
            Map<String, String> parametersMap = ApexPages.currentPage().getParameters();

            if (ApexPages.CurrentPage().getparameters().get('lid') != null) {
                leadId = ApexPages.CurrentPage().getparameters().get('lid');
            } else if (ApexPages.CurrentPage().getparameters().get('eid') != null) {
                String decryptParams = doDecryptParams(ApexPages.CurrentPage().getparameters().get('eid'));
                if (decryptParams != null) {
                    leadId = decryptParams.substringBefore('-');
                }
            }
            if (leadId == null) {
                return new PageReference(ETEGlobalUtils.returnSiteUrl(null));
            }

            List<Lead> leadsList = [
                    SELECT Owner.Name, IsConverted, ConvertedOpportunity.E2E_Encoded_URL__c, Country, Anzahl_der_Fahrzeuge__c, Channel__c, Salutation, RecordType.Name, Status,
                            LeadSource, CCS_number_of_cards__c, Email, CountryCode, Number_of_Cards_facebook__c, Sec_Channel__c, E2E_Assistant__c, E2E_Manual_Adoption_Date__c, Partner_OBN__c,
                            Utm_campaign__c, Agree_to_receive_comm_info_by_email__c, FirstName, LastName, Phone, Company, Owner.Type, Agree_to_process_pers_data_for_marketing__c,
                            Agree_to_telephone_contact__c
                    FROM Lead
                    WHERE Id = :leadId AND
                          Country != NULL
                    LIMIT 1];

            if (leadsList.isEmpty()) {
                return new PageReference(ETEGlobalUtils.returnSiteUrl(null));
            }

            String countryCode = leadsList.get(0).CountryCode.toLowerCase();
            String implKey = leadsList.get(0).Country;
            if (leadsList.get(0).Country == 'Poland' && leadsList.get(0).RecordType.Name == 'Lotos') {
                implKey = implKey + ' ' + leadsList.get(0).RecordType.Name;
            }

            String urlPath = ETEGlobalUtils.returnUrlPath(implKey).getUrl();

            if ( ! leadsList.isEmpty() && leadsList.get(0).IsConverted && leadsList.get(0).ConvertedOpportunity.E2E_Encoded_URL__c != null) {
                return new PageReference(urlPath + '?source=' + leadsList.get(0).ConvertedOpportunity.E2E_Encoded_URL__c);
            } else if ( ! leadsList.isEmpty() && leadsList.get(0).IsConverted && leadsList.get(0).ConvertedOpportunity.E2E_Encoded_URL__c == null) {
                return new PageReference(urlPath);
            }

            Lead currentLead = leadsList.get(0);

            if (GlobalUtils.isSwitchToE2EFromFacebook(currentLead) || GlobalUtils.isSwitchToE2EInboundCall(currentLead) || GlobalUtils.isSwitchToE2EInboundEmail(currentLead) ||
                    GlobalUtils.isSwitchToE2EShellEmail(currentLead) || GlobalUtils.isSwitchToE2EFromPopup(currentLead) || GlobalUtils.isSwitchToE2EFromShortForm(currentLead) ||
                    GlobalUtils.isSwitchToE2EFromPartnerJITB(currentLead) || GlobalUtils.isSwitchToE2ETabletShortForm(currentLead) || GlobalUtils.isSwitchToE2EManualAdoption(currentLead) ||
                    (GlobalUtils.isAdoptionProcessLotos(currentLead) && currentLead.RecordType.Name == 'Lotos') ||
                    (GlobalUtils.isAdoptionProcessShell(currentLead) && currentLead.RecordType.Name == 'Endkunde') ||
                    GlobalUtils.isE2EAdoptionHU(currentLead)) {
                if (currentLead.CCS_number_of_cards__c == null) {
                    if (currentLead.Number_of_Cards_facebook__c != null) {
                        currentLead.CCS_number_of_cards__c = Integer.valueOf(currentLead.Number_of_Cards_facebook__c);
                    } else if (currentLead.Anzahl_der_Fahrzeuge__c != null) {
                        currentLead.CCS_number_of_cards__c = Integer.valueOf(currentLead.Anzahl_der_Fahrzeuge__c);
                    }
                }

                E2E_Data_Object__c dataObject;
                List<E2E_Data_Object__c> dataObjectToCheck = [SELECT Id FROM E2E_Data_Object__c WHERE Lead__c = :leadId];

                if (dataObjectToCheck.isEmpty()) {
                    ETEDatabaseInterface e2eDatabase = ETEGlobalUtils.getDatabaseConnector(countryCode);
                    ETEStepInterface e2eStep = ETEGlobalUtils.getETEStepImplementation(implKey);
                    Map<String, Object> untypedSettings = e2eDatabase.getSettings(implKey, countryCode);
                    List<String> availableStepsList = e2eStep.getAvailableSteps(untypedSettings, null);
                    ETEBusinessObjectsInterface businessObjectsHandler = ETEGlobalUtils.getETEBusinessObjectsHandler(implKey);
                    String shortCompanyName = leadsList.get(0).Company;
                    if (shortCompanyName.length() > 25) {
                        shortCompanyName = shortCompanyName.substring(0, 25);
                    }
                    dataObject = businessObjectsHandler.initDataObject(availableStepsList, countryCode, implKey);
                    dataObject.Name = leadsList.get(0).Company;
                    dataObject.Lead__c = leadsList.get(0).Id;
                    dataObject.Company_Short_Name__c = shortCompanyName;
                    dataObject.Agree_to_process_pers_data_for_marketing__c = leadsList.get(0).Agree_to_process_pers_data_for_marketing__c;
                    dataObject.Agreement_To_Receive_Info_By_Email__c = leadsList.get(0).Agree_to_receive_comm_info_by_email__c;
                    dataObject.Agreement_To_Phone_Contact__c = leadsList.get(0).Agree_to_telephone_contact__c;

                    if ( ! parametersMap.isEmpty() ) {
                        for (String key : parametersMap.keySet()) {
                            key = key.toLowerCase();
                            if (key == 'utm_campaign') {
                                dataObject.Utm_Campaign__c = parametersMap.get(key);
                            } else if (key == 'utm_content') {
                                dataObject.Utm_Content__c = parametersMap.get(key);
                            } else if (key == 'utm_medium') {
                                dataObject.Utm_Medium__c = parametersMap.get(key);
                            } else if (key == 'utm_placement') {
                                dataObject.Utm_Placement__c = parametersMap.get(key);
                            } else if (key == 'utm_source') {
                                dataObject.Utm_Source__c = parametersMap.get(key);
                            } else if (key == 'utm_term') {
                                dataObject.Utm_Term__c = parametersMap.get(key);
                            } else if (key == 'utm_url') {
                                dataObject.Utm_Url__c = parametersMap.get(key);
                            } else if (key == 'utm_products') {
                                dataObject.Utm_Products__c = parametersMap.get(key);
                            }
                        }
                    }

                    insert dataObject;

                    E2E_Data_Contact__c dataContact = new E2E_Data_Contact__c(
                            E2E_Data_Object__c = dataObject.Id,
                            First_Name__c = leadsList.get(0).FirstName,
                            Last_Name__c = leadsList.get(0).LastName,
                            Email__c = leadsList.get(0).Email,
                            Phone__c = leadsList.get(0).Phone,
                            Salutation__c = 'Mr.',
                            Role__c = 'Decision Maker',
                            isPrimary__c = true,
                            Index__c = 0
                    );
                    insert dataContact;

                    // insert data log to run checkBusinessObjects after redirect
                    List<RecordType> e2eDataLogRecordTypeList = [SELECT Id FROM RecordType WHERE SobjectType = 'E2E_Data_Log__c' AND DeveloperName = 'Job_Status' LIMIT 1];
                    E2E_Data_Log__c dataLog = new E2E_Data_Log__c(
                            E2E_Data_Object__c = dataObject.Id,
                            Job_Status__c = 'Completed',
                            Name = 'checkBusinessObjects'
                    );
                    if ( ! e2eDataLogRecordTypeList.isEmpty() ) {
                        dataLog.RecordTypeId = e2eDataLogRecordTypeList.get(0).Id;
                    }
                    insert dataLog;

                    if (currentLead.Salutation == null || currentLead.Salutation == '' || currentLead.Owner.Type != 'User') {
                        E2E_Form_General_Settings__c e2eGeneralSettings = E2E_Form_General_Settings__c.getInstance(currentLead.Country);
                        currentLead.OwnerId = e2eGeneralSettings.Integration_Admin_Id__c;
                        currentLead.Salutation = 'Mr.';

                        update currentLead;
                    }

                    List<String> jobsNeededToRun = new List<String>{'checkBusinessObjects'};
                    ETEJobChainHandler jobChainHandler = new ETEJobChainHandler(jobsNeededToRun, dataObject.Id, countryCode, implKey);
                    jobChainHandler.runNext();
                } else {
                    dataObject = dataObjectToCheck.get(0);
                }
                String source = ETEGlobalUtils.doEncryptParams(dataObject.Id, countryCode);

                return new PageReference(urlPath + '?source=' + source);
            } else {
                return new PageReference(urlPath);
            }
        } catch (Exception e) {
            ExceptionLogger.sendException(String.valueOf('Lead Switch to E2E Exception: ' + e.getMessage()), String.valueOf(e.getStackTraceString()));
            this.isError = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Internal error'));
            return null;
        }
    }


    private String doDecryptParams(String encryptedParams) {
        encryptedParams = encryptedParams.replaceAll('(\\s|%2B)', '+');
        Blob key = EncodingUtil.base64Decode(E2EKeysAPI__c.getValues('E2EForm').AES256_Key__c);
        Blob dest = EncodingUtil.base64Decode(encryptedParams);
        Blob decrypted = Crypto.decryptWithManagedIv('AES256', key, dest);
        String decryptedParams = decrypted.toString();
        return decryptedParams;
    }
}