default/objects/ERP__c/ERP__c.object-meta.xml
<CustomObject>
    <label>GFN</label>
    <nameField>
        <label>GFN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GFNs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/ERP__c/fields/ColCo__c.field-meta.xml
<CustomField>
    <fullName>ColCo__c</fullName>
    <label>ColCo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

default/objects/ERP__c/fields/ColCoID__c.field-meta.xml
<CustomField>
    <fullName>ColCoID__c</fullName>
    <label>ColCo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

default/objects/ERP__c/fields/GFN_Nr__c.field-meta.xml
<CustomField>
    <fullName>GFN_Nr__c</fullName>
    <externalId>true</externalId>
    <label>GFN Nr</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/ERP__c/fields/GFN_Number__c.field-meta.xml
<CustomField>
    <fullName>GFN_Number__c</fullName>
    <externalId>true</externalId>
    <label>GFN Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/GFNI_Batch_Settings__c/GFNI_Batch_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>GFNI Batch Settings</label>
</CustomObject>

default/objects/GFNI_Batch_Settings__c/fields/Error_Message_Reciever__c.field-meta.xml
<CustomField>
    <fullName>Error_Message_Reciever__c</fullName>
    <label>Error Message Reciever</label>
    <type>Email</type>
</CustomField>

default/objects/GFNI_Batch_Settings__c/fields/Query_Limit__c.field-meta.xml
<CustomField>
    <fullName>Query_Limit__c</fullName>
    <label>Query Limit</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/GFNI_Batch_Settings__c/fields/Where_Condition__c.field-meta.xml
<CustomField>
    <fullName>Where_Condition__c</fullName>
    <label>Where Condition</label>
    <type>TextArea</type>
</CustomField>

default/classes/UpdateGfnNumberOfCardsBatch.cls
global with sharing class UpdateGfnNumberOfCardsBatch implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful {
    private String query;
    private GFNI_Batch_Settings__c updateBatchSetting;
    private List<UpdateGfnNumberOfCardsBatchHandler.ExceptionWrapper> errorList = new List<UpdateGfnNumberOfCardsBatchHandler.ExceptionWrapper>();
    // private Map<String, Exception> errorMap = new Map<String, Exception>();
    public UpdateGfnNumberOfCardsBatch(GFNI_Batch_Settings__c updateBatchSetting) {
        this.query = 'SELECT Id, Gfn_Nr__c, Gfn_Number__c, RecordTypeId, ColCo__c, ColCoID__c FROM ERP__c';
        this.updateBatchSetting = updateBatchSetting;
        System.debug(' updateBatchSetting=== ' + updateBatchSetting);
        if(updateBatchSetting != null) {
            if(updateBatchSetting.Where_Condition__c != null) {
                this.query = this.query + ' WHERE ' + updateBatchSetting.Where_Condition__c;
            }
            if(updateBatchSetting.Query_Limit__c != null) {
                this.query = this.query + ' LIMIT ' + updateBatchSetting.Query_Limit__c;
            }
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        try {
            return Database.getQueryLocator(this.query);
        } catch(Exception e) {
            UpdateGfnStatusBatchHandler.saveLogs(e.getMessage());
            UpdateGfnStatusBatchHandler.sendErrorMessage(e, this.updateBatchSetting.Error_Message_Reciever__c);
            return Database.getQueryLocator('SELECT Id FROM ERP__c LIMIT 0');
        }
    }


    global void execute(Database.BatchableContext BC, List<ERP__c> erpList) {
        try{
            UpdateGfnNumberOfCardsBatchHandler.updateGfnNumberOfCards(erpList, errorList);
            if(errorList.size() > 50) {
                UpdateGfnNumberOfCardsBatchHandler.handleErrors(this.updateBatchSetting.Error_Message_Reciever__c, this.errorList);
                this.errorList.clear();
            }
        } catch(Exception e) {
            UpdateGfnStatusBatchHandler.saveLogs(e.getMessage());
            UpdateGfnStatusBatchHandler.sendErrorMessage(e, this.updateBatchSetting.Error_Message_Reciever__c);
        }
    }


    global void finish(Database.BatchableContext BC) {
        UpdateGfnNumberOfCardsBatchHandler.handleErrors(this.updateBatchSetting.Error_Message_Reciever__c, this.errorList);
    }
}